#+TODO: X 0 1 2 | OK
#+TITLE: Mathematical analysis conspect of lections by Kokhas' K.P. - III term

* Definitions
** o(h) при h → 0
   Бесконечно малое в xₒ: φ: E ⊂ ℝᵐ → ℝˡ; 0 ∈ Int E
   φ(h) = o(h) при h → 0 - это по определению lim{h → 0} φ(h)/|h| = oₘ
** Дифференцируемое отображение
   F: E ⊂ ℝᵐ → ℝˡ, a ∈ Int(E),
   * F дифференцируемо в (.) а, если ∃ L: ℝᵐ → ℝⁿ |
     F(a + h) = F(a) + L(h)*h + o(h), где h → 0
** Производный оператор
   Это такое L, что F(a+h) = F(a) + L(h) + α(h)*|h|
** Матрица Якоби
   Это матрица производного оператора L (n×m)
** Дифференциал отображения
   Это одно из двух:
   1. Производная оператора: h ↦ F'(a)*h (ℝᵐ → ℝˡ)
   2. Отображение V(a)×ℝᵐ (x,h) ↦ F'(x)*h
** Частные производные
   f: E ⊂ ℝᵐ → ℝ, a ∈ Int(E), a = (a₁...aₘ), φₖ(t) = f(a₁,...,aₖ₋₁, t, aₖ₊₁,...,aₘ)
   * fₖ'(a) = lim(φ(aₖ+t) - φ(aₖ))/t при t → 0  – если существует, то называется
     k-й частной производной в а
** Производная по вектору, по направлению
   ξ ∈ ℝᵐ, |ξ|=1, ξ - направление
   * ∂f/∂ξ (a) = lim{t→0}((f(a + tξ) - f(a))/t)
** Градиент
   ∇f = ∂f/∂x₁ * e₁ + ... + ∂f/∂xₙ * eₙ
** Частная производная второго порядка, $k$-го порядка
   ]g(x) = f'ₓᵢ(x):
   * g'ₓₖ(x) - частная производная f по xᵢ, xₖ.
   * Аналогично n-того
** Классы C^r(E)
   r ∈ N, D - открыто в ℝᵐ
   * Cʳ - множество фуккций D → ℝ, у которых ∃ все r непрерывных производных
   * C⁰(D) ⊂ C¹(D) ⊂ ... ⊂ Cⁿ(D)
   * Cⁱⁿᶠ= ⋂Cʳ
** Мультииндекс и обозначения с ним
   * Вектор (i₁...iₙ), |i| = ∑iⱼ, i! = ∏iⱼ!, aⁱ = a₁ⁱ¹*...*aₘⁱᵐ
   * f⁽ⁱ⁾ = ∂^{|i|}*f/(∂x₁ⁱ¹*...*∂xₘⁱᵐ)
** Формула Тейлора (различные виды записи)
   f(x) = ∑{k=0,r}(∑{i:|i|=k}1/i!*f⁽ⁱ⁾(a)(x-a)ⁱ) + ∑{i:|i|=r+1}(1/i!*f⁽ⁱ⁾(a + t(x - a))(x-a)ⁱ)
   f(x) = ∑{i=0,r}(1/i!*f⁽ⁱ⁾(a)(x-a)ⁱ) + f⁽ʳ⁺¹⁾(a~)/(r+1)!*(x-a)ʳ⁺¹
** $n$-й дифференциал
   ∂ᵏf(a,h) = ∑{i:|i|=k}(f⁽ⁱ⁾(a)hⁱ)
** Норма линейного оператора
   ∥A∥ = sup{|x|≤1, x ∈ X}(|Ax|)
   Отметим, что sup достигается всегда на |x|=1
** Положительно-, отрицательно-, незнако- определенная квадратичная форма
   Q(h) = ∑{i≤j}αᵢⱼhⱼhᵢ; положительно определена если всегда больше нуля
   незнакоопределена, если может быть <> (но не равна нулю). Полуопределена положительнo
   если везде >=0, но ∃h!=0 | Q(h) = 0
** Локальный максимум, минимум, экстремум
   f: E ⊂ ℝᵐ → ℝ x₀ ∈ E - локальный максимум f, если ∃U(x₀) | ∀x∈U(x₀)∩E f(x) ≤ f(x₀)
   Строго – знак и точечка над U.
   Экстремум = min | max
** Диффеоморфизм
   F: O ⊂ ℝᵐ → ℝᵐ диффеоморфизм, если F дифф в O, обратимо и F⁻¹ дифференцируемо
** Формулировка теоремы о локальной обратимости в терминах систем уравнений
   f₁(x₁...xₙ) = y₁
   .
   .
   .
   fₙ(x₁...xₙ) = yₙ
   (x⁰₁....x⁰ₙ, y⁰₁...y⁰ₙ) - решение - (x⁰, y⁰)
   Если все f₁ - гладкие в окружении x⁰ и при этом det(∂fᵢ/∂xⱼ(x₀))≠0
   * ∃U(y⁰), V(x⁰) ∀y система разрешима и ∃ед.решение в V(x⁰) и это решение гладкое.
** Формулировка теоремы о неявном отображении в терминах систем уравнений
   F: E ⊂ ℝᵐ⁺ⁿ → ℝⁿ F ∈ Cʳ(E, ℝⁿ), (a, b) ∈ E, F(a, b) = 0ₙ, F'_y обратима,
   * ∃ P(a) - окрестность в ℝᵐ Q(b) - открыта в ℝⁿ, ∃φ:P→Q (φ(a)=b) | ∀x∈P(a) F(x, φ(x))=0_b
     При этом φ ∈ Cⁿ, φ'(a)=-(F'_y(a, b))⁻¹ - Fₓ⁻¹(a, b)
** Гладкое простое k-мерное многообразие в ℝ^{m}
   M ⊂ ℝᵐ, 1≤k<m
   M - простое k-мерное многообразие в ℝᵐ
   M гомеоморфно O ⊂ ℝᵏ
   ∃Φ:O → M гомеоморфизм
** Относительно локальный максимум, минимум, экстремум
   Имеем максимум по f в окрестности, где Φ обнуляется.

   Φ: E ⊂ ℝᵐ⁺ᵏ → ℝᵏ, f: E ⊂ ℝᵐ⁺ᵏ → ℝ гладкие
   a - точка относительно локального максимума при Φ = 0, если
   Φ(a) = 0, ∃U(a) ∀x ∈ U(a) Φ(x) = 0, f(x) ≤ f(a)
** Формулировка достаточного условия относительного экстремума
   Имеет необходимые условия из теоремы о необходимых условиях.
   Тогда возьмем F(x) = f(x) - λ₀Φ(x), Q(h) = d²F(x₀, h), где h ∈ ℝᵐ⁺ⁿ
   Выразим из системы Φ'(x⁰) * h = 0 (rang Φ'(x⁰) = n)
   hₘ₊₁...hₘ₊ₙ через остальные, Q~ = Q(...hₘ₊₁(...), ...) (подставили)
   * Определенность Q~ определяет экстремум как обычно
** ------------------------------------------------------------------------------
** Кусочно-гладкий путь
   Путь называется кусочно-гладким, если он гладкий кроме {t₁...tₙ}, но
   ∀tᵢ ∃γ₊'(tᵢ), γ₋'(tᵢ)
** Интеграл векторного поля по кусочно-гладкому пути
   I(V, γ) = ∫_γ(V₁(γ(t))dγ₁(t)+V₂dx₂+...+Vₘdxₘ)
** Потенциальное векторное поле
   Поле потенциально, если существует его потенциал:
** Потенциал векторного поля
   f - потенциал V в O (V: O ⊂ ℝᵐ → ℝᵐ), если ∀x ∈ O (∇f)(x) = V(x)
** Локально-потенциальное векторное поле
   Поле, для каждой точки которого сужение его самого на окрестность точки
   потенциально.
** Похожие пути
   γ₁ и γ₂ похожи, если существует обшщая гусеница из лемме о гусеницы
** Интеграл локально-потенциального векторного поля по произвольному пути
   Интеграл локально-потенциального векторного поля по произвольному пути
   равен его интегралу по кусочно-гладкому пути, близкому к данному.
** Гомотопия путей связанная и петельная
   Два пути связанно гомотопны, если у них совпадают начала и концы,
   причем ∃Γ:[a,b]×[c,d] → O непрерывная, что
   Γ(t,0) = γ(t), Γ(t,1) = γ~(t),
   для s ∈ [0,1] Г(a,s) = γ(a), Г(b,s) = γ(b)
   для петель то же самое, с учетом того, что у петель может
   вообще ничего не совпадать (кроме их собственных начала и конца)
** Односвязная область
   Односвязная область -- область, на которой любая петля стягивается, то
   есть гомотопна постоянному пути γ(s) = k
** ------------------------------------------------------------------------------
** Полукольцо
   P - полукольцо над X -- множество 2^X с правилами:
   1. ∅∈P
   2. ∀A,B ∈ P (A∩B) ∈ P
   3. ∀A,B ∃конечный дизъюнктный набор D₁...Dₖ | A\B=⊔Dᵢ
** Алгебра
   A над X - 2^X (множество всех подмножеств X) - алгебра:
   1. ∀A,B ∈ Al A\B ∈ Al
   2. A U B ∈ Al
   3. ∅ ∈ Al
   Непустое подмножество
** Сигма-алгебра
   A - алгебра, σ - алгебра  = A + ∀ счетного набора множество их объединение ∈ A
** Объем
   μ: P -> ℝ~(+inf) - аддитивная функция, положительна
   1. μ не принимает бесконечное значение разных знаков
   2. μ(∅) = 0
   3. ∀A₁...Aₙ - дизъюнктивные множества они ∈ P и A=⊔Aᵢ ∈ P
      μ(A) = ∑μ(Aᵢ)
** Мера
   μ - объем & μ счетно аддитивна (A = ⊔{inf}Aᵢ all ∈ P => μA = ∑μAᵢ)
** Сигма-конечный объем
   Это объем, такой что все пространство X можно представить в виде объединения
   Aₖ, причем μ(Aₖ)<∞ (каждого)
** Полная мера
   μ": P → ℝ~ - полная мера, если
   ∀ A ⊂ P μA = 0 верно ∀ B ⊂ A (B ∈ P & μB = 0)
** Мера Лебега
   Мера Лебега -- результат Лебеговского продолжения классического объема.
** Борелевская сигма-алгебра в ℝᵐ
   Это сигма-алгебра в ℝᵐ | минимальна & содержит все открытые множества (число элементов - континуум)
** X Формулировка теоремы о мерах, инвариантных относительно сдвига
   Pᵐ ⊂ A ⊂ Mᵐ; μ - мера на A; μ инвариантна относительно сдвигов
   ∃ ячейки P μP > 0, μP < ∞
   * ∃ c > 0 ∀ a in A λ(a) = cμ(a)
** Мера Лебега--Стилтьеса, мера Бореля--Стилтьеса
   g: ℝ → ℝ - возрастает, непрерывна
   μ[a, b) = g(b) - g(a) - это конечно аддитивный объем.
   его продолжение по Лебегу -- мера Лебега Стилтьеса
   Мера Бореля-Стилтьеса -- сужение меры Л-С на борелеву алгебру
** Ступенчатая функция
   X - множество, f: X → R ступеньчата, если
   ∃ ⊔Xᵢ | ∀x ∈ Xᵢ f(x) = cᵢ
** Разбиение, допустимое для ступенчатеой функции
   Разбиение, которое подходит для того, чобы на нем функция была ступеньчата
** Измеримая функция
   Лебегово множество - E(f<a) = {x ∈ E: f(x) < a}
   f: E ⊂ X → R~, f измеримо на E, если
   ∀a ∈ R E(f<a), E(f>a), E(f≤a), E(f≥a) измеримы
** Свойство, выполняющееся почти везде
   Высказывание w(x) выполняется почти всюду, если множества, на которых
   оно не выполняестя, имеют меру ноль
** Сходимость почти везде
   Полагаю, что функции сходятся почти везде, если типа вот сходятся везде, а там
   где не сходятся, там мера ноль)))
** Сходимость по мере
   fₙ, f: X → R~
   fₙ ⇒μ f, если ∀ε>0 μX(|fₙ-f| < ε) → 0
** Теорема Егорова о сходиомсти почти везде и почти равномерной сходиомсти
   μX < ∞, fn, f измеримы почти везде конечны
   fₙ → f почти везде
   Тогда
   ∀ε > 0 ∃e∈X измеримое μe < ε, fₙ⇉f на X\e
** Интеграл ступенчатой функции
   f = ∑αᵢX_{Eᵢ}
   ∫fdμ = ∑αᵢμEᵢ (0*∞ = 0)
** Интеграл неотрицательной измеримой функции
   f - изм, f≥0, ∫fdμ = sup{∫gdμ, 0≤g≤f, g - ступ}
** Суммируемая функция
   f - суммируемая, если она измерима, и ее разность интегралов по срезке не ±∞
** Интеграл суммируемой функции
   ∫f = ∫f₊dμ - ∫f₋dμ
* Lemmas, theorems
** Единственность производной
   Оператор F'(a) - единственный

*** Доказательство
    Рассмотрим малые t, a + tu ∈ E, подставим h = tu:
    F(a + tu) = F(a) + L*tu + o(tu), t → 0
    L*u = (F(a + tu) - F(a) - o(tu)*|t|*u) / t
    = lim{t → 0}((F(a + tu) - F(a)) / t) + 0
    Тогда в силу единственности предела единсвтеннен и L.
** Лемма о покоординатной дифференцируемости
   F:E ⊂ ℝᵐ → ℝˡ, a ∈ IntE, F(x) = ((F₁(x)...Fₗ(x)))
   1. F - дифференцируема в (.) a ⇔ F₁...Fₗ дииференцируемы в (.) а
   2. Если F дифференцируема в (.) а, то матрица Якоби F'(a) есть
      столбик из векторов Fᵢ'(a) — m×l

*** Доказательство
    1. По определению рассмотрим F' - это столбец из F'ᵢ, тогда очевидно,
       что они существуют, и наоборот.
    2. Опять-таки, давайте посмотрим на F'
       Fᵢ(a + h) = Fᵢ(a) + (F'(a))ᵢ*h + αᵢ(h)*|h|
       Ну типа i у нас от одного до l, потому что у нас область значений
       l-мерная, ну и умножаем мы его на h, а h - m-мерный, тогда F' m×l.
** Необходимое условие дифференцируемости
   f: E ⊂ ℝᵐ → ℝ, a ∈ Int(E), f - дифф в (.) а
   1. Cуществуют все m частных производных f'x₁...f'xₘ (a)
   2. f'(a) = (f'x₁(a), f'x₂(a), ..., f'xₘ(a))

*** Доказательство
    f(a + h) = f(a) + f'(a)*h + α(h)*|h|
    по определению частичной производной h = (0,...0, t, 0,...0),
    φₖ(x) = f(a₁....aₖ + t, ...aₙ)
    тогда φₖ(t) = φₖ(0) + (f'(a))ₖ*t + α(h)*|t|
    Собственно вон мы берем k-столбец нашей f'(a),
    то есть 2 пункт доказан
** Достаточное условие дифференцируемости
   f: E ⊂ ℝᵐ → ℝ, a ∈ Int(E);
   ∃ B(a, r) ⊂ E ∀x ∈ B(a, r) ∃ f'ₓ₁(x)...f'ₓₙ(x)  и
   все эти частные производные непрерывны в a
   * f дифференцируема в (.) a

*** Доказательство
    f(x₁, x₂) - f(a₁, a₂)
    = (f(x₁, x₂) - f(a₁, x₂)) + (f(a₁, x₂) - f(a₁, a₂))        вычели\прибавили
    = f'ₓ₁(x₁~, x₂)(x₁ - a₁) + f'ₓ₂(a₁, x₂~)(x₂ - a₂)          теорема Лагранжа
    = f'ₓ₁(a₁, a₂)(x₁ - a₁) + f'ₓ₂(a₁, a₂)(x₂ - a₂) +
    + |x ± a| [(f'ₓ₁(x₁~, x₂) - f'ₓ₁(a₁, a₂)) (x₁ - a₁)/|x - a|
    + (f'ₓ₂(a₁, x₂~) - f'ₓ₂(a₁, a₂)) (x₂ - a₂)/|x - a|
** Лемма об оценке нормы линейного оператора
   A: ℝᵐ → ℝⁿ, линейный;
   * ∀u ∈ ℝᵐ: |Aₙ| ≤ Cₐ|u|, где Cₐ = √(∑{i, j}(a²ᵢⱼ))

*** Доказательство
    Имеем |Aₙ|² = ∑(∑(aᵢⱼ*uᵢ))²
    ≤ ∑((∑aᵢⱼ²)(∑uⱼ²))              Коши-Буняковский-Шварц
    = (∑∑aᵢⱼ²)(∑uⱼ²)
    = ∑{i, j}(aᵢⱼ²) * |u|
** Дифференцирование композиции
   F: E ⊂ ℝᵐ → ℝˡ; G: E ⊂ ℝˡ → ℝⁿ; a ∈ IntE,
   F(E) ∈ I, F(a) ∈ Int(I), ]b = F(a), G,F дифф
   * G∘F:E→ℝⁿ - дифф в а, причем (G∘F)'(a) = G'(F(a))*F'(a)

*** Доказательство
    F(x) = F(a) + F'(a)(x - a) + α(x)|x - a|
    G(y) = G(b) + G'(b)(y - b) + β(y)|y - b|
    G(F(x)) = G(F(a) + F'(a)(x - a) + α(x)|x - a|)
    = G(F(a)) + G'(F(a))*(F'(a)(x - a) - α(x)|x - a|) + β(y)*|F'(a)(x - a) - α(x)|x - a||
    = G(F(a)) + G'(F(a))*F'(a)(x - a)
    + G'(b)α(x)|x - a|                          Эта штука ≤ C * |α(x)| → 0
    + |x - a|β(y)|F'(a)(x-a)/|x-a| + α(x)|      Эта бм * огр (≤ C * |(x-a)/|x-a|| + |α(x)| огр. при x → a)
    Таким образом видно, что
    G(F(x)) = G(F(a)) + G'(F(a))*F'(a)*(x-a) + o(...)
    G'(F(a))*F'(a) - это и есть производная G(F(x)) по опр.
** Дифференцирование "произведений"
   F, G : E ⊂ ℝᵐ → ℝˡ, λ: E → ℝ, a ∈ IntE
   1. (λF)'(a)h = (λ'(a)*h)F(a) + λ(a)F'(a)h
   2. (<F, G>)'(a)h = <F'(a)h, G(a)> + <F(a), G'(a)h>

*** Доказательство
    1. F = (f₁...fₙ)
       λ(x)f(x) = (λ(a) + λ'(a)h + α(x)|h|)(f(a) + f'(a)h + β(x)|h|)
       = λ(a)f(a) + (λ'(a)h)f(a) + λ(a)f'(a)h +
       + |h| * какую-то ограниченную * бесконечно малую фигню.
    2. <F, G>(x) = ∑fᵢ(x)gᵢ(x)
       <F, G>'(a)h = ∑((fᵢgᵢ)'(a)h) = ∑((fᵢ'h)gᵢ + fᵢ(gᵢ'h)) = <F'h, G> + <F, G'h>
** Теорема Лагранжа для векторнозначных функций
   F[a,b] → ℝˡ F непрерывно на [a, b], дифф на (a, b)
   * ∃c ∈ [a, b] : |F(b) - F(a)| ≤ |F'(c)|(b - a)

*** Доказательство
    ] φ(t) = <F(b) - F(a), F(t) - F(a)>
    φ(a) = 0, φ(b) = |F(b) - F(a)|²
    φ'(t) = <F(b) - F(a); F'(t)>
    Воспользуемся теоремой Лагранжа для φ:
    ∃c: φ(b) - φ(a) = φ'(c)(b - a)
    Тогда |F(b) - F(a)|² - 0 = <F(b) - F(a); F'(c)>(b - a)
    ≤ |F(b) - F(a)||F'(a)|(b-a)
** Экстремальное свойство градиента
   f: E ⊂ ℝᵐ -> ℝ, a ∈ Int(E), f дифф в (.) a, grad f(a) ≠ 0
   * ξ=∇f(a)/|∇f(a)|
   * ∀h |∂f/∂h| ≤ ∂f/∂ξ

*** Доказательство
    ∂f/∂h = <∇f, h> ≤ |∇f|*|h| = |∇f| = <∇f, ∇f/|∇f|> = ∂f/∂ξ
    Второй переход – КБШ
** Независимость частных производных от порядка дифферненцирования
   f: E ⊂ ℝᵐ → ℝ, B(a, r) ⊂ E, m = 2
   ∃f''_{x,y), f''_{y,x}, они непрерывны в a
   * f''_{x,y} == f''_{y,x} в точке а

*** Доказательство
    ] x = a₁ + h, y = a₂ + k
    Δ² = f(a₁+h, a₂+k) - f(a₁+h, a₂) - f(a₁, a₂+k) + f(a₁, a₂)
    Типа давайте зафиксируем k, примем за g(x) = f(a₁+x, a₂+k) - f(a₁+x, a₂),
    тогда по теореме лагранжа g(h)-g(0) → g'(h~)*h
    Тогда в общем Δ² = h(f'ₓ(a₁+h~, a₂+k) - f'ₓ(a₁+h~, a₂))
    зафиксируем h теперь, получим Δ² = f''_{xy}(a₁+h~, a₂+k~)*h*k
    Понятно, что порядок фиксирования переменных приводит к одинаковому
    результату, то есть f''_{xy} = f''_{yx}
** Полиномиальная формула
   (a₁ + ... + aₙ)ʳ = ∑{i:|i|=r}(r!/i!*aⁱ)

*** Докзаательство
    Давайте доказывать индукцией по r:
    * База
      r = 1 очевидно вроде да.
    * Переход (пусть верно для r)
      (a₁+...+aₘ)ʳ⁺¹ = (a₁+...+aₘ)*∑(r!/(i₁!*...*iₙ!))*a₁!*...*aₙ!
      = раскроем первую скобку, получим кучу сумм в которых каждый
      aᵢ имеет степень на одну больше.
      сделаем замену в каждой сумме, i ~ k, такую что (i₁...iₙ)
      преобразуется в (k₁...kₙ), где kᵢ для i-й суммы ≥ 1, а все
      остальные 0, тогда в итоге сложим все суммы и получим
      ∑r!(k₁+...+kₘ)/(k₁!k₂!...kₘ!) * a₁ᵏ¹*...aₘᵏᵐ = ∑(r+1)!/... * ...
** X Лемма о дифференцировании ``сдвига''
   f: E ⊂ ℝᵐ → ℝ, E открытое, f ∈ Cʳ(E), a ∈ E, фикс. h ∈ ℝᵐ
   φ(t):=f(a+th), t ∈ [-1, 1], h мал.
   * ∀k≤r φ⁽ᵏ⁾(0) = ∑{i:|i|=k}(k!/i!*hᵏ*f⁽ⁱ⁾(a)

*** Доказательство
    φ'(t) = f'(a+th) * t = f'ₓ₁(a+th)*t₁ + ... + f'ₓₘ(a+th)*tₘ
    = по индукции как-то видимо
** Многомерная формула Тейлора (с остатком в форме Лагранжа и Пеано)
   f: E ⊂ ℝᵐ → ℝ, E открытое r ∈ N, f ∈ Cʳ⁺¹(E),
   a ∈ E, B(a, g) ⊂ E
   * ∀ x ∈ B(a, g) ∃t ∈ (0, 0) |
     1. f(x) = ∑{k=0,r}(∑{i:|i|=k}1/i!*f⁽ⁱ⁾(a)(x - a)ⁱ) + ∑{i:|i|=r+1}(1/i!*f⁽ⁱ⁾(a + t(x - a))(x-a)ⁱ)
     2. f(x) = ∑{|i|=0,r}(1/i!*f⁽ⁱ⁾(a)(x-a)ⁱ) + f⁽ʳ⁺¹⁾(a~)/(r+1)!*(x-a)ʳ⁺¹

*** Доказательство
    1. x = a + h
       φ(t) = f(a + th)
       Заюзаем одномерную формулу тейлора.
       f(x) = φ(0) + φ'(0) + φ''(0)/2! * 1² + ... + φ⁽ʳ⁺¹⁾(t)/(r+1)! =
       ∑{k=0,r}∑(1/i!*f⁽ⁱ⁾(a)(x-a)ⁱ) + ∑{i:|i|=r+1}(1/i! * f⁽ⁱ⁾(a+t(x+a))(x-a)ⁱ)
    2. Ну и типа можно остаток выбрать другой, тогда преобразуется чуть иначе
** Теорема о пространстве линейных отображений
   L(X, Y) - пространство линейный отображений
   * ∥.∥ обладает всеми свойствами нормы
     1.  ∥A∥ ≥ 0, =0 только если A = 0
     2.  ∥λA∥ = |λ|∥A∥
     3. ∥A + B∥ ≤ ∥A∥ +  ∥B∥
   * A ∈ L(X,Y), B ∈ L(Y,Z) => ∥AB∥ ≤ ∥A∥*∥B∥

*** Доказательство
    1. Норма
      1. Очевидно из определения sup|..|
      2. ∥λA∥ = sup(|λA|) = |λ|sup(A) = |λ|*∥A∥
      3. ∥A+B∥ = sup(|Ax| + |Bx|) ≤ sup|Ax| + sup|Bx| = ∥A∥ + ∥B∥
    2. |B * Aₓ| ≤ ∥B∥*|Ax| ≤ ∥B∥∥A∥*|x|
** Лемма об условиях, эквивалентных непрерывности линейного оператора
   X, Y - нормированные пространства, A:X→Y, A ∈ L(X,Y)
   * Эквивалентно:
     0. А ограничен
     2. A непрерывен в нуле
     3. A непрерывен всюду
     4. A равномерно непрерывен (∀ε>0 ∃δ>0 ∀x₁,x₂∈X |x₁-x₂|<δ |Ax₁-Ax₂|<ε)

*** Доказательство
    4→3→2 очевидно
    2→1:
    Возьмем определение непрервыности в 0:
    ε=1, ∃δ>0 ∀x:|x|<δ |Ax|<1
    δ|Ax| = |A(δx)| < 1 (по непрерывности, δx < x),
    то есть |Ax| ≤ 1/δ => sup|Ax| ≤ 1/δ => ||A|| ≤ 1/δ
    1→4
    Короче |Ax₁-Ax₂| = |A(x₁-x₂)| ≤ ||A|| * |x₁ - x₂| по свойству
    Ну и типа ∀ε>0 ∃δ = ε/||A||, тогда |x₁ + x₂| < ε/||A||, тогда
    эта фигня ||A|| * |x₁ - x₂| < ε
** Теорема Лагранжа для отображений
   F:E ⊂ ℝᵐ → ℝⁿ, B(a,r) ⊂ E, F дифф в B(a,r), x ∈ B(a,r)
   * ∃c∈(a,x) (отрезок) | c = a + Θ(x-a); 0 < Θ < 1 : |F(x)-F(a)|≤∥F'(c)∥*|x-a|

*** Доказательство
    f(t) = F(a + t(x-a))  t ∈ [0, 1]
    f'(t) = F'(a + t(x-a))(x-a)
    Тогда |F(x) - F(a)| = |f(1) - f(0)| ≤ |f'(θ)| * 1
    = (F'(a + θ(x-a))(x-a)| ≤ ||f'(a + θ(x-a))|| * |x - a|
** Теорема об обратимости линейного отображения, близкого к обратимому
   ]L∈Ωₘ, M∈Lₘₘ: ∥M-L∥ < 1/∥L⁻¹∥
   1. M ∈ Ωₘ
   2. ∥M⁻¹∥ ≤ 1/(∥L⁻¹∥⁻¹ - ∥M-L∥)
   3. ∥M⁻¹-L⁻¹∥ ≤ ∥L⁻¹∥ * ∥M - L∥ / (∥L⁻¹∥⁻¹ - ∥M-L∥)

*** Доказательство
    1. Лемма
       A ∈ Lₘₘ, ∃c>0, ∀x ∈ ℝᵐ |Ax| ≥ C|x|,
       тогда A ∈ Ωₘ, ∥A∥⁻¹ ≤ c

       Имеем |Ax| ≥ C * |x| <=> 1/c * |y| ≥ |A⁻¹y| => ∥A⁻¹∥ ≤ 1/c
       И вообще |x| = |A⁻¹Ax| ≤ ∥A⁻¹∥*|Ax| => |Ax| ≥ |x|/∥A⁻¹∥
    2. |Mx| = |Lx + (M-L)x| ≥ |Lx| - |(M-L)x| ≥ 1/∥L⁻¹∥|x| - ∥M-L∥|x| =>
       Тогда |Mx| ≥ C|x| (C из пред. строки)
       Отсюда проверка на kerA = 0 такая: ∥A∥ = 0 => C|x| ≤ 0 = 0 => |x| = 0
    3. Из |Mx| ≥ C|x| с помощью 1 пункта леммы: ∥M⁻¹∥ ≤ 1/(∥L⁻¹∥⁻¹ - ∥M-L∥)
    4. ∥M⁻¹-L⁻¹∥ = ∥L⁻¹(L-M)M⁻¹∥ ≤ ∥L⁻¹∥*∥L-M∥*∥M⁻¹∥ ≤ ∥L⁻¹∥*∥L-M∥/(∥L⁻¹∥⁻¹ - ∥M-L∥)
** Теорема о непрерывно дифференцируемых отображениях
   Производная гладкой функции непрерывна
   F: E_откр ⊂ ℝᵐ → ℝⁿ дифф на Е
   F': E → Lₘₙ:
   * Эквивалентно:
     1. fᵢ ∈ C¹(E, ℝⁿ)
     2. F':E → Lₘₙ непрерывно

*** Доказательство
    1. 1→2
       ∥F'(x) - F'(x₀)∥ ≤ √(∑(∂fᵢ(x)/∂xⱼ - ∂fᵢ(x₀)/∂xⱼ)²) ≤ √(∑(ε²/mn)) = ε
       (первое неравенство по лемме об оценке линейного оператора)
       (по выбору окрестности xⱼ можем сделать, поскольку по дифференцируемости
       частные производные довольно близкo)
    2. 2→1
       ∥F'(x) - F'(x₀)∥ ≤ ε
       Тогда по лемме из предыдущего |(F'(x) - F'(x₀))*h| ≤ ∥F'(x)-F'(x₀)∥*|h| < ε
       где h = (0,..,1,...0)
       Тогда для h с единичкой на k-m месте |(F'(x)-F'(x₀))*h| = ∂f(x)/∂xₖ - ∂f(x₀)/∂xₖ < ε
** Лемма об оценке квадратичной формы и об эквивалентных нормах
   Q - положительно определенная кв.ф. в ℝᵐ. Тогда ∃γ_q>0: ∀h Q(h) ≥ γ_q|h|²
   p: ℝᵐ → ℝ - норма. Тогда С₁, C₂ > 0 ∀ x C₁|x| ≤ p(x) ≤ C₂|x|

*** Доказательство
    1. Возьмем в качестве γ_q=min{h:|h|=1}Q(h)
       (существует по теореме Вейерштрасса, {x | |x| = 1} - компакт), тогда
       Q(h) = |h|²Q(h/|h|) ≥ |h|²*γ_q
    2. C₁ = min{|x|=1}p(x), C₂=max(-//-),
       тогда если p(x) непрерывно, то
       p(x) = |x|*p(x/|x|) ≤ |x|*C₂; Аналогично C₁*|x| ≤ p(x)
       Значит докажем непрерывность p(x)
       p(x) - p(y)
       ≤ p(x - y)                        по треугольнику
       = p(∑((xₖ-yₖ)eₖ))                eᵢ - элемент ортонорм. базиса
       ≤ ∑p((xₖ-yₖ)eₖ)
       = ∑|xₖ-yₖ|p(eₖ)
       ≤ M∑|xₖ-yₖ| ≤ M|x-y|√m           M = max(p(e₁), p(e₂)...)
** Теорема Ферма. Необходимое условие экстремума. Теорема Ролля
   1. f: E ⊂ ℝᵐ → ℝ, x₀ ∈ Int(E), x₀ экстремум,
      тогда ∀l ∈ ℝᵐ | ∥l∥ = 1 | ∂f/∂l(x₀) = 0
   2. f'(x₀) = 0
   3. f:E ⊂ ℝᵐ → ℝ, непрерывно на закрытом шаре, дифференцируемо на открытом,
      на сфере константа, тогда ∃a ∈ B | f'(a) = 0

*** Доказательство
    1. l - прямая {x₀ + tl, t ∈ ℝ}, f|ₗ имеет в точке 0 локальный экстремум
       g(t) = f(x₀ + tl), g'(0) = 0 по одномерной теореме Ферма.
    2. Прямое следствие из теоремы Ферма – если ч. производная по любому
       направлению нуль, тогда и по xᵢ.
    3. B - компакт, f - непрерывна => ∃max, min => ∃a ∈ B(x₀, r) точка экстремума,
       тогда f'(a) = 0
** X Достаточное условие экстремума
   f: E ⊂ ℝᵐ → ℝ, B(x₀, r) ⊂ E, f ∈ C²(B(x₀, r)), f'(x₀) = 0 (∇x₀ = 0)
   1. d²f(x₀, h) = Q(h) - пол.опр.кв.ф => x₀ - точка минимума (строгая)
   2. -//-//-//-//-//-//- отр. -//-//-//-//-//-//-// максимума -//-//-/
   3. неопределенная форма - нет экстремума

*** Доказательство
    x, x₀, h = x - x₀ ∈ ℝᵐ
    1. f(x) - f(x₀) =
       = 1/2∑f''xᵢxⱼ(x₀+th)            (формула Тейлора в du до 2 слаг. - 1 слаг = 0 по усл.)
       = 1/2∑(f''ₓᵢₓᵢ(x₀ + th) - f''ₓₓ(x₀)) + 2∑(f''ₓᵢₓⱼ(x₀ + th) - f''ₓᵢₓⱼ(x₀))*hᵢ*hⱼ)
** Лемма о "почти локальной инъективности"
   Диффеоморфизм не может склеить точки

   F: O(откр) ⊂ ℝᵐ → ℝᵐ диффеоморфизм, x₀ ∈ O, detF'(x₀) ≠ 0
   * ∃ c > 0, δ > 0 | ∀ x | ro(x,x₀) < δ | |F(x) - F(x₀)| ≥ c|x - x₀|

*** Доказательство
    1. F - линейное отображение, тогда F' = F (F(a+h) = F(a) + F(h) = F(a) + F'(h) + o(...))
       Тогда |x-x₀| = |F⁻¹(F(x-x₀))| ≤ ∥F⁻¹∥*|F(x-x₀)|
       Видим, что |F(x-x₀)| ≥ C * |x-x₀| (C = 1/∥F⁻¹∥)
    2. F(x) - F(x₀) = F'(x₀)(x-x₀) + α(x)|x-x₀|           (по определению производного оператора)
       ̣|F(x) - F(x₀)| ≥ |F'(x₀)(x-x₀)| - |α(x)|*|x-x₀|
       ≥ 1/∥(F')⁻¹∥*|x-x₀| - |α(x)|*|x-x₀|              (тут переход по пункту 1)
       = |x-x₀|*(1/∥(F')⁻¹∥ - α(x)) = C * |x-x₀|
** Теорема о сохранении области
   Невырожденный в обалсти диффеоморфизм сохраняет
   еe (не портит ее свойства)

   F: O_откр ⊂ ℝᵐ → ℝᵐ, F - диффеморфизм в О, ∀x ∈ O det F'(x) ≠ 0
   * F(O) открыто
*** Доказательство
    y₀ ∈ F(b), y₀ = f(x₀)
    По лемме о почти локальной инъективности ∃C,δ |F(x)-F(x₀)|≥C|x-x₀| при |x-x₀|<δ
    Таким образом F(x) ≠ F(x₀)
    r = 1/2*dist(F(x₀), F(S(x₀, δ))) = inf(|F(x₀)-F(x)|, x ∈ S(x₀, δ)) > 0
    по теореме Вейерштрасса, так как S компакт, inf конечен
    Проверим, что B(y₀, r) ∈ F(O)
    y ∈ B(y₀, r) ?=> ∃x: y = F(x)
    g(x) = |F(x) - y|² = (f₁(x) - y₁)²+...+(fₘ(x)-yₘ)² для x ∈ B(x₀, δ)
    Тогда min(g(x)) существует по теореме Вейерштрасса, поскольку
    непрерывный (сумма непрерывных функций) образ компакта  – компакт.
    Значит в минимуме производная g(x) равна нулю
    Тогда g(x₀) = |F(x₀) - y|² = |y₀ - y|² < r²
    Напишем типа систему для этого в точке минимумa, там каждая
    компонента будет равна нулю, то есть
    2(f₁ - y)*∂f₁/∂x₁ + ... + 2(fₘ - y)*∂fₘ/∂x₁ = 0
    Система не вырождена, значит (по известной теореме ЛА) она имеет только нулевое
    решение, то есть fᵢ = y, тогда g(x) = 0, то есть в этой самой точке минимума
    fᵢ = y, то есть мы нашли такой x для y, что F(x) = y.
** 0 Теорема о диффеоморфизме
   Если наше ображение дифференцируемо на O, обратимо, невырожденно,
   то таково и его обратное отображение.
   А еще есть биекция между их производными

   O ⊂ ℝᵐ, F ∈ C'(O, ℝᵐ), F - обратимо, невырожденно (det F' ≠ 0)
   * F⁻¹∈ C'(F(O), ℝᵐ), ∀x | y = F(x), (F⁻¹)'(y) = (F'(x))⁻¹

*** Доказательство

** Лемма об оценке линейного приближения
   F ∈ C¹(O, ℝᵐ); x₀ ∈ O
   * |F(x) - F(x₀) - F'(x₀)(x-x₀)| < sup{z ∈ [x₀, x]}(∥F'(z) - F'(x₀)∥) * |x - x₀|

*** Доказательство
    Имеем |T(x) - T(x₀)| ≤ ∥T'(c)∥ * |x-x₀| (теорема Ферма для отображений)
    T(x) := F(x) - F'(x₀)x
    T'(z) = F'(z) - F'(x₀)
    T(x) - T(x₀) = F(x) - F'(x₀)*x - F(x₀) + F'(x₀)*x₀ = F(x) - F(x₀) + F'(x₀)(x₀ - x)
    И вот эта вся фигня меньше чем ∥T'(c)∥ * |x-x₀| по теореме Ферма
** 0 Теорема о локальной обратимости
   Если нам не хватает условия обратимости для функции до диффеоморфизма,
   то можно смело утверждать, что сужение ок в окрестности любой точки
   для которой верно, что в ней производный оператор не вырожден

   F ∈ C¹(O, ℝᵐ); x₀ ∈ O; det(F'(x₀)) ≠ 0
   * ∃U(x₀) | F|ᵤ₍ₓ₀₎ - диффеоморфизм

*** Доказательство

** 0 Теорема о неявном отображении
   Возьмем для F точку, что он в ней ноль, а его производная по y обратима
   Тогда мы можем найти две окрестности, установить между ними биекцию
   φ, такую, что F(x, φ(x)) = 0, при этом φ той же гладкости что и F,
   умеем выражать φ'.

   F: E ⊂ ℝᵐ⁺ⁿ → ℝⁿ; F ∈ Cʳ(E, ℝⁿ), a ∈ ℝᵐ, b ∈ ℝⁿ, (a, b) ∈ E, F(a, b) = 0ₙ
   F'_y(a, b) обратима (det F'_y(a, b) ≠ 0)
   * ∃ P(a) - окрестность в ℝᵐ, Q(b) - окрестность в ℝⁿ,
     φ: P → Q (ф(a) ↦ b) | ∀ x ∈ P(a) F(x, φ(x)) = Oₙ
     При этом ф ∈ Cⁿ, φ'(a) = -(F'_y(a, b))⁻¹ * F'_x(a, b)
** 0 Теорема о задании гладкого многообразия системой уравнений
** 0 Необходимое условие относительного локального экстремума
   Φ, f из условия относительного экстремума, a - точка локального экстремума
   rang Φ(a) = k
   * ∃ λ=(λ₁...λₖ) ∈ ℝᵏ | f'(a)-λΦ'(a) = 0 && Φ(a) = 0
** Вычисление нормы линейного оператора с помощью собственных чисел
   A ∈ Lₘₙ
   * ∥A∥ = max {√λ, где λ - сч Aᵀ*A}

*** Доказательство
    ∑aᵢⱼxᵢxⱼ=λ(x₁²+...)
    AᵀAx = λx
    <AᵀAx, x> = <Ax, Ax> = |Ax|²
    ∥A|| = sup|Ax| = max|Ax| = max√(<AᵀAx, x>) = √(max<AᵀAx ,x>) = тому что надоλ
** ---------------------------------------------------------------------------
** Простейшие свойства интеграла векторного поля по кусочно-гладкому пути
   1. Линейность по полю I(αV+βU, γ) = αI(V, γ)+...
   2. Аддитивность по пути: берем дробление, γ₁ = γ|_[a, c], γ₂ = γ|_[c, b]
      I(V, γ) = I(V, γ₁) + I(V, γ₂)
   3. Замена параметра
      γ~ = γ∘φ (φ:[p, q] → [a, b], φ(p) = a, φ(q) = b, φ ∈ C¹)
      I(V, γ) = I(V, γ~)
   4. Объединение носителей
      γ~: [a, b] → ℝᵐ, γ~~: [p, q] → ℝᵐ, γ~(b) = γ~~(p), γ = γ~∘γ~~ (понятно как)
      γ: [a, q - p + b], тогда I(V, γ) = I(V, γ~) + I(V, γ~~)
   5. Противоположный путь
      γ: [a, b] → ℝᵐ, γ₋: [a, b] → ℝᵐ, γ₋(t) = γ(b - t + a)
      I(V, γ₋) = -I(V, γ)
   6. Оценка
      γ: [a, b] → ℝᵐ, гладкий
      L := γ([a, b]), l(γ) - длина пути
      Тогда |I(V, γ)| ≤ max{x ∈ L}(|V(x)|*l(γ))

*** Доказательство
    1. Следует из линейности интеграла и скалярного произведения
    2. Следует из свойств обычного интеграла и скалярного произведения
    3. I(V,γ)[t:=φ(s)] = ∫(V(γ(φ(s)))*γ'(φ(s)) + ... ) * φ'(s)*ds = точтонужно
    4. Следует из ∫{a,c} + ∫{c,b} = ∫{a,b}
    5. ∫<V(γ(t)), γ'(t)>dt = ∫<V(γ(b-s+a)), γ'(b-s+a)> (-1)ds = -∫
    6. ∫ ≤ ∫|V(γ(t))|*|γ'(t)|dt ≤ max|V(x)|*∫|γ'(t)|dt = max|V(x)|*l(γ)
** Обобщенная формула Ньютона-Лейбница
   V: O ⊂ ℝᵐ → ℝᵐ потенциальное, f: O → ℝ
   γ: [a, b] → O - кусочно-гладкий путь
   A = γ(a), B = γ(b)
   * ∫_γ(V₁dx₁+...) = f(B) - f(A)

*** Доказательство
    Vᵢ=f'ₓᵢ
    ∫(V₁γ₁+V₂γ₂+...)*dt = ∫(f'ₓ₁*γ₁ + ...)dt = ∫f'(γ(t))dt
** Характеризация потенциальных векторных полей в терминах интегралов
   V: O → ℝᵐ - гладкое векторное поле, тогда эквивалентно:
   1. V потенциально
   2. Интеграл V не зависит от пути в O
   3. Интеграл по любой петле равен 0

*** Доказательство
    1. 1→2
       Юзаем формулу Ньютона лейбница, видим, что важен только конец и начало
    2. 2→3, 3→2
       Очевидно, 3 частный случай 2
       А из 3 можно вывести 2
    3. 2→1
       Зададим x₀, F(x) = ∫{γₓ}(∑(Vᵢdxᵢ))
       Проверим, что F(x) потенциал - докажем, что ∂fᵢ/∂x₁ = Vᵢ
       F'_{x₁}(x) = lim(F(x+hc)-F(x))/h
       = lim 1/h * ∫∑Vᵢdxᵢ          (считаем разность интегралом по линейному пути)
       = lim 1/h * ∫V₁(x₁+t, x₂...)dx₁ = V₁
** Лемма о дифференцировании интеграла по параметру
   f: [a, b]×[c, d] → ℝ
   ∀(x, y) ∃ f'_y(x, y) - непрерывно на [a, b]×[c, d]
   Φ(y) = ∫ₐᵇf(x, y)dx
   * Φ(y) - дифф на [c, d] и Φ'(y) = ∫ₐᵇf'_y(x, y)dx

*** Доказательство
    Φ'(y) = lim∫(f(x, y+h) - f(x, y))/h
    = lim∫f'_y(x, y+ch)dx                    по одномерной теореме Лагр.
    Сравним: |∫f'_y(x,y + ch) - f'_y(x,y)dx|
    ≤ ∫|f'_y(x,y+ch)-f'_y(x,y)|dx
    ≤ ∫εdx = ε(b-a)                          по непрерывности замену
** Необходимое условие потенциальности гладкго поля. Лемма Пуанкаре
   V - гладкое векторное поле в области О, потенциальное
   * ∀x ∈ O ∀i, j ∈ 1...m ∂Vᵢ/∂xⱼ(x) = ∂Vⱼ/∂xᵢ(x)

   O ⊂ ℝᵐ - выпукла, V: O → ℝᵐ - гладкое, удовл. свойству выше
   * V - потенциально в O

*** Доказательство
    1. Если F - потенциал, то для него
       ∂Vᵢ/∂xⱼ(x) = ∂²F/∂xⱼ∂xᵢ = ∂Vⱼ/∂xᵢ(x)
    2. A ∈ O
       γ(t) = A + t(x-A), t ∈ [0, 1],
       γ' = x - a
       F(x) = ∫_γ∑Vᵢdxᵢ = ∫∑Vᵢ(A+t(x-A)) * (xᵢ-Aᵢ)dt
       ∂F/∂xₖ = ∫{0,1}(∑[∂Vₗ(A+t(X-A))/∂xₖ * t] + Vₖ(A+t(x-A)))dt     тут мы типа произв. и комп. продифф.
       = ∫{0,1}(t∑[...] + Vₖ(a+t(x-A)))dt
       = ∫{0,1}(t*Vₖ(A+t(x-A)))'ₜdt = t*Vₖ(A+t(x-A))|^1_0 = Vₖ(x)
** Лемма о гусенице
   γ: [a, b] → O ∈ ℝᵐ - непрерывный путь, ε > 0,
   * ∃ разбиение a = t₀ < t₁ < ... < tₘ = b,
     ∃ набр шаров Bₙ, радиуc < ε, ∀k ∈ 1...m γ([tₖ₋₁,tₖ]) ⊂ Bₖ
*** Доказательство
    t ∈ [a,b], возьмем шар Bₜ с центром γ(t), радиуса <ε ∈ O
    Возьмем такой промежуток [αₜ, βₜ], что γ(...) ∈ Bₜ (если βₜ=b, то [), или (] наоборот)
    Получим покрытие t ↦ (αₜ, βₜ), опять таки с оговоркой про концы
    Возьмем конечное подпокрытие.
    выкинем все такие промежутки, которые полностью содержатся
    в объединении каких-либо других
    ∀(αᵢ, βᵢ) из оставшихся ∃dᵢ такой что он принадлежит только этому отрезку
    Составим соответствие dᵢ ↔ (αᵢ, βᵢ), между каждыми соседними dᵢ, dᵢ₊₁ поставим
    tᵢ, чтобы она принадлежала пересечению промежутков
    Тогда tᵢ, Bᵢ искомые.
** Лемма о равенстве интегралов по похожим путям
   γ, γ~: [a, b] → O ∈ ℝᵐ кусочно-гладкие, похожие, совпадают начала и концы
   V - локально потенциально векторное поле в О
   * I(V, γ~) = I(V, γ)

*** Доказательство
    Возьмем общую гусеницу, пройдемся по пути и каждые
    соседние потенциалы в шарах "уравняем" -- они могут
    быть разные у соседних шаров, но всегда отличаются на константу.
    Тогда I(V, γ)=∑{по всем шарикам}∫[∑Vᵢdₓᵢ] = телескопом
    = pₙ(γ(tₙ)) - p₁(γ(t₀))
    С другой стороны I(V, γ~) = то же самое с телескопом
    = pₙ(γ~(tₙ)) - p₁(γ~(t₀))
    Поскольку у путей по условию начала и концы совпадают, то эти штуки равны.
** Лемма о похожести путей, близких к данному
   γ: [a, b] → O ⊂ ℝᵐ, непрерывный
   ∃ δ > 0 ∀ γ~, γ~~: [a, b] → O | ∀t ∈ [a, b] |γ(t) - γ~(t)| < δ, |γ(t) - γ~~(t)| < δ
   * γ~ и γ~~ похожи (в гусеничном плане)

*** Доказательство
    Для основного пути γ уже существует гусеница.
    γ[tₖ, tₖ₊₁] - компакт в Bₖ
    Утверждвается, что ∃δₖ>0, δₖ=dist(γ[tₖ,tₖ₊₁], ∂Bₖ);
    g(t) = dist(γ(t), ∂Bₖ)
    δ = min δₖ
    ∃δ ∀t ∈ [t_k-1, t_k] B(γ(t), δ) ⊂ Bₖ
    t ↦ dist(γ(t), ∂Bₖ) непрерывна
    Тогда типа вот мы возьмем по всему пути δ = δ_min,
    оно будет нам подходить
** Равенство интегралов по гомотопным путям
   V - локально потенциальное векторное поле в ℝᵐ,
   тогда для двух гомотопных путей γ, γ~:
   ∫{γ}(∑Vᵢdxᵢ) = ∫{γ~}(∑Vᵢdxᵢ)

*** Доказательство
    Γ - гомотопия между путями
    определим промежуточным путь γₛ(t) = Γ(t, s)
    Φ(s) = ∫{γₛ}(∑Vᵢdxᵢ): [0,1] → ℝ
    Проверим, что Φ - локально постоянна (для любой окрестности s Φ не меняется)
    Г у нас равномерно непрерывна (она действует с компакта [a,b]×[0,1] и непр.)
    Тогда по модной теореме кантора равномерная непрерывность есть:
    ∀δ>0 ∃ξ>0 ∀(t₁,s₁),(t₂,s₂)∈[a,b]×[0,1] |t₁-t₂|<ξ & |s₁-s₂|<ξ ⇒ |Г(t₂,s₂) - Γ(t₁,s₁)|<δ/2
    На основании равномерной непрерывности мы всегда можем доказать, что пути будут достаточно
    близко при близких s, ну возьмем какую-нибудь точку s₀, для каждого t проведем такую
    операцию:
    Для s₀ найдем по 3 лемме два похожих близких путя - нам дали δ, мы построили по непрерывности
    Γ два путя -- Г(t, s₀), Г(t, s₀+ε), ну тогда повторим операцию для второго путя и докажем
    что все пути на гомотопии похожие, значит у них интегралы равны по лемме 2, значит у них
    вообще все круто и мы все доказали.
** Почему резиночку нельзя снять с гвоздика
   В поле с дыркой посередине не любая петля стягивается.

*** Доказательство
    Возьмем поле V = (-y²/(x²+y²), -x²/(x²+y²))
    Оно потенциально (производная левого по y равна произв. правого по x)
    Возьмем путь x=cosφ, y=sinφ, тогда
    ∫(sin² + cos²)dφ = 1|^2π_0 = 2π
    А так бы ноль получился.
** ------------------------------------------------------------------------------
** Свойства объема: усиленная монотонность, конечная полуаддитивность, "субтрактивность"
   μ: P -> ℝ
   * Усиленная монотонность: ⊔Ak ⊂ A; Akᵢ, A ∈ P => ∑{n}μAₖ ≤ μA
   * Конечная полуаддитивность A ⊂ ⋃A; A, Aki ∈ P => μA ≤ ∑{n}μAₖ
   * A, B, A\B ∈ P; μ(A\B) < +∞ => μ(A\B) ≥ μA - μB, а если B⊂A, то равно

*** Доказательство
    1. По свойству полукольца A \ ⊔Aᵢ = ⊔Bᵢ, тогда μA = ∑μAᵢ + ∑μBᵢ =>
       μA ≥ ∑μAᵢ
    2. Bₖ = A ∩ Aₖ ⊂ P
       C₁ = B₁,
       Cₖ = Bₖ\(⋃Bᵢ) всех до k
       В свою очередь Cₖ = ⊔Dᵢ по свойству полукольца
       A = ⊔Cₖ
       A = ⊔Dₖⱼ
       μA = ∑μDₖⱼ, тогда по пункту 1, исходя из ⊔Dₖⱼ ⊂ Cₖ ⊂ Bₖ ⊂ Aₖ
       ∑μDₖⱼ ≤ ∑μAₖ => μA ≤ ∑μAₖ
    3. Если B⊂A:
       A=B⊔(A∖B)
       μA=μB+μ(A∖B)
       μ(A∖B)=μA−μB

       В общем случае:
       C:=A∩B
       C⊂B ⇒ μC≤μB
       C⊂A ⇒ μ(A∖C)=μA−μC
       A∖C = A∖B (можно картинку нарисовать, чтобы понять)
       μ(A∖B) = μ(A∖C) = μA−μC ≥ μA−μB
** Теорема об эквивалентности счетной аддитивности и счетной полуаддитивности
   μ: P → ℝ~, μ - объем, тогда эквивалентно:
   1. μ - мера (счетно-аддитивна)
   2. μ - счетно полуаддитивна (μA ≤ ∑...)

*** Доказательство
    1. 1→2
       Доказывается как пункт 2 свойств объема
    2. 2→1
       A ⊂ ⊔Aᵢ => A ⊂ ∪Aᵢ, μA ≤ ∑{n}Aᵢ, n → inf =>
       по конечной полуаддитивности μA ≤ ∑{∞}μAᵢ
       ⊔Aᵢ ⊂ A => по усиленной монотонности μA ≥ ∑{∞}μAᵢ
       μA ≥ ∑{∞}μAᵢ & μA ≤ ∑{∞}μAᵢ → μA = ∑{∞}μAᵢ
** Теорема о непрерывности снизу
   A - алгебра, μ: A -> ℝ~, тогда эквивалентно
   1. μ - мера
   2. μ непрерывна снизу (A₁ ⊂ A₂ ...; A; Aᵢ ⊂ A; A = ⋃Aᵢ; => μA = lim{n→∞}(μAₙ))

*** Доказательство
    1. 1→2
       Bᵢ = Aᵢ, Bₖ = Aₖ\Aₖ₋₁
       A = ⊔Bᵢ, μA = ∑{i=1,∞}μBᵢ = lim{n→∞}(∑{i=1,n}μBᵢ) = lim(μAₙ)
    2. 2→1
       По условию уже объем есть, докажем счетную аддитивность
       C = ⊔Cᵢ
       D₁ = C₁, D₂ = C₁⊔C₂
       D∞ = C
       μC = lim(μDₙ) = lim(∑{1,n}μCᵢ) = ∑{∞}Cᵢ
** Формулировка теоремы о лебеговском продолжении меры
   μ₀ - конечный σ-объем на P₀;
   * ∃ σ-алгебра A : P ⊂ A, мера μ: A → ℝ~:
     1. μ - продолжение μ₀ ∈ P₀ на A
     2. μ - полная мера
     3. Минимальность: μ~ - мера на σ-алгебре A~, тогда A ⊂ A~ & μ~|ₐ = μ
     4. Сужение на полукольцо поменьше
        P₁ - полукольцо. P₀ ⊂ P₁ ⊂ A, μ₁ - продолжение μ₀ на P₁, тогда μ|ₚ₁ = μ₁
     5. ∀a∈A  μ(a)=inf{∑μPₖ, a⊂⋃{inf}Pₖ, Pₖ∈P₀}

   Без доказательства
** Счетная аддитивность классического объема
   μ - классический объем в ℝᵐ
   * μ - σ-конечная мера на Pᵐ

*** Доказательство
    1. Докажем сигма-конечность
       Очевидно, мы можем умостить все ℝⁿ такими штуками ⋃[-n,n]ⁿ
    2. Докажем счетную аддитивность
       По лемме о эквивалентности счетной аддитивности и полуаддитивности докажем
       полуаддитивность:
       P ⊂ ⋃Pₖ ?=> μP ≤ ∑μPₖ
       P = [a, b) ⊂ ⋃{∞}[aₖ, bₖ)
       выберем b', a'ₖ:
       [a, b'] ⊂ [a, b) ⊂ ⋃{∞}[aₖ, bₖ) ⊂ ⋃(a'ₖ, bₖ)
       подберем b' так чтобы μ[a,b) - μ[a,b') < ε
       Тогда ∃ конечный набор kᵢ:
       [a, b') ⊂ [a, b'] ⊂ ⋃{N}[a'ₖᵢ, bₖ) ⊂ ⋃{∞}[a'ₖᵢ, bₖ)
       μ[a, b') ≤ ∑μ[aₖᵢ', bₖᵢ)
       μ[a, b) - ε ≤ ∑μ[aₖᵢ, bₖᵢ) + ε
** X Лемма о построении открыого множества с помощью ячеек
   А открыто, тогда
   1. ∃ дизъюнктивные ячейки P₁... | A = ⊔Pₖ
   2. Можно считать, что Pᵢ - кубы, вершины которых имеют двоично-рациональные
      координаты, Pᵢ~ ⊂ A
   3. E измеримо. λE = 0, ∀ε> 0 ∃Pᵢ - кубические ячейки E ⊂ ⊔Pᵢ | ∑λPᵢ < ε

*** Доказательство
    Для любого x возьмем какую-нибудь ячейку P(x) с рацион. коорд.:
    x ∈ P(x) ⊂ A
    Возьмем такое не более чем счетное множество различных ячеек и все перенумеруем:
    ⋃{∞}Rᵢ
** Пример неизмеримого по Лебегу множества
   Множество Витали
   Введем эквивалентность на [0,1] X ~ Y если X-Y рационально.
   Возьмем множество представителей Е - оно неизмеримо.

*** Доказательство
    Пусть E - множество представителей класса эквивалентности ~
    на [0, 1]
    [0, 1] ⊂ ⊔{q ∈ Q∩[-1,1]}(E+q) ⊂ [-1, 2]
    Пусть E измеримо и μE = 0, тогда мера [0, 1] тоже 0
    Пусть E измеримо и μE > 0, тогда в силу счетной аддитивности μ[-1,2] = +∞
** Регулярность меры Лебега
   A ⊂ Mᵐ
   * ∀ε>0 ∃G - открыт., F - замкн. | F⊂A⊂G => λ(G\F) < ε - плохая формулировка
   * λ(A) = inf{λ(G), A ⊂ G, G открыто} = sup{λ(F), F ⊂ A, F компактно}
*** Доказательство
    Короче первый факт на inf достигается через 5 пункт теоремы о продолжении
    меры -- μ(A) = inf{∑μ(Pₖ), A ⊂ ⋃Pₖ, Pₖ ∈ P₀}
    Построим из Pk открытое множество по лемме о построении открытого множества с помощью
    ячеек, ну и короче для него работает.
    для закрытого возьмем его дополнение, оно будет открытым и удовлетворять 1 пункту
** Лемма о прообразе меры
   (X', A', μ), (X, A), T: X → X';
   ∀a ∈ A T(a) ∈ A'; ]T(X) = X'; ] ν(a)=μ(T(a)) для a ∈ A
   * ν - мера

*** Доказательство
    ν(⊔Aᵢ) = μ(T(⊔Aᵢ)) = μ(⊔T(Aᵢ)) = ∑μT(Aᵢ) = ∑ν(Aᵢ)
** Лемма о сохранении измеримости при непрерывном отображении
   T: ℝᵐ → ℝᵐ - непрерывно
   ∀c ∈ Mᵐ λₘ(c) = 0; λₘ(T(c)) = 0
   * ∀ A ⊂ Mᵐ T(A) измеримо по Лебегу

*** Доказательство
    1. A ∈ Mᵐ, A ограничено.
       Тогда A = (⋃{∞}Bₖ)⊔C, где λC = 0, Bₖ компактны
       T(A) = T(⋃Bₖ⊔C) = ⋃T(Bₖ) ∪ T(C), тогда первое компактно по непрерывности
       Т, а второе по условию измеримо.
       Если компактно, то замкнуто и ограничено, значит как дополнение открытого
       множества измеримо (дополнение это "\" в алгебре)
    2. A не ограничено, создаем клеточки
       A = ∪Aₖ, T(A) = ∪T(Aₖ)
** Инвариантность меры Лебега относительно сдвигов
   x₀ ∈ ℝᵐ, T: ℝᵐ → ℝᵐ - сдвиг (x ↦ x + x₀)
   * ∀A измеримого T(A) измеримо и λ(a) = λ(T(A))

*** Доказательство
    Сдвиг не меняет структуру ячейки, то есть λ(P) = λ(T(P))
    Покажем через предыдущую лемму, что если A | μA = 0,
    то T(A) = 0
    Теорема о продолжении, пункт 5:
    Опишем множество А: μA = inf{∑μPₖ, A ∈ ⋃Pₖ, Pₖ - ячейки}
    то есть ∀ε>0 ∃{Pₖ} A ∈ ⋃Pₖ, ∑μPₖ < ε
    На основании инвариантности ячеек относительно T:
    T(A) ⊂ ⋃T(Pₖ); ∑λT(Pₖ)<ε
    T(A) ⊂ ⋂U_{1/N}, где Uᵢ = ⋃T(Pₖ)
    но это пересечение -- измеримое множество меры 0
    T(A) = 0, тогда T(A) измеримо.
** Лемма о покрытии множества нулевой меры шарами
   C ∈ Mᵐ, λ(C) = 0, тогда
   * ∀ ε > 0 ∃ (Bₖ) - посл. шаров | C ⊂ ⋃Bₖ; ∑λBₖ < ε

*** Доказательство
    Что такое 1 строчка
    C ⊂ ⋃Gₖ ⊂ ⋃Bₖ ⊂ ⋃Qₖ   (первый переход по свойству 5 продолжения)
    Q(0,1) ⊂ B(0, √m/2) ⊂ Q(0, √m)
    Куб в нуле со стороной 1 вкладывается в шар в нуле с радиусом √m/2, в куб...
    ∑μBₖₗ < (меры большей ячейки, которая связана с меньшей условием на сторону)
    < (√m)^n * ε
** Инвариантность леммы Лебега при ортогональном преобразовании
   T: ℝᵐ → ℝᵐ - линейное ортогональное преобразование
   * ∀ A ∈ Mᵐ T(A) ∈ Mᵐ; λ(A) = λ(T(A))

*** Доказательство
    1. Измеримость
       T непрерывное
       Проверим для λA = 0
       Ортогональное преобразование для шара -- то же самое, что и сдвиг
       A ⊂ ⋃Bₖ, ∑λBₖ < ε
       T(A) ⊂ ⋃T(Bₖ)
       Так как преобразование ортогональное, то радиус шара сохр. то есть
       λ(T(Bₖ)) = T(λ(Bₖ))
       T(A) ⊂ B_{1/N}, тогда
       T(A) ⊂ ⋂B_{1/N}, уменьшаем шары, получим μT(A) < ε => μT(A) = 0
    2. μ = λ(T(A)) => измерима по пункту один этого д-ва
       μ - инвариантно относительно сдвига по лемме
       μ(a+A) = λ(T(a+A)) = λ(T(a) + T(A)) = λ(T(A))
       Значит ∃c: μ(A) = c*λ(A)
       поскольку ортогональное преобр. не трогает шары, c = 1:
       μ(B(0,1)) = ‌λ(T(B(0,1))) = λ(B(0,1)) => c = 1
** Теорема о сохранении измеримости при гладком отображении
   F: O ⊂ ℝᵐ → ℝᵐ; f ∈ C¹(O)
   * ∀ A ∈ Mᵐ, A ⊂ O F(A) измеримо
** Лемма о структуре компактного оператора
   V: ℝᵐ → ℝᵐ линейно, невырожденное.
   * ∃ h₁...hₘ, g₁...gₘ, s₁...sₘ > 0 | ∀ x V(x) = ∑₁ᵐ {sᵢ<x;gᵢ>hᵢ}
     и при этом |detV| = s₁*s₂*...
** Теорема о преобразовании меры Лебега при линейном отображении
   V: ℝᵐ → ℝᵐ линейное
   * ∀ E ∈ Mᵐ V(E) ∈ Mᵐ
   * ∀ E ∈ Mᵐ λ(V(E)) = |detV| * λE (или 0, если 0 * ∞)

*** Доказательство
    1. V - вырожденное, тoгда V(ℝᵐ) ⊂ ℝᵐ - подпространство =>
       λ(V(ℝᵐ)) = 0
    2. det V ≠ 0
       Сохранение измеримости, тк V - гладкое
       μE = λ(V(E)) - по лемме о гладком отображении
       инвариантно относительно сдвигов
       μ(a+E) = λ(V(a+E)) = λ(V(a)+V(E)) = λ(V(E)) = μ(E)
       => ∃c μE = c * λE
       E := куб(g₁...gₘ), V(E) - прллп(s₁h₁..sₘhₘ)
       λE = 1,  λ(V(E)) = μE = (s₁*...) = |detV|
** Теорема об измеримости пределов и супремумов
   1. fₙ измерима ⇒ sup{fₙ} и inf{fₙ} измеримы
   2. Верхний и нижний пределы измеримы
   3. ∀x ∃limfₙ(x) = f(x), тогда f(x) измерим
** Характеризация измеримых функций с помощью ступенчатых. Следствия
   (X, A, μ), f:X→ℝ, f≥0
   Тогда ∃ ступенчатая gₙ:
   1. 0≤gₙ(x)≤f(x) ∀x∈X
   2. g₁(x) ≤ g₂(x) ≤ ..., ∀x∈X
   3. ∀x limgₙ(x) = f(x)

   Следствия:
   1. f измерима ⇒ ∃gₙ ступенчатая, что limgₙ = f
   2. f, g измеримы ⇒ f*g измерима
   3. f, g измеримы и они не принимают значения ∞ ⇒ f + g изм
** X Измеримость монотонной функции
** Теорема Лебега о сходимости почти везде и сходимости по мере
   (X, A, μ) μX < +∞ !!!
   fₙ → f почти везде,
   Тогда fₙ ⇒μ f
** Теорема Рисса о сходимости по мере и сходимости почти везде
   (X, A, μ), fₙ ⇒μ f,
   Тогда ∃nₖ, f_nₖ → f почти везде
** Простейшие свойства интеграла Лебегa
   1. f, g - суммируемые и f ≤ g, тогда ∫fdμ ≤ ∫gdμ
   2. ∫_E 1dμ = μE, ∫0dμ = 0
   3. μE = 0, f - изм, ∫fdμ = 0
   4. f сумм, a≥0, ∫afdμ = a∫fdμ, ∫-fdμ = -∫fdμ
   5. f сумм, |∫fdμ| ≤ ∫|f|dμ
   6. f изм, a ≤ f ≤ b, тогда a*μE ≤ ∫_E fdμ ≤ b*μE
   7. f сумм на E, тогда f конечно почти везде на E
** Счетная аддитивность интеграла (по множеству)
   A = ⊔^∞(Aₖ), f ≥ 0, измерима, Aₖ, A измеримы,
   Тогда ∫_A fdμ = ∑∫_Aₖ fdμ
** Теорема Леви о предельном переходе под знаком интеграла
   (X, A, μ)
   fₙ≥0, измеримая, 0≤fₙ≤fₙ₊₁≤..., f(x) = limfₙ(x),
   тогда lim∫fₙ(x)dμ = ∫f(x)dμ
** Линейность интеграла
   f, g ≥ 0, измеримые, тогда ∫(f+g)dμ = ∫fdμ + ∫gdμ
* List
  1. Единственность производной
  2. Лемма о покоординатной дифференцируемости
  3. Необходимое условие дифференцируемости.
  4. Достаточное условие дифференцируемости
  5. Лемма об оценке нормы линейного оператора
  6. Дифференцирование композиции
  7. Дифференцирование "произведений"
  8. Теорема Лагранжа для векторнозначных функций
  9. Экстремальное свойство градиента
  10. Независимость частных производных от порядка дифференцирования
  11. Полиномиальная формула
  12. Лемма о дифференцировании ``сдвига''
  13. Многомерная формула Тейлора (с остатком в форме Лагранжа и Пеано)
  14. Теорема о пространстве линейных отображений
  15. Лемма об условиях, эквивалентных непрерывности линейного оператора
  16. Теорема Лагранжа для отображений
  17. Теорема об обратимости линейного отображения, близкого к обратимому
  18. Теорема о непрерывно дифференцируемых отображениях
  19. Лемма об оценке квадратичной формы и об эквивалентных нормах
  20. Теорема Ферма. Необходимое условие экстремума. Теорема Ролля
  21. Достаточное условие экстремума
  22. Лемма о "почти локальной инъективности"
  23. Теорема о сохранении области
  24. Теорема о диффеоморфизме
  25. Лемма об оценке линейного приближения
  26. Теорема о локальной обратимости
  27. Теорема о неявном отображении
  28. Теорема о задании гладкого многообразия системой уравнений
  29. Необходимое условие относительного локального экстремума
  30. Вычисление нормы линейного оператора с помощью собственных чисел

  31. Простейшие свойства интеграла векторного поля по кусочно-гладкому пути
  32. Обобщенная формула Ньютона--Лейбница
  33. Характеризация потенциальных векторных полей в терминах интегралов
  34. Лемма о дифференцировании интеграла по параметру
  35. Необходимое условие потенциальности гладкого поля. Лемма Пуанкаре
  36. Лемма о гусенице
  37. Лемма о равенстве интегралов по похожим путям
  38. Лемма о похожести путей, близких к данному
  39. Равенство интегралов по гомотопным путям
  40. Почему резиночку нельзя снять с гвоздика

  41. Свойства объема: усиленная монотонность, конечная полуаддитивность, "субтрактивность"
  42. Теорема об эквивалентности счетной аддитивности и счетной полуаддитивности
  43. Теорема о непрерывности снизу
  44. Формулировка теоремы о лебеговском продолжении меры
  45. Счетная аддитивность классического объема
  46. Лемма о построении открыого множества с помощью ячеек
  47. Пример неизмеримого по Лебегу множества
  48. Регулярность меры Лебега
  49. Лемма о "прообразе меры"
  50. Лемма о сохранении измеримости при отображении
  51. Инвариантность меры Лебега относительно сдвигов
  52. Лемма о покрытии множества нулевой меры шарами
  53. Инвариантность меры Лебега при ортогональном преобразовании
  54. Теорема о сохранении измеримости при гладком отображении
  55. Лемма "о структуре компактного оператора"
  56. Теорема о преобразовании меры Лебега при линейном отображении
  57. Теорема об измеримости пределов и супремумов
  58. Характеризация измеримых функций с помощью ступенчатых. Следствия
  59. Измеримость монотонной функции
  60. Теорема Лебега о сходимости почти везде и сходимости по мере
  61. Теорема Рисса о сходимости по мере и сходимости почти везде
  62. Простейшие свойства интеграла Лебега
  63. Счетная аддитивность интеграла (по множеству)
  64. Теорема Леви о предельном переходе под знаком интеграла
  65. Линейность интеграла
