#+TODO: X 0 1 2 | OK
#+TITLE: Дифференциальные уравнения, Холодова. Набор билетов.

* Questions
** Дифференциальные уравнения первого порядка
  Тут определение.
** Понятие уравнения и решения
  Тут тоже определение
** Поле направлений
   Ну это типа поле интегральных кривых - для каждой кривой
   в ее точке тангенс угла касательной совпадает с направлением
   поля, определяемым уравнением в данной точке.
** Задача Коши
** Теорема Пикара
** Общее, частное и особое решения.
** Методы интегрирования уравнений первого порядка
** Уравнения с разделяющимися переменными
** Однородное уравнение и уравнения, приводящиеся к однородным.
** Линейные уравнения первого порядка
** Уравнение Бернулли.
** Уравнения в полных дифференциалах
** Интегрирующий множитель.
** Уравнения первого порядка, неразрешенные относительно производной
** Уравнения Лагранжа и Клеро.
** Дифференциальные уравнения высших порядков
** Основные понятия и определения
** Задача Коши
** Теорема Пикара
** Понижение порядка уравнения
** Уравнения, не содержащие искомой функции и последовательных первых производных
** Уравнения, не содержащие независимой переменной.
** Линейные дифференциальные уравнения n-го порядка
** Свойства решений линейного однородного уравнения
** Фундаментальная система решений и определитель Вронского
** Признак линейной независимости решений
** Формула Остроградского-Лиувилля.
** Построение общего решения линейного однородного уравнения по фундаментальной системе решений
** Структура общего решения неоднородного уравнения
** Принцип наложения
** Метод вариации произвольных постоянных (метод Лагранжа) для уравнения 2-го порядка
** Случай уравнения n-го порядка.
** Системы дифференциальных уравнений
** Основные понятия и определения
** Нормальная система
** Задача Коши
** Механическое истолкование нормальной системы и ее решения
** Теорема Пикара
** Связь между уравнениями высшего порядка и системами дифференциальных уравнений 1-го порядка.
** Линейные системы
** Свойства линейных систем
** Фундаментальная матрица
** Определитель Вронского
** Критерий линейной независимости вектор-функций
** Формула Остроградского-Лиувилля.
** Построение общего решения линейной однородной системы по фундаментальной системе решений
** Интегрирование линейной однородной системы с постоянными коэффициентами методом Эйлера.
** Структура общего решения неоднородной линейной системы
** Метод вариации произвольных постоянных (метод Лагранжа).
** Матричный метод интегрирования линейной однородной системы с постоянными коэффициентами
** Фундаментальная матрица
** Структура фундаментальной матрицы.
** Краевая задача для обыкновенного дифференциального уравнения 2-го порядка
** Функция Грина краевой задачи Дирихле
** Построение функции Грина
** Задача Штурма-Лиувилля.
** Элементы теории устойчивости
** Основные понятия и определения
** Устойчивость по Ляпунову, асимптотическая устойчивость систем обыкновенных дифференциальных уравнений
** Уравнения возмущенного движения
** Устойчивость нулевого решения.
** Устойчивость системы линейных дифференциальных уравнений
** Критерий устойчивости
** Устойчивость систем линейных дифференциальных уравнений с постоянными коэффициентами
** Теоремы Ляпунова об устойчивости по первому приближению
** Теорема Рауса-Гурвица.
** Функции Ляпунова
** Теоремы Ляпунова об устойчивости и асимптотической устойчивости
** Теоремы Ляпунова и Четаева о неустойчивости.
** Особые точки на фазовой плоскости
** Фазовый портрет системы
** Случай однородной системы линейных дифференциальных уравнений с постоянными коэффициентами.
** Первый интеграл системы
** Теорема о локальном существовании первых интегралов
** Понятие порядка системы обыкновенных дифференциальных уравнений при помощи первых интегралов
** Симметричная форма записи нормальной автономной системы дифференциальных уравнений
** Система нелинейных дифференциальных уравнений.
** Дифференциальные уравнения первого порядка с частными производными
** Линейные дифференциальные уравнения с частными производными
** Уравнения характеристик
** Задача Коши
** Квазилинейное дифференциальное уравнение.
** Непрерывная зависимость решений от начальных данных и параметров.
** Дифференцируемость решений по начальным данным и параметрам.
** Метод малого параметра.
** Элементы теории нелинейных колебаний
** Периодические решения квазилинейных систем при отсуствии резонанса.
** Периодические решения квазилинейных систем при резонансе.
** Устойчивость периодических решений квазилинейных систем.
** Колебания в окрестности состояния равновесия.
** Предельные циклы.
** Бифуркация рождения периодического решения.
* Tickets
  * Дифференциальные уравнения первого порядка. Понятие уравнения и
    решения. Поле направлений. Задача Коши. Теорема Пикара. Общее,
    частное и особое решения.
  * Методы интегрирования уравнений первого порядка. Уравнения с
    разделяющимися переменными. Однородное уравнение и уравнения,
    приводящиеся к однородным.
  * Линейные уравнения первого порядка. Уравнение Бернулли.
  * Уравнения в полных дифференциалах. Интегрирующий множитель.
  * Уравнения первого порядка, неразрешенные относительно
    производной. Уравнения Лагранжа и Клеро.
  * Дифференциальные уравнения высших порядков. Основные понятия и
    определения. Задача Коши. Теорема Пикара. Понижение порядка
    уравнения. Уравнения, не содержащие искомой функции и
    последовательных первых производных. Уравнения, не содержащие
    независимой переменной.
  * Линейные дифференциальные уравнения n-го порядка. Свойства решений
    линейного однородного уравнения. Фундаментальная система решений и
    определитель Вронского. Признак линейной независимости
    решений. Формула Остроградского-Лиувилля.
  * Построение общего решения линейного однородного уравнения по
    фундаментальной системе решений. Структура общего решения
    неоднородного уравнения. Принцип наложения. Метод вариации
    произвольных постоянных (метод Лагранжа) для уравнения 2-го
    порядка. Случай уравнения n-го порядка.
  * Системы дифференциальных уравнений. Основные понятия и
    определения. Нормальная система. Задача Коши. Механическое
    истолкование нормальной системы и ее решения. Теорема
    Пикара. Связь между уравнениями высшего порядка и системами
    дифференциальных уравнений 1-го порядка.
  * Линейные системы. Свойства линейных систем. Фундаментальная
    матрица. Определитель Вронского. Критерий линейной независимости
    вектор-функций. Формула Остроградского-Лиувилля.
  * Построение общего решения линейной однородной системы по
    фундаментальной системе решений. Интегрирование линейной
    однородной системы с постоянными коэффициентами методом Эйлера.
  * Структура общего решения неоднородной линейной системы. Метод
    вариации произвольных постоянных (метод Лагранжа).
  * Матричный метод интегрирования линейной однородной системы с
    постоянными коэффициентами. Фундаментальная матрица. Структура
    фундаментальной матрицы.
  * Краевая задача для обыкновенного дифференциального уравнения 2-го
    порядка. Функция Грина краевой задачи Дирихле. Построение функции
    Грина. Задача Штурма-Лиувилля.
  * Элементы теории устойчивости. Основные понятия и
    определения. Устойчивость по Ляпунову, асимптотическая
    устойчивость систем обыкновенных дифференциальных
    уравнений. Уравнения возмущенного движения. Устойчивость нулевого
    решения.
  * Устойчивость системы линейных дифференциальных уравнений. Критерий
    устойчивости. Устойчивость систем линейных дифференциальных
    уравнений с постоянными коэффициентами. Теоремы Ляпунова об
    устойчивости по первому приближению. Теорема Рауса-Гурвица.
  * Функции Ляпунова. Теоремы Ляпунова об устойчивости и
    асимптотической устойчивости. Теоремы Ляпунова и Четаева о
    неустойчивости.
  * Особые точки на фазовой плоскости. Фазовый портрет системы. Случай
    однородной системы линейных дифференциальных уравнений с
    постоянными коэффициентами.
  * Первый интеграл системы. Теорема о локальном существовании первых
    интегралов. Понятие порядка системы обыкновенных дифференциальных
    уравнений при помощи первых интегралов. Симметричная форма записи
    нормальной автономной системы дифференциальных уравнений. Система
    нелинейных дифференциальных уравнений.
  * Дифференциальные уравнения первого порядка с частными
    производными. Линейные дифференциальные уравнения с частными
    производными. Уравнения характеристик. Задача Коши. Квазилинейное
    дифференциальное уравнение.
  * Непрерывная зависимость решений от начальных данных и параметров.
  * Дифференцируемость решений по начальным данным и параметрам.
  * Метод малого параметра.
  * Элементы теории нелинейных колебаний. Периодические решения
    квазилинейных систем при отсуствии резонанса.
  * Периодические решения квазилинейных систем при резонансе.
  * Устойчивость периодических решений квазилинейных систем.
  * Колебания в окрестности состояния равновесия.
  * Предельные циклы.
  * Бифуркация рождения периодического решения.
  * Приближенные методы решения дифференциальных уравнений.
