#+TODO: X 0 1 2 | OK
#+TITLE: Дифференциальные уравнения, Холодова

* Questions [0/92]
** 2 Дифференциальные уравнения первого порядка
  Тут определение.
** 2 Понятие уравнения и решения
  Тут тоже определение
** 2 Поле направлений
   Ну это типа поле интегральных кривых - для каждой кривой
   в ее точке тангенс угла касательной совпадает с направлением
   поля, определяемым уравнением в данной точке.
** 2 Задача Коши
** 1 Теорема Пикара
** 2 Общее, частное и особое решения.
** X Методы интегрирования уравнений первого порядка
** 2 Уравнения с разделяющимися переменными
** 2 Однородное уравнение и уравнения, приводящиеся к однородным.
** 2 Линейные уравнения первого порядка
** 2 Уравнение Бернулли.
** 2 Уравнения в полных дифференциалах
** X Интегрирующий множитель.
** 2 Уравнения первого порядка, неразрешенные относительно производной
** 1 Уравнения Лагранжа и Клеро.
** 2 Дифференциальные уравнения высших порядков
** 2 Основные понятия и определения
** 2 Задача Коши
** 2 Теорема Пикара
** 2 Понижение порядка уравнения
** 2 Уравнения, не содержащие искомой функции и последовательных первых производных
** 2 Уравнения, не содержащие независимой переменной.
** 2 Линейные дифференциальные уравнения n-го порядка
** 2 Свойства решений линейного однородного уравнения
** 1 Фундаментальная система решений и определитель Вронского
** X Признак линейной независимости решений
** X Формула Остроградского-Лиувилля.
** X Построение общего решения линейного однородного уравнения по фундаментальной системе решений
** X Структура общего решения неоднородного уравнения
** X Принцип наложения
** X Метод вариации произвольных постоянных (метод Лагранжа) для уравнения 2-го порядка
** X Случай уравнения n-го порядка.
** X Системы дифференциальных уравнений
** X Основные понятия и определения
** X Нормальная система
** X Задача Коши
** X Механическое истолкование нормальной системы и ее решения
** X Теорема Пикара
** X Связь между уравнениями высшего порядка и системами дифференциальных уравнений 1-го порядка.
** X Линейные системы
** X Свойства линейных систем
** X Фундаментальная матрица
** X Определитель Вронского
** X Критерий линейной независимости вектор-функций
** X Формула Остроградского-Лиувилля.
** X Построение общего решения линейной однородной системы по фундаментальной системе решений
** X Интегрирование линейной однородной системы с постоянными коэффициентами методом Эйлера.
** X Структура общего решения неоднородной линейной системы
** X Метод вариации произвольных постоянных (метод Лагранжа).
** X Матричный метод интегрирования линейной однородной системы с постоянными коэффициентами
** X Фундаментальная матрица
** X Структура фундаментальной матрицы.
** X Краевая задача для обыкновенного дифференциального уравнения 2-го порядка
** X Функция Грина краевой задачи Дирихле
** X Построение функции Грина
** X Задача Штурма-Лиувилля.
** X Элементы теории устойчивости
** X Основные понятия и определения
** X Устойчивость по Ляпунову, асимптотическая устойчивость систем обыкновенных дифференциальных уравнений
** X Уравнения возмущенного движения
** X Устойчивость нулевого решения.
** X Устойчивость системы линейных дифференциальных уравнений
** X Критерий устойчивости
** X Устойчивость систем линейных дифференциальных уравнений с постоянными коэффициентами
** X Теоремы Ляпунова об устойчивости по первому приближению
** X Теорема Рауса-Гурвица.
** X Функции Ляпунова
** X Теоремы Ляпунова об устойчивости и асимптотической устойчивости
** X Теоремы Ляпунова и Четаева о неустойчивости.
** X Особые точки на фазовой плоскости
** X Фазовый портрет системы
** X Случай однородной системы линейных дифференциальных уравнений с постоянными коэффициентами.
** X Первый интеграл системы
** X Теорема о локальном существовании первых интегралов
** X Понятие порядка системы обыкновенных дифференциальных уравнений при помощи первых интегралов
** X Симметричная форма записи нормальной автономной системы дифференциальных уравнений
** X Система нелинейных дифференциальных уравнений.
** X Дифференциальные уравнения первого порядка с частными производными
** X Линейные дифференциальные уравнения с частными производными
** X Уравнения характеристик
** X Задача Коши
** X Квазилинейное дифференциальное уравнение.
** X Непрерывная зависимость решений от начальных данных и параметров.
** X Дифференцируемость решений по начальным данным и параметрам.
** X Метод малого параметра.
** X Элементы теории нелинейных колебаний
** X Периодические решения квазилинейных систем при отсуствии резонанса.
** X Периодические решения квазилинейных систем при резонансе.
** X Устойчивость периодических решений квазилинейных систем.
** X Колебания в окрестности состояния равновесия.
** X Предельные циклы.
** X Бифуркация рождения периодического решения.
* Tickets
1. Дифференциальные уравнения первого порядка. Понятие уравнения и решения. Поле направлений. Задача Коши. Теорема Пикара. Общее, частное и особое решения.
2. Методы интегрирования уравнений первого порядка. Уравнения с разделяющимися переменными. Однородное уравнение и уравнения, приводящиеся к однородным.
3. Линейные уравнения первого порядка. Уравнение Бернулли.
4. Уравнения в полных дифференциалах. Интегрирующий множитель.
5. Уравнения первого порядка, неразрешенные относительно производной. Уравнения Лагранжа и Клеро.
6. Дифференциальные уравнения высших порядков. Основные понятия и определения. Задача Коши. Теорема Пикара. Понижение порядка уравнения. Уравнения, не содержащие искомой функции и последовательных первых производных. Уравнения, не содержащие независимой переменной.
7. Линейные дифференциальные уравнения n-го порядка. Свойства решений линейного однородного уравнения. Фундаментальная система решений и определитель Вронского. Признак линейной независимости решений. Формула Остроградского-Лиувилля.
8. Построение общего решения линейного однородного уравнения по фундаментальной системе решений. Структура общего решения неоднородного уравнения. Принцип наложения. Метод вариации произвольных постоянных (метод Лагранжа) для уравнения 2-го порядка. Случай уравнения n-го порядка.
9. Системы дифференциальных уравнений. Основные понятия и определения. Нормальная система. Задача Коши. Механическое истолкование нормальной системы и ее решения. Теорема Пикара. Связь между уравнениями высшего порядка и системами дифференциальных уравнений 1-го порядка.
10. Линейные системы. Свойства линейных систем. Фундаментальная матрица. Определитель Вронского. Критерий линейной независимости вектор-функций. Формула Остроградского-Лиувилля.
11. Построение общего решения линейной однородной системы по фундаментальной системе решений. Интегрирование линейной однородной системы с постоянными коэффициентами методом Эйлера.
12. Структура общего решения неоднородной линейной системы. Метод вариации произвольных постоянных (метод Лагранжа).
13. Матричный метод интегрирования линейной однородной системы с постоянными коэффициентами. Фундаментальная матрица. Структура фундаментальной матрицы.
14. Краевая задача для обыкновенного дифференциального уравнения 2-го порядка. Функция Грина краевой задачи Дирихле. Построение функции Грина. Задача Штурма-Лиувилля.
15. Элементы теории устойчивости. Основные понятия и определения. Устойчивость по Ляпунову, асимптотическая устойчивость систем обыкновенных дифференциальных уравнений. Уравнения возмущенного движения. Устойчивость нулевого решения.
16. Устойчивость системы линейных дифференциальных уравнений. Критерий устойчивости. Устойчивость систем линейных дифференциальных уравнений с постоянными коэффициентами. Теоремы Ляпунова об устойчивости по первому приближению. Теорема Рауса-Гурвица.
17. Функции Ляпунова. Теоремы Ляпунова об устойчивости и асимптотической устойчивости. Теоремы Ляпунова и Четаева о неустойчивости.
18. Особые точки на фазовой плоскости. Фазовый портрет системы. Случай однородной системы линейных дифференциальных уравнений с постоянными коэффициентами.
19. Первый интеграл системы. Теорема о локальном существовании первых интегралов. Понятие порядка системы обыкновенных дифференциальных уравнений при помощи первых интегралов. Симметричная форма записи нормальной автономной системы дифференциальных уравнений. Система нелинейных дифференциальных уравнений.
20. Дифференциальные уравнения первого порядка с частными производными. Линейные дифференциальные уравнения с частными производными. Уравнения характеристик. Задача Коши. Квазилинейное дифференциальное уравнение.
21. Непрерывная зависимость решений от начальных данных и параметров.
22. Дифференцируемость решений по начальным данным и параметрам.
23. Метод малого параметра.
24. Элементы теории нелинейных колебаний. Периодические решения квазилинейных систем при отсуствии резонанса.
25. Периодические решения квазилинейных систем при резонансе.
26. Устойчивость периодических решений квазилинейных систем.
27. Колебания в окрестности состояния равновесия.
28. Предельные циклы.
29. Бифуркация рождения периодического решения.
30. Приближенные методы решения дифференциальных уравнений.
