#+TITLE: Life safety lectures by some funny guy with a little braid on his head's back

* Lections
** 4.09.2014
   Чет несет про пирамиду Маслоу, про риск -- индивидуальный и социальный.
   Будем учить экологию техносферы, а конкретно безопасность жизнедеятельности.
   * Биосфера -- область существования жизни на Земле.
   * Техносфера -- часть биосферы, преобразованной людьми с помощью технических
     средств с целью наилучшего потребления. Делится на производственную и бытовую среды.
   * Производственная среда -- это пространтво, в котором совершается труд. деятельность
   * Гомосфера -- пространство, где находится человек в процессе деятельности
   * Ноксосфера -- пространство, в котором возникают и существуют опасности.
   Есть три метода -- разделения ноксосферы и гомосферы (невозможно), обезопасивание
   ноксосферы и обезопасивание человека в гомосфере
   * Безопасность жизнедеятельности -- это состояние деятельности человека, при которой
     с определенной вероятностью исключаются потенциальные опасности, влияющие на
     жизнь и здоровье человека и его потомства.
   * Охрана труда -- это система сохранения жизни и здоровья работников в процессе
     трудовой деятельности, включающее в себя правовые, социально-экономические,
     организационно-технические, санитарно-гигиенические, ребиалитационные и иные
     мероприятия
   В основе законодательства лежит конституция, она подкрепляется кодексами, вот
   Рассказывает про ГОСТ, ОСТ, СТП.
   ГОСТ -- это стандарт *безопасности*, не имеющий отношения к качеству.
   Существуют основные и дополнительные ГОСТы, основные маркируются так:
   ГОСТ 12.A.BBB-CCCС, где А -- подсистемнный шифр, ВВВ -- порядковый номер стандарта
   в системе, СССС -- год утверждения при просмотре стандарта
** 18.09.2014
   ==== Говорит про труд вот.
   Формы деятельности человека:
   1) Труд, требующий значительной мышечной активности
   2) Полуавтоматическое производство
   3) Конвейерная форма труда
   4) Дистанционное управление производственными процессами и механизмами
   5) Интеллектуальный труд
      1. Оператор
      2. Управленческий труд
      3. Преподаватель и медработник
      4. Учащиеся и студенты
      5. Творческий труд

   Гигиеническая классификация труда:
   1) Оптимальные условия -- все сохраняется
   2) Допустимые условия -- условия, при которых уровни вредных факторов не превышают пдк
   3) Вредные условия -- металлурги, регулировщики -- необходимы средства защиты
   4) Опасные условия -- пожарники и тд

   Динамика раотоспособности --
   1) Фаза врабатывания, длится до 2-3 часов в худшем случае
   2) Фаза высокой усточивойсти работоспособности -- 8 часов
   3) Фаза снижения работоспособности

   ==== Про воздух еще
   * Параметры чистоты воздуха -- загрязнённость, запылённось
   * Параметры микроклимата -- температура, относительная влажность, скорость
     движения воздуха на рабочем месте, интенсивность теплового излучения
   * Предельно допустимая концентрация в воздухе рабочей зоны -- такая концентрация
     вредных веществ, которая в течение 8-ми часового рабочего дня или другой
     продолжительности, но не более 40 чаа в неделю не вызывает отклонений в остоянии
     здоровья работающих, а также не влияет на настоящее и будущее поколения. Оптимально - 50%
   Оптимальная температура -- 22-24, влажность -- 40-60.
   * ИЗА -- индекс загрязнения атмосферы

   Системы вентиляции:
   1) По способу подачи воздуха
      1. Естественная
         1) Аэрация -- организованная вентиляция (ветровой, тепловой напор)
         2) Инфильтрация -- неорганизованная
      2. Механическая -- приточная, вытяжная, приточно-вытяжная
   2) По принципу организации воздухообмена
      1. Общеобменная
      2. Местная
   3) По условиям применения
      1. Аварийная
      2. Основная

   Способы очисти воздуха -- механические и химические
** 02.10.2014
   Человек наиболее приспособлен к желтой части спектра
   Свет делиться на естественные источики и искусственные
   Искусственные источники:
       1) Лампы накаливания
       2) Газоразрядные лампы
       3) Галогеновые лампы
       4) Люминисцентные

   Солнце короче улучшает иммунитет, работоспособность, повышает
   настроение (потому что ШИРОКИЙ СПЕКТР!!!!!!)))0)
   Свет делится, напирмер, по конструктивному исполнению
   (общее освещение, комбинированое)
   и по функциональному назначению:
   рабочее освещение, аварийное, специальное (охранное,  дежурное,
   эвакуационное, эритемное (широкий спектр), бактерицидное)

   Второе существенное преимущество света -- он бесплатный. И еще
   яркость выше, чем у всех источников света.
   Третье -- оно сохраняет естественные цвета.

   Источники электромагнитных полей -- естественные и искусственные
   Естественные -- земля, солнце, всякие радиоактивные вещества
   Искусственные - реакторы, электростанции и тд

   Опасности при воздействии электромагнитных полей
       * Перегрев
       * Поляризация ткани
       * Нарушение обмена веществ и функционирования систем организма
       * Возможность возникновения разряда между человеком и объектом
       * Развитие злокачественных заболеваний (катаракта, лейкемия, рак)
** 16.10.2014
   Он тут расказывает о том, как устроены фазовые провода. Рисунок
   в точности, как в лабораторной по электричеству. Место соединения
   проводов, идуших от обмоток (которая звезда), назыается нейтралью.

   Если происходит провисание кабеля, при котором провод касается
   поверхности, категорически запрещается ходить большими шагами около
   места соприкосновения, так как поле распостраняется неравномерно,
   а из-за этого ток может потечь через ноги человека из-за разного
   потенциала их как проводников. Таким образом, намного лучше скакать
   (хто не скаче) на одной ноге, лол.

   Групповое заземление - это такой контур из вертикальных электродов
   в поверхности полового покрытия (может быть не контур, а линия).
   Это позволяет достичь равномерного высокого потенциалa, распределенного
   по площадке.

   Первоочередным поражающим фактором тока является термическое действие
   (обугливание, испарение, коагуляция белка), потом идет электрическое
   (всякие штуки...?), биологическое (нарушение объема веществ, прерывание
   биоэлектрического воздействия, нарушение работы мышц).

   Виды поражения: электрические травмы на отдельные органы,
   электрический удар (полное поражение тела).
       1) Электрические травмы
          1) Электрический ожог -- контактный и бесконтактный (дуговой)
             Второй возникает при изменении факторов микроклимата --
             ионизации, высокой влажности...
          2) Электрические знаки -- всякие ожоги, гематомы. Еще есть такая
             металлизация кожи -- какая-нибудь часть установки может расплавиться
             и проникнуть в кожу или глаза (электроофтальмолагическая травма).
          3) Механические повреждения -- судороги мышц, ведущие к разрыву мышц,
             кожы, разрыву костей, падения с высоты, например.
       2) Электрический удар -- с потерей сознания, без, с тяжелыми
          последствиями. Может вызвать эффекты вплоть до клинической смерти.

   Поражающие факторы -- напряжение, сила тока, сопротивление, область поражения,
   частота.
   * Сопротивление тела человека -- 10^3 Ом. Но это приблизительно. Сопротивление
     тела человека, очевидно, не одинаково, не однородно. Наибольшее
     спротивление имеет кожа, падает от влажности. Таким образом, главным
     фактором защиты человека является хорошее состояние кожи + микроклимата.
     Микроклимат -- это очень важно.
       * Самая поражаемая часть человека -- это рука, путь через две руки гораздо
         более опасен, так как на пути лежит сердце (чем через ноги, например).
         Самый опасный путь -- это через голову, является наиболее опасным (очевидно).
       * Частота. Малые частоты являются в каком-то смысле даже стимулирующими,
         но есть граница для параметров тока, при котором он становится
         опасным. Эта граница, очевидно, разная для постоянного и переменного тока.

     |                   | Переменный ток | Постоянный ток |
     |-------------------+----------------+----------------|
     | Ощутимость        | 0.6-1.5 mA     | 5.7 mA         |
     | Неотпускающий ток | 10-15 mA       | 50-60 mA       |
     | Фибрилляция       | 100 mA         | 300 mA         |
     | Электрический шок | 5 A            | 5A             |

     Ток в розетке имеет силу около 5 мА.

     Кроме защиты расположением электродов используется изоляция -- на
     устройствах понятно, эффективным является также расположение
     электрических щитков на высоте или под замками, в недоступных местах.
     У шахтерских фонарей и в шахтах используют как можно меньшую силу тока,
     чтобы избежать неотпускающего тока. Организуетя заземление, зануление
     и компенсация тока.
** 30.10.2014
   Взрывы и пожары на производстве (вау сач бжд)
   Короче есть огонь просто, есть взрыв -- это когда вещество жидкое
   или твердое, детонация -- о взрыве воздуха (взвешенные частицы).

   Основным поражающим фактором при взрыве является ударная волна.
   Пламя распостраняется со скоростью десятков метров в секунды,
   а ударная со скоростью звука.

   * Что может взорваться
     * Вещества - конденсированные или газы\пыли
     * Оборудование

   Обычно оборудование делают безопасным -- безопасная оболочка...

   Предотвращение детонации - использование безопасных смесей,
   использование мембран и других устройств для регулировки давления.

   Изоляция электропроводки -- для предотвращения дуговых разрядов,
   защиты проводки от коррозии, человека от поражения.
   Изоляция газовых и электрических плит
   Изоляция от влаги розеток
   Использование подсвечников и пепельниц
   Запрет использования открытого огня

   Зоны: зона горения, зона теплового воздействия, зона заземления
** 13.11.2014
   Температура:
   21-25 Лето
   22-28 Зима
   Влажность нужна быть в районе 40%. Много рассказывается о компуктерах, их
   заземлении, как сидеть надо.

   Стихийные бедствия
   Определение тут было сказано не очень нужное
   Риск делится на индивидуальный и социальный. Социальный - совокупность опасных
   факторов и технологий на заводе\предприятии. n = r / R, где r - число погибших
   на производстве, R - число рабочих.
   Забавный факт -- величина идивидуального риска при использовании автотранспорта
   на два порядка меньше чем при использовании авиатранспорта. И еще на два порядка
   меньше атомная энергетика.
   Главная причина травматизма -- человеческий фактор -- больше половины риска. Еще
   много зависит от того, как человек реагирует в стрессовой ситуации
** 27.11.2014
   Чрезвычайные ситуации: защита и ликвидация последствий
   По природе возникновения делятся на техногенные, природные, экологические,
   биологические, антропогенные (террор), др.
   Существует единая государственная система предупреждения
   и ликвидации чрезвычайных ситуаций (РСЧС)
   * Координирующие органы
   * Органы управления по делам гражданской обороны и чрезв.сит.
   * Силы и средства
   * Резервы финансовых и материальных средств

   При наводнении:
   * Эвакуация
   * Перед эвакуацией отключить электричество, газ, воду, взять стафф
   * После возвращения проверить сохранность здания, не прикасаться к электросети

   Химическое поражение:
   * Повязки -- сода от хлора, лимон от аммиака. Лучше противогаз
   * Укрыться в здании с едой и водой
   * Покинуть зону поражения, двигаясь перпендикулярно ветру, защищать дых. пути

   Пожар
   * Изучить план пожарной эвакуации
   * Знать, где огнетушители и всякие другие пожарные штуки

   Радиационное:
   * Укрытие
   * Индвидуальная защита -- плотная герметичная одежда, повязка

* Labs
** Исследование эффективности действия общеобменной механической вентиляции
*** Ход работы
    Определяем период года (холодный -- меньше 10 градусов), категорию работ
    дает преподаватель, выбираем по этому допустимые нормы темп. воздуха.
    Записываем температуры воздуха в камере и приточного.
    Включаем нашу машинку, ждем, пока температура поднимется на 1-2 градуса
    выше допустимой нормы температуры воздуха. Потом включаем вентиляцию и
    ждем, пока достигнется балланс в температуре с вентиляцией.
    Дальше рассчитываем по формулам, что должно было иметь место, строим два
    графика. Рассчитываем количество необходимого приточного воздуха в камеру,
    реальное его количество, сравниваем, делаем вывод (хватило ли).
*** Вопросы
    1. Что такое вентиляция?
       Вентиляция – это организованный воздухообмен, в процессе которого из
       помещения удаляется загрязненный, влажный, перегретый воздух и в него
       поступает свежий наружный воздух.
    2. Решение какой задачи можно обеспечить с помощью вентиляции в рабочей
       зоне помещения?
       С помощью вентиляции можно обеспечить решение задачи обеспечения требуемой
       чистоты воздуха и допустимых метеорологических условий в рабочей зоне помещений
    3. Что такое рабочая зона помещения?
       Рабочая зона – пространство, ограниченное по высоте 2 м над уровнем пола
       или площадки, где находятся места постоянного или временного пребывания
       работающих.
    4. Решение какой задачи должна была обеспечить экспериментальная вентиляционная
       установка? Эффективно ли ее действие?
       Экспериментальная установка вытяжной вентиляции предназначена для обеспечения
       нормальных метеорологических условий при наличии в помещении источника
       тепловыделений.
       Костя Астраханцев (23:09:23 5/10/2009) ну я когда делал установилась температура
       больше нормы. Значит, неэффективно)
    5. Какие применяют виды вентиляции, различающиеся по способу перемещения воздуха?
       Какой вид вентиляции исследовался в работе?
       По способу перемещения воздуха вентиляция может быть естественной и механической.
       Возможно сочетание естественной и механической вентиляции – смешанная вентиляция.
       В работе исследовалась механическая вентиляция.
    6. Что является побудителем перемещения воздуха при естественной и механической
       вентиляции?
       При естественной вентиляции воздухообмен происходит в результате действия
       гравитационного давления, возникающего вследствие разности температур
       воздуха в помещении и наружного воздуха, а также в результате действия
       ветра. При механической – перемещение воздуха осуществляется вентилятором
       (осевым или центробежным), создающим избыточное давление (разрежение)
       по сравнению с атмосферным.
    7. Какие в зависимости от назначения бывают виды механической вентиляции?
       Какой вид вентиляции исследовался в работе?
       В зависимости от назначения механическая вентиляция может быть приточной –
       для подачи в помещение свежего воздуха, вытяжной – для удаления из помещения
       воздуха, не соответствующего санитарно-гигиеническим требованиям и
       приточно-вытяжной – для того и другого одновременно. Общеобменная = приточная,
       вытяжная, приточно-вытяжная.
    8. Какие бывают типы вентиляции, различающиеся по месту действия? В каких
       случаях их применяют на производстве?
       По месту действия вентиляция бывает общеобменной и местной.
       Общеобменную вентиляцию применяют при равномерном расположении по площади
       производственного помещения источников выделения теплоты, влаги, вредных веществ.
       Местную вентиляцию устраивают для удаления вредных веществ и избытков тепла
       непосредственно в месте их образования, чем обеспечивается максимальное
       улавливание вредностей при минимальном расходе воздуха.
    9. По месту действия какой вид вентиляции исследовался в работе? В каком
       случае на производстве устраивается такая вентиляция?
       В лабораторной работе исследуется эффективность действия общеобменной вентиляции.
       Её применяют при равномерном расположении по площади производственного помещения
       источников выделения теплоты, влаги, вредных веществ.
    10. В каком случае наличие в помещении источника тепловыделений может стать
        вредным фактором окружающей среды?
        Длительное воздействие высокой температуры воздуха на организм может вызвать
        нарушение терморегуляции. Терморегуляция – совокупность физиологических процессов,
        обеспечивающих постоянство температуры тела человека в допустимых физиологических
        границах 36,4 – 37,5 °С. Данный диапазон температур внутренних органов человека
        наиболее благоприятен для протекания в организме биохимических реакций и деятельности
        мозга.
    11. Что собой представляет процесс конвекции, организуемый за счет действия вентиляции?
        Организуемый за счет действия вентиляционной установки воздухообмен является
        процессом конвекции (перемещением среды), в ходе которого удаляемый вентилятором
        из помещения перегретый воздух восполняется притоком более холодного наружного воздуха.
    12. Для эффективной борьбы с избытками теплоты в помещении на сколько градусов температура
        приточного воздуха должна быть ниже допустимой?
        Для эффективной борьбы с  избытками теплоты в помещении температура приточного воздуха
        Tпр должна быть не менее, чем на 5-8 °С ниже допустимой нормы температуры воздуха в
        рабочей зоне Tдоп.
    13. От каких факторов зависит величина допустимой температуры воздуха в рабочей зоне?
        От периода года (холодный, тёплый), от категории работ (лёгкая, средней тяжести,
        тяжёлые физические работы).
    14. С учетом величины какого фактора определяется период года?
        Период года определяется по среднесуточной температуре наружного воздуха. Теплый
        период года характеризуется среднесуточной температурой наружного воздуха +10 °С и
        выше, холодный период года – ниже +10 °С.
    15. Назовите все элементы вентиляционной установки.
        Экспериментальная вентиляционная установка состоит из следующих элементов:
        вентилятора; приточного отверстия, через которое в камеру поступает воздух; вытяжного
        отверстия, через которое воздух удаляется из камеры. Температура воздуха контролируется
        термометром (всего их 2 1-ый для контролирования температуры воздуха в камере, 2-ой –
        приточного воздуха.). Скорость движения воздуха в плоскости вытяжного отверстия измеряется
        термоанемометром. Включение электропитания установки, источника тепловыделений и
        вентилятора производится с пульта. (Из методички для лабораторных работ.)
        Экспериментальная установка вытяжной вентиляции, предназначенная для обеспечения
        нормальных метеорологических условий, состоит из центробежного вентилятора, установленного
        в вытяжном отверстии в стенке камеры, электродвигателя, вал которого непосредственно
        соединен с валом лопаточного колеса вентилятора, и приточного отверстия.
    16. Как повысить эффективность действия механической вентиляции?
        При эффективно действующей вентиляции температура воздуха в помещении понизится до
        допустимых гигиенических норм Тдоп, установленных ГОСТ 12.1.005 – 88 “Общие
        санитарно-гигиенические требования к воздуху рабочей зоны”. Величина Тдоп для
        производственных помещений выбирается с учетом периода года и категории работы. В нашем
        случае период года холодный, категория работ лёгкая, следовательно, Тдоп равна 20-25 °С.
** Исследование искусственного освещения на рабочем месте
*** Ход работы
    Меряем освещенность в пяти точках для каждого типа ламп для двух типов
    стенок. Берем среднюю освещенность, считаем фактический поток по формуле
    Ф_факт = E_ср * S (у нас площадь 0.4)
    Ф_ламп табличное
    μ = Ффакт / Фламп
    Мерям пульсацию, записываем и сравниваем, делаем выводы

    Рассчитываем освещенность, выясняем отклонение от нормы, должно быть
    от -10 до +20
*** Вопросы
    1. Что собой представляет светильник?
       Светильник – представляет собой совокупность электрического источника света и осветительной арматуры.
    2. Какие функции выполняет осветительная арматура в светильнике?
       Осветительная арматура предназначена: 1) для перераспределения излучаемого источником светового потока в требуемом направлении, 2) предохранения глаз работающих от слепящего действия источника света, 3) для подвода электрического питания, 4) для крепления и защиты источника света от механических повреждений и воздействия окружающей среды.
    3. Каким бывает по конструктивному исполнению искусственное освещение? Почему запрещается применять одно местное освещение?
       Искусственное освещение по конструктивному исполнению бывает общее и комбинированное.
       Так как резкий контраст между ярко освещенными и неосвещенными местами приводит к зрительному напряжению, замедляет скорость работы и может стать причиной несчастных случаев.
    4. Что такое общее освещение? Какими способами можно увеличить освещенность, создаваемую общим освещением?
       Общее освещение равномерное или локализованное предназначено для освещения всего помещения с помощью светильников, размещенных в верхней части помещения. Общее равномерное освещение создает условия для выполнения работ в любом месте освещаемого помещения без учета расположения оборудования.
       При общем локализованном освещении светильники размещают с учетом расположения рабочих мест, что позволяет создавать на местах повышенную освещенность.
    5. Что такое комбинированное освещение? В каких случаях оно применяется?
       Комбинированное освещение – когда к общему освещению добавляется местное, концентрирующее световой поток непосредственно на рабочих местах.
       Комбинированное освещение применяется: 1) при выполнении точных зрительных работ, 2) для освещения наклонных рабочих поверхностей, 3) на рабочих местах, где оборудование создает резкие тени, 4) при необходимости создания в процессе работы определенной направленности светового потока с помощью местных светильников.
    6. Какие преимущества у ламп накаливания перед газоразрядными?
       Лампы накаливания удобны в эксплуатации, простоты в изготовлении, не требуют дополнительных пусковых устройств, надежны в работе при колебаниях напряжения в электрической сети и различных метеорологических условиях, выпускаются для сетей напряжением 127 и 220 В и для сетей малых напряжений – 12, 24 и 36 В.
    7. Каков принцип действия ламп, применяемых в аудитории? Каковы преимущества у данных ламп?
       Газоразрядные лампы – это источники света низкого и высокого давления, в которых видимое излучение возникает в результате электрического разряда в атмосфере инертных газов и паров металлов, а также за счет явления люминесценции.
       Самые распространённые – люминесцентные лампы. Они имеют форму цилиндрической стеклянной трубки с двумя электродами, наполненную дозированным количеством ртути и смесью инертных газов. Внутренняя поверхность трубки покрыта тонким слоем люминофора, который преобразует ультрафиолетовое излучение, возникающее при газовом электрическом разряде, в видимый свет.
       Преимуществом газоразрядных ламп перед лампами накаливания является большая светоотдача от 40 до 110 лм/Вт. Они имеют значительно больший срок службы – свыше 10 тыс. ч., низкую температуру поверхности лампы, близкий к солнечному свету спектр излучения, обеспечивающий высокое качество цветопередачи. Газоразрядные люминесцентные лампы обеспечивают более равномерное освещение и рекомендуются для применения в светильниках общего освещения.
    8. Какие недостатки у газоразрядных ламп?
       Существенным недостатком является пульсация светового потока (ведёт к возникновению стробоскопического эффекта). К недостаткам следует также отнести: 1) необходимость применения специальных пусковых устройств, 2) зависимость работоспособности лампы от температуры окружающей среды и 3) величины питающего напряжения, 4) длительный период разгорания у ламп высокого давления (10 – 15 минут).
    9. Какова причина пульсации светового потока источников света? У какого типа ламп больше коэффициент пульсации освещенности?
       Пульсация светового потока возникает вследствие малой инерционности свечения люминофора.
       У газоразрядных ламп коэффициент пульсации больше, чем у остальных типов ламп. (Коэффициент пульсации освещенности Кп – это критерий глубины колебаний освещенности во времени в результате изменения светового потока используемых источников света.)
    10. Что такое стробоскопический эффект и чем он опасен?
        Стробоскопический эффект проявляется в искажении зрительного восприятия движущихся или вращающихся объектов.
        Стробоскопический эффект опасен, так как вращающиеся части механизмов, детали, инструмент могут показаться неподвижными и стать причиной травматизма.
    11. Допустимые значения каких показателей искусственного освещения устанавливаются СНиП 23-05-95? Какие из них измерялись в работе?
        Нормируемыми показателями для систем искусственного освещения согласно строительных норм и правил СНиП 23-05-95 «Естественное и искусственное освещение» являются: величина минимальной освещенности рабочих поверхностей, коэффициент пульсации освещенности и показатель ослепленности.
        Измерялись: освещённость, коэффициент пульсации.
    12. В зависимости от каких факторов устанавливаются допустимые значения показателей искусственного освещения?
        Устанавливается в зависимости от характера зрительной работы, применяемой системы освещения, типа используемых источников света.
    13. Какие факторы определяют характеристику зрительной работы?
        Характеристика зрительной работы определяется минимальным размером объекта различения, контрастом объекта с фоном и свойствами фона.
    14. Что такое объект различения? Приведите примеры.
        Объект различения – наименьший элемент рассматриваемого предмета или дефект, которые необходимо различить в процессе работы (например, линия, знак, нить, пятно, трещина, риска и т. п.).
    15. Каким способом можно уменьшить коэффициент пульсации освещенности? В чем суть предложенного способа?
        Для уменьшения коэффициента пульсации освещенности люминесцентные лампы включаются в разные фазы трехфазной электрической сети.
        За счет сдвига фаз в трехфазной сети на 1/3 периода “провалы” в световом потоке каждой из ламп компенсируются световыми потоками двух других ламп, в результате пульсации суммарного светового потока, следовательно, и освещенности существенно меньше.
    16. По какой характеристике, полученной при расчете освещения, выбирается источник света? Какие параметры лампы необходимо определить?
        Рассчитывается необходимый световой поток лампы Ф, обеспечивающий в помещении нормируемое значение освещенности E, и по светотехническому справочнику выбирается тип и мощность стандартной лампы со световым потоком Фгост, близким по величине расчетному.
        Основная расчетная формула имеет вид: Ф = (E·S·кз·z)/(N·η·n), где Ф – световой поток лампы, лм; E – допустимая наименьшая освещенность, лк; S – площадь помещения, м2; кз – коэффициент запаса; z – коэффициент неравномерности освещенности (для люминесцентных ламп z = 1,1); N – число светильников, шт.; η – коэффициент использования светового потока (в долях единицы); n – число ламп в светильнике, шт.
** Исследование электробезопасности трехфазных сетей переменного тока до 1000 В
*** Вопросы

** Определение дозы облучения источником ионизирующего излучения
*** Ход работы
    Включаем все приборы, смотрим на датчик, если имп\с < 0.5 выбираем режим звук
    Считаем Р в имп/с, берем среднее, по шкале переводим.
    Смотрим мощность эквивалентной дозы без источника, вычитаем из наших измерений
    фон - получаем реальные значения. Считаем Н - полученная эквивалентная доза за
    время проведения лабы (умножаем на время).
    Проводим околоаналогичные вычисления для кожи населения с учетом табличных
    данных об облучении в неделю
*** Вопросы
    1. Что такое ионизирующее излучение? Какие различают его виды?
       Это излучение, взаимодействие которого с веществом приводит к образованию в этом веществе ионов разного знака.
       Различают следующие виды ионизирующего излучения:
       - альфа-излучение – поток ядер атомов гелия;
       - бета-излучение – поток электронов или позитронов;
       - гамма-излучение и рентгеновское (тормозное или характеристическое) излучение – фотонное (электромагнитное) излучение;
       - нейтронное излучение – поток электронейтральных частиц ядра.
    2. Чем опасна ионизация живой ткани?
       Она приводит к разрыву молекулярных связей, образованию вредных химических соединений, не свойственных организму. Это приводит к гибели клеток, нарушению биологических процессов и обмена веществ. Даже при незначительных дозах облучения происходит торможение функций кроветворных органов, нарушение свертываемости крови, увеличение хрупкости кровеносных сосудов, ослабление действия иммунной системы.
    3. От каких характеристик зависит степень вредного действия разных видов ионизирующего излучения?
       Зависит от их проникающей способности и удельной ионизации – числа пар ионов, образующихся в тканях организма на каждом сантиметре пути пробега. В ряду альфа-бета-гамма- и рентгеновского излучений проникающая способность возрастает, а удельная ионизация уменьшается.
    4. Какие виды облучения могут возникнуть при работе с источниками ионизирующего излучения? Какой вид облучения наиболее опасен?
       При работе с источниками ионизирующего излучения может возникнуть внешнее, внутреннее и комбинированное облучение персонала. Скорее всего комбинированное.
    5. Чем может быть вызвано внешнее облучение? Какие виды ионизирующего излучения наиболее опасны при внешнем облучении?
       Внешнее облучение обусловлено действием источников, находящихся на рабочих местах и в помещениях. При внешнем облучении наиболее опасны рентгеновское и гамма-излучения.
    6. Чем может быть вызвано внутреннее облучение? Какой вид ионизирующего излучения наиболее опасен при таком облучении?
       Внутреннее облучение – радиоактивной пылью, попавшей в организм вместе с воздухом, пищей, водой. При внутреннем наиболее опасны все виды излучения (особенно альфа), действующие непрерывно и практически на все органы.
    7. Какие показатели используются для оценки радиационной обстановки и ожидаемых последствий облучения?
       Используются следующие основные показатели: активность, поглощённая доза, эквивалентная доза, эффективная доза, предел дозы.
    8. Что такое эквивалентная доза? Как ее величина определялась в работе? Укажите единицу измерения.
       Эквивалентная доза (НT,R) – поглощенная доза в органе или ткани, умноженная на соответствующий взвешивающий коэффициент для данного вида ионизирующего излучения: HT, R = WR DT, где DT – средняя поглощенная доза в органе или ткани Т; WR – взвешивающий коэффициент для данного вида ионизирующего излучения
       Единицей эквивалентной дозы является зиверт (Зв).
    9. Какой вид ионизирующего излучения при расчете эквивалентной дозы имеет наиболее высокий взвешивающий коэффициент?
       Для рентгеновского, гамма- и бета- излучений взвешивающий коэффициент WR = 1, для альфа-частиц – 20.
    10. Пределы каких показателей ионизирующего излучения устанавливаются НРБ-99? Укажите единицу измерения.
        Эффективной и Эквивалентной доз. Единица измерения – мЗв (мили зиверт)
    11. С учетом каких факторов в НРБ-99 устанавливаются пределы эквивалентной дозы?
        Эквивалентная доза за год в хрусталике глаза, в коже, в кистях и стопах. А так же категории обслуживающего персонала.
    12. Какими мерами и средствами обеспечивается безопасность работающих с источниками ионизирующего излучения?
        Применение защиты временем, защиты расстоянием, экранирование источников излучения, использования средств индивидуальной защиты.
    13. Какие применялись меры и средства защиты от опасного облучения в процессе выполнения лабораторной работы?
        Стальной экран, расстояние, продолжительность времени пребывания у установки.
    14. Какой вид ионизирующего излучения создает Со60? Из каких материалов изготавливают экраны, защищающие от такого излучения?
        Гамма-излучения. Применяют материалы с большой атомной массой и высокой плотностью: свинец, чугун, сталь, вольфрам и т.п. Стационарные экраны, являющиеся частью строительных конструкций, изготавливают из бетона и баритобетона.
    15. Для защиты от ионизирующего излучения из какого материала изготавливаются эластичные экраны и средства индивидуальной защиты?
        Материалом для изготовления эластичных экранов и средств индивидуальной защиты (фартуков, перчаток и др.) служит свинцовая резина.
    16. Какой параметр ионизирующего излучения измерялся в ходе работы? Укажите единицу его измерения.
        Мощность эквивалентной дозы Pc. Имп/с или мкЗв/ч.
