#+TODO: X 0 1 2 | OK
#+TITLE: Mathematical analysis conspect of lections by Kokhas' K.P. - IV term

* Theorems
** OK [#A] 1. ะะฑ ะธะฝัะตะณัะธัะพะฒะฐะฝะธะธ ะฟะพะปะพะถะธัะตะปัะฝัั ััะดะพะฒ
   Uโ - ะฟะพะปะพะถะธัะตะปัะฝัะต ััะฝะบัะธะธ, ะธะทะผะตัะธะผั
   *ัะพะณะดะฐ*
   โซ(โUโ)dฮผ = โโซ(Uโ)dฮผ
*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะกะพัะปะฐัััั ะฝะฐ ะะตะฒะธ ะดะปั ัะฐััะธัะฝัั ััะผะผ Uโ
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ะขะตะพัะตะผะฐ ะะตะฒะธ: fโโคfโโคfโโค...โf โ lim(โซfโdฮผ) = โซfdฮผ
    ะะฐะผะตัะธะผ, ััะพ ัะฐััะธัะฝัะต ััะผะผั ะฟะพะดัะพะดัั ะฟะพะด ััะพ ััะปะพะฒะธะต.
    โโโซ = limโNโซ = limโซโN = {ะฟะพ ะะตะฒะธ} = โซโโ
** OK [#B] 2. ะะฑ ะฐะฑัะพะปััะฝะพะน ะฝะตะฟัะตััะฒะฝะพััะธ ะธะฝัะตะณัะฐะปะฐ
   (X, ๐ด, ฮผ), f ััะผะผะธััะตะผะฐ,
   *ัะพะณะดะฐ*
   โฮต>0 โฮด>0 | โEโ๐ด | ฮผ(E)<ฮด โซ{E}(|f|)dฮผ<ฮต

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะกััะพะธะผ Xโ, ััะพ โซ{Xโ}|f| โ 0, ะฟะพัะพะผ ัะฐััะผะฐััะธะฒะฐะตะผ E ะบะฐะบ (EโฉXโ) โช (Eโฉ(Xโ)แถ).
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ะะพะปะพะถะธะผ Xโ=X(|f|>n), XโโXโโโโ..., โฉ{โ}Xโ = e, ะณะดะต ฮผe = 0
    ะะฐะผะตัะธะผ, ััะพ ฮฝ: E โฆ โซ{E}|f|dฮผ - ััะพ ะผะตัะฐ, ะฟัะธัะตะผ ะฒ ัะธะปั ััะผะผะธััะตะผะพััะธ f, ฮฝ(x) < +โ
    ะขะพะณะดะฐ ะฟะพ ะฝะตะฟัะตััะฒะฝะพััะธ ะผะตัั ัะฝะธะทั ฮฝ(Xโ) โ 0
    ะขะพ ะตััั โฮต>0 โnโ ััะพ ฮฝ(Xโโ) < ฮต/2 โ โซ{Xโโ}|f|dฮผ < ฮต/2
    ะะพ ััะปะพะฒะธั ฮผE < ฮด, ัะพะณะดะฐ ะฒะพะทัะผะตะผ ฮด = ฮต/2nโ, ะฒััะพะดะธั ฮผE < ฮต/2nโ
    โซ{E}|f|dฮผ = โซ{EโฉXโโ} |f|dฮผ + โซ{Eโฉ(Xโโ)แถ} |f|dฮผ
    โค โซ{Xโโ}|f|dฮผ + โซ{Eโฉ(Xโโ)แถ}|f|dฮผ (ััั ะฟะตัะฒัะน ะฟะตัะตัะพะด ะฟัะพััะพ ะฟะพ "โค" (ะผะพะถะตะผ ัะดะตะปะฐัั ะฑะพะปััะต), ะฒัะพัะพะน ะฟะพัะพะผั ััะพ ะฟะพ ัะฒะพะนััะฒั (Xโโ)แถ fโคnโ ะธ EโฉA โ E)
    โค ฮต/2 + nโ*ฮผE โค ฮต
** OK [#B] 3. ะะตะฑะตะณะฐ ะพ ะผะฐะถะพัะธะพะฒะฐะฝะฝะพะน ััะพะดะธะผะพััะธ ะดะปั ััะพะดะธะผะพััะธ ะฟะพ ะผะตัะต (2)
   (X, ๐ด, ฮผ), f, fโ: X โ โ~, fโ โฮผ f,
   โg: g - ััะผะผะธััะตะผะฐั ะธ |fโ| โค g ะดะปั ะฟะพััะธ ะฒัะตั x,
   *ัะพะณะดะฐ*
   fโ, f ััะผะผะธััะตะผั ะธ โซ{X}|fโ-f|dฮผ โ 0, ะธ ัะถ ัะตะผ ะฑะพะปะตะต โซ{X}fโdฮผ โ โซ{X}fdฮผ

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะขัะธ ะฟัะฝะบัะฐ.
    ะ ะฟะตัะฒะพะผ ะดะตะปะฐะตะผ ะฒัะฒะพะดั ะพ ััะผะผะธััะตะผะพััะธ.
    ะะพ ะฒัะพัะพะผ ะดะปั ฮผX<+โ ัััะพะธะผ Xโ, ัะฐัะบะปะฐะดัะฒะฐะตะผ X = Xโ โช (Xโ)แถ.
    ะ ััะตััะตะผ ะดะปั ฮผX>+โ ัะฐัะบะปะฐะดัะฒะฐะตะผ X = A โช X\A, ะณะดะต โซ{X\A}g < ฮต. A -- ะฝะพัะธัะตะปั ัััะฟะตะฝัะฐัะพะน, ะบะพัะพัะพะน ัะพะทะดะฐะตะผ g. ะะพัะพะผ ัััะปะฐะตะผัั ะตะฐ 1 ะฟัะฝะบั.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. fโ ััะผะผะธััะตะผั: โซ|fโ| โค โซg < +โ.
       f ััะผะผะธััะตะผะฐ: ะธะผะตะตั ะผะตััะพ ะฟะพัะพัะตัะฝะฐั ััะพะดะธะผะพััั โnโ fโโโf ะฟ.ะฒ. โ (|fโโ|โคg โ |f|โคg)
       ะ ะตัะต |โซfโ - โซf| = |โซ(fโ-f)| โค โซ|fโ-f|, ะดะพะบะฐะถะตะผ, ััะพ ะฟะพัะปะตะดะฝะตะต โ0
    2. *ฮผX < +โ*, ]ฮต>0, fโ โฮผ f, Xโ=X(|fโ-f|>ฮต), ฮผXโ โ 0
       โซ{X}|fโ-f|dฮผ = โซ{Xโ} + โซ{(Xโ)แถ}
       โค โซ{Xโ}2gdฮผ + โซ{(Xโ)แถ}ฮตdฮผ  (|fโ-f| โค |fโ|+|f| โค 2g, ะฒัะพัะพะน ะฟะตัะตัะพะด ะฟะพ ัะฒ-ะฒั (Xโ)แถ)
       โค 2โซ{Xโ}gdฮผ + ฮตฮผX  (ะฟะตัะฒะพะต ะฒ ัะธะปั ะฝะตะฟั.ะธะฝั. ะผะฐะปะพ ะตัะปะธ ฮผXโ<ฮด, ะฒัะพัะพะต ะผะฐะปะพ*ะพะณั)
       โค ฮต(2+ฮผX)
       ะขะฐะบะธะผ ะพะฑัะฐะทะพะผ, โฮต>0 โN โn>N โซ|fโ-f|dฮผ<ฮต(2+ฮผX)
    3. *ฮผX = +โ*, ]ฮต>0,
       * ะะตะผะผะฐ: โAโ๐ด ฮผa < +โ, โซX\A g < ฮต
         โซX g = sup(โซhโ, 0โคhโโคg, hโ - ัััะฟะตะฝัะฐัะฐั)
         ะะพะทัะผะตะผ h: โซ{X}(g-h)dฮผ < ฮต; ะ - ะฝะพัะธัะตะปั h - {x: h(x) โ 0}
         โซ{X\A}g = โซ{X\A}g-h โค โซ{X}g-h < ฮต (โซ{X\A}h = 0 ะฟะพ ัะฒะพะนััะฒั ะฝะพัะธัะตะปั A)
       ะขะพะณะดะฐ:
       โซ{X}|fโ-f| = โซ{A} + โซ{X\A}
       โค ฮต + 2โซ{X\A}g (ะฟะตัะฒะพะต ะผะฐะปะพ ะฟะพ ะฟัะฝะบัั 2 ััะพะน ัะตะพัะตะผั)
       โค 2ฮต (ะฒัะพัะพะต ะผะฐะปะพ ะฟะพ ะฟะพัะปะตะดะฝะตะน ะปะตะผะผะต)
** OK [#A] 4. *!* ะะตะฑะตะณะฐ ะพ ะผะฐะถะพัะธัะพะฒะฐะฝะฝะพะน ััะพะดะธะผะพััะธ ะดะปั ััะพะดะธะผะพััะธ ะฟะพััะธ ะฒะตะทะดะต
   (X, ๐ด, ฮผ), fn, f: X โ R~, fโ โ f ะฟะพััะธ ะฒะตะทะดะต
   โg, ััะผะผะธััะตะผะฐั, โn |fโ|โคg ะดะปั ะฟะพััะธ ะฒัะตั x
   *ัะพะณะดะฐ*
   fโ, f ััะผะผะธััะตะผัะต, โซ|fโ - f|dฮผ โ 0

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะกััะพะธะผ hโ ะบะฐะบ sup(|fโ-f|), ััะฐะฒะฝะธะฒะฐะตะผ โซ|fโ-f| ั ะฝะธะผ, ะพะฝ โ 0.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    fโ ะธ f ััะผะผะธััะตะผัะต (ัะผ. ะฟัะตะด. ัะตะพัะตะผั)
    hโ = sup(|fโ-f|, |fโโโ-f|, ...), hโโฅhโโโโฅ...
    ะขะฐะบ ะบะฐะบ |fโ-f| โค 2g, ัะพ hโ โค 2g
    ะ ะตัะต lim(hโ) = limฬ(|fโ-f|) = 0 ะฟ.ะฒ.x
    lim(2โซg-โซhโ) = limโซ{X}(2g-hโ) = {ะะตะฒะธ} = โซlim(2g-hโ) = 2โซg
    โ โซhโ โ 0
    ะขะพะณะดะฐ โซ{X}|fโ-f| โค โซhโ โ 0
** OK [#A] 5. ะขะตะพัะตะผะฐ ะคะฐัั
   (X, ๐ด, ฮผ), fโ, f ััะผะผะธััะตะผะพ, fโ โ f ะฟะพััะธ ะฒะตะทะดะต ะฟะพ X, ะธ โC โn โซfโdฮผ < C,
   *ัะพะณะดะฐ*
   โซfdฮผ < C

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะกััะพะธะผ gโ ะบะฐะบ inf(fโ), ะฟะตัะตัะพะดะธะผ ะฟะพ ะฟัะตะดะตะปั โซf = limโซgโ โค C.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    gโ(x) = inf(fโ(x), fโโโ(x), ...)
    gโ(x) โค gโโโ(x) โค ...
    lim gโ(x) = _lim_ fโ = f
    โซgโ โค โซfโ โค C, ะฟะตัะตะนะดะตะผ ะบ ะฟัะตะดะตะปั ะฟะพ ัะตะพัะตะผะต ะะตะฒะธ ะพัะฝะพัะธัะตะปัะฝะพ gโ
    โซf = lim{nโโ}โซgโ โค C
** OK [#A] 6. *!* ะขะตะพัะตะผะฐ ะะตะฑะตะณะฐ ะพ ะฝะตะฟัะตััะฒะฝะพััะธ ะธะฝัะตะณัะฐะปะฐ ะฟะพ ะฟะฐัะฐะผะตััั (4)
   (X, ๐ด, ฮผ), (Y, ๐ต, ฮฝ), f: XรY โ R,
   0. x โฆ f(x, y) ะธะผะตะตั ัะผััะป, ัะพ ะตััั ััะผะผ.
   1. f ัะดะพะฒะปะตัะฒะพััะตั L_loc ะฒ yโ
   2. f(x, y) ะฝะตะฟัะตััะฒะฝะพ ะฒ yโ ะฟัะธ ะฟะพััะธ ะฒัะตั x
   *ัะพะณะดะฐ*
   I(y) = โซf(x, y)dฮผ(x) ะฝะตะฟัะตััะฒะฝะพ ะฒ yโ

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะัะพะฒะตัะบะฐ ะฟะพ ะะตะนะฝะต yโ โ yโ, I(yโ) โ? I(yโ). ะัััะปะบะฐ ะบ ัะตะพัะตะผะต ะพ ะผะฐะถ. ััะพะดะธะผะพััะธ ะดะปั ัั. ะฟะพััะธ ะฒะตะทะดะต + ััะปะพะฒะธะต Lloc ััะฐะทั ะดะฐะตั ะพัะฒะตั.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
     ะัะพะฒะตัะธะผ ะฟะพ ะะตะนะฝะต: yโ โ yโ โ? I(yโ) โ I(yโ)
     fโ(x) = f(x, yโ); fโ(x) = f(x, yโ);
     1. โ fโ(x) โ fโ(x) ะฟัะธ ะฟ.ะฒ.x (ะฟะพ ััะปะพะฒะธั)
     2. yโโU(yโ) |fโ(x)|โคg(x) ะฟัะธ ะฟ.ะฒ.x
     ะขะพะณะดะฐ ะฟะพ ัะตะพัะตะผะต ะะตะฑะตะณะฐ ะพ ะผะฐะถะพัะธัะพะฒะฐะฝะฝะพะน ััะพะดะธะผะพััะธ โซfโ(x)dฮผ โ โซfโ(x)d
** OK [#A] 7. *!* ะัะฐะฒะธะปะพ ะะตะนะฑะฝะธัะฐ ะพ ะดะธััะตัะตะฝัะธััะตะผะพััะธ ะธะฝัะตะณัะฐะปะฐ ะฟะพ ะฟะฐัะฐะผะตััั (4)
   (X, ๐ด, ฮผ), (Y, ๐ต, _), f: XรY โ R,
   0. x โฆ f(x, y) ััะผะผะธััะตะผะพ
   1. f ะดะธััะตัะตะฝัะธััะตะผะพ ะฟะพ y ะฟัะธ ะฟะพััะธ ะฒัะตั x
   2. f'_y ัะดะพะฒะปะตัะฒะพััะตั L_loc ะฒ y0
   *ัะพะณะดะฐ*
   I'(yโ) = (โซf(x, y)dฮผ(x))'_y = โซf'_y(x, y)dฮผ(x)

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    F(x,h) = f(x,yโ+h)-f(..)/h, ะดะพะบะฐะทัะฒะฐะตะผ F(x) โ Lloc(0), ัะผัะบะฐะตะผ ะผะฐะถ. ััะพะดะธะผะพััั ะดะปั ััะพะดะธะผะพััะธ ะฟ.ะฒ.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    F(x, h) = (f(x, yโ+h)-f(x, yโ))/h โ{hโ0} f'_y(x, y) ะฟ.ะฒ.x โ f'_y(x, y) ะธะทะผะตัะธะผะฐ
    (I(yโ+h)-I(yโ))/h = โซF(x, h)dฮผ โ? โซf'_y(x, y)dฮผ
    ะะพะบะฐะถะตะผ FโLloc(0): โxโyโ{U~=U(yโ)-yโ}  |F(x, h)| = |f'_y(x, yโ+0h)|โคg(x) ะฟะพ ััะป
    ะขะพะณะดะฐ ะฟัะธะผะตะฝะธะผ ัะตะพัะตะผั ะะตะฑะตะณะฐ ะพ ะผะฐะถ. ััะพะดะธะผะพััะธ.
** OK [#C] 8. ะััะธัะปะตะฝะธะต ะธะฝัะตะณัะฐะปะฐ ะะธัะธัะปะต (6, 7)
   โซ_0^โ (sinฮฑx/x) = ฯ/2

*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    I(y) = โซ{0,โ}eโปหฃสธ(sinx/x)dx, y>0.
    I'(y) = {ะฟะพ ะฟัะฐะฒะธะปั ะะตะนะฑะฝะธัะฐ} = -โซ{0,โ}eโปหฃสธsinxdx
    = Im(โซ{0,โ}eโปหฃสธeโปโฑหฃdx)
    = Im(โซ{0,โ}e^(-x(y+i))dx = {ะฒะพะทัะผะตะผ ะธะฝัะตะณัะฐะป}
    = Im(1/(y+i))
    = Im((y-i)/(yยฒ+i))
    = -1/(yยฒ+1)
    ะะฑะพัะฝะพะฒะฐะฝะธะต ะฟะตัะตัะพะดะฐ ะฟะพ ะฟัะฐะฒะธะปั ะะตะนะฑะฝะธัะฐ:
    1. |eโปหฃสธ(sinx/x)| โค |eโปหฃสธ|, ะฒัะพัะพะต ััะผะผะธััะตะผะพ
    2. eโปหฃสธ(sinx/x) ะพัะตะฒะธะดะฝะพ ะดะธััะตัะตะฝัะธััะตะผะพ
    3. |eโปหฃสธsinx| โค e^(-xyโ/2), ััะผะผะธััะตะผะพ

    ะฃัะธััะฒะฐั, ััะพ I' = -1/(yยฒ+1), I = -arctgy+C. ะะฐะนะดะตะผ C, ััััะตะผะธะฒ yโโ.
    ะัะตะฒะธะดะฝะพ, I โ{yโโ}โ 0 (ะฟะพ ะฝะตะฟัะตััะฒะฝะพััะธ ะะตะฑะตะณะฐ (6), ะฝะตัะปะพะถะฝะพ ะดะพะบะฐะทะฐัั).
    ะขะพะณะดะฐ C = ฯ/2, I = arctg(y)+ฯ/2 โ{yโโ} 0.

    ะะพะบะฐะถะตะผ, ััะพ ะตัะปะธ I = arctg(y)+ฯ/2, ัะพ *โซsinx/x = ฯ/2* (ะผั ะบะฐะบ ะฑั ััััะตะผะธะปะธ yโ0).
    ะะปั ััะพะณะพ ะดะพะบะฐะถะตะผ, ััะพ J = โซeโปหฃสธ(sinx/x)dx - โซsinx/xdx = โซ((eโปหฃสธ-1)/x)*sinxdx โ 0 ะฟัะธ yโ0.
    J = โซ{0,t} + โซ{t,โ}.
    1. |โซ{0,t}((eโปหฃสธ-1)/x)*sinxdx| โค โซ{0,t}|((eโปหฃสธ-1)/x)*sinx|dx โค โซy|sinx|dx = โซ{0,t}ydx = yt.
    2. ะกะฝะฐัะฐะปะฐ ะฒะพะทัะผะตะผ ะฟะพ ัะฐัััะผ: โซ{t,โ}((eโปหฃสธ-1)/x)*sinx = (1-eโปหฃสธ)/x cosx |^โ_t + โซ{t,โ}sinx*(-yeโปหฃสธ/x - (eโปหฃสธ-1)/xยฒ)dx
       ะัััะดะฐ ะพัะตะฝะธะผ ะฟะพ ะผะพะดัะปั: |โซ{t,โ}...dx| โค 1/t + โซ{t,โ}1/xยฒ + โซ{t,โ}y/x*eโปหฃสธ.
       ะญัะธ ััะธ ัะปะฐะณะฐะตะผัั ะฟะพะปััะฐัััั ะธะท ััะตั ัะปะฐะณะฐะตะผัั ะฒ ัะฐะทะปะพะถะตะฝะธะธ ะฟะพ ัะฐัััะผ ัะพะพัะฒะตัััะฒะตะฝะฝะพ ะพัะฑัะฐััะฒะฐะฝะธะตะผ cos ะฒ ะฟะตัะฒะพะผ ะธ sin ะฒะพ ะฒัะพัะพะผ-ััะตััะตะผ.
       ะะฐะถะดะพะต ะธะท ะฝะธั <1/t.
    ะขะพะณะดะฐ J โค yt + 1/t. ะะพะดะฑะตัะตะผ t, ััะพ 1/t<ฮต/2, ะธ y ััะพะฑ tyโคฮต/2. ะขะพะณะดะฐ J < ฮต.
** 2 [#B] 9. ะขะตะพัะตะผะฐ ะพะฑ ะฒััะธัะปะตะฝะธะธ ะธะฝัะตะณัะฐะปะฐ ะฟะพ ะฒะทะฒะตัะตะฝะฝะพะผั ะพะฑัะฐะทั ะผะตัั (ะะตะฒะธ)
   (X, ๐ด, ฮผ), (Y, ๐ต, _), ฮฆ, ฮฝ = โซwdฮผ,
   f - ะฟะพะปะพะถะธัะตะปัะฝะฐั, ะธะทะผะตัะธะผะฐั ะธะปะธ ััะผะผะธััะตะผะฐั ะฝะฐ Y,
   *ัะพะณะดะฐ*
   โซ{Y}fdฮฝ = โซ{ฮฆโปยน(Y)} f(ฮฆ(x))w(x)dฮผ

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะกัััะบัััะฝะฐั ะธะฝะดัะบัะธั ะฟะพ ัะธะฟั f (ะพะดะฝะฐ ัััะฟะตะฝัะบะฐ, ัััะฟะตะฝัะฐัะฐั, ะธะทะผะตัะธะผะฐั, ััะผะผะธััะตะผะฐั).
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. f = Xb (ะพะดะฝะฐ ัััะฟะตะฝัะบะฐ), bโB
       โซfdฮฝ = ฮฝ(b),
       โซ{ฮฆโปยน(Y} f(ฮฆ(x))w(x)dฮผ = {ะฒ ะผะตัั ะพะฟั. ัััะฟะตะฝัะบะธ ะธ ฮฆโปยน(Y)=X}
       = โซ_ฮฆโปยน(Y) 1*w(x)dฮผ = ฮฝ(b) ะฟะพ ะพะฟั. ะฒะทะฒะตั. ะพะฑัะฐะทะฐ ะผะตัั
    2. f = โฮฑ*Xb (ัััะฟะตะฝัะฐัะฐั). ะะตัะฝะพ ะฒ ะผะตัั ะฟัะฝะบัะฐ 1 ะธ ัะฒ-ะฒ ััะผะผั
    3. fโฅ0, ะธะทะผะตัะธะผะฐั
       โซfdฮฝ = sup{โซpdฮฝ, 0โคpโคf, p - ัััะฟะตะฝัะฐัะฐั} -- ะพะฟั
       ะะพะทัะผะตะผ pโโคpโโค...โคf, โx pโ(x)โf
       ะฟะพ ัะตะพัะตะผะต ะะตะฒะธ lim(โซpโdฮฝ) = โซfdฮฝ
       pโ(ฮฆ(x))w(x) โค pโโโ(ฮฆ(x))w(x) โค ... โ f(ฮฆ(x))w(x)
    4. f ััะผะผะธััะตะผะฐั
       โซf = โซf+ - โซf-, ัะฐะฒะตะฝััะฒะพ ะฒัะฟะพะปะฝะตะฝะพ ะดะปั ััะตะทะพะบ ะฟะพ ะฟ.3, ัะพ ะตััั
       โซfdฮฝ = โซf+(ฮฆ(x))w(x) - ... = โซf(ฮฆ(x))w(x)dฮผ
** 2 [#A] 10. ะัะธัะตัะธะน ะฟะปะพัะฝะพััะธ
   (X, ๐ด, ฮผ), (Y, ๐ต, _), X=Y, ๐ด=๐ต,
   w - ะฟะพะปะพะถะธัะตะปัะฝะฐั, ะธะทะผะตัะธะผะฐั ะฝะฐ X,
   *ัะพะณะดะฐ*
   w - ะฟะปะพัะฝะพััั ฮฝ ะพัะฝะพัะธัะตะปัะฝะพ ฮผ
   โ
   โAโ๐ด ฮผA*infw โค ฮฝA โค ฮผA*supw

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะะฟัะฐะฒะพ ะพัะตะฒะธะดะฝะพ, ะฒะปะตะฒะฐ ัััะพะธะผ Aโ = A(qแตโคw<qแตโปยน), ะดะพะผะฝะพะถะฐะตะผ ัะฐะผ, ะฟะพัะพะผ q โ 1-0.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. โ
       ะัะตะฒะธะดะฝะพ: ะฟะพ ะพะฟั. ฮฝA = โซ{A}wdฮผ, ฮผA*infw โค โซ{A}wdฮผ โค ฮผA*supw
    2. โ
       w>0, eโ=X(w=0), v(eโ)=0
       Aโ = A(qแตโคw<qแตโปยน); qโ(0, 1), A = โAโ
       ะขะพะณะดะฐ ัะฐััะผะพััะธะผ ะดะฐะฝะฝะพะต ะฝะตัะฐะฒะตะฝััะฒะพ (.. โค ฮฝA โค ..) ะฟะพ Aโ
       qแตฮผAโ โค ฮฝ(Aโ) โค qแตโปยนฮผAโ
       qแตฮผAโ โค โซ{Aโ}wdฮผ โค qแตโปยนฮผAโ (ััะพ ััะฒะตัะถะดะตะฝะธะต ะฝะต ะทะฐะฒะธัะธั ะพั ะฟัะตะด.)
       ..ะฃะผะฝะพะถะธะผ/ะฟะพะดะตะปะธะผ ััั ะฒัะต ะฝะฐ q,..
       qโซ{Aโ}wdฮผ โค qแตฮผAโ โค ฮฝ(Aโ) โค 1/q * qแตฮผAโ โค 1/q * โซ{Aโ}wdฮผ
       qโซ{Aโ}wdฮผ โค ฮฝ(Aโ) โค 1/q * โซ{Aโ}wdฮผ
       qโซ{A}wdฮผ โค ฮฝ(A) โค 1/q * โซ{A}wdฮผ (ััะตะฟะตะฝะตะน ะฒ ะฟัะตะด. ะฝะตัะฐะฒะตะฝััะฒะต ะฝะตั)
       q โ 1-0
       โซ{A}w โค ฮฝ(A) โค โซ{A}w โ w - ะฟะปะพัะฝะพััั ฮฝ ะพัะฝะพัะธัะตะปัะฝะพ ฮผ
** 2 [#A] 11. ะะตะผะผะฐ ะพ ะผะฝะพะถะตััะฒะฐั ะฒะฟะพะปะฝะต ะฟะพะปะพะถะธัะตะปัะฝะพััะธ ะทะฐััะดะฐ
   (X, ๐ด, ฮผ), Aโ๐ด, ฮผA โฅ 0 (ะทะฐะผะตัะธะผ, A ะฝะต ะผะฝะพะถะตััะฒะพ ะฟะพะปะพะถะธัะตะปัะฝะพััะธ)
   *ัะพะณะดะฐ*
   โ GโA -- ะผะฝะพะถะตััะฒะพ ะฟะพะปะพะถะธัะตะปัะฝะพััะธ, ฮผ(G) โฅ ฮผ(A)

*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ะะฟัะตะดะตะปะธะผ ะฟะพะฝััะธะต: E -- ะผะฝะพะถะตััะฒะพ ฮต-ะฟะพะปะพะถะธัะตะปัะฝะพััะธ, ะตัะปะธ โBโE ฮผBโฅ-ฮต
    ะฃัะฒะตัะถะดะฐะตััั, ััะพ โฮต>0 A ัะพะดะตัะถะธั ะผะฝะพะถะตััะฒะพ ฮต-ะฟะพะปะพะถะธัะตะปัะฝะพััะธ
    1. ะัะปะธ A -- ะผะฝะพะถะตััะฒะพ ฮต-ะฟะพะปะพะถะธัะตะปัะฝะพััะธ, ัะพ ะฒัะต ะพะบ
    2. ะัะปะธ ะฝะตั:
       โBโโA, ฮผBโ<-ฮต; Cโ=A\Bโ, ฮผCโ>ฮผA; Cโ -- ะผะฝะพะถะตััะฒะพ ะฟะพะปะพะถะธัะตะปัะฝะพััะธ? ะัะปะธ ะฝะตั, ัะพ
       โBโโCโ, ฮผBโ<-ฮต; Cโ=Cโ\Bโ, ฮผCโ>ฮผCโ, ... ะฟัะพะดะพะปะถะฐั ะดะพ ะฑะตัะบะพะฝะตัะฝะพััะธ, ะฟะพะปััะธะปะธ ะฑั
       B = โBโ, ฮผB=-โ, ััะพ ัะปะธัะบะพะผ ะผะฝะพะณะพ ะดะปั A, ะบะพัะพัะพะต ะฟะพ ััะปะพะฒะธั ฮผA โฅ 0

    CโโA ะผะฝะพะถะตััะฒะพ 1-ะฟะพะปะพะถะธัะตะปัะฝะพััะธ, ฮผCโโฅฮผA
    CโโCโ ะผะฝะพะถะตััะฒะพ 1/2-ะฟะพะปะพะถะธัะตะปัะฝะพััะธ,...
    ...
    CโโCโโโ ะผะฝะพะถะตััะฒะพ 1/n-ะฟะพะปะพะถะธัะตะปัะฝะพััะธ ฮผCโโฅฮผCโโโ
    ะั ะผั ะฝะฐัะปะธ ะฝะฐัะต G: G = โ{โ}Ci
    โC โ G ฮผC โฅ 0, ัะฐะบ ะบะฐะบ ะตัะปะธ ฮผC=-1/100, ัะพ C โ C_101, ะฝะพ ะฟะพ ะพะฟัะตะดะตะปะตะฝะธั G ะพะฝะพ ัะพะดะตัะถะธััั ะฒ ะบะฐะถะดะพะผ Ci.
    ฮผG = lim{iโโ}ฮผCi โฅ ฮผA
** 2 [#A] 12. ะขะตะพัะตะผะฐ ะะฐะดะพะฝะฐ-ะะธะบะพะดะธะผะฐ, ะตะดะธะฝััะฒะตะฝะฝะพััั
   (X, ๐ด, (ฮฝ,ฮผ)) ฮฝ ะฐะฑัะพะปััะฝะพ ะฝะตะฟัะตััะฒะฝะฐ ะพัะฝะพัะธัะตะปัะฝะพ ฮผ,
   *ัะพะณะดะฐ*
   โ!w(x) | w - ะฟะปะพัะฝะพััั ฮฝ ะพัะฝะพัะธัะตะปัะฝะพ ฮผ, ัะพ ะตััั
   โf-ะธะทะผะตัะธะผะฐั ะธะปะธ ััะผะผ โซfdฮฝ = โซfwdฮผ
   ะธะปะธ ะฟัะพััะพ ฮฝ(b) = โซ{b}wdฮผ

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะัะฟะธัะฐัั ะพะฟัะตะดะตะปะตะฝะธะต ะฟะปะพัะฝะพััะธ ะดะปั ะดะฒัั ััะฝะบัะธะน, ะพัะตะฝะธัั ัะฐะทะฝะพััั.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ะะดะธะฝััะฒะตะฝะฝะพััั
    ะะพะบะฐะถะตะผ ัะปะตะดัััะตะต:
    f,g - ฮผ-ััะผะผะธััะตะผั, โaโ๐ด โซ{a}fdฮผ=โซ{a}gdฮผ โ f=g ะฟ.ะฒ.
    h = f-g, h=0 ะฟ.ะฒ.
    โซ{X}|h|=โซhโ+โซhโ=โซ{X(hโฅ0)}h-โซ{X(h<0)}h = 0 โ โซh=0
    ะขะพะณะดะฐ โAโ๐ด โซ{A}hdฮผ=0
    ะั ะธ ัะธะฟะฐ ัะพะณะดะฐ ะฟัััั ััะธ f,g ะบะฐะบ ัะฐะท ะฒะตัะฐ, ัะพะณะดะฐ ฮฝ(b)=โซ{b}fdฮผ=โซ{b}gdฮผ โ f==g
** 1 [#C] 13. ะะฐะดะพะฝ-ะะธะบะพะดะธะผ, ัััะตััะฒะพะฒะฐะฝะธะต
   ะกะผ. ะฟัะตะด. ัะตะพัะตะผั

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะกะพะทะดะฐะตะผ P:={hโฅ0 | h-ะธะทะผะตัะธะผะฐั, โAโ๐ด โซ{A}hdฮผ โค ฮฝ(A)}, ะฟะพัะพะผ hโ~=max(hโ...hโ), ัะฐะบ ััะพ hแตข โ I.
    ะะฐัะตะผ ะดะพะบะฐะทัะฒะฐะตะผ ะพั ะฟัะพัะธะฒะฝะพะณะพ ั ะฟะพะผะพััั ะทะฐััะดะฐ ฯ ััะพ I < โซ{X}(f+a๐B) โค ฮฝ(B). ะญัะพ ะฟัะพัะธะฒะพัะตัะธะต.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    P:={hโฅ0 | h-ะธะทะผะตัะธะผะฐั, โAโ๐ด โซ{A}hdฮผ โค ฮฝ(A)}
    {hโ, hโ}โP โ max(hโ, hโ)โP
    โซ{A}max(hโ, hโ) = โซ{A(hโโฅhโ)}hโ+โซ{A(hโ<hโ)}hโ โค ฮฝA(hโโฅhโ)+ฮฝA(hโ<hโ)=ฮฝ(A)
    โhโ...hโโP max(hโ...hโ)โP
    I:=sup{โซ{X}hdฮผ | hโP} โค ฮฝ(X)
    ะัะฑะตัะตะผ {hแตข}, ััะพ โซhแตขdฮผ โ I
    hโ~ = max(hโ...hโ); hโ~ โค hโ~ โค ...; โซ{X}hแตข~ โ I; โซ{X}hแตขโคโซ{X}hแตข~โคI
    ะขะพะณะดะฐ ะธัะบะพะผะฐั f:=limhโ~. โซf = โซlimhโ = limโซhโ โค ฮผA.

    ะฅะพัะธะผ ะดะพะบะฐะทะฐัั, ััะพ โA โซAfdฮผ = ฮฝ(A).

    ะั ะฟัะพัะธะฒะฝะพะณะพ: ะดะพะฟัััะธะผ, ััะพ โAโ โซ{Aโ}fdฮผ < ฮฝ(Aโ).
    ะขะพะณะดะฐ ฮผAโ > 0, ฮฝ(Aโ) - โซ{Aโ}fdฮผ > a*ฮผ(Aโ) ะดะปั ะบะฐะบะพะณะพ-ัะพ ะบะพัััะธัะธะตะฝัะฐ a>0.
    ะะพะทัะผะตะผ ะทะฐััะด ฯ, ฯ(E) = ฮฝ(E)-โซ{E}fdฮผ-aฮผ(EโฉAโ), ฯ(Aโ)>0 (ะฟะพะดััะฐะฒะธัั, ะฟัะพะฒะตัะธัั), ฮฝ(E) โฅ ฯ(E).
    ะะพ ะปะตะผะผะต ะพ ะผะฝะพะถะตััะฒะฐั ะฒะฟะพะปะฝะต ะฟะพะปะพะถะธัะตะปัะฝะพััะธ โB โ Aโ, ััะพ ฯ(B) โฅ ฯ(Aโ) > 0. ะะพัะบะพะปัะบั ฮฝ(A) โฅ ฯ(A), ัะพ ฮฝ(B) โฅ ฯ(B) > 0 โ ฮฝ(B) > 0.
    ะะฐะนะดะตะผ ะฟัะพัะธะฒะพัะตัะธะต ะฒ ัะปะตะดัััะตะผ:
    1.โE โซ{E}(f+a๐B)dฮผ = โซf + aฮผ(BโฉE) = โซ{E\B}fdฮผ + โซ{EโฉB}fdฮผ + aฮฝ(BโฉE) = {ะฒัะพััะต ะดะฒะฐ ะทะฐะผะตะฝะธะผ ะฟะพ ัะพัะผัะปะต ฯ}
    = โซ{E\B}fdฮผ + ฮฝ(EโฉB) - ฯ(EโฉB) โค {ะฟะตัะฒะพะต ะฟะพ ัะฒะพะนััะฒั f} โค ฮฝ(E\B) + ฮฝ(EโฉB) - ฯ(EโฉB) = ฮฝ(B) - ฯ(EโฉB) โค ฮฝ(B).
    2. โซ{X}(f+a๐B) = โซ{X}f + aฮผB = I + a*ฮผB > I.
    ะขะพะณะดะฐ I < ฮฝ(X).
    ะญั ะธ ะตััั ะฟัะพัะธะฒะพัะตัะธะต.
    ะะธะดะธะผะพ, I = โซ(X) ะพัะตะฒะธะดะฝะพ)))0
    โโ
** 2 [#B] 14. ะะตะผะผะฐ ะพะฑ ะพัะตะฝะบะต ะผะตั ะพะฑัะฐะทะพะฒ ะบัะฑะพะฒ ะธะท ะพะบัะตััะฝะพััะธ ัะพัะบะธ ะดะธััะตัะตะฝัะธััะตะผะพััะธ (ะฟัะตะพะฑั. ะผะตัั ะะตะฑะตะณะฐ ะฟัะธ ะป.ะพ. ะธ ัะดะฒะธะณะต)
   ฮฆ: O โ โแต โ โโฟ, a โ O, ฮฆ ะดะธัั ะฒ a, 0 < |detฮฆ'(a)| < C,
   *ัะพะณะดะฐ*
   โUโ | โQ - ะบัะฑ, Q โ Uโ, a โ Q, ฮป - ะผะตัะฐ ะะตะฑะตะณะฐ
   ฮป(ฮฆ(Q)) โค c * ฮปQ

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะัะฟะธััะฒะฐะตะผ ฮฆ(x), ะดะตะปะธะผ, ะทะฐะฒะพะดะธะผ ฯ, ะฟะพะบะฐะทัะฒะฐะตะผ ััะพ |ฯ(x)-x| ะผะฐะปะพ ะฟะพ ะพะฟั., ะฟะพะบะฐะทัะฒะฐะตะผ ััะพ ฮป(ฯ(Q)) โฅ (1+2ฮต)แตฮปQ.
    ะะฐะปััะต ะธะท ะฟะตัะฒะพะฝะฐัะฐะปัะฝะพะน ัะพัะผัะปั ะฒััะฐะถะฐะตะผ ฯ ะธ ะฟัะธะผะตะฝัะตะผ ัะตะพัะตะผั ะพ ะฟัะตะพะฑั. ะผะตัั ะะตะฑะตะณะฐ ะธะท ะฟัะตะด. ัะตะผะฐ, ะพัะบัะดะฐ ะธ ะฒัะปะฐะทะธั |det|.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ฮฆ(x)=ฮฆ(a)+L(x-a)+o(x-a), ะณะดะต L=ะค'(a)
    a+Lโปยน(ฮฆ(x)-ฮฆ(a))=x+oโ(x-a); oโ=Lโปยน(o); (ัะผะฝะพะถะธะปะธ ะฒัะต ะฝะฐ Lโปยน)
    ฯ(x)=x+o(x-a)
    โฮต>0 โU(a):=B(a) โxโB(a) |ฯ(x)-x| < ฮต/โm * |x-a|    ะฟะพ ะพะฟัะตะดะตะปะฝะธั o(x-a)
    Q(ะบัะฑ ัะพ ััะพัะพะฝะพะน h) โ U(a) xโQ |x-a|โคโm * h
    ะขะพะณะดะฐ |ฯ(x)-x| โค ฮต * h
    x, y โ Q |ฯแตข(x)-ฯแตข(y)| โค |ฯแตข(x)-xแตข|+|ฯแตข(y)-yแตข|+|xแตข-yแตข| โค |ฯ(x)-x|+|ฯ(y)-y|+|x-y| โค (1+2ฮต)h
    ะขะพ ะตััั ฯ(Q)โะัะฑ ัะพ ััะพัะพะฝะพะน (1+2ฮต)h
    ะัััะดะฐ ฮป(ฯ(Q)) โค (1+2ฮต)แต*ฮปQ ะฟะพ ะบะฐะบะธะผ-ัะพ ะพะฑัะธะผ ัะฒะพะนััะฒะฐะผ.
    ะะท ะฒัะพัะพะน ัััะพัะบะธ ะดะพะบะฐะทะฐัะตะปัััะฒะฐ ฮฆ(x) = L(ฯ(x)-a) + ฮฆ(a).
    ะญัะพ ะปะธะฝะตะนะฝะพะต ะพัะพะฑัะฐะถะตะฝะธะต ะธ ัะดะฒะธะณ, ัะพะณะดะฐ ะฟะพ ัะตะพัะตะผะต ะพ ะฟัะตะพะฑัะฐะทะพะฒะฐะฝะธะธ ะผะตัั ะะตะฑะตะณะฐ ะฟัะธ ะป.ะพ ะธ ะธะฝะฒะฐัะธะฐะฝัะฝะพััะธ ะฟัะธ ัะดะฒะธะณะต (3 ัะตะผ), ะธะผะตะตะผ:
    ฮป(L(ฯ(Q))) = |detL|โฮปฯ(Q)
    ฮป(ฮฆ(Q)) โค |detL|(1+2ฮต)แตฮปQ -- ะฟะพะดะฑะตัะตะผ ััั ะฝัะถะฝะพะต ฮตแตข
** 2 [#B] 15. ะขะตะพัะตะผะฐ ะพ ะฟัะตะพะฑัะฐะทะพะฒะฐะฝะธะธ ะผะตัั ะะตะฑะตะณะฐ ะฟัะธ ะดะธััะตะพะผะพััะธะทะผะต (10, 14)
   ฮฆ: โโฟ โ โโฟ - ะดะธััะตะพะผะพััะธะทะผ,
   โbโMแต ฮป(ฮฆ(b))=โซ_b |detฮฆ'(x)|dฮป

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะัะพะฒะตัะธะผ ฮปโฮฆ ะฝะฐ ะฟะปะพัะฝะพััั ะฟะพ ะบัะธัะตัะธั, ะฒะพะทัะผะตะผ ัะพะปัะบะพ ะพะดะฝะพ ะฝะตัะฐะฒะตะฝััะฒะพ.
    ะะพะบะฐะถะตะผ ะพั ะฟัะพัะธะฒะฝะพะณะพ ะดะปั ะบัะฑะพะฒ ัะตัะตะท ะปะตะผะผั 14, ะฟะพัะพะผ ะดะปั ะพัะบััััั ัะตัะตะท ะพะฟัะตะดะตะปะตะฝะธะต ะพัะบัััะพะณะพ ะพะฑัะตะดะธะฝะตะฝะธะตะผ ะบัะฑะพะฒ.
    ะะปั ะฝะตะพัะบััััั ะฟัะตะดััะฐะฒะธะผ ะบะฐะบ inf ะพัะบััััั, ะดะพะบะฐะถะตะผ infsupX = supY, ะฒ ะฝะตะผ โฅ ะพัะตะฒะธะดะฝะพ ัะตัะตะท ะพะฟั. inf, ะดััะณะพะต ะดะพะบะฐะทัะฒะฐะตััั ั ะฟะพะผะพััั ะฟะพะดะฑะพัะฐ cโ, c, ฮต, ะพัะตะฝะพะบ sup ะธ ะฒะบะปะฐะดัะฒะฐะฝะธั E ะฒ Eโ. ะะฐััะตั ะฟะพัะปะตะดะฝะตะณะพ -- ะผะพะถะฝะพ ะทะฐะฟะธัะฝััั ะฒ ะบัะฑ ะธ ัะพัะปะฐัััั ะฝะฐ ัะตะพัะตะผั 14.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ฮฝ(A) = ฮปฮฆ(A) -- ะผะตัะฐ.
    J(x) = |detฮฆ'(x)|.
    ะัะพะฒะตัะธะผ, ััะพ J ัะฒะปัะตััั ะฟะปะพัะฝะพัััั ฮฝ ะพัะฝะพัะธัะตะปัะฝะพ ฮป.
    ะะปั ััะพะณะพ ะดะพะบะฐะถะตะผ ะฟะพ ะบัะธัะตัะธั ะฟะปะพัะฝะพััะธ ััะพ infJ*ฮปA โค ฮฝ(A) โค supJ*ฮปA.
    ะะพััะฐัะพัะฝะพ ะดะพะบะฐะทะฐัั ัะพะปัะบะพ ะฟัะฐะฒะพะต ะฝะตัะฐะฒะตะฝััะฒะพ, ะปะตะฒะพะต ะฑัะดะตั ัะฐะฑะพัะฐัั ะฐะฝะฐะปะพะณะธัะฝะพ ะพัะฝะพัะธัะตะปัะฝะพ ฮฆโปยน. 1/infJ = supJ.
    1. ะะฐััะผะพััะธะผ ััะพ ััะฒะตัะถะดะตะฝะธะต ัะฟะตัะฒะฐ ะดะปั ะบัะฑะพะฒ Q.
       ะขะพะณะดะฐ ะพั ะฟัะพัะธะฒะฝะพะณะพ: ะฟัััั ฮฝ(A) > supJ*ฮปA.
       ฮฝ(Q) > supJ*ฮปQ.
       ะะฐะทะพะฑัะตะผ Q ะฝะฐ 2โฟ ัะฐััะตะน, ัะพะณะดะฐ ัััะตััะฒัะตั ะฟะพัะปะตะดะพะฒะฐัะตะปัะฝะพััั ะบัะฑะพะฒ Qโ โ Qโ โ Qโ..., ะบะฐะถะดัะน ะธะท ะบะพัะพััั ะฒ 2i ัะฐะท ะผะตะฝััะต ะฟัะตะดัะดััะตะณะพ, ะธ ะดะปั ะฒัะตั ะฒัะฟะพะปะฝะตะฝะพ ะฝะตัะฐะฒะตะฝััะฒะพ.
       ะัััะดะฐ a = โฉ{โ}Qแตข, ะธ ัะพะณะดะฐ โk aโQโ, ฮฝ(Q) > ฮปQโ*c.
       ะ ะฟะพัะปะตะดะฝะตะผ ะฝะตัะฐะฒะตะฝััะฒะต ะฟัะพัะธะฒะพัะตัะธะต ั ะปะตะผะผะพะน ะพะฑ ะพัะตะฝะบะต ะผะตั ะพะฑัะฐะทะพะฒ ะบัะฑะพะฒ ะธะท ะพะบัะตััะฝะพััะธ ัะพัะบะธ ะดะธััะตัะตะฝัะธััะตะผะพััะธ.
    2. ะะปั ะพัะบััััั ะผะฝะพะถะตััะฒ ััะฒะตัะถะดะตะฝะธะต ะฒะตัะฝะพ ะฒ ัะธะปั ัะพะณะพ, ััะพ ะพัะบัััะพะต ะผะฝะพะถะตััะฒะพ ะผะพะถะฝะพ ะฟัะตะดััะฐะฒะธัั ััะตัะฝัะผ ะพะฑัะตะดะธะฝะตะฝะธะตะผ ะบัะฑะพะฒ.
       A = โชQแตข, ัะพะณะดะฐ ฮฝA = โฮฝQแตข = โsup{Qแตข}J*ฮปQแตข = โsup{A}J*ฮปQแตข = sup{A}J*โQแตข = supJ*ฮปA.
    3. ะะปั ะดััะณะธั ะผะฝะพะถะตััะฒ ฮฝA = inf{E}(ฮฝE) โค inf{E}(sup{xโE}J*ฮปE) ~= sup{A}J*ฮปA.
       ะะพััะฝะตะฝะธะต ะฟะตัะฒะพะณะพ/ะฒัะพัะพะณะพ ะฟะตัะตัะพะดะฐ: inf(ฮฝA) = inf(ฮป(ฮฆ(A))) = inf(ฮปE'), ะณะดะต E' ะพัะบัััะพะต ะธ ฮฆ(A) โ E'. ะขะพะณะดะฐ A โ ฮฆโปยนE', ะธ ะดะปั E := ฮฆโปยนE' ะฒัะฟะพะปะฝะตะฝะพ ะดะพะบะฐะทัะฒะฐะตะผะพะต ะฝะตัะฐะฒะตะฝััะฒะพ.
       ะะพััะฝะตะฝะธะต inf{E}(sup{xโE}J*ฮปE) ~= sup{A}J*ฮปA:
       ะะพะบะฐะถะตะผ โค ะธ โฅ.
       ะัะปะธ ฮปA = 0, ัะพ ะฒัะฟะพะปะฝะตะฝะพ ัะฐะฒะตะฝััะฒะพ.
       ะัััั ฮปA โฅ 0.
       โฅ ะพัะตะฒะธะดะฝะพ:
       โx.A(x) โฅ B โ inf{x}A(x) โฅ B ะฟะพ ะพะฑัะตะผั ัะฒะพะนััะฒั ะธะฝัะธะผัะผะฐ.
       ะะดะตัั A = sup{E}J*ฮปE, B = sup{A}J*ฮปA. ะัะตะฒะธะดะฝะพ ััะพ A โฅ B (sup ะฟะพ ะฑะพะปััะตะผั ะผะฝะพะถะตััะฒั, ะผะตัะฐ ะพั ะฑะพะปััะตะณะพ ะผะฝะพะถะตััะฒะฐ).
       โค ะฝะตะพัะตะฒะธะดะฝะพ:
       ะัััั A โ E โ Q โ O, ะณะดะต E -- ะพัะบัััะพะต ะผะฝะพะถะตััะฒะพ, Q -- ะทะฐะผะบะฝัััะน ะบัะฑ. ะัะปะธ ะฝะต ะฟะพะปััะฐะตััั ัะฐะบ, ัะฐััะผะพััะธะผ Aแตข, ััะพะฑั Aแตข โ Qแตข.
       ะะฐะผะตัะธะผ, ััะพ sup{xโA}J ะพะณัะฐะฝะธัะตะฝ, sup{xโE}J < cโ < c.
       ะขะฐะบะถะต Jโปยน(-โ, cโ) ะพัะบัััะพะต ะผะฝะพะถะตััะฒะพ.
       ะะพะทัะผะตะผ Eโ โ A, ัะฐะบ ััะพ ฮป(Eโ\A) < ฮต.
       E := Eโ โฉ Jโปยน(-โ, cโ).
       ฮป(E\A) < ฮป(Eโ\A) < ฮต. ะะตัะฒัะน ะฟะตัะตัะพะด ะฟะพัะพะผั ััะพ E โ Eโ.
       ะขะพะณะดะฐ supJ*ฮปE โค cโ(ฮปA+ฮต) โค ฮปA*c. ะัะพัะพะน ะฟะตัะตัะพะด ะฒะตัะตะฝ ะตัะปะธ ะฟะพะดะพะฑัะฐัั ะฝัะถะฝะพะต ฮต.
** 2 [#A] 16. ะขะตะพัะตะผะฐ ะพ ะณะปะฐะดะบะพะน ะทะฐะผะตะฝะต ะฟะตัะตะผะตะฝะฝะพะน ะฒ ะธะฝัะตะณัะฐะปะต ะะตะฑะตะณะฐ (ะปัััะฐั ัะตะพัะตะผะฐ) (15)
   ฮฆ: O โ โโฟ โ โโฟ ะดะธััะตะพะผะพััะธะทะผ, O' = ฮฆ(O), ัะพะณะดะฐ
   f - ะฟะพะปะพะถะธัะตะปัะฝะฐั, ะธะทะผะตัะธะผะฐั ะฝะฐ O' ะธะปะธ ััะผะผะธััะตะผะฐั ะฝะฐ O'
   โซ_O' fdฮป = โซ_O fโฮฆ(x)|detฮฆ'(x)|dฮป

*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ฮฝ(E)=ฮป(ฮฆ(E)) ะธะผะตะตั ะฒะตั |detฮฆ'(x)| ะพัะฝะพัะธัะตะปัะฝะพ ฮป.
    ฮป(B) = โซ{ฮฆโปยน(B)}|detฮฆ'(x)|dฮป ะฟะพ ะพะฟัะตะดะตะปะตะฝะธั ะฒะตัะฐ))))
** OK [#A] 17. ะขะตะพัะตะผะฐ ะพ ะฟัะพะธะทะฒะตะดะตะฝะธะธ ะผะตั
   ะ โโฟ ะฒัะตะณะดะฐ ะฒัะฟะพะปะฝัะตััั ฮปโรฮปโ = ฮปโโโ

*** ะะตะท ะดะพะบะฐะทะฐัะตะปัััะฒะฐ (ะฝั ะพะฝะพ ะพัะตะฒะธะดะฝะพ), ะฑะพะฝััะฝะฐั ัะตะพัะตะผะฐ!
** 2 [#C] 18. ะัะธะฝัะธะฟ ะะฐะฒะฐะปัะตัะธ (6, ะะตะฒะธ, 1)
   (X, ๐ด, ฮผ), (Y, ๐ต, ฮฝ), m = ฮฝรฮผ, ฮผ, ฮฝ - ฯ-ะบะพะฝะตัะฝัะต, ะฟะพะปะฝัะต
   1. Cโ ฮฝ-ะธะทะผะตัะธะผะพ ะฟัะธ ะฟ.ะฒ. X
   2. x โ Cโ ฮผ-ะธะทะผะตัะธะผะพ ะฟัะธ ะฟะพััะธ ะฒัะตั x
   3. m(C) = โซ_X ฮผCโdฮผ

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    D -- ะผะฝะพะถ. ัะพ ัะฒะพะนััะฒะฐะผะธ. ะัะพะฒะตััะตะผ:
    1. ๐ดร๐ต โ D,
    2. โEแตข โ D
    3. EโโEโโEโโ... โi m(Eแตข) ะบะพะฝะตัะฝะพะต โ โEแตขโD (ััั ะะตะฑะตะณ-6 ะธ ะฝะตะฟัะตััะฒะฝะพััั ะผะตัั ะธัะฟ.)
    4. E โ ๐ดโ๐ต. mE=0 โ EโD (ััั E โ H:=โฉโชD)
    5. E - ะธะทะผะตัะธะผะฐ, Eโ๐ดโ๐ต, mE<+โ, E = H\N, ะณะดะต H = โโDแตขโฑผ, N ะฝัะปะตะฒ. ะผะตัั, H,NโD, ัะพะณะดะฐ EโD.
    6. E - ะฟัะพะธะทะฒะตะดะตะฝะธะต ะธะทะผะตัะธะผัั, E โ D.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ะัััั D -- ะบะปะฐัั ะผะฝะพะถะตััะฒ โ ๐ดร๐ต, ะฒ ะบะพัะพัะพะผ ะฒัะฟะพะปะฝััััั ััะธ ะฟัะฐะฒะธะปะฐ ะฒััะต.
    1. ะัะพะฒะตัะธะผ, ััะพ ๐ดร๐ต โ D.
       1. ะัะตะฒะธะดะฝะพ (C = AรB. Cโ = if x โ A then B else โ)
       2. ะญัะฐ ััะฝะบัะธั X_A * ฮฝB
       3. โซ{X}(Cโ)dฮผ = โซX_A(x)ฮฝ(B)dฮผ(X) = ฮผA*ฮผB = m(AรB)
    2. Eโ, Eโ,... โ D โ โEแตข โ D
       1. (โEแตข)โ = โ(Eแตข)โ, ะธะทะผะตัะธะผั ะฟะพ ะธะฝะด. ะฟัะตะดะฟะพะปะพะถะตะฝะธั.
       2. ฮฝ(Eโ) = ฮฝ(โ(Eแตข)โ) = โฮฝ((Eแตข)โ) ะฟะพ ััะผะผะธััะตะผะพััะธ ะธะทะผะตัะธะผะพะน ััะฝะบัะธะธ
       3. โซฮฝ(Cโ) = โโซฮฝ(Eแตข)โ=โmEแตข=mE
    3. Eโ,Eโ,...โD, EโโEโโEโโ... โi m(Eแตข) ะบะพะฝะตัะฝะพะต. ะขะพะณะดะฐ โEแตขโD.
       1) mEแตข = โซฮฝ(Eแตขโ) dฮผ ะบะพะฝะตัะฝะพะต โ ฮฝ(Eแตขโ) ะบะพะฝะตัะฝะพ ะฟัะธ ะฟ.ะฒ. x.
       2) E = โEแตข, Eโ = (โEแตขโ).
       3) Eโโ โ Eโโ โ Eโโ โ ... ะธะทะผะตัะธะผั ะฟัะธ ะฟ.ะฒ. x.

       ะขะตะฟะตัั ะบ ะฒัะฒะพะดะฐะผ:
       1. ะะท ะฟัะฝะบัะพะฒ 2, 3 ัะปะตะดัะตั, ััะพ Eโ ะธะทะผะตัะธะผะพ ะฟัะธ ะฟ.ะฒ x.
       2. ะะท ะธะทะผะตัะธะผะพััะธ Eโ ะธะทะผะตัะธะผะพ ะฟัะธ ะฟ.ะฒ. x ะธ ะฟัะฝะบัะฐ 1) ะฟะพ ะฝะตะฟัะตััะฒะฝะพััะธ ะผะตัั ัะฝะธะทั ัะปะตะดัะตั, ััะพ ฮฝ(Eโ) - ะบะพะฝะตัะฝะพ ะฟัะธ ะฟ.ะฒ.x, ัะฐะบ ะบะฐะบ ฮฝ(Eโ) = lim ฮฝ(Eแตขโ).
       3. ฮฝ(Eโโ) โฅ ฮฝ(Eโโ) โฅ ..., ัะพะณะดะฐ
          โซฮฝ(Eโ)dฮผ = {ะฟะพ ัะตะพัะตะผะต ะะตะฑะตะณะฐ, ฮฝ(Eโโ) -- ะผะฐะถะพัะฐะฝัะฐ} = โซlim(ฮฝ(Eแตขโ))dฮผ = {ะะตะฒะธ} = lim โซฮฝ(Eแตขโ)dฮผ = lim m(Eแตข) = mE

       ะะพั ะตัะต ััะฒะตัะถะดะตะฝะธะต ัะพะผะฝะธัะตะปัะฝะพะน ะฟะพะปะตะทะฝะพััะธ:
       m(A) = inf(โm(PแตขรQแตข) | A โ โ(PแตขรQแตข)), โAโ๐ดโ๐ต โDแตขโฑผโ๐ดร๐ต, A โ โ{j}โ{i}Dแตขโฑผ, m(โโDแตขโฑผ \ A) = 0,
    4. E โ ๐ดโ๐ต. mE=0 โ EโD
       โH=โโDแตขโฑผ, ะณะดะต Dแตขโฑผโ๐ดโ๐ต: E โ H, mH=0, Dแตขโฑผ โ D.
       1. HโD, ะฟัะธ ะฟ.ะฒ.x Hโ ะธะทะผะตัะธะผะพ, EโโHโ, ะทะฝะฐัะธั ะธ Eโ ะธะทะผะตัะธะผะพ.
       2. ฮฝ(Eโ) โค ฮฝ(Hโ) = 0, ะฟะพัะพะผั ััะพ mH=0 = โซฮฝ(Hโ)dฮผ (ะณะดะต ฮฝ(Hโ)โฅ0) โ ััะฝะบัะธั xโฆฮฝ(Hโ) - ะฟ.ะฒ ัะฐะฒะฝะฐ 0.
       3. 0 โค โซmE = โซฮฝ(Eโ) โค โซฮฝ(Hโ) = 0
    5. E - ะธะทะผะตัะธะผะฐ, Eโ๐ดโ๐ต, mE<+โ, E = H\N, ะณะดะต H = โโDแตขโฑผ, N ะฝัะปะตะฒ. ะผะตัั, H,NโD, ัะพะณะดะฐ EโD.
       1. Eโ = Hโ\Nโ ะธะทะผะตัะธะผะพ ะฟัะธ ะฟ.ะฒ.x
       2. x โฆ ฮฝ(Eโ) = ฮฝ(Hโ)-ฮฝ(Nโ) = ฮฝ(Hโ) - ะธะทะผะตัะธะผะพ
       3. โซฮฝ(Eโ) = โซฮฝ(Hโ) = mH = mE
    6. E - ะฟัะพะธะทะฒะตะดะตะฝะธะต ะธะทะผะตัะธะผัั, E โ D.
       E = XรY. ะัะตะดััะฐะฒะธะผ E ะฟะพ-ะดััะณะพะผั.
       X = โXแตข, ฮผXแตข<+โ
       Y = โYแตข, ฮฝYแตข<+โ
       XรY = โXแตขรYแตข, ัะพะณะดะฐ
       E = โEแตขโฑผ, ะณะดะต Eแตขโฑผ = Eโฉ(XแตขรYแตข)
       1. Eโ=โEแตขโฑผโ,
       2. ฮฝ(Eโ) = โฮฝ(Eแตขโฑผโ)
       3. โซฮฝ(Eโ) = โซโฮฝ((Eแตขโฑผ)โ) = {ะพ ะธะฝัะตะณัะธัะพะฒ. ะฟะพะป. ััะดะพะฒ} = โโซฮฝ((Eแตขโฑผ)โ) = โmEแตข = mE
** 2 [#B] 19. ะขะตะพัะตะผะฐ ะขะพะฝะตะปะปะธ (18, 1, ะะตะฒะธ)
   fโ(y) = f(x, y) : Y โ range(f)

   (X, A, ฮผ), (Y, B, ฮฝ), ฮผ, ฮฝ - ฯ-ะบะพะฝะตัะฝัะต, ะฟะพะปะฝัะต, m=ฮผรฮฝ
   f(x, y): XรY โ R, ะธะทะผะตัะธะผะฐั
   1. fโ ะธะทะผะตัะธะผะพ ะฟัะธ ะฟะพััะธ ะฒัะตั x
   2. x โ โซfโdฮฝ ะธะทะผะตัะธะผะพ
   3. โซ_XรY fdm = โซ(โซfโdฮฝ)dฮผ
*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะะฐััะผะพััะตัั ััะธ ััะฒะตัะถะดะตะฝะธะต ะดะปั ัััะฟะตะฝัะบะธ (ะฟั.ะะฐะฒะฐะปัะตัะธ ััั), ัััะฟะตะฝัะฐัะพะน ััะฝะบัะธะธ ะธ ะฝะตะพััะธัะฐัะตะปัะฝะพะณะพ ะฟัะตะดะตะปะฐ ัััะฟะตะฝัะฐััั (ััั ะะตะฒะธ).
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. E โ ๐ดโ๐ต. f=๐_E
       fโ = ๐_{Eโ}(y)
       Eโ - ะธะทะผะตัะธะผะฐ ะฟัะธ ะฟ.ะฒ.x โ ๐_{Eโ} - ะธะทะผะตัะธะผะฐ
       ฯ(x) = โซ{X} fโ(y)dฮฝ(y)  = โซ๐_{Eโ}dฮฝ = ฮฝ(Eโ)
       ฯ(x) = x โฆ ฮฝ(Eโ) - ะธะทะผะตัะธะผะพ ะฟะพ ะฟัะธะฝัะธะฟั ะะฐะฒะฐะปัะตัะธ.
       โซฯdฮผ = โซฮฝ(Eโ)dฮผ = mE = โซf
    2. f - ัััะฟะตะฝัะฐัะฐั, f = โCโ๐_{Eโ}
       fโ = โCโ๐_{Eโโ}
       โซfโ = โCโโซ๐_{Eโโ}dฮฝ
       โซฯ(x)dฮผ = Cโโซ(โซ๐_{Eโโ})dฮผ = โCโ*mEโ = โซf
    3. f - ะธะทะผ, โฅ0, f=limgโ, ะณะดะต ะฒัะต gแตข-ัััะฟ, 0โคgโโคgโโค..
       โx fโ=lim{nโโ}((gโ)โ) โ fโ - ะธะทะผะตัะธะผะพ ะบะฐะบ ะฟัะตะดะตะป ะธะทะผะตัะธะผัั ะฟัะธ ะฟ.ะฒ.x
       ฯ(x) = โซfโdฮฝ(y) = {ะฟะพ ะะตะฒะธ} = limโซY (gโ)โdฮฝ(y)
       โซฯ(x) = {ะะตะฒะธ} = limโซ(โซ(gโ)โdฮฝ(y))dฮผ(x) = limโซgโdm = {ะะตะฒะธ} = โซfdm
** 2 [#B] 20. ะคะพัะผัะปะฐ ะดะปั ะะตัะฐ-ััะฝะบัะธะธ (19)
   s, t > 0, B(s, t) = โซ{0,1}x^{s-1} (1-x)^{t-1}dx
   ฮ(t) = โซ{0,โ}xแตโปยนeโปหฃdx, t > 0
   ะขะพะณะดะฐ B(s, t) = ฮ(s)*ฮ(t)/ฮ(s+t)

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะะพัะผัะพัะตัั ะฝะฐ ะ(s)ะ(t), ัะดะตะปะฐัั ะทะฐะผะตะฝั y=u-x, ะฝะฐัะธัะพะฒะฐัั ะพะฑะปะฐััั, ะฟะตัะตััะฐะฒะธัั ะธะฝัะตะณัะฐะปั, x=u*z ะธ ัะผัะบ.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ฮ(s)*ฮ(t) = โซ{0,โ}xหขโปยนeโปหฃ(โซ{0,โ}yแตโปยนeโปสธdy)dx = {y=u-x}
    = โซ{0,โ}xหขโปยนeโปหฃ(โซ{x,โ}(u-x)แตโปยนeโปแตโบหฃdu)dx
    = โซโซxหขโปยน(u-x)แตโปยนeโปแตdudx = {ััั ะฟะตัะตัะพะด ะณัะฐะฝะธั ะพัะตะฒะธะดะตะฝ ะตัะปะธ ะฝะฐัะธัะพะฒะฐัั ะพะฑะปะฐััั} =
    = โซ{0,โ}du(โซ{0,u}xหขโปยน(u-x)แตโปยนeโปแตdx) = {x=u*z}
    = โซ{0,โ}du eโปแตโซ{0,1}(uz)หขโปยนโบแตโปยนโบยนzหขโปยน(1-z)แตโปยนdz
    = โซ{0,โ}uหขโบแตโปยนeโปแตB(s, t)du
    ฮ(s)ฮ(t) = ฮ(s+t)B(s,t)
** OK [#A] 21. *!* ะขะตะพัะตะผะฐ ะคัะฑะธะฝะธ (19)
   (X, A, ฮผ), (Y, B, ฮฝ), ฮผ,ฮฝ - ฯ-ะบะพะฝะตัะฝัะต, ะฟะพะปะฝัะต
   f: XรY โ R m-ััะผะผะธััะตะผะฐั
   1. fโ ฮฝ-ััะผะผะธััะตะผะฐั
   2. x โ โซfโdฮฝ ฮผ-ััะผะผะธััะตะผะฐั
   3. โซโซfdฮผรdฮฝ=โซ(โซfโdฮฝ)dฮผ=โซ(โซf(x,y)dฮฝ(y))dฮผ(x)

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะัะตะดััะฐะฒะธัั ััะฝะบัะธั ะฒ ะฒะธะดะต ัะฐะทะฝะพััะธ + ะธ -, ัะฐะทะพะฑัะฐัั 3 ะฟัะฝะบัะฐ.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    f = fโ - fโ, โซfโโdm ะบะพะฝะตัะฝัะต, โซf = โซfโ - โซfโ
    1. โซ(fโ)โ, โซ(fโ)โ ะบะพะฝะตัะฝัะต ะฟัะธ ะฟ.ะฒ.x
       โซ{XรY}fโ = โซ{X}โซ{Y}(fโ)โdฮฝ)dฮผ - ะบะพะฝะตัะฝะพ
       ะัััะดะฐ โซ{Y}(fโ)โdฮฝ ะบะพะฝะตัะฝะพ ะฟัะธ ะฟ.ะฒ.x
    2. x โฆ ฯ(x) = โซfโdฮฝ -- ััะผะผะธััะตะผะพ ะฝะฐ X
       ฯ(x) = โซ(fโ)โ - โซ(fโ)โ
       โซ|ฯ(x)|dฮผ = โซ|โซfโโ - โซfโโ|dฮผ โค โซ(|โซfโโdฮฝ| + |โซfโโdฮฝ|) = โซโซfโโ + โซโซfโโ, ะบะพะฝะตัะฝั
    3. โซfdm = โซ{XรY}fโ - โซ{XรY}fโ = โซโซfโโ - โซโซfโโ = โซ(โซfโโ - โซfโโ) = โซโซfโ
** 2 [#A] 22. ะะฑัะตะผ ัะฐัะฐ ะฒ โโฟ
   V(B(0, r)) = ฮฑโ * r^n
   ฮฑโ = (โฯ)โฟ / ฮ(n/2 + 1)

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะะพ ะธะฝะดัะบัะธะธ ะฟะตัะฒะพะณะพ ััะฒะตัะถะดะตะฝะธั.
    ะะฐะทะฐ ะพัะตะฒะธะดะฝะฐ, ะธะฝะดัะบัะธั ัะฐะบะฐั: ัะฐััะผะพััะธะผ ะธะฝัะตะณัะฐะป, ะฒัะดะตะปะธะผ ะพะดะฝั ะพัั, ะฟัะธะผะตะฝะธะผ ะฟัะตะดะฟะพะปะพะถะตะฝะธะต, ะฒัะฝะตัะตะผ ฮฑ, ะทะฐะผะตะฝะฐ x = โt, ะฟะพัะพะผ ะธะฝะดัะบัะธั ะฟะพ ะฒัะพัะพะผั ะฒััะฐะถะตะฝะธั.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ะะฐะนัะธ ะพะฑัะตะผ xโยฒ+xโยฒ + ... โค rยฒ
    ฮฑโ = ฮปโ(B(0,1)), ะฟัะธัะตะผ ฮปm(B(0,r)) = ฮฑโrแต
    ฮฑโ = โซ{B(0,1)}1dฮปโ = โซ{[-1,1]}(โซ{B(0, โ(1-xยฒ))}1dฮปโโโ)dxโ =
    = โซ{[-1,1]}ฮฑโโโ(1-xโยฒ)^((m-1)/2)dxโ = 2ฮฑโโโโซ{0,1}(1-xยฒ)^((m-1)/2)dx = {โt = x} =
    = ฮฑโโโโซ{0,1}t^(-1/2)(1-t)^((m-1)/2)dt =
    = ฮฑโโโ ฮ(1/2)*ฮ((m+1)/2)/ฮ(m/2+1)
    = (โฯ)แต/ฮ(m/2 + 1)
** 2 [#A] 23. ะขะตะพัะตะผะฐ ะพ ะฒััะธัะปะตะฝะธะธ ะธะฝัะตะณัะฐะปะฐ ั ะฟะพะผะพััั ะผะตัั ะะพัะตะปั-ะกัะธะปััะตัะฐ (ะฝะตะฟั. ะผะตัั ัะฝะธะทั)
   ะะตะผะผะฐ: h - ะธะทะผะตัะธะผะฐ, โt H(t) ะบะพะฝะตัะฝะฐ, ฮฝ(A)=ฮผ(hโปยน(A), ัะพะณะดะฐ
   ฮผH = ฮฝ ะฝะฐ ๐ต (ะะพัะตะปะตะฒัะบะพะน ัะธะณะผะฐ-ะฐะปะณะตะฑัะต), ฮผH(a, b) = H(b-0) - H(a-0)
   ะขะตะพัะตะผะฐ: ะฒัะต ัะพ ะถะต ัะฐะผะพะต, โซ_X f(h(x))dฮผ(x) = โซ_โ f(t) dฮผH(t)

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะ ะปะตะผะผะต ะฒัะฟะธัะฐัั ฮผH[a, b), ัะฐะทะปะพะถะธัั, ะฒััะฐะทะธัั ัะตัะตะท hโปยน, ะฟัะธะผะตะฝะธัั ะะตะฑะตะณะพะฒะพ ะฟัะพะดะพะปะถะตะฝะธะต
    ะ ัะตะพัะตะผะต ะฟัะพััะพ ะฟัะธะผะตะฝะธัั ะพะฟัะตะดะตะปะตะฝะธะต ะพะฑัะฐะทะฐ ะผะตัั ะฟัะธ ะพัะพะฑั. (w=1).
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ ะปะตะผะผั
    ฮผH[a, b) = H(b-0) - H(a-0) = H(b) - H(a) = ฮผX(h<b) - ฮผX(h<a) = ฮผX(aโคh<b) = ฮผhโปยน([a, b)) = ฮฝ([a, b)).
    ะะฑัััะฝะธะผ ะฟะตัะตัะพะด:
    H(b - 0) = lim(ฮผX(h < b - 1/m)) = ฮผX(h<b) ะฟะพ ะฝะตะฟัะตััะฒะฝะพััะธ ะผะตัั ัะฝะธะทั.
    ะขะพะณะดะฐ ะฟะพ ะฟัะฝะบัั 3 ะฟัะพะดะพะปะถะตะฝะธั ฮผH = ฮฝ ะฝะฐ ๐ต (ะตัะปะธ ะฝะฐ ััะตะนะบะฐั, ัะพ ะฟะพ ะฟัะพะดะพะปะถะตะฝะธั ะธ ะฝะฐ ัะธะณะผะฐ-ะฐะปะณะตะฑัะต).
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ ัะตะพัะตะผั
    ฮฝ(A) = โซ{hโปยน(A)}1dฮผ ะธะปะธ ฮฝ(A) = โซ{hโปยน(A)}wdฮผ
    (X, ๐ด, ฮฝ), (Y, ๐ต, ฮฝ=hฮผ), h:XโY, ัะพะณะดะฐ โซ{X} f(h(x))dฮผ(x) = โซ{Y} f(y)dฮฝ,
    ะฟะพ ัะตะพัะตะผะต ะพ ะทะฐะผะตะฝะต ะผะตัั ะฒ ะธะฝัะตะณัะฐะปะต (w=1)
** 2 [#A] 24. ะขะตะพัะตะผะฐ ะพ ะฒะปะพะถะตะฝะธะธ ะฟัะพัััะฐะฝััะฒ Lp
     (X, ๐ด, ฮผ), ฮผX<+โ, 1 โค s < r < +โ
     *ัะพะณะดะฐ*
     1. Lสณ โ Lหข
     2. โฅfโฅโ โค (ฮผX)^(1/s - 1/r)*โฅfโฅแตฃ

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    1 ะธะท ะฒัะพัะพะณะพ ัะปะตะดัะตั, ะฒะพ ะฒัะพัะพะผ ัะฐััะผะพััะตัั โฅfโฅโหข p:=r/s, q=ะฒััะฐะทะธัั, ะฟะพัะพะผ ะฟัะธะผะตะฝะธัั ัะพัะผัะปั ะัะปัะดะตัะฐ.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. ะกะปะตะดัะตั ะธะท ะฒัะพัะพะณะพ:
       ะัััั โฅfโฅแตฃ ะบะพะฝะตัะฝะพ, ัะพะณะดะฐ โโฅfโฅโ ัะพะถะต ะบะพะฝะตัะฝะพ, ะฐ ะทะฝะฐัะธั ะฟะพ ะพะฟัะตะดะตะปะตะฝะธั Lโ f ะฒัะพะดะธั ะฒ Ls, ะตัะปะธ f ะฒัะพะดะธั ะฒ Lr.
    2. ะะฟัะตะดะตะปะธะผ p, q:
       r/s = p>1, q=r/(r-s) (1/p+1/q=1)
       โฅfโฅโหข = โซโฃf|หข*1 โค {ั-ะปะฐ ะัะปัะดะตัะฐ ะฒ ะพะฟัะตะดะตะปะตะฝะธัั} โค (โซ|f|^(s*r/s))^(s/r) * (โซ1^(r/(r-s)))^((r-s)/r) = (โฅfโฅแตฃ)หข(ฮผX)^(1-s/r).
       ะขะตะฟะตัั ะฒะพะทัะผะตะผ ะพัััะดะฐ ะบะพัะตะฝั.
** 2 [#B] 25. ะะพะปะฝะพัะฐ Lp (5)
   (X, ๐ด, ฮผ), (1โคp<+โ)
   *ัะพะณะดะฐ*
   Lแต(X) -- ะฟะพะปะฝะพะต

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะ ะบะฐัะตััะฒะต ะบะฐะฝะดะธะดะฐัะฐ ะฑะตัะตะผ f(x) = lim{kโโ}(f_Nโ(x) + โ(f_{Nโโโ} - f_{Nโ})) = lim{kโโ}f_Nโโโ(x).
    ะะฝัััะตะฝะฝัั ััะผะผั ะผั ัััะพะธะผ ะฒ ะฝะฐัะฐะปะต ะปะตะผะผั ะธ ะดะพะบะฐะทัะฒะฐะตะผ ะตะต ะฐะฑั. ััะพะดะธะผะพััั ะฟ.ะฒ. ัะตัะตะท โฅSโฅ.
    ะญัะพั ะฝะพะฒัะน ะฟัะตะดะตะป ัะพััะพััะธะน ัะพะปัะบะพ ะธะท ะฟะตัะฒัั ัะปะตะผะตะฝัะพะฒ f_Nโ - f_Nโ ะผั ะธ ะฑะตัะตะผ.
    ะัะพะฒะตััะตะผ โฅf(x) - f_N(x)โฅโ โ 0, ะฟะพะปัะทัะตะผัั ะคะฐัั.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ะะพะทัะผะตะผ fโ ััะฝะดะฐะผะตะฝัะฐะปัะฝัั ะฒ Lแต.
    1. ะกััะพะธะผ ะบะฐะฝะดะธะดะฐัะฐ ะฝะฐ ัะพะปั ะฟัะตะดะตะปะฐ.
       ฮต = 1/2   โNโ, โm,n>Nโ โฅfโ-fโโฅโ < 1/2
       ฮต = 1/4   โNโ>Nโ, โm,n>Nโ โฅfโ-fโโฅโ < 1/4
       ...
       ฮต = 1/2แต
       ะขะพะณะดะฐ โ{โ}โฅf_{Nโโโ} - f_{Nโ}โฅโ < 1 (ัะธะฟะฐ ัะบัะฟะพะฝะตะฝัะฐ ะฒัะต-ัะฐะบะธ)
       ะะฐััะผะพััะธะผ S(x)=โ{โ}|f_{Nโโโ}(x) - f_{Nโ}(x)| โ [0,+โ] (ััั ะผะพะดัะปั, ะฝะต ะฝะพัะผะฐ)
       โฅS_Nโฅโ = โฅโ{N}..โฅโ โค โ{N}โฅf_{Nโโโ} - f_{Nโ}โฅโ < 1
       ะขo ะตััั โซ{X}|S_N(x)|แตdฮผ(x) < 1 ะธ ะฟัะธ ะฒัะตั x Sโ(x) โ S(x). ะัััะดะฐ ะฟะพ ะคะฐัั โซ{X}|S(x)|แตdฮผ(x) < 1.
       ะัััะดะฐ |S(x)|แต ะฟะพััะธ ะฒะตะทะดะต ะบะพะฝะตัะฝะฐ, ะฐ ะธะท ััะพะณะพ ัะปะตะดัะตั, ััะพ โ(f_{Nโโโ} - f_{Nโ}) ะฐะฑัะพะปััะฝะพ ััะพะดะธััั ะฟะพััะธ ะฒะตะทะดะต.
       f_N(x) = f_Nโ(x) + โ{N}(f_{Nโโโ} - f_{Nโ}).
       ะั ัะฐะท ัะฐะบ, ัะพ ะฒะพะทัะผะตะผ: f(x) = lim{kโโ}(f_Nโ(x) + โ(f_{Nโโโ} - f_{Nโ})) = lim{kโโ}f_Nโโโ(x).
       ะัะพะฒะตัะธะผ, ััะพ โฅf(x)-f_n(x)โฅโ โ 0 (ััั ะฒัะพัะพะต -- ะฟะตัะฒะพะฝะฐัะฐะปัะฝะฐั ะฟะพัะปะตะดะพะฒะฐัะตะปัะฝะพััั)
       โฮต>0 โN โn,m>N (โฅfโ-fโโฅโ)แต<ฮตแต. ะะพะทัะผะตะผ m=Nโ>N, ัะพะณะดะฐ (โฅfโ-f_Nโโฅโ)แต<ฮตแต.
       โซ|fโ-f_Nโ|แตdฮผ < ฮตแต
       ะะพัะบะพะปัะบั |fโ-f_Nโ|แต โ |fโ-f|แต ะฟะพััะธ ะฒะตะทะดะต, ะฟะพ ะคะฐัั โซ|fโ(x)-f(x)|แตdฮผ < ฮตแต, ัะพ ะตััั โฅfโ-fโฅโ<ฮต.
** 2 [#A] 26. ะะปะพัะฝะพััั ะฒ Lp ะผะฝะพะถะตััะฒะฐ ัััะฟะตะฝัะฐััั ััะฝะบัะธะน (ะฐะฟะฟัะพะบัะธะผะฐัะธั ัััะฟะตะฝัะฐััะผะธ, 4)
   (X, ๐ด, ฮผ), f - ัััะฟะตะฝัะฐัะฐั, f=โCโ๐Eโ, X=โEโ.
   ฮผX(fโ0) ะบะพะฝะตัะฝะพ, p โ [0, โ]
   *ัะพะณะดะฐ*
   ะ Lแต ะผะฝะพะถะตััะฒะพ ัััะฟะตะฝัะฐััั ััะฝะบัะธะน ะฟะพะปะฝะพ.

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะะปั p=โ ะฟะพะดัััะฐะธะฒะฐะตะผ hโ ัะฒะตััั, ัะพะณะดะฐ โฅf-hโโฅโ = essup โค sup โ 0.
    ะะปั p<โ ะฟะพะดะฑะธัะฐะตะผ ัะฝะธะทั ัััะฟะตะฝัะฐััะต ััะฝะบัะธะธ, ัะผะพััะธะผ ะฝะฐ ะธะฝัะตะณัะฐะป, ะฝะตะฟัะตััะฒะฝะพััั ะฒ 0 ะณะฐัะฐะฝัะธััะตะผ 4 ัะตะพัะตะผะพะน.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. p=โ, ะฟัะพะฒะตัะธะผ fโLโ โ? โฅf-hโฅโ<ฮต, โฅfโฅโ = esssup|f|<+โ.
       ะะพะฟัะฐะฒะธะผ f ะฝะฐ ะผะฝะพะถะตััะฒะต ะผะตัั ะฝะพะปั, โxโX |f(x)| โค โฅfโฅโ.
       f ะธะทะผะตัะธะผะฐ, ะพะณัะฐะฝะธัะตะฝะฐ, โะฟะพัะปะตะดะพะฒะฐัะตะปัะฝะพััั hโ (ัะปะตะดััะฒะธะต ะธะท ัะตะพัะตะผั ะพะฑ ะฐะฟะฟัะพะบัะธะผะฐัะธะธ ััะฝะบัะธะธ ัััะฟะตะฝัะฐััะผะธ), ััะพ sup|f-hโ|โ0, ัะพะณะดะฐ โฅf-hโโฅโ = essup โค sup โ 0.
    2. p<โ, fโLแต, B(f,ฮต) โ ะตััั ะปะธ ััั ัััะฟ. ััะฝะบัะธะธ?
       f โฅ 0, โัััะฟ, 0โคhโโคhโโโโค... โ f. ะกััะตััะฒะพะฒะฐะฝะธะต ะฟะพ ัะพะน ะถะต ัะตะพัะตะผะต.
       ะะพ ะะตะฑะตะณั, ะผะฐะถะพัะฐะฝัะฐ: |f - fโ| < f โ |f - fโ|แต < |f|แต
       โฅf-hโโฅโ = โซ{X}|f-hโ|แตdฮผ โ 0
** 0 27. ะะตะผะผะฐ ะฃัััะพะฝะฐ
** 1 28. ะะปะพัะฝะพััั ะฒ Lp ะฝะตะฟัะตััะฒะฝัั ัะธะฝะธัะฝัั ััะฝะบัะธะน
   โp 1โคp<โ Cโ(โแต) ะฟะปะพัะฝะพ ะฒ Lแต(โแต)

*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    f โ Lแต, ฮต>0 ? B(f, ฮต) ัะพะดะตัะถะธั ัะธะฝะธัะฝัั ะฝะตะฟัะตััะฒะฝัั ััะฝะบัะธั?
    โัััะฟะตะฝัะฐัะฐั h, ััะพ โฅf-hโฅโ < ฮต/2
    h = โ{n}aโ๐Eโ. ะะฐะบ ะฟัะธะฑะปะธะทะธัั ๐Eโ?
    FโโEโโGโ, ััะพ ฮป(Gโ\Fโ) < ฮด.
    ะัััั ััะฝะบัะธั fโ -- ัะฐะทะดะตะปัััะฐั. fโ = 1 ะฝะฐ ะผะฝะพะถะตััะฒะต Fโ, fโ = 0 ะฝะฐ ะผะฝะพะถะตััะฒะต Gโแถ
    โฅ๐Eโ-fโโฅโ = (โซ{โแต}|๐โ-fโ|แต)^(1/p) = {ะฟะพ ะฟะพะปะพัะบะต ะตััั ัะผััะป ะธะฝัะตะณัะธัะพะฒะฐัั, ะฝะฐ ะพััะฐะปัะฝัั ะพะฑะปะฐัััั 0} = (โซ{Gโ\Fโ}|๐Eโ-fโ|แต)^(1/p) โค {ะฟะพะดัะฝัะตะณัะฐะปัะฝะพะต ะฒััะฐะถะตะฝะธะต โค1} โค ฮด^(1/p)
    โฅh-โaโfโโฅโ = โฅโaโ(๐Eโ-fโ)โฅโ โค โ|aโ|*โฅ๐Eโ-fโโฅโ โค maxโฃaโ|*n*ฮด^(1/p) โค ฮต/2.
** OK [#B] 29. *!* ะขะตะพัะตะผะฐ ะพ ะฝะตะฟัะตััะฒะฝะพััะธ ัะดะฒะธะณะฐ
   fโ(x) = f(x+h),
   *ัะพะณะดะฐ*
   1. f ัะฐะฒะฝะพะผะตัะฝะพ ะฝะตะฟะตััะฒะฝะฐ ะฝะฐ โแต โ โฅf-fโโฅโ โ{hโ0}โ 0
   2. 1 โค p โค +โ, f โ Lโ(โแต) โ โฅfโ-fโฅโ โ 0
   3. f โ C~([0, T]) โ โฅfโ-fโฅโ โ 0
   4. 1 โค p < +โ, f โ Lแต([0, T]) โ โฅfโ-fโฅโ โ 0

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    1 ััะธะฒะธะฐะปัะฝะพ ะธะท ะพะฟั. ัะฐะฒะฝะพะผ. ะฝะตะฟั. + sup ะฟัะธะผะตะฝะธัั. (esssup < sup).
    3 ัะปะตะดัะตั ะธะท 1.
    2 ะดะพะบะฐะทัะฒะฐะตััั ะบะฐะบ 4, ะฐ ะฒ 4 ะฟะพะดะฑะธัะฐะตะผ g ัะธะฝะธัะฝัั, ััะพ โฅf-gโฅ<ฮต/3 ะธ ัะฐัะบะปะฐะดัะฒะฐะตะผ ั gโ.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. โฮต>0 โฮด>0, โx,y |x-y|<ฮด |f(x)-f(y)| < ฮต -- ัะฐะฒะฝะพะผะตัะฝะฐั ะฝะตะฟัะตััะฒะฝะพััั
       โฮต>0 โฮดโ>0, โh=x-y, |h|<ฮดโ, sup{xโโแต}|f(x)-f(x+h)| โค ฮต (esssup < sup)
    2. ะะพะบะฐะทัะฒะฐะตััั ะบะฐะบ 4
    3. ะะตะฟัะตััะฒะฝะพััั ะฝะฐ ะบะพะผะฟะฐะบัะต ะฒะปะตัะตั ัะฐะฒะฝะพะผะตัะฝัั ะฝะตะฟัะตััะฒะฝะพััั.
    4. f โ ัะธะฝะธัะฝะฐั, ะฒะพะทัะผะตะผ g -- ัะธะฝะธัะฝัั, ััะพ โฅf-gโฅ<ฮต/3
       โฅfโ-fโฅโ โค โฅfโ-gโโฅโ + โฅgโ-gโฅโ + โฅg-fโฅโ
       (โซ{โแต}|f(x+h)-g(x+h)|แตdฮผ)^(1/p) = (โซ{h,T+h}(..))^(1/p) = (โซ{0,T}(..))^(1/p) โโค {ัะพ ะถะต ััะพ ะธ โฅg-fโฅ}
       (โซ{0,T}|g(x+h)-g(x)|แตdx)^(1/p) โค (sup{x}|g(x+h)-g|*โซ{0,T}1dx))^(1/p) = (โฅgโ-gโฅโ * T)^(1/p) โ 0.
       ะขะพะณะดะฐ โฅfโ-fโฅโ โค 2ฮต/3 + โฅgโ - gโฅโ โค โฅgโ - gโฅโ * (ฮปB(0,2R))^(1/n) โ 0
** 1 30. ะขะตะพัะตะผะฐ ะพ ัะฒะพะนััะฒะฐั ััะพะดะธะผะพััะธ ะฒ ะณะธะปัะฑะตััะพะฒะพะผ ะฟัะพัััะฐะฝััะฒะต
   1. xโ โ x, yโ โ y, *ัะพะณะดะฐ* <xโ,yโ> โ <x,y>
   2. โ{โ}xโ - ััะด, ััะพะดััะธะนัั ะฒ ๐ป, *ัะพะณะดะฐ* โy <y, โxโ> = โ<y,xโ>
   3. โxโ - ะพััะพะณะพะฝะฐะปัะฝัะน ััะด, *ัะพะณะดะฐ*
      โxโ - ััะพะดะธััั โ โโฅxโโฅยฒ ััะพะดะธััั

*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. |<xโ,yโ>-<x,y>| โค |<xโ,yโ> - <xโ,y>| + |<xโ,y> - <x, y>| = |<xโ,yโ-y>|+|<xโ-x,y>| โค โฅxโโฅโฅyโ-yโฅ + โฅxโ-xโฅโฅyโฅ.
    2. Sโ = โ{N}xโ, ัะพะณะดะฐ <y,Sโ>=โ{N}<y,xโ> -- ะบะพะฝะตัะฝะฐั ะฐะดะดะธัะธะฒะฝะพััั.
       N โ +โ.
       <y,Sโ> โ <y, S> (ะฟะพ 1 ะฟัะฝะบัั), โ{N}<y,xโ> โ โ{โ}<y,xโ>.
    3. Sโ = xโ+...+xโ, โฅSโโฅยฒ = <Sโ, Sโ> = {ะฟะพ ะปะธะฝะตะนะฝะพััะธ} = โ<xแตข, xโฑผ> = {ะฟะพ ะพััะพะณะพะฝะฐะปัะฝะพััะธ} = โ<xแตข, xแตข> = {ัะตะพัะตะผะฐ ะะธัะฐะณะพัะฐ} = โโฅxแตขโฅยฒ =: Cโ.
       โฅSโ-Sโโฅยฒ = Cโ-Cโ (m<n)
       Sโ, Sโ -- ะตัะปะธ ััะฝะดะฐะผะตะฝัะฐะปัะฝัะต ัะพ ะพะดะฝะพะฒัะตะผะตะฝะฝะพ (โฅSโ - Sโโฅ โ{m,nโ0}โ 0).
       1. โโฅSโโฅยฒ = Cโ โ โlim Cโ, ัะพ ะตััั โโฅxโโฅยฒ ััะพะดะธััั.
          (โฅSโโฅยฒ โ โฅSโฅยฒ ะฟะพ ะฟัะฝะบัั 1)
       2. Cโ โ C โ Cโ ััะฝะดะฐะผะตะฝัะฐะปัะฝะฐั โ Sโ ััะฝะดะฐะผะตะฝัะฐะปัะฝะฐั โ Sโ ััะพะดะธััั
** 2 [#A] 31. ะขะตะพัะตะผะฐ ะพ ะบะพัััะธัะธะตะฝัะฐั ัะฐะทะปะพะถะตะฝะธั ะฟะพ ะพััะพะณะพะฝะฐะปัะฝะพะน ัะธััะตะผะต
   ๐ป -- ะณะธะปัะฑะตััะพะฒะพ ะฟัะพัััะฐะฝััะฒะพ, {eโ} - ะะก, x = โCโeโ,
   *ัะพะณะดะฐ*
   1. {eโ} -- ะะะ (โ{N}Cโฑผeโฑผ = 0 โ โi Cโฑผ=0)
   2. Cโ=<x,eโ>/โฅeโโฅยฒ
   3. x = Cโeโ + z โ z โฅ eโ
      Cโeโ -- ััะพ ะฟัะพะตะบัะธั x ะฝะฐ ะพะดะฝะพะผะตัะฝะพะต ะฟัะพัััะฐะฝััะฒะพ ะฟะพัะพะถะดะตะฝะฝะพะต eโ.

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะ ะฟะตัะฒะพะผ ะดะพะผะฝะพะถะธะผ ะฝะฐ eโฑผโ, ะฒะพ ะฒัะพัะพะผ ัะพะถะต, ะฒ ััะตััะตะผ ะฟัะพะฒะตัะธะผ <,>=0.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. โCโฑผeโฑผ = 0, ะฒัะฑะตัะตะผ jโ, ะฟะพะบะฐะถะตะผ ััะพ Cโฑผโ=0. ะฃะผะฝะพะถะธะผ ะฒัะต ะฝะฐ eโฑผโ
       โCโฑผ<eโฑผ,eโฑผโ> = 0 โ Cโฑผโโฅeโฑผโโฅยฒ = 0 โ Cโฑผโ = 0
    2. โCโeโ=x, โCโ<eโ,eโโ>= <x,eโโ> โ Cโโโฅeโโโฅยฒ = <x, eโโ>
    3. zโฅeโ? <z,eโ> = <x - Cโeโ,eโ> = {x = โn, ะฒัะฑะตัะตะผ ะพัััะดะฐ ะฝะฐั ะบะพะฝะบัะตัะฝัะน k, ะพััะฐะปัะฝัะต ะฟะตัะฟะตะฝะดะธะบัะปััะฝั k ะฟะพ ะะก} = Cโโฅeโโฅยฒ - Cโ<eโ, eโ> = 0
** OK [#A] 32. ะขะตะพัะตะผะฐ ะพ ัะฒะพะนััะฒะฐั ัะฐััะธัะฝัั ััะผะผ ััะดะฐ ะคัััะต. ะะตัะฐะฒะตะฝััะฒะพ ะะตััะตะปั
   1. ะขะตะพัะตะผะฐ
      {eโ} - ะะก ะฒ ๐ป, xโ๐ป
      Sโ = โ{0,n}Cโ(x)eโ - ัะฐััะธัะฝะฐั ััะผะผะฐ ััะดะฐ ะคัััะต.
      ๐โ = Lin(eโ...eโ) (ะปะธะฝะตะนะฝะฐั ะพะฑะพะปะพัะบะฐ, ัะพ ะตััั ะผะฝะพะถะตััะฒะพ ะฒัะตะณะพ, ััะพ ะผะพะถะฝะพ ัะพััะฐะฒะธัั ะธะท ฮฑeแตข)
      *ัะพะณะดะฐ*
      1. Sโ -- ะฟัะพะตะบัะธั x ะฝะฐ ๐โ
      2. Sโ -- ัะปะตะผะตะฝั ะฝะฐะธะปัััะตะณะพ ะฟัะธะฑะปะธะถะตะฝะธั (ะฒ ๐โ) ะดะปั x (โฅx-Sโโฅ = inf{yโ๐โ}โฅx-yโฅ)
      3. โฅSโโฅ โค โฅxโฅ
   2. ะะตัะฐะฒะตะฝััะฒะพ ะะตััะตะปั
      โ{โ}|Cโ(x)|ยฒโฅeโโฅยฒ โค โฅxโฅยฒ

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะขะตะพัะตะผะฐ: ะฒ ะฟะตัะฒะพะผ ะพัะตะฝะธัั <z,eโ>, ะฒะพ ะฒัะพัะพะผ ะดะพะบะฐะทะฐัั โฅx-yโฅยฒ โฅ โฅzโฅยฒ, ะฒ ััะตััะตะผ ะพัะตะฝะธัั โฅxโฅยฒ. ะะพะปัะทะพะฒะฐัััั ะะฐััะตะฒะฐะปะตะผ.
    ะะตัะฐะฒะตะฝััะฒะพ -- ัะพัะปะฐัััั ะฝะฐ 3 ัะฐััั ัะตะพัะตะผั.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. ะขะตะพัะตะผะฐ
       1. x = Sโ + z, z โฅ ๐โ, <z,eโ> = <x-Sโ, eโ> = <x, eโ> - Cโโฅeโโฅ = <x, eโ> - <x, eโ> = 0.
       2. โฅx-yโฅยฒ = โฅ(Sโ+z)-yโฅยฒ = โฅSโ-yโฅยฒ + โฅzโฅยฒ โฅ โฅzโฅยฒ = โฅx-Sโโฅยฒ
       3. โฅxโฅยฒ = โฅSโ+zโฅยฒ = โฅSโโฅยฒ + โฅzโฅยฒ โฅ โฅzโฅยฒ
       PS: ะฒัะต ะฟะตัะตัะพะดั โฅa+bโฅยฒ=โฅaโฅยฒ+โฅbโฅยฒ ะฟะพ ะฝะฐะธะฒะฝะพะผั ะฟะพะฝะธะผะฐะฝะธั ัะฐะฒะตะฝััะฒะฐ ะะฐััะตะฒะฐะปั (ะพะบะพะปะพะะธัะฐะณะพัะฐ) ะธะท ะฟะตัะฟะตะฝะดะธะบัะปััะฝะพััะธ.
    2. ะะตัะฐะฒะตะฝััะฒะพ
       โฅSโโฅยฒ = โ{n}|Cโ(x)|ยฒโฅeโโฅยฒ โค โฅxโฅยฒ ะธะท ัะตะพัะตะผั ะฟัะฝะบั 3
** 1 33. ะขะตะพัะตะผะฐ ะะธััะฐ -- ะคะธัะตัะฐ ะพ ััะผะผะต ััะดะฐ ะคัััะต. ะะฐะฒะตะฝััะฒะพ ะะฐััะตะฒะฐะปั
   {eโ} -- ะะก ะฒ ๐ป, x โ ๐ป,
   *ัะพะณะดะฐ*
   1. ะัะด ะคัััะต ัะปะตะผะตะฝัะฐ x ััะพะดะธััั ะฒ ๐ป
   2. x = โCโ(x)eโ + z, ัะพะณะดะฐ โk zโฅeโ
   3. x = โCโ(x)eโ โ โ|Cโ(x)|ยฒโฅeโโฅยฒ = โฅxโฅยฒ (ัะฐะฒะตะฝััะฒะพ ะะฐััะตะฒะฐะปั)

*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. ะะพ ัะตะพัะตะผะต ะพ ัะฒะพะนััะฒะฐั ััะพะดะธะผะพััะธ ะฒ ๐ป: โxโ ััะพะดะธััั โ โโฅxโโฅยฒ ััะพะดะธััั.
       ะะตััะตะปั: โ|Cโ(x)|ยฒโฅCโโฅยฒ โค โฅxโฅยฒ, ะพัััะดะฐ ะตัะปะธ โฅxโฅยฒ ะบะพะฝะตัะฝะพ, ัะพ ััะด ััะพะดะธััั, ะฐ ะทะฝะฐัะธั ััะพะดะธััั ะธ ััะด ะคัััะต.
    2. <z, eโ> = <x-โ, eโ> = <x, eโ> - <โCโ(x)eโ, eโ> = <x, eโ> - Cโโฅeโโฅ = 0.
    3. โ
       x = โCโeโ โ x = limโ{N}, ะขะพะณะดะฐ โฅxโฅยฒ = limโ{N}|Cโ(x)|ยฒโฅeโโฅยฒ
       โ
       x = โCโ(x)eโ + z, zโฅeโ, x = limโ + z
       โฅxโฅยฒ = limโ{N}|Cโ(x)|ยฒโฅeโโฅยฒ + โฅzโฅยฒ = โ{โ}|Cโ(x)|ยฒโฅeโโฅยฒ + โฅzโฅยฒ, ะฟะพ ััะปะพะฒะธั z = 0.
** 0 34. ะขะตะพัะตะผะฐ ะพ ัะฐัะฐะบัะตัะธััะธะบะต ะฑะฐะทะธัะฐ
   {eโ} -- ะะก ะฒ ๐ป, *ัะพะณะดะฐ* ัะบะฒะธะฒะฐะปะตะฝัะฝะพ:
   1. {eโ} -- ะฑะฐะทะธั
   2. ะัะฟะพะปะฝัะตััั ะพะฑะพัะตะฝะฝะพะต ััะฐะฒะฝะตะฝะธะต ะทะฐะผะบะฝััะพััะธ <x,y> = โCโ(x)(Cโ(y)~)โฅeโโฅยฒ
   3. ะฃัะฐะฒะฝะตะฝะธะต ะทะฐะผะบะฝััะพััะธ ะฒัะฟะพะปะฝะตะฝะพ
   4. {eโ} ะฟะพะปะฝะฐ
   5. ะะ{eโ} ะฟะปะพัะฝะพ ะฒ ๐ป

*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. 1โ2
       x = โCโ(x)eโ, y = โCโ(y)eโ
       <x, y> = <โ, โ> = โCโ(x)<eโ, โCโ(y)eโ> = โCโ(x)(Cโ(y)~)<eโ,eโ> = ...
    2. 2โ3
       ะฒะพะทัะผะตะผ x=y
    3. 3โ4

** 2 [#A] 35. ะะตะผะผะฐ ะพ ะฒััะธัะปะตะฝะธะธ ะบะพัััะธัะธะตะฝัะพะฒ ััะธะณะพะฝะพะผะตััะธัะตัะบะพะณะพ ััะดะฐ
   T(x) -- ััะธะณะพะฝะพะผะตััะธัะตัะบะธะน ััะด, Sโ(x) -- ัะฐััะธัะฝัะต ััะผะผั. ะัััั โfโLยน[-ฯ,ฯ], Sโ โ f ะฒ Lยน. ะขะพะณะดะฐ
   aโ = 1/ฯโซ{-ฯ,ฯ}f(x)coskxdx, k = 0,1,...
   bโ = 1/ฯโซ{-ฯ,ฯ}f(x)sinksdx, k = 0,1,...
   cโ = 1/2ฯโซ{-ฯ,ฯ}f(x)eโฑแตหฃdx, k = 0,1,...

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    <Sโ(x), coskx> ะธ ะฟะพะดะพะฑะฝัะต ัะฐัะบััะฒะฐะตะผ ะฟะพ Lโ ะฝะพัะผะต.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    aโ: ะทะฐะผะตัะธะผ, ััะพ <Sโ(x), coskx> = {ะพะฟั. ะฝะพัะผั Lโ} = โซ{-ฯ,ฯ}Sโ(x)coskx = aโฯ
    ะขะพะณะดะฐ |โซ{-ฯ,ฯ}Sโ(x)coskx - โซ{-ฯ,ฯ}f(x)coskx| โค โซ{-ฯ,ฯ}|(Sโ(x)-f(x))coskx|dx โค โซ{-ฯ,ฯ}|Sโ(x)-f(x)|dx โ 0
** 1 35. ะขะตะพัะตะผะฐ ะะธะผะฐะฝะฐ--ะะตะฑะตะณะฐ
   E โ โ -- ะธะทะผะตัะธะผะพ, f โ Lยน(E)
   *ัะพะณะดะฐ*
   โซ{E}f(x)eโฑแตหฃdx โ{kโโ}โ 0
   โซ{E}f(x)coskxdx โ 0
   โซ{E}f(x)sinkxdx โ 0

*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ะกัะธัะฐะตะผ, ััะพ f โก 0 ะฒะฝะต E.
    โซf(x)eโฑแตหฃ = โซ{โ}eโฑแตหฃ = {y = x - ฯ/k} = -โซ{โ}f(y+ฯ/k)eโฑแตสธ = {y=x} = -โซ{โ}f(x+ฯ/k)eโฑแตหฃ
    ะขะพะณะดะฐ |โซ{E}f(x)eโฑแตหฃ| = 1/2 |(โซ(f(x)eโฑแตหฃ - f(x+ฯ/x))eโฑแตหฃdx| โค 1/2 โซ{โ}|f(x)-f(x+ฯ/k) โค 1/2โซ{โ}|f(x)-f(x+ฯ/k)|dx = โฅf-f_{ฯ/k}โฅโ โ 0
** 0 37. ะัะธะฝัะธะฟ ะปะพะบะฐะปะธะทะฐัะธะธ ะะธะผะฐะฝะฐ
   f,g โ Lยน[-ฯ,ฯ], xโ โ [-ฯ,ฯ], โฮด>0 f(x)=g(x) ะฟัะธ xโ[xโ-ฮด,xโ+ฮด] (ะฒะพัััะฐะฝะพะฒ. ะฟะพ ะฟะตัะธะพะดั).
   *ัะพะณะดะฐ*
   Sโ(f,xโ)-Sโ(g,xโ) โ 0
** OK [#B] 38. *!* ะัะธะทะฝะฐะบ ะะธะฝะธ. ะกะปะตะดััะฒะธั
   f โ Lยน[-ฯ,ฯ], xโ โ [-ฯ, ฯ], Sโโ. ะัััั โซ{0,ฯ}(|f(xโ+t)+f(xโ-t)-2S|/t dt) < +โ
   *ัะพะณะดะฐ*
   Sโ(f,xโ) โ S = aโ/2+โ..

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะัะฟะธััะฒะฐะตะผ Sโ(f,xโ)-S, ัะฐัะบััะฒะฐะตะผ ะฟะพ ัะฒะพะนััะฒั ะะธัะธัะปะต, ัะพะบัะฐัะฐะตะผ [-ฯ,ฯ] ะฒ 2 ัะฐะทะฐ, ะดะพะฟะธััะฒะฐะตะผ f(x-h), ัะฐัะบััะฒะฐะตะผ Dโ, ะฟะพะปััะฐะตะผ aโ+bโ ะพั ะดะฒัั ััะฝะบัะธะน.
    ะะพะบะฐะทัะฒะฐะตะผ ะฝะฐะปะธัะธะต ััะธั ััะฝะบัะธะน ะฒ Lโ. ะะปั ะฒัะพัะพะน ัะผะพััะธะผ ะธะฝัะตะณัะฐะป, ะฝะตะฟั. ะฒ ะฝัะปะต -- ัะดะฐะฒะปะธะฒะฐะตะผ.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    Sโ(f,xโ)-S = {ัะฒะพะนััะฒะพ ัะดัะฐ ะะธัะธัะปะต} = โซ{-ฯ,ฯ}f(xโ+t)Dโ(t)dt - โซ{-ฯ,ฯ}SDโ(t)dt =
    // โซ{0,ฯ}f(xโ+t)Dโ(t)dt = โซ{0,ฯ}f(xโ-t)Dโ(t)dt, ััะผะผะธัะพะฒะฐะปะธ ะธ ัะฐัะบััะปะธ ะฟะพ ัะตัะฝะพััะธ Dโ
    = โซ{0,ฯ}(f(xโ+t) + f(xโ-t) - 2S)Dโdt = {ะพะฑะพะทะฝะฐัะธะผ ะฟะพะดัะฝัะตะณัะฐะปัะฝะพะต ะบัะพะผะต ัะดัะฐ ฯ} =
    // ััั ะผั ัะฐัะบััะปะธ Dโ(t)= sin((n+1/2)t)/sin(t/2)/2ฯ
    // ะขัั sin((n+1/2)t)/sin(t/2) = (sin(nt)cos(t/2)-cos(nt)sin(t/2))/sin(t/2) = ctg(t/2)sinnt - cosnt
    = 1/ฯ โซ{0,ฯ}ฯ(t)/2 * (ctg(t/2)sinnt + cosnt)dt = bโ(hโ) + aโ(hโ) โ 0, ะณะดะต hโ=ฯ(t)/2ctg(t/2), hโ = ฯ(t)/2.

    ะัะถะฝะพ ะดะพะบะฐะทะฐัั ััะพ hโ, hโ โ Lยน. ะัะพัะฐั ะพัะตะฒะธะดะฝะพ ะฟะพัะพะผั ััะพ ััะพ ะบะพะผะฟะพะทะธัะธั.
    ะะตัะฒะฐั -- ctgโ, ฯโ.
    โซ{0,ฯ}|ฯ(t)ctg(t/2)| โค โซ|ฯ(t)|/t*(t*ctgt/2)dt โค {t*ctg(t/2) ะฝะตะฟั.ะฒ ะฝัะปะต} โค 2015โซ|ฯ(t)|/t dt < +โ.
** 0 39. ะะพััะตะบัะฝะพััั ะพะฟัะตะดะตะปะตะฝะธั ัะฒะตััะบะธ
** 1 40. ะกะฒะพะนััะฒะฐ ัะฒะตััะบะธ ััะฝะบัะธะธ ะธะท Lp ั ััะฝะบัะธะตะน ะธะท Lq
   f โ Lแต, K โ Lq (1/p + 1/q = 1)
   *ัะพะณะดะฐ*
   f*K - ะฝะตะฟัะตััะฒะฝะฐ ะฝะฐ [-ฯ,ฯ].
   โฅf*Kโฅโ โค โฅfโฅโโฅKโฅq (ะฝะตัะฐะฒะตะฝััะฒะพ ะัะปัะดะตัะฐ)

*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. |(f*K)(x+h) - (f*K)(x)| โค |โซ{-ฯ,ฯ}(f(x+h-t)-f(x-t))K(t)dt| โค{ะัะปัะดะตั}โค (โซ{-ฯ,ฯ}|f(x+h-t)-f(x-t)|แตdt)^(1/p)โฅKโฅ_q = {s=x-t}= (โซ|f(s+h)-f(s)|แตds)^(1/p)โฅKโฅ_q = โฅfโ-fโฅโโฅKโฅ_q โ 0.
** 0 41. ะขะตะพัะตะผะฐ ะพ ัะฒะพะนััะฒะฐั ะฐะฟะฟัะพะบัะธะผะฐัะธะฒะฝะพะน ะตะดะธะฝะธัั
   Kโ - ะฐะต. ะขะพะณะดะฐ
   1. f โ C~[-ฯ,ฯ] โ f*Kโ โ f
   2. f โ Lแต[-ฯ,ฯ] โ โฅf*Kโ-fโฅโ โ 0
   3. f โ Lยน, f ะฝะตะฟั. ะฒ xโ, R'โ ััะธะป.ะฐ.ะต, f*Kโ ะฝะตะฟัะตััะฒะฝะพ ะฒ xโ, (f*Kโ)(xโ) โ f(xโ)
** 2 [#A] 42. ะขะตะพัะตะผะฐ ะะพัะธ ะพ ะฟะตัะผะฐะฝะตะฝัะฝะพััะธ ะผะตัะพะดะฐ ััะตะดะฝะธั ะฐัะธัะผะตัะธัะตัะบะธั
   โaโ = S โ โaโ {ัะตะทะฐัะพ}= S

*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ะัััั S โ โ.
    ัะฐััะผะพััะธะผ |(โ{n}Sโ)/(n+1) - S| = |โ{n}(Sโ-S)/(n+1)| โค โ{n}|Sโ-S|/(n+1) โค
    // โฮต>0 โNโ: โn>Nโ |Sโ-S|<ฮต/2
    โค (โ{Nโ}|Sโ-S|)/(n+1) + โ{Nโ+1,โ}|Sโ-S|/(n+1) โค ฮต/2 + ฮต/2 = ฮต

    ะัะปะธ S=โ, ัะพ โR โN, โn>N Sโ > R, ัะพะณะดะฐ (โ{n}Sโ)/(n+1) > ะฝั ะบะพัะพั ัะพะถะต ะฑะพะปััะต ะฝะฐะฒะตัะฝ
** 2 [#B] 43. *!* ะขะตะพัะตะผะฐ ะคะตะนะตัะฐ (41)
   1. f โ C~[-ฯ,ฯ] โ ฯโ(f,x) โ f(x)
   2. f โ Lแต[-ฯ,ฯ] โ โฅฯโ(f,x)-fโฅโ โ 0
   3. f โ Lยน, f ะฝะตะฟัะตััะฒะฝะพ ะฒ x โ ฯโ(f,x) โ f(x)

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะะพะบะฐะทัะฒะฐะตะผ, ััะพ ฯโ(f,x) = f*ฮฆโ(x), ะดะพะบะฐะทะฒัะฐะตะผ ะฐะบัะธะพะผั ะฃะะ (ะฒ ััะตััะตะน ะฟะพะปัะทัะตะผัั sinยฒ/sinยฒ ั-ะปะพะน ะดะปั ฮฆโ).
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ะกะฒะตะดะตะผ ะดะพะบะฐะทะฐัะตะปัััะฒะพ ะบ ัะตะพัะตะผะต ะพ ัะฒะพะนััะฒะฐั ััะธะปะตะฝะฝะพะน ะฐะฟะฟัะพะบัะธะผะฐัะธะฒะฝะพะน ะตะดะธะฝะธัั (41).
    ะะฐะผะตัะธะผ, ััะพ Sโ ะฒััะฐะถะฐัััั ัะตัะตะท ัะดัะพ ะะธัะธัะปะต:
    Sโ = โซ{-ฯ,ฯ}f(x+t)Dโ(t)dt, ัะพะณะดะฐ
    ฯโ(f,x) = โซ{-ฯ,ฯ}f(x+t)ฮฆโ(t)dt, ะณะดะต ฮฆโ(t) = 1/(n+1)*โDโ(t)

    ะัะปะธ ฯโ(f,x) = f*ฮฆโ(x), ฮฆโ - AE(ััะธะป), ัะพ ะฒัะต ัะฒะพะนััะฒะฐ ะธะท ะบะพัะพะฑะบะธ.
    ฮฆโ = 1/(2ฯ(n+1)) sinยฒ((n+1/2) * x)/sinยฒ(x/2) -- ะฝะตะฟัะตััะฒะฝะพ ะฝะฐ [-ฯ,ฯ] โ Lโ, Lยน.
    AE1) โซ[-ฯ,ฯ]ฮฆโdx=1
    AE2) ฮฆโ โฅ 0, โฅฮฆโโฅโ = โซฮฆโ = 1
    AE3) essup{Eฮด}|ฮฆโ| โค 1/(2ฯ(n+1)) * 1/sinยฒ(ฮด/2) โ 0
** 2 [#A] 44. ะะพะปะฝะพัะฐ ััะธะณะพะฝะพะผะตััะธัะตัะบะพะน ัะธััะตะผั (43)
   1. ะขัะธะณะพะฝะพะผะตััะธัะตัะบะฐั ัะธััะตะผะฐ ะฟะพะปะฝะฐ ะฒ Lยฒ
   2. fโLยน[-ฯ,ฯ], โk aโ(f)=bโ(f)=0 (โn Cโ(f)=0) โ f=0 ะฟะพััะธ ะฒะตะทะดะต

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะ 2 ฯโ(f,x) โ f ัะตัะตะท 43. 1 ัะตัะตะท 2 ั ะฟะพะผะพััั <f,sinkx> ะฟัะพะฒะตัะบะธ ะธ Lโ ะฝะพัะผั.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    2 โ 1 ััะธะฒะธะฐะปัะฝะพ: <f,sinkx> = โซ{-ฯ,ฯ}f(k)sinkx = ฯbโ(f) (ะฒ Lโ <a,b> = โซX a(x)b(x)dฮผ
    2. f โ Lยน, ฯโ(f,x) โ f ะฒ Lยน. ฯโโก0
** 2 [#B] 45. ะคะพัะผัะปะฐ ะัะธะฝะฐ
   โยฒ, D โ โยฒ -- ะบะพะผะฟะฐะบัะฝะพะต, ัะฒัะทะฝะพะต, ะพะดะฝะพัะฒัะทะฝะพะต, ั Cยฒ -- ะณะปะฐะดะบะพะน ะณัะฐะฝะธัะตะน.
   (P,Q) -- ะณะปะฐะดะบะพะต ะฒะตะบัะพัะฝะพะต ะฟะพะปะต.
   ะัััั โD ะพัะธะตะฝัะธัะพะฒะฐะฝะพ ัะพะณะปะฐัะพะฒะฐะฝะฝะพ ั ะพัะธะตะฝัะฐัะธะตะน ะฟะปะพัะบะพััะธ.
   *ัะพะณะดะฐ*
   โซ{โD}(Pdx + Qdy) = โซโซ{D}(โQ/โx - โP/โy)dxdy

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    ะะฐะทะฑะธัั ะฟััั ะฝะฐ 4 ัะฐััะธ, ะฟัะพะฒะตัะธัั ะพัะดะตะปัะฝะพ ะดะปั P ะพั ัะปะพะถะฝะพะณะพ (โซโซ) ะบ ะฟัะพััะพะผั (โซ).
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    ะะฐััะผะพััะธะผ ัะปััะฐะน Q=0. ะะปั Q ะฟะพัะพะผ ะฐะฝะฐะปะพะณะธัะฝะพ.
    ะะฐััะผะพััะธะผ D ะบะฐะบ ัะฐะทะฝะพััั ะดะฒัั ะฟะปะพัะฐะดะตะน (ะบัะธะฒะพะปะธะฝะตะนะฝัั ััะฐะฟะตัะธะน). ะขะพะณะดะฐ ะฝัะผะตัะฐัะธั ัะฐััะตะน: ะฝะธะถะฝัั ััะฐะฟะตัะธั ฮณโ, ะปะตะฒะฐั ะฒะตััะธะบะฐะปัะฝะฐั ฮณโ, ะฒะตััะฝัั ััะฐะฟะตัะธั ฮณโ, ะฟัะฐะฒะฐั ะฒะตััะธะบะฐะปัะฝะฐั ฮณโ. ะะตััะฝัั ะทะฐะดะฐะตั ฯโ, ะฝะธะถะฝัั ฯโ.
    -โซโซ{D}โP/โydydx = -โซ{a,b}dxโซ{ฯโ(x),ฯโ(x)} โP/โy dy = โซ{a,b}(P(x, ฯโ(x))-P(x, ฯโ(x)))dx.
    โซ{โD}Pdx+0dy = โซฮณโ + โซฮณโ + โซฮณโ + โซฮณโ = {x = t, y = ฯโ(t), x'=1, y' = ฯโ'(t)} = โซ{a,b}P(t, ฯโ(t))dt + 0 + โซ{a,b}P(t, ฯโ(t))dt + 0 = โซ{a,b}(P(x, ฯโ(x))-P(x, ฯโ(x)))dx (ัะพะฒะฝะพ 2 ัััะพัะบะธ ะฒะฒะตัั) = -โซโซ{D}โP/โydydx

    ะะปั ะดัััะฐััั ะพะฑะปะฐััะตะน ะฟัะธะผะตะฝััั ัะตะพัะตะผั ะฟะพะบััะพัะฝะพ.
** 2 [#B] 46. *!* ะคะพัะผัะปะฐ ะกัะพะบัะฐ
   D โ โยณ - ะฟัะพััะฐั ะณะปะฐะดะบะฐั ะดะฒัะผะตัะฝะฐั ะฟะพะฒะตััะฝะพััั ะฒ โยณ, โD - Cยฒ-ะณะปะฐะดะบะฐั ะบัะธะฒะฐั.
   nโ -- ััะพัะพะฝะฐ ะฟะพะฒะตััะฝะพััะธ, ะพัะธะตะฝัะฐัะธั โD ัะพะณะปะฐัะพะฒะฐะฝะฐ.
   (P,Q,R) -- ะณะปะฐะดะบะพะต ะฒะตะบัะพัะฝะพะต ะฟะพะปะต ะฝะฐ D.
   *ัะพะณะดะฐ*
   โซ{โD}Pdx+Qdy+Rdz = โซโซ{D}(R'_y-Q'_z)dydz + (P'_z-R'_x)zdx + (Q'_x-P'_y)dxdy.

*** ะัะฐัะบะพะต ะดะพะบะฐะทะฐัะตะปัััะฒะพ
    (P, 0, 0)
    ะกะฒะพะดะธะผ ะปะตะฒัะน ะธะฝัะตะณัะฐะป ะบ ฯโปยน(u,v), ะฟัะธะผะตะฝัะตะผ ัะพัะผัะปั ะัะธะฝะฐ, ัะฐัะบััะฒะฐะตะผ ะฟัะพะธะทะฒะพะดะฝัะต ะฟะพ ัะพัะผัะปะต *, ะฒะพะทะฒัะฐัะฐะตะผ ะทะฐะผะตะฝั.
*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    (P, 0, 0)
    โซ{โD}Pdx+0+0 =? โซโซ{D}P'_z dzdx - P'_y dxdy
    ะัััั ั ะฝะฐั ะตััั ะพัะพะฑัะฐะถะตะฝะธั ั ะผะฝะพะถะตััะฒะฐ E โ โยฒ ะฒ ะฝัะถะฝัั ะพะฑะปะฐััั ะฒ โยณ.
    โซ{โD}Pdx =
   # = โซ{โE}P(x(u,v),y(u,v),z(u,v))(x'แตคdu+x'แตฅdv)
   # = {ะฟะฐัะฐะผะตััะธะทะฐัะธั u(t), v(t) }
   # = โซ{a, b}P(..)*(x'แตค*u'โ+x'แตฅ*u'โ)dt
    = โซ{โE}(Px'แตคdu + Px'แตฅdv)
    = โซโซ{E}((Px'แตฅ)'แตค - (Px'แตค)'แตฅ)dudv
    = โซโซ{E}(P'โx'แตค + P'_y*y'แตค + P'_z*z'แตค)x'แตฅ - (P'โx'แตฅ + P'_y*y'แตฅ + P'_z*z'แตฅ)x'แตค + Px'แตคแตฅ - Px'แตคแตฅ dudv
    = โซโซP'_z(z'แตคx'แตฅ - z'แตฅx'แตค) - P'_y(y'แตฅx'แตค-y'แตคx'แตฅ)dudv = โซโซ{D}P'\_zdzdx - P'_ydxdy
** 2 [#A] 47. *!* ะคะพัะผัะปะฐ ะะฐัััะฐ--ะัััะพะณัะฐะดัะบะพะณะพ
   1. ะงะฐััะฝัะน ัะปััะฐะน
      D โ โยณ, D -- ัะฐะทะฝะพััั ะดะฒัั ะฟะพะดะณัะฐัะธะบะพะฒ f, F: ฮฉโโยฒ โ โ
      R: D โ โ ะณะปะฐะดะบะฐั ััะฝะบัะธั,
      *ัะพะณะดะฐ*
      โซโซ{โD}R(x,y,z)dxdy = โซโซโซ{D}(โR/โz)dxdydz
   2. ะะพะปะฝะฐั ัะพัะผัะปะฐ.
      D โ โยณ, โD ะพัะธะตะฝัะธัะพะฒะฐะฝะฐ ะฟะพะปะตะผ ะฒะฝะตัะฝะธั ะฝะพัะผะฐะปะตะน.
      (P, Q, R) -- ะณะปะฐะดะบะพะต ะฒะตะบัะพัะฝะพะต ะฟะพะปะต ะฒ D
      *ัะพะณะดะฐ*
      โซโซ{โD}Pdydz + Qdxdz + Rdxdy = โซโซโซ{D}(P'x + Q'y + R'z)dxdydz

*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. ะะฐะทะดะตะปะธะผ ะฝะฐัะต ัะตะปะพ ะฝะฐ ััะธ ัะฐััะธ: ะฒะตััะฝะธะน ะฟะพะดะณัะฐัะธะบ (โDโ), ะฝะธะถะฝะธะน ะฟะพะดะณัะฐัะธะบ (โDโ), ัะธะปะธะฝะดัะธัะตัะบะฐั ัะฐััั ะผะตะถะดั ะฝะธะผะธ (โDโ).
       โซโซโซ{D}(โR/โz)dxdydz = โซโซ{ฮฉ}dxdy(โซ{f(x,y), F(x,y)}โR/โzdz) = โซโซ{ฮฉ}R((x,y,F(x,y)) - R(x,y,f(x,y)))) = โซโซ(โDโ)R(x,y,z)dxdy + โซโซ{โDโ}.. +  โซโซ{โDโ}... ะขัะตัะธะน ัะฐะฒะตะฝ ะฝัะปั, ะฟะตัะฒัะต ะดะฒะฐ ัะฐะฒะฝั ะฟัะตะดัะดััะตะผั ััะฐะฒะฝะตะฝะธั ะฒ ัะฐะฒะตะฝััะฒะต.
    2. ะัะธะผะตะฝะธัั 1 ัะตะพัะตะผั 3 ัะฐะทะฐ ะดะปั ะบะฐะถะดะพะณะพ ัะพััะฐะฒะปัััะตะณะพ ะฟะพะปั, ะฟะพะปััะธัั ัะพ, ััะพ ะฝัะถะฝะพ.
** 2 48. ะะตัะบะพะพัะดะธะฝะฐัะฝะพะต ะพะฟัะตะดะตะปะตะฝะธะต ัะพัะพัะฐ
   V -- ะณะปะฐะดะบะพะต ะฒะตะบัะพัะฝะพะต ะฟะพะปะต
   *ัะพะณะดะฐ* ัะบะฒะธะฒะฐะปะตะฝัะฝะพ:
   1. โB ะณะปะฐะดะบะพะต, ััะพ V = rotB
   2. divV = 0

*** ะะพะบะฐะทะฐัะตะปัััะฒะพ
    1. โ
       div(rot(B)) = 0?
       div(Vโ, Vโ, Vโ) = (Vโ)'_x + (Vโ)_y + (Vโ)_z
       div(rot(P,Q,R)) = (R'y-Q'z)'x + (P'z-R'x)'y + (Q'x-P'y)'z = 0 (ะฒัะต ะฟะพัะพะบัะฐัะฐะปะพัั.
    2. โ
       V = (Aโ,Aโ,Aโ), Aโ'x + Aโ'y + Aโ'z = 0. ะะฐะนะดะตะผ B = (Bโ,Bโ,Bโ), ััะพ rotB = V
       ะะฐะผะตัะธะผ, ััะพ rot(B+C) = V = rot(B) โ rot(C) = 0
       ะะตัะธะผ ัะธััะตะผั:
       Bโ'y-Bโ'z = Aโ
       Bโ'z-Bโ'x = Aโ
       Bโ'x-Bโ'y = Aโ
       ะัะตะดะฟะพะปะพะถะธะผ ััะพ Bโ = 0 (ะตัะปะธ ััะฐะฝะตั ะฟะปะพัะพ, ะผั ะทะฐะผะตัะธะผ), ัะพะณะดะฐ
       ะธะท ะฟะตัะฒะพะณะพ Bโ = -โซ{zโ, z}Aโdz,
       ะธะท ะฒัะพัะพะณะพ Bโ =  โซ{zโ, z)Aโdz + ฯ(x,y),
       ะขะพะณะดะฐ Bโ'x-Bโ'y = - โซ{zโ, z}Aโ'_xdz - โซ{zโ, z)Aโ'_ydz - ฯ'_y(x,y),
       ะะท ะดะธะฒะตัะณะตะฝัะธะธ
       โซ{zโ,z}(Aโ'x - Aโ'y)dz - ฯ'_y(x,y) = โซ{zโ,z}Aโ'_zdz - ฯ'_y(x,y)
       = Aโ(x,y,z) - Aโ(x,y,zโ) - ฯ'y = Aโ(x,y,z)
       ะัััะดะฐ ฯ'_y = -Aโ(x,y,zโ)
** 0 49. ะะตัะบะพะพัะดะธะฝะฐัะฝะพะต ะพะฟัะตะดะตะปะตะฝะธะต ะดะธะฒะตัะณะตะฝัะธะธ
** 0 50. ะะฟะธัะฐะฝะธะต ัะพะปะตะฝะพะธะดะฐะปัะฝัั ะฟะพะปะตะน ะฒ ัะตัะผะธะฝะฐั ะดะธะฒะตัะณะตะฝัะธะธ
* Definitions
** OK 1. ะฃัะปะพะฒะธะต L_loc
   ะคัะฝะบะธั f ัะดะพะฒะปะตัะฒะพััะตั ััะปะพะฒะธั L_loc(yโ) ะตัะปะธ โU_{yโ}, โg(x), ััะพ
   โy โ U_{yโ}, โx, |f(y, x)|โคg(x) ะธ g(x) ััะผะผะธััะตะผะฐั
** OK 2. ะะฑัะฐะท ะผะตัั ะฟัะธ ะพัะพะฑัะฐะถะตะฝะธะธ
   (X, ๐ด, ฮผ), (Y, ๐ต, _)
   ะัััั ะตััั ะพัะพะฑัะฐะถะตะฝะธะต ะค:X โ Y, ะฟัะธัะตะผ
   ฮฆโปยน(๐ต) = {ฮฆโปยน(b), b โ B}, ฮฆโปยน(๐ต) โ ๐ด
   ัะพะณะดะฐ โb โ ๐ต ฮฝ(b) = ฮผ(ฮฆโปยน(b)) -- ััะพ ะพะฑัะฐะท ะผะตัั ะฟัะธ ะพัะพะฑัะฐะถะตะฝะธะธ
** OK 3. ะะทะฒะตัะตะฝะฝัะน ะพะฑัะฐะท ะผะตัั
   (X, ๐ด, ฮผ), (Y, ๐ต, _)
   w - ะฒะตั, wโฅ0, ะธะทะผะตัะธะผะฐ,
   ฮฆ: X โ Y, ฮฆโปยน(B)โ๐ด
   ฮฝ(b) = โซ_ฮฆโปยน(b) (w)dฮผ - ะฒะทะฒะตัะตะฝะฝัะน ะพะฑัะฐะท ะผะตัั ฮผ
** OK 4. ะะปะพัะฝะพััั ะพะดะฝะพะน ะผะตัั ะฟะพ ะพัะฝะพัะตะฝะธั ะบ ะดััะณะพะน
   X = Y, ๐ด = ๐ต, ฮฆ = id,
   w - ะฒะตั, ะฟะพะปะพะถะธัะตะปัะฝะฐั ะธะทะผะตัะธะผะฐั ั-ั,
   f - ะธะทะผะตัะธะผะฐั ะฝะฐ X
   ฮฝ(B) = โซ_B wdฮผ, โซfdฮฝ=โซf(x)w(x)dฮผ
   ัะพะณะดะฐ ะฒะตั w - ััะพ ะฟะปะพัะฝะพััั ฮฝ ะพัะฝะพัะธัะตะปัะฝะพ ฮผ.
** OK 5. ะะฐััะด
   (X, ๐ด)
   ฮผ: ๐ด โ โ -- ััะพ ะทะฐััะด, ะฝะต ะพะฑัะทะฐะฝ ะฑััั โฅ0
** OK 6. ะะฝะพะถะตััะฒะพ ะฟะพะปะพะถะธัะตะปัะฝะพััะธ ะทะฐััะดะฐ
   (X, ๐ด, ฮผ)
   BโA -- ะผะฝะพะถะตััะฒะพ ะฟะพะปะพะถะธัะตะปัะฝะพััะธ ะทะฐััะดะฐ, ะตัะปะธ โEโB ฮผE โฅ 0
** OK 7. ะะตัะฐ ะฐะฑัะพะปััะฝะพ ะฝะตะฟัะตััะฒะฝะฐั ะพัะฝะพัะธัะตะปัะฝะพ ะดััะณะพะน
   ฮฝ ะฐะฑัะพะปััะฝะพ ะฝะตะฟัะตััะฒะฝะฐ ะพัะฝะพัะธัะตะปัะฝะพ ฮผ, ะตัะปะธ
   โa.(ฮผ(a)==0 โ ฮฝ(a)==0)
** OK 8. ะัะพะธะทะฒะตะดะตะฝะธะต ะผะตั
   (X, ๐ด, ฮผ), (Y, ๐ต, ฮฝ)
   ๐ดโ๐ต = {AรB, Aโ๐ด, Bโ๐ต}
   ]mโ = ฮผรฮฝ (mโ(AรB) = ฮผ(A)*ฮฝ(B)), ัะพะณะดะฐ.
   ะฟัะพะดะพะปะถะตะฝะธะต ะฟe ะะตะฑะตะณั mโ ั ๐ดโ๐ต ะฟะพัะพะดะธั (XรY, ๐ดโ๐ต, m), ะธ ัะพะณะดะฐ m - ััะพ ะบะฐะบ ัะฐะท ะฟัะพะธะทะฒะตะดะตะฝะธะต ะผะตั.
** OK 9. ะกะตัะตะฝะธะต ะผะฝะพะถะตััะฒะฐ
   ะัััั ั ะฝะฐั ะตััั C โ XรY, ัะพะณะดะฐ
   Cโ = {y โ Y | (x, y) โ C}
   Cy = {x โ X | (x, y) โ C}
** OK 10. ะคัะฝะบัะธั ัะฐัะฟัะตะดะตะปะตะฝะธั
   (X, A, ฮผ), h: X โ R, X(h<x) ะบะพะฝะตัะฝะพ, ัะพะณะดะฐ H(x) = ฮผX(h<x)
** OK 11. ะะฝัะตะณัะฐะปัะฝัะต ะฝะตัะฐะฒะตะฝััะฒะฐ ะะตะปัะดะตัะฐ ะธ ะะธะฝะบะพะฒัะบะพะณะพ
   ะัะพัััะต ะฒะฐัะธะฐะฝัั:
   ะัะปัะดะตั: p,q > 1, 1/p+1/q=1, ัะพะณะดะฐ โโโฅfโgโฅโ = โฅfโฅ_p * โฅgโฅ_q.
   ะะธะฝะบะพะฒัะบะธะน: p โฅ 1, โโฅf+gโฅโ โค โฅfโฅโ + โฅgโฅโ.
   ะะพะปะฝัะต ะฒะฐัะธะฐะฝัั:
   ะัะปัะดะตั: p,q > 1, 1/p+1/q=1, ัะพะณะดะฐ โซX |fg| dฮผ = (โซX |f|แต)^(1/p) * (โซX |g|^q)^(1/q)
   ะะธะฝะบะพะฒัะบะธะน: p โฅ 1, ัะพะณะดะฐ (โซ|f+g|แต)^(1/p) โค (โซ|f|แต)^(1/p) + (โซ|g|^p)^(1/p)
** OK 12. ะะฝัะตะณัะฐะป ะบะพะผะฟะปะตะบัะฝะพะทะฝะฐัะฝะพะน ััะฝะบัะธะธ
   โซf = โซRef + i*โซImf
** OK 13. ะัะพัััะฐะฝััะฒะพ L^p(E,ฮผ)
   1 โค p โค +โ
   (X, ๐ด, ฮผ), ัะฐััะผะพััะธะผ {f:Xโโ~ โจ โ~; ะธะทะผะตัะธะผะพะต, ััะพ โซX |f|แต-ะบะพะฝะตัะฝะพ}
   ะะฝะพะถะตััะฒะพ ัะฐะบะธั ััะบะฝัะธะน ะฑัะดะตั ะปะธะฝะตะนะฝัะผ ะฟัะพัััะฐะฝััะฒะพะผ ะฒ ัะธะปั ะฝะตัะฐะฒะตะฝััะฒะฐ ะผะธะฝะบะพะฒัะบะพะณะพ: f โฆ โฅfโฅโ = (โซ|f|แตdฮผ)^(1/p) - ัะดะพะฒะปะตัะฒะพััะตั ะฝะตัะฐะฒะตะฝััะฒั.
   Lแต(X, ฮผ) -- ััะพ ัะฐะบัะพัะธะทะฐัะธั ัะฐะบะพะณะพ ะปะธะฝะตะนะฝะพะณะพ ะฟัะพัััะฐะฝััะฒะฐ ะฟะพ ัะฐะฒะตะฝััะฒั ะฟะพััะธ ะฒะตะทะดะต.
** OK 14. ะกััะตััะฒะตะฝะฝัะน ััะฟัะตะผัะผ
   f:X โ โ~,
   esssup(f) = inf{MโR, f(x) โค M ะฟัะธ ะฟะพััะธ ะฒัะตั X}
** OK 15. ะัะพัััะฐะฝััะฒะพ L^โ(E,ฮผ)
   Lโ ัะพััะพะธั ะธะท f:X โ โ~(โ~), ะพะฝะธ ะธะทะผะตัะธะผั ะธ ะพะณัะฐะฝะธัะตะฝั (esssup|f|<โ) + ะผั ะพัะพะถะดะตััะฒะปัะตะผ ััะฝะบัะธะธ ัะพะฒะฟะฐะดะฐััะธะต ะฟะพััะธ ะฒะตะทะดะต. ะขะฐะบะฐั ะบะพะฝััััะบัะธั ัะพะถะต ะปะธะฝะตะนะฝะพะต ะฟัะพัััะฐะฝััะฒะพ ะฟะพ ัะฒะพะนััะฒั esssup.
   โฅgโฅโ = esssup|f|
** OK 16. ะคัะฝะดะฐะผะตะฝัะฐะปัะฝะฐั ะฟะพัะปะตะดะพะฒะฐัะตะปัะฝะพััั, ะฟะพะปะฝะพะต ะฟัะพัััะฐะฝััะฒะพ
   * xโ โ L - ะปะธะฝะตะนะฝะพะต ะฟัะพัััะฐะฝััะฒะพ, xโ ััะฝะดะฐะผะตะฝัะฐะปัะฝะพ ะตัะปะธ โฮต>0 โN โn>N,m>N โฅxโ-xโโฅ<ฮต
     xโ โ x, ัะพะณะดะฐ xโ ััะฝะดะฐะผะตะฝัะฐะปัะฝะพ (โฅxโ-xโโฅ โค โฅxโ-xโฅ+โฅxโ-xโฅ)
   * L -- ะฟะพะปะฝะพะต, ะตัะปะธ โxโ, xโ ััะฝะดะฐะผะตะฝัะฐะปัะฝะพ โ โlim xโ
** OK 17. ะะปะพัะฝะพะต ะผะฝะพะถะตััะฒะพ
   X โ ะผะตััะธัะตัะบะพะต ะฟัะพัััะฐะฝััะฒะพ, A โ X -- ะฒััะดั ะฟะปะพัะฝะพ ะฒ X ะตัะปะธ โัะฐัะฐ B(xโ,r) ะฒ ะฝะตะผ ะตััั ัะพัะบะธ ะธะท A ะธะปะธ โะพัะบัััะพะณะพ ะผะฝะพะถะตััะฒะฐ G โ X  AโฉGโโ
** OK 18. ะคะธะฝะธัะฝะฐั ััะฝะบัะธั
   f โ ัะธะฝะธัะฝะฐั ะฒ โแต, ะตัะปะธ f=0 ะฒะฝะต ะฝะตะบะพัะพัะพะณะพ ัะฐัะฐ.
   Cโ(โแต) โ ะผะฝะพะถะตััะฒะพ ัะธะฝะธัะฝัั ะฝะตะฟัะตััะฒะฝัั ััะฝะบัะธะน. โp Cโ โ Lแต(โแต)
** OK 19. ะะปะฐัั ะฟะตัะธะพะดะธัะฝัั ััะฝะบัะธะน
   Lแต[0,T] - ะฟัะพัััะฐะฝััะฒะพ T-ะฟะตัะธะพะดะธัะฝัะน ััะฝะบัะธะน :โ โ โ~ ั ััะปะพะฒะธะตะผ ััะผะผะธััะตะผะพััะธ โซ{0,T}|f|แตdฮป < +โ.
   ะกะพะผะฝะธัะตะปัะฝัะต ััะฒะตัะถะดะตะฝะธั: fโ(x) = f(x+h), โซ{0,T}.. = โซ{0+h, T+h}
** OK 20. ะะธะปัะฑะตััะพะฒะพ ะฟัะพัััะฐะฝััะฒะพ
   L - ะปะธะฝะตะนะฝะพะต ะฟัะพัััะฐะฝััะฒะพ ะฝะฐะด (โ ะธะปะธ โ) ั ะพะฟะตัะฐัะธะตะน <,>: LรL โ โ(โ)
   ะัะธัะตะผ โฅฮฑโฅ = โ<ฮฑ,ฮฑ>, |<ฮฑ,ฮฒ>| โค โฅฮฑโฅโฅฮฒโฅ.
** OK ะััะพะฝะพัะผะธัะพะฒะฐะฝะฝะฐั ัะธััะตะผะฐ ะฒะตะบัะพัะพะฒ, ะฟัะธะผะตัั
   {eโ...} ะพััะพะณะพะฝะฐะปัะฝะฐ, ะตัะปะธ โiโj <eแตข,eโฑผ> = 0. ะััะพะฝะพัะผะธัะพะฒะฐะฝะฐ ะตัะปะธ โi |eแตข|=1.
   1. eโ = (0,..1(ะฝะฐ k-ะผ ะผะตััะต),..).
   2. Lยฒ[0,2ฯ] (ะธะปะธ Lยฒ[-ฯ,ฯ]), sinx, cosx, sin2x, cos2x,...
      โซ{-ฯ,ฯ}sinkx*coslxdx = 0 ะธะท ะฝะตัะตัะฝะพััะธ.
      โซ{-ฯ,ฯ}sinkxsinlx = 1/2โซ{-ฯ,ฯ}(cos(k-l)x-cos(k+l)x)dx =
      1. 1/2(sin(k-l)x/(k-l) - sin(k+l)x/(k+l))|_{-ฯ,ฯ} = 0
      2. 1/2โซ{-ฯ,ฯ}(1-cos2kxdx) = ฯ
** OK 21. ะกัะพะดััะธะนัั ััะด ะฒ ะณะธะปัะฑะตััะพะฒะพะผ ะฟัะพัััะฐะฝััะฒะต
   โxโ ััะพะดะธััั ะฒ ๐ป, ะตัะปะธ โS, ััะพ โ{N}xโ โ S. ะัะถะฝะพ ะตัะต ัะฐัะฟะธัะฐัั ฮต-ะพะฟัะตะดะตะปะตะฝะธะต "โ" ัะตัะตะท ะฝะพัะผั, ััะพะฑั ััะพ ะพะฟัะตะดะตะปะตะฝะธะต ะฑัะปะพ ะดะปั ะบะพะฝะบัะตัะฝะพ ะะธะปัะฑะตััะพะฒัั ะฟัะพัััะฐะฝััะฒ.
** OK 24. ะะพัััะธัะธะตะฝัั ะคัััะต
   Cโ = <x,eโ>/โฅeโโฅยฒ -- ะบะพัััะธัะธะตะฝั ััััะต ัะปะตะผะตะฝัะฐ x ะฟะพ ะะก {eโ}
** OK 25. ะัะด ะคัััะต
   ะัะด ััััะต ะฒ ะะก {eโ} -- โCโeโ
** OK ะะตัะฐะฒะตะฝััะฒะพ ะะตััะตะปั, ัะฐะฒะตะฝััะฒะพ ะะฐััะตะฒะฐะปั
   ะะตััะตะปั: โ|Cโ|ยฒโฅeโโฅยฒ โค โฅxโฅยฒ
   ะะฐััะตะฒะฐะปั ั "=". ะะฐะผะตัะธะผ, ััะพ ััะพ ะพะฑะพะฑัะตะฝะธะต ะะธัะฐะณะพัะฐ ั โยฒ.
** OK 26. ะะฐะทะธั, ะฟะพะปะฝะฐั, ะทะฐะผะบะฝััะฐั ะะก
   {eโ} - ะะก -- ะฑะฐะทะธั, ะตัะปะธ โx โ ๐ป x = โ{โ}Cโ(x)eโ
   ะะก ะฟะพะปะฝะฐั ะฒ ๐ป, ะตัะปะธ โk โz (z โฅ eโ โ z = 0)
   ะะก ะทะฐะผะบะฝััะฐ, ะตัะปะธ ะดะปั ะฝะตะต ะฒัะฟะพะปะฝะตะฝะพ ัะฐะฒะตะฝััะฒะพ ะะฐััะตะฒะฐะปั (ะทะฐะผะบะฝััะพััะธ): โ|Cโ(x)|ยฒโฅeโโฅยฒ = โฅxโฅยฒ
** OK 27. ะขัะธะณะพะฝะพะผะตััะธัะตัะบะธะน ััะด
   Tโ = aโ/2 + โ{1,n}(aโcoskx + bโsinkx) -- ััะธะณะพะฝะพะผะตััะธัะตัะบะธะน ะผะฝะพะณะพัะปะตะฝ ััะตะฟะตะฝะธ n
   aโ/2 + โ{โ}(aโcoskx + bโsinkx) -- ััะธะณะพะฝะพะผะตััะธัะตัะบะธะน ััะด
   ะะปะธ ะฒ ะบะพะผะฟะปะตะบัะฝะพะทะฝะฐัะฝะพะน ัะพัะผะต: โ{โ}Cโeโฑแตหฃ = limโ{-n, n}...
** OK 28. ะะพัััะธัะธะตะฝัั ะคัััะต ััะฝะบัะธะธ
   aโ = 1/ฯโซ{-ฯ,ฯ}f(x)coskxdx, k = 0,1,...
   bโ = 1/ฯโซ{-ฯ,ฯ}f(x)sinksdx, k = 0,1,...
   cโ = 1/2ฯโซ{-ฯ,ฯ}f(x)eโฑแตหฃdx, k = 0,1,...
** 2 29. ะฏะดัะพ ะะธัะธัะปะต, ัะดัะพ ะคะตะนะตัะฐ
   Dโ(t) = 1/ฯ(1/2+โ{n}coskt) -- ัะดัะพ ะะธัะธัะปะต
   ฮฆโ(t) = 1/(n+1)โDโ(t) -- ัะดัะพ ะคะตะนะตัะฐ

   Dโ(t)=sin((n+1/2)t)/(2ฯ*sin(t/2))
   ฮฆโ(t)=sinยฒ((n+1/2)t)/(2ฯ*sinยฒ(t/2)) * (1/(n+1))
   โซ{-ฯ,ฯ}Dโ(t) = ...ฮฆโ(t) = 1
   Sโ(f) = โซ{-ฯ,ฯ}f(x+t)Dโ(t)dt. -- ะฒะฝะตะทะฐะฟะฝะพะต ัะฒะพะนััะฒะพ ัะดัะฐ ะะธัะธัะปะต ะดะปั ัะตะพัะตะผั ะะธะฝะธ.
** OK 30. ะกะฒะตััะบะฐ
   f,K โ Lยน[-ฯ,ฯ], (f*K)(x) -- ัะฒะตััะบะฐ:
   (f*K)(x) = โซ{-ฯ,ฯ}f(t)K(x-t)dt = โซ{-ฯ,ฯ}f(x-t)K(t)dt
** 2 31. ะะฟะฟัะพะบัะธะผะฐัะธะฒะฝะฐั ะตะดะธะฝะธัะฐ
   D โ โ, xโ โ R~ -- ะฟัะตะดะตะปัะฝะฐั ัะพัะบะฐ D, โh โ D ะพะฟัะตะดะตะปะตะฝะฐ Kโ(x) -- ะฐะฟะฟัะพะบัะธะผะฐัะธะฒะฝะฐั ะตะดะธะฝะธัะฐ, ะตัะปะธ:
   1. AE1 โh>0 Kโ โ Lยน[-ฯ,ฯ], โซ{-ฯ,ฯ}Kโ(t)=1
   2. AE2 Lยน-ะฝะพัะผะฐ ััะฝะบัะธะธ Kโ ะพะณัะฐะฝะธัะตะฝะฐ ะฒ ัะพะฒะพะบัะฟะฝะพััะธ: โM โhโD โซ{-ฯ,ฯ}|Kโ|dt < M
   3. AE3 โฮด>0 โซ{Eฮด}|Kโ| โ{hโxโ}โ 0, ะณะดะต Eฮด=[-ฯ,ฯ]\[-ฮด,ฮด]
** 2 32. ะฃัะธะปะตะฝะฝะฐั ะฐะฟะฟัะพะบัะธะผะฐัะธะฒะฝะฐั ะตะดะธะฝะธัะฐ
   ะัััั Kโ โ Lโ[-ฯ,ฯ].
   ะะผะตััะพ AE3 ะตััั AE3': essup{Eฮด}|Kโ| โ{hโxโ} 0
** OK 33. ะะตัะพะด ััะผะผะธัะพะฒะฐะฝะธั ััะตะดะฝะธะผะธ ะฐัะธัะผะตัะธัะตัะบะธะผะธ
   lim{nโโ}[(Sโ+...+Sโ)/(n+1)] ะฝะฐะทัะฒะฐัััั ััะผะผะพะน ััะดะฐ โaโ ะฟะพ ะงะตะทะฐัะพ.
   ะัะธัะตะผ ัะฐััะฝะพะต ะฝะฐะทัะฒะฐะตััั ััะผะผะพะน ะคะตะนะตัะฐ -- ฯโ(f) = 1/(n+1) โ{n}Sโ(f)
** ---------------------------------------------------------------------------
** OK 34. ะะทะผะตัะธะผะพะต ะผะฝะพะถะตััะฒะพ ะฝะฐ ะฟัะพััะพะน ะดะฒัะผะตัะฝะพะน ะฟะพะฒะตััะฝะพััะธ ะฒ โยณ
   M -- ะฟัะพััะฐั ะณะปะฐะดะบะฐั 2-ะผะตัะฝะฐั ะฟะพะฒะตััะฝะพััั ะฒ โยณ.
   ฯ: ฮฉโโยฒ โ โยณ ะณะปะฐะดะบะฐั, ะฟะฐัะฐะผะตััะธัะตัะบะฐั
   ะขะพะณะดะฐ A โ M ะธะทะผะตัะธะผะฐ ะฟะพ ะะตะฑะตะณั ะตัะปะธ ฯโปยน(A) ะธะทะผะตัะธะผะพ ะฒ ๐ยฒ
** OK 35. ะะตัะฐ ะะตะฑะตะณะฐ ะฝะฐ ะฟัะพััะพะน ะดะฒัะผะตัะฝะพะน ะฟะพะฒะตััะฝะพััะธ ะฒ โยณ
   A โ ๐ดโ -- ฯ-ะฐะปะณะตะฑัะฐ ะธะทะผะตัะธะผัั ะผะฝะพะถะตััะฒ. ะะตัะฐ ะฝะฐ ๐ดโ: ฯ(A) = โซ{ฯโปยน(A)) |ฯ'แตครฯ'แตฅ|dudv
** OK 36. ะะพะฒะตััะฝะพััะฝัะน ะธะฝัะตะณัะฐะป ะฟะตัะฒะพะณะพ ัะพะดะฐ
   โซ{A} fdฯ = โซโซ{ฯโปยน(A)} fโฯ|ฯ'แตครฯ'แตฅ|dudv
** OK 37. ะััะพัะฝะพ-ะณะปะฐะดะบะฐั ะฟะพะฒะตััะฝะพััั ะฒ โยณ
   M โ โยณ -- ะบััะพัะฝะพ ะณะปะฐะดะบะฐั, ะตัะปะธ M = โN + โD + โX (ะฒัะต ะบะพะฝะตัะฝะพ),
   ะณะดะต N -- ะฟัะพััะฐั ะณะปะฐะดะบะฐั ะฟะพะฒะตััะฝะพััั, D -- ะฟัะพัััะต ะดัะณะธ, X -- ัะพัะบะธ
** OK 38. ะกัะพัะพะฝะฐ ะฟะพะฒะตััะฝะพััะธ
   ะะตะฟัะตััะฒะฝะพะต ะฟะพะปะต ะตะดะธะฝะธัะฝัั ะฝะพัะผะฐะปะตะน ะฝะฐ ะฟะพะฒะตััะฝะพััะธ.
   M โ โยณ, nโ: M โ โยณ (x โฆ hโ(x)), |nโ| = 1
** OK 39. ะะฐะดะฐะฝะธะต ััะพัะพะฝั ะฟะพะฒะตััะฝะพััะธ ั ะฟะพะผะพััั ะบะฐัะฐัะตะปัะฝัั ัะตะฟะตัะพะฒ
   ะะตะฟะตั -- ััะพ ะฝะตะฑะพั ะธะท ะดะฒัั ะฝะตะบะพะปะปะธะฝะตะฐัะฝัั ะบะฐัะฐัะตะปัะฝัั ะบ ะฟะพะฒะตััะฝะพััะธ ะฒะตะบัะพัะพะฒ,
   ัะพะณะดะฐ ะฟะพะปะต ัะตะฟะตัะพะฒ Vโ, Vโ ะทะฐะดะฐะตั ััะพัะพะฝั ะฟะพะฒะตััะฝะพััะธ. nโ=Vโ(x)รVโ(x)/|Vโ(x)รVโ(x)|.
** 2 40. ะะฝัะตะณัะฐะป II ัะพะดะฐ
   M โ โยณ -- ะฟัะพััะฐั ะณะปะฐะดะบะฐั ะดะฒัััะพัะพะฝะฝัั ะฟะพะฒะตััะฝะพััั ัะพ ััะพัะพะฝะพะน nโ.
   F:M โ โยณ -- ะฒะตะบัะพัะฝะพะต ะฟะพะปะต, ัะพะณะดะฐ
   โซ{M}<F,nโ>dฯ - ะฟะพะฒะตััะฝะพััะฝัะน ะธะฝัะตะณัะฐะป 2 ัะพะดะฐ. ะกะผะตะฝะฐ ััะพัะพะฝั -- ัะผะตะฝะฐ ะทะฝะฐะบะฐ.
** OK 41. ะัะธะตะฝัะฐัะธั ะบะพะฝัััะฐ, ัะพะณะปะฐัะพะฒะฐะฝะฝะฐั ัะพ ััะพัะพะฝะพะน ะฟะพะฒะตััะฝะพััะธ
   ะัะปะธ ั ะฝะฐั ะตััั ะฟะพะฒะตััะฝะพััั D, ัะพ ะพัะธะตะฝัะฐัะธั ะบะพะฝัััะฐ, ัะฒะปัััะตะณะพัั ะตะณะพ ะณัะฐะฝะธัะตะน, ะฟะพ ะฟัะฐะฒะธะปั ะฑััะฐะฒัะธะบะฐ.
** OK 42. ะะพัะพั, ะดะธะฒะตัะณะตะฝัะธั ะฒะตะบัะพัะฝะพะณะพ ะฟะพะปั
   V = (P,Q,R)
   rot(V) = (R'y-Q'z, P'z-R'x, Q'x-P'y)
   div(V) = P'x+Q'y+R'z
** OK 43. ะกะพะปะตะฝะพะธะดะฐะปัะฝะพะต ะฒะตะบัะพัะฝะพะต ะฟะพะปะต
   ะะพะปะต V ัะพะปะตะฝะพะธะดะฐะปัะฝะพะต, ะตัะปะธ โB, ััะพ rotB = V.
