#+TODO: X 0 1 2 | OK
#+TITLE: Mathematical analysis conspect of lections by Kokhas' K.P. - II term

* Definitions [42/46]
** 2 Выпуклое множество
** OK Выпуклая функция, строго выпуклая функция
   CLOSED: [2014-06-25 Wed 16:02]
   Это функция для которой f(αa+(1-α)b) <= αf(a) + (1-α)f(b)
** OK Следствия о непрерывности и дифференцируемости выпуклой функции
   CLOSED: [2014-06-25 Wed 16:03]
   Счетная функция дифференцируема везде кроме счетного множества
** OK Опорная прямая
   CLOSED: [2014-06-25 Wed 16:08]
   ∀ l(x) = ax + b | y = l(x) γ опорной прямой в x₀, если f(x) >= l(x),
   f(x₀) == l(x₀)
** OK Первообразная
   CLOSED: [2014-06-25 Wed 16:08]
   F(x) γ первообразной, если F'(x) = f(x) ∀ x ∈ <a, b>
** OK Теорема о существовании первообразной
   CLOSED: [2014-06-25 Wed 16:21]
   Непрерывная на <a,b> функция имеет первообразную.
** 2 Таблица первообразных
   Самые проблемные:
   * ∫dx/(1+x²) = arctgx, -arcctgx
   * ∫dx/√(1-x²) = arcsinx, -arccosx
   * ̣∫dx/(1-x²) = 0.5 ln|(1+x)/(1-x)|
   * ∫dx/√(x²+-1) = ln|x + √(x²+-1)|
   * 1/cos² -> tg, 1/sin² -> -ctg
** OK Преобразование Абеля
   CLOSED: [2014-06-26 Thu 09:51]
   ∑_N^M (ak*bk) = A{M}*b{M} - A{N-1}b{N-1} - ∑_N^(M-1) (A{k}*(b{k+1} - b{k}))
** OK Площадь, аддитивность площади, ослабленная аддитивность
   CLOSED: [2014-06-25 Wed 16:33]
   Ну типа функция из подмножества всех фигур в R^2 в R, аддитивная и нормированная по
   прямоугольнику, ослабленная аддитивность -- это про отрезок. А еще площадь
   монотонна
** OK Определенный интеграл
   CLOSED: [2014-06-26 Thu 09:53]
   Разница площадей подграфиков положительной и отрицательной срезок
** OK Интеграл с переменным верхним пределом
   CLOSED: [2014-06-25 Wed 16:37]
   Φ(x) = ∫₀ˣf(x)
** OK Дробление промежутка, оснащение, риманова сумма
   CLOSED: [2014-06-25 Wed 16:38]
   Дробление – a = x1 < x2 < .. < xn = b
   Оснащение – точки внутри единицы дробления
   Риманова сумма – ∑f(ξₖk)(x{k+1}-xk)
** OK Метод Остроградского интегрирования рациональных дробей
   CLOSED: [2014-06-26 Thu 09:54]
   P/Q = (P1/Q1)' + P2/Q2,
   n2 + n1 = n (Q)
   m1 < n1, m2 < n2
** OK Интегральная сумма для центральных прямоугольников
   CLOSED: [2014-06-25 Wed 16:44]
** OK Интегральная сумма трапеций
   CLOSED: [2014-06-25 Wed 16:44]
** OK Постоянная Эйлера
   CLOSED: [2014-06-25 Wed 17:13]
   lim{k->∞}(∑₁ᵏ1/n - lnk)
** OK Интегральное неравенство Коши--Буняковского
   CLOSED: [2014-06-25 Wed 17:14]
** OK Интегральное неравенство Минковского
   CLOSED: [2014-06-26 Thu 09:56]
   Модули не забыть
** OK Кусочно-непрерывная функция
   CLOSED: [2014-06-26 Thu 03:13]
   Конечное множество точек, а не счетное
** OK Почти первообразная
   CLOSED: [2014-06-26 Thu 09:57]
   F'(x) = f(x) на везде\конечное_множество_точек, F непрерывная
** OK Функция промежутка, аддитивная функция промежутка
   CLOSED: [2014-06-26 Thu 03:15]
** OK Плотность аддитивной функции промежутка
   CLOSED: [2014-06-25 Wed 17:25]
** OK Формула площади подграфика параметрически заданной функции
   CLOSED: [2014-06-26 Thu 03:15]
   ∫x'(t)y(t)dt
** OK Путь, гладкий путь, вектор скорости
   CLOSED: [2014-06-26 Thu 03:15]
   Гладкий – дифференцируемый
** OK Длина пути (определение)
   CLOSED: [2014-06-26 Thu 12:28]
   Ну эта такая функция l, что
   * Она положительно определена
   * Она аддитивна (l(γ) = l(γ|[a,c]) + l(γ|[c,b]))
   * Если ∃ T:Cγ -> Cγ⁺, где Cγ – носитель пути γ, причем эта биекция есть
     сжатие ρ(T(A), T(B)) ≤ ρ(A, B), тогда l(γ⁺) ≤ l(γ)
   * Она нормирована – l(γ) = (b-a)||v||, если γ=u+vt (линейный путь)
** OK Допустимая функция
   CLOSED: [2014-06-26 Thu 10:12]
   [a,b)→R если ∀ c ∈ (a,b) f - кусочно-непрерывная на [a,b]
** OK Несобственный интеграл, сходимость, расходимость
   CLOSED: [2014-06-25 Wed 17:46]
** OK Критерий Больцано--Коши сходимости несобственного интеграла
   CLOSED: [2014-06-26 Thu 03:16]
** OK Абсолютно сходящийся интеграл
   CLOSED: [2014-06-25 Wed 17:47]
** 2 Гамма функция Эйлера
   Γ(t)=∫_{0}^{+inf}(x^(t-1)e^(-x)dx)
** OK Числовой ряд, сумма ряда, сходимость, расходимость
   CLOSED: [2014-06-26 Thu 03:18]
   Числовой ряд – предел частичных сумм, сущ - сход
** OK $n$-й остаток ряда
   CLOSED: [2014-06-25 Wed 17:57]
   Очевидно
** OK Критерий Больцано--Коши сходимости числового ряда
   CLOSED: [2014-06-25 Wed 17:58]

** OK Абсолютно сходящийся ряд
   CLOSED: [2014-06-25 Wed 17:59]

** OK Перестановка ряда
   CLOSED: [2014-06-26 Thu 03:18]
   φ:N->N
** OK Теорема Римана о рядах, сходящихся неабсолютно
   CLOSED: [2014-06-25 Wed 18:02]
   Лол ясно
** OK Произведение рядов
   CLOSED: [2014-06-25 Wed 18:03]
** 2 Произведение степенных рядов
   ∑an*xⁿ * ∑bn*xⁿ = ∑(ak*b{n-k})xⁿ
** OK Поточечная сходимость последовательности функций на множестве
   CLOSED: [2014-06-25 Wed 18:09]
** OK Равномерная сходимость последовательности функций на множестве
   CLOSED: [2014-06-25 Wed 18:09]
** OK Поточечная  сходимость функционального ряда
   CLOSED: [2014-06-25 Wed 18:09]
** OK Равномерная сходимость функционального ряда
   CLOSED: [2014-06-25 Wed 18:09]
** OK Формулировка критерия Больцано--Коши для равномерной сходимости
   CLOSED: [2014-06-25 Wed 18:10]
** OK Признак Абеля равномерной сходимости функционального ряда
   CLOSED: [2014-06-26 Thu 12:21]
   а(x)b(x), ∑a(x) сходится равномерно, ∀x bn(x) равномерно ограничена и монотонна по n
** OK Степенной ряд, радиус сходимости степенного ряда, формула Адамара
   CLOSED: [2014-06-25 Wed 18:12]
   Изи
** OK Производная комплексной функции
   CLOSED: [2014-06-25 Wed 18:12]
   Ну это изи
** PROBLEM Следствие о почленном интегрировании степенного ряда
   Похоже, что ∑an/(n+1)*(x-x₀)^{n+1}
** PROBLEM Ряд Тейлора
* Lemmas and theorems [57/68]
** OK Лемма о построении последовательности с более высокой скоростью сходимости
   CLOSED: [2014-06-25 Wed 15:51]
   Ну там подбираем такую z, чтобы она стремилась к тому же, что и остальные
   члены, затем еще две подпоследовательности p q, два неравенства через корни
   и все заходит
** OK Правило Лопиталя
   CLOSED: [2014-06-26 Thu 03:29]
   Две последовательности, стремящиеся к предельной точке, для них юзаем теорему Коши
   о среднем, потом выражаем все, что нужно и говорим, что одна из последовательностей
   как раз из теоремы 1
** OK Теорема Штольца
   CLOSED: [2014-06-25 Wed 16:01]
   Говорим, раз та жесткая хрень стремится к L, то сделаем двойное неравенство на эпсилон.
   Пишем k таких неравенств для разных коэффициентов а потом магическим образом складываем
   и устремляем к пределу
** OK Лемма о трех хордах
   CLOSED: [2014-06-25 Wed 18:50]
   Рассматриваем любое неравенство из двух, выражаем оттуда один член, получаем что нужно
   (определение выпуклости)
** OK Теорема об односторонней дифференцируемости выпуклой функции
   CLOSED: [2014-06-26 Thu 10:21]
   Теорема о пределе монотонной функции – доказывам монотонность и ограниченность
   Запилим такую функцию g(c) для выделенногo x, определенную на всем аб кроме этого самого
   х. Эта самая функция возрастает на аб по лемме о трех хордах, а затем определяем, где
   она ограничена, понимаем, что при устремлении к x g = f', все.
** OK Теорема об описании выпуклости в терминах касательных
   CLOSED: [2014-06-26 Thu 10:22]
   Необходимость: выделим x0, положим x > x0, тогда для любого c из (x0, x) верна
   лемма о трех хордах, откуда, устремсляя c -> x, получаем как раз определение касательной
   Достаточность: расписываем для двух точек x1 < x2 уравнения касательных, потом вытаскиваем
   из них f'(x), пилим двойное неравенство, которое образует как раз лемму о трех хордах
** OK Дифференциальный критерий выпуклости
   CLOSED: [2014-06-26 Thu 10:22]
   Необходимость напрямую из односторонней дифференцируемости функции
   Достаточность: подбираем x₁, x₂, по Лагранжу находим c₁, c₂ (a < x₁ < c₁ < x < x₂ < x₂ < b),
   а f' по условию возрастает, значит f'(c₁) < f'(c₂), расписываем, получаем определение
   выпуклости
** OK Неравенство Йенсена
   CLOSED: [2014-06-26 Thu 03:46]
   Показываем, почему вся сумма принадлежит отрезку (max(xⱼ))
   берем опорную прямую в точке X = sum...
   потом говорим, что f(x) <= l(x) = l(sum...) = (раскрываем по линейности и каждое l раскрываем)
** OK Неравенство Коши
   CLOSED: [2014-06-26 Thu 03:46]
   Среднее арифметическое меньше среднего геом (изи)
** OK Неравенство Гельдера для конечных сумм
   CLOSED: [2014-06-26 Thu 10:24]
   Декларируем, что xᵖ выпуклая функция на [0, +∞), пилим неравенство Йенсена, затем
   подбираем нужные x, α: α = bi^q / ∑bi^q; x = aᵢbᵢ^(-1/p-1) (∑bᵢ^q)
   Подставляем, готово
** OK Неравенство Минковского
   CLOSED: [2014-06-26 Thu 03:48]
   Юзаем два раза неравенство Гельдера для aᵢ(aᵢ + bᵢ)^(p-1), bᵢ(aᵢ + bᵢ)^..., складываем их,
   делим на то, что в правой части вынеслось из-за скобок. Готово.
** OK Теорема о свойствах неопределенного интеграла
   CLOSED: [2014-06-26 Thu 12:23]
   f+g, αf, первообразная от композиции функций, интеграл от чего-то, где выносим 1/α,
   интегрировение по частям (из того, что (fg)' = f'g + g'f)
** OK Запись рациональной дроби в виде, удобном для интегрирования (док-во для случая вещ. корней)
   CLOSED: [2014-06-26 Thu 03:50]
   P(x)/Q(x), вытаскиваем из знаменателя одну скобочку, остальное раскладываем магическим
   образом
   Вычитаем это из нашей дроби на энтом шаге, получаем в числителе (x-a)()()()()...Q'''..'' (где в
   Qмногоштрихов хранятся все корни кроме тех, что уже вытащили). Делаем так, пока Q не обратится в
   одну скобку с одним корнем какой-то кратности. Все.
** OK Интегрирование неравенств, следствия об оценке интеграла по модулю и теорема о среднем
   CLOSED: [2014-06-26 Thu 03:51]
   f <= g -> intf <= intg через определение площади, про модули через f ≤ |f|, про среднее через неравенство +
   терема о сохранении промежутка
** X Теорема Барроу, формула Ньютона--Лейбница, обобщение на случай кусочно-непрерывных функций
   Барроу: расписываем по определению Ф', разницу интегралов объединяем в один, пользуемся теоремой о среднем
   (плюс там +0, -0 аналогичны вплоть до знака)
   Ньютон-Лейбниц: мы знаем что ∫f = Fa - Fb, но Ф тоже первообразная и константа если что исчезнет
   ??? Кусочно-непрерывные функции – ну типа суммируем по нормальным участкам формулой Ньютона-Лейбница
   и все сокращается
** OK Свойства интеграла: аддитивность, линейность, интегрирование по частям, замена переменной (ЧЕРЕЗ НЬЮТОНА-ЛЕЙБНИЦА)
   CLOSED: [2014-06-26 Thu 03:54]
   Аддитивность халявно через аддитивность площади
   Линейность -- просто раскрыть через первообразные и Ньютона лейбница
   Интегрирование по частям как-то через Ньютона-Лейбница
   Замена переменной – просто говорим, что в левой части и правой части F(φ(q))-F(φ(p))
** OK Неравенство Чебышева для интегралов монотонных функций. Следствие для сумм
   CLOSED: [2014-06-26 Thu 10:29]
   (f(x)-f(y))(g(x)-g(y)) >= 0 последовательно интегрируем по x, y.
   В суммах вместо (b-a) просто n (до него суммируем).
** 2 Иррациональность числа $\pi$
   (4n-2)I_{n-1} - pi²I_{n-2}???
   Чет какая-то математическая магия
** OK Формула Валлиса
   CLOSED: [2014-06-26 Thu 10:32]
   Получаем рекурсивное соотношение для In=̆∫0->pi/2 (sinⁿ(x)) через отделение одной степени и по частям
   исходя из равенства I2n+1<=I2n<=I2n-1 и того, что четные члены pi/2 (I0=pi/2) приходим к
   двойному неравенству B < pi/2 < A, где A-B = pi/что-то, стремится короче к нулю. И такое.
** OK Формула Тейлора с остатком в интегральной форме
   CLOSED: [2014-06-26 Thu 03:58]
   Ну там короче расписываем по определению f(x) - f(x0) через t, интегрируем
   пр частям через единицу (∫1 = (x-t)), ...
** OK Интеграл как предел интегральных сумм
   CLOSED: [2014-06-26 Thu 03:58]
   Трансформируем слагаемые в неравенстве в ∫(что-нибудь) по куску от x до x(k+1), пихаем
   в неравенство, обнаруживаем, что это все меньше ∑∫|f(x)-f(ξ)| (занесли внутрь модуль),
   а еще меньше по Кантору какой-нибудь эпсилон, которую выносим из интеграла, его считаем
   и получаем чистую эпсилон (или * С)
** OK Теорема об интегральных суммах для центральных прямоугольников
   CLOSED: [2014-06-26 Thu 03:58]
   Разбиваем наш интеграл по кусочку на два относительно ξ, берем в них
   d(x-xk), d(x-x{k-1}), по частям, сокращаем, по частям то, что остальнось, потом еще раз
   по частям, выживает f(ξ)(xk-x{k-1}) + ∫f''(x)φ(x)dx. Запихиваем
   нашу радость в главное неравенство (сравнение интеграла и суммы), потом говорим что такая вот странная
   пирамидка из парабол слева и справа имеет высоту порядка δ²/8, все.
** OK Теорема о формуле трапеций, формула Эйлера--Маклорена
   CLOSED: [2014-06-26 Thu 03:58]
   Принимаем за tk полусумму xk, x{k+1}, интеграл по кусочку по частям с расчетом на ∫1 = (x-tk),
   потом остаток еще раз по частям с расчетом получить 0.5∫f''(x)(xk-x)(x{k-1}-x)dx, пихаем в основное
   неравенство, сокращаются члены кроме интеграла со второй производной, откуда мы, утверждая, что
   (xk-x)(x{k-1}-x)<δ²/4, получаем ответ.
   Для доказательства МаклорЕна мы на предпоследнем шаге (заменяя функцию на дельту) оставим все
   как есть, а (xk-k) заменим на {x},.. (оно и есть)
** OK Асимптотика частичных сумм гармонического ряда
   CLOSED: [2014-06-26 Thu 04:19]
   Берем ряд ∑1/n, его формула по Эйлеру-маклорЕну есть lnn+ (1+1/n)/2 + ∫... := lnn+γ+ε,
   где γ - постоянная Эйлера-Маскерони (предел разницы между суммой и lnn), а
   ε = 1/2n - 1/(12n²) + ... = 1/2n - ∑B_{2k}/(2k*n²ᵏ)
** OK Формула Стирлинга
   CLOSED: [2014-06-26 Thu 10:34]
   Сначала расписываем сумму логарифмов в ряд -> получаем нечто вроде n*ln(n)-n+0.5ln(n)+c+O(1), делаем exp,
   далее по формуле Валлиса исследуем sqrt(pi), домножаем на числитель, в знаменателе остается чистый
   факториал, в числителе дальше вытаскиваем 2^2k, тоже оставляем факториал, заменяем на нашу аппроксимацию,
   получаем приближенное значение для e^c ~ sqrt(2pi)
** OK Интегральное неравенство Гельдера
   CLOSED: [2014-06-26 Thu 04:21]
   Выбираем на отрезке ab нужное дробление, оснащение, дальше говорим, что
   dx - это некоторая дельта, а f(x), g(x) сопоставляем f(xk), g(xk), потом делим
   дельту в отношении (1/p):(1/q) (ничего не изменилось), одну даем f, другую g,
   а потом видим в этом чистое неравенство Гельдера для сумм, после которого предельно
   переходим по дельте.
** OK Интегральное неравенство Йенсена. Неравенство о ср. арифметическом и среднем геометрическом
   CLOSED: [2014-06-26 Thu 04:21]
   Действия похожи на аналогичные при доказательстве дискретного неравенства
   Йенсена: обозначаем нашу точку как некоторую c, доказываем что поскольку все
   фишки внутри меньше чем максимальная, а даже с максимальной влазит в промежуток, то и с лежит где надо.
   Выбираем опорную кривую в этой точке как ac+b, где с -- наша точка, а b=b(∫λdx), приравниваем интегралы
   и получаем то, что нам хотелось бы.
   Насчет среднего значения: логарифмируем наше неравенство и видим, что,
   приняв φ(x) = ln(f(x)), а λ(x) = 1/(b-a), наше неравенство есть неравенство Йенсена (только для
   вогнутой функции ln, то есть знак меняем): ln(∫λ(x)f(x)dx) >= ∫λ(x)ln(f(x))dx
** OK Теорема о вычислении аддитивной функции промежутка по плотности
   CLOSED: [2014-06-26 Thu 10:35]
   Определяем функцию F(x) = (x == p) ? 0 : Ф[p, x]; Рассматриваем производную этой функции
   как есть - (F(x+h) - F(x))/h = (Ф[p, x] + Ф[x, x+h] - Ф[p, x])/h - это подходит под
   требования f.
** OK Обобщенная теорема о плотности
   CLOSED: [2014-06-26 Thu 10:36]
   Определяем функцию F(x) через Ф[p,q];
   ̱mΔ ≤ (F(x+h)-F(x))/h ≤ MΔ  (Δ = [x, x+h])
   mΔ ≤ f(x) ≤ MΔ
   Вычли, получили что это почти одно и то же (разность - MΔ - mΔ -> 0 по условию)
   Нашли правую производную. Левая так же.
** OK Площадь криволинейного сектора: в полярных координатах и для параметрической кривой
   CLOSED: [2014-06-26 Thu 10:37]
   В первой части просто орудуем формулой площади сектора – 1/2 ρ²*Δφ, ограничиваем сектором
   радиуса минимум на отрезке и максимум.
   Во втором осознаем, что наши зависимости x(t) и y(t) -> φ = arctg(y(t)/f(t)),
   r = f(t)² + y(t)². Потом интегрируем все это руками и получаем то, что
   нужно (важно не забывать, что f и g - это сложные функции)
** OK Изопериметрическое неравенство
   CLOSED: [2014-06-26 Thu 05:11]
   Полагаем, что наша фигура задана неким путем в полярных координатах. Вернее
   мы короче построили полярные координаты, присобачив опорную кривую слева
   (а если не присобачивается, повернем фигуру, от этого ее площадь не изменится),
   затем интегрируем с помощью стандартной формулы для такой чепухи, разделяем
   интеграл на два относительно нулевого угла, второй пилим в те же границы,
   объединяем два под одними границами, говорим, что это все меньше диаметра²
   потому что наши радиусы перпендикулярны друг другу.
** 2 Вычисление длины гладкого пути
   ПОЧИТАТЬ ОПРЕДЕЛЕНИЕ ДЛИНЫ ПРО СУЖЕНИЕ\РАСТЯЖЕНИЕ
   Воспользуемся обобщенной теоремой о плотности:
   ]Δ < (a, b); m{iΔ}=min{t∈Δ}(|γ'{i}(t)|), M..=max.., mΔ = √m1Δ²+m2Δ²+..., MΔ = √M1Δ² + ...
   1) mΔ < |γ'(t)| < MΔ. Очевидно, средний член это √γ'1² + ...
   2) MΔ - mΔ -> 0 (if l(Δ) -> 0). MΔ -> |γ'|, so is mΔ.
   3) mΔ*l(Δ) ≤ Φ(Δ) ≤ MΔ*l(Δ). Берем растяжение γ -> γ~.Расписываем метрику между двумя точками t1, t2 через
      Эвклида (корень-квадраты). По Лагранжу пишем под корнем ∑(γ'(t{~i})(t1-t2))², что
      меньше √∑(MΔ²(t1-t2)²), а это есть MΔ*(t1-t2), ну и определим так ρ(γ~1, γ~2).
      => l(γ|_{Δ}) = ρ(γ1, γ2) = Φ(Δ) ≤ l(γ~|_{Δ}) = MΔ*l(Δ)
** OK Объем фигур вращения
   CLOSED: [2014-06-26 Thu 05:21]
   Вообще изи: ограничиваем фигуру двумя цилиндрами и пишем, что наш объем меньше
   чего-то или больше чего-то. Фактически из общей теоремы о плотности доказываем
   только второй пункт, первый и третий очевидны. Формулы запомнить!
   1) 2π∫xf(x)dx (MΔ = πmax(2x)max(f(x)))
   2) π∫f²(x)dx (MΔ = πmax(f²(x)))
** OK Простейшие свойства несобственного интеграла
   CLOSED: [2014-06-26 Thu 10:41]
   * Критерий Б-К (можем найти такое B, что для B < b₁ < b₂ < b : |∫_b₁^{b₂} f(x)dx| < ε
   * Можем наш интеграл вверху испорченный разбить на два, хороший и плохой, но без нижней
     части – берем обычные интегралы чуть поменьше размером и устремляем верхнюю границу к
     b-0 (если пределы не существуют, значит что-то расходится)
   * Линейность (полагаю, доказывается тоже предельным переходом на b-0)
   * Интеграл меньшей функции меньше. Тоже предельный переход, походу.
   * Интегрирование по частям
   * Композиция функций
** OK Признаки сравнения сходимости несобственного интеграла
   CLOSED: [2014-06-26 Thu 10:41]
   * Если Ф(A) - интеграл с верхней границей, а ∫f = lim{x->b-0}Ф(х), то
     ограниченность такого Ф эквивалентно сходимости интеграла
   * Признак сходимости на больше\меньше доказывается через первый пункт
     (просто подбираем нужные интегралы с переменным верхним пределом и
     сравниваем их).
     По поводу второго пункта – говорим, что f(x)/g(x) < a + ε, значит
     f < g(a+ε), навешиваем интегралы и обрашаемся к первой части признака.
     Аналогично с a-ε.
** OK Теорема об абсолютно сходящихся интегралах
   CLOSED: [2014-06-26 Thu 05:30]
   Доказываем три следствия. Из абсходимости сходимость следует тривиально.
   Из сходимости сходимость срезок следует по признаку сравнения (0 <=  f+ <= |f|)
   Из сходимости срезок следует сходимость модуля f (|f| = f+ + f-
** OK Признак Абеля--Дирихле сходимости несобственного интеграла
   CLOSED: [2014-06-26 Thu 10:41]
   * Абель – интегрируем по частям, чтобы вылезла F, которая по условию
     у нас ограничена. В первом слагаемом у нас ноль минус константа, а второй
     сходится абсолютно.
   * Абель-Дирихле – рассматриваем сумму интегралов ∫f(x)(g(x)-α)dx + α∫f(x)dx,
     где α – это конечный предел g(x). Тогда первый интеграл сходится по Абелю, а
   второй по условию.
** OK Изучение интеграла $\int_1^{\infty} \frac{\sin x\,dx}{x^p}$ на сходимость и абсолютную сходимость
   CLOSED: [2014-06-26 Thu 05:43]
   * Сходится по Дирихле – cos ограничен, а 1/xᵖ -> 0 монотонно
   * Сходится абсолютно при p > 1 (синус заменяем на 1)
   * Тут что-то хз
   * Для p ∈ [0, 1] имеем расходимость по Коши (арки растут), расходимость при замене
     синуса на синус квадрат и сравнением и раскрытием тригонометрии (там дирихле и абсолютно)
** 2 Интеграл Эйлера--Пуассона
   Исходим из неравенства (1-x²) ≤ e^{-x²} ≤ 1/(1+x²) (это вытекает из разложений eˣ и e⁻ˣ по
   Тейлору). Ну короче возводим все в степень n, берем от всего этого интеграл
   (слева от 0 до 1, справа тоже, но это меньше чем от 0 до +∞), а потом модифицируем то, что вышло:
   Слева делаем замену x = cost, справа x=ctgt, посередине t=√(n)x.
   Смотрим на это все внимательно и впихиваем слева и справа формулы Валлиса,
   доказываем, что левая √(n)(2n)!!/(2n+1)!! и правая √(n)π((2n-3)!!)/(2n-2)!!
   сходятся к √(π) / 2, ну и ок!
** OK Гамма функция Эйлера. Простейшие свойства
   CLOSED: [2014-06-26 Thu 10:45]
   * Определение
   * Сходимость при t > 0
   * Выпуклая на [0, +∞), а значит непрерывна кроме не более чем счетного множества точек
   * Формула понижения (похоже на !)
   * Г(0.5) = π, замена y=√x
   * Г(t) = Г(t+1)/t ~ 1/t (t->0)
   * -Γ'(1) = γ
** 2 Интеграл Дирихле
   Тут берем короче такие и говорим, что cost+cos2t+cos3t+...+cosnt=sin(n+0.5)t/(2sin(t/2)) - 1/2
   Отталкиваемся от этого, интегрируем от нуля до пи слева и справа, слева ноль
   Доказываем лемму что ∫sin(n+1/2)x*f(t) -> 0 если f ∈ C¹
   На основании этой леммы мы доказываем дифференцируемость в нуле разности нашего
   и нашего с упрощенным знаменателем (sin(x/2) -> x/2), а вообще эту разность доказываем
   Делаем какую-то нехитрую замену переменных в члене с t/2 и получаем что нужно
** OK Иррациональность числа $e$
   CLOSED: [2014-06-26 Thu 05:52]
   Пусть e=p/q, тогда p = eq,
   p(q-1)! = e(q!) = ∑q!/n! (0,inf) = sum(0, q) + sum(q+1, inf)
   sum(q+1, inf) = p(q-1)! - sum(0, q)
   Справа что-то целое, а слева что-то положительное -> слева > 1
   sum{q+1,inf}(q!/n!) = sum{m=1, inf}(q!/(q+m)!) < sum(1/(q+m)!) < sum(1/(q+1)ᵐ)
   По формуле геом прогрессии b₁/(1-q) сумма последнего есть 1/q < 1. -><-
** OK Свойства рядов: линейность, свойства остатка, необх. условие сходимости, критерий Больц-Кош
   CLOSED: [2014-06-26 Thu 05:54]
   * Линейность изи, свойство остатка изи – все доказывается через предельный переход
   * Свойства остатка вроде тоже изи
   * Необходимое условие сходимости вроде абсолютно очевидно
   * Критерий БК определяется
** OK Признак сравнения сходимости положительных рядов
   CLOSED: [2014-06-26 Thu 10:47]
   * Лемма о том, что сходимость равноценна ограниченности конечных сумм (ведь у них
     есть супремум)
   * Сходимости на больше-меньше доказываются с этой леммой (если у нас S_n не
     ограничена, а есть что-то еще большее, то о какой сходимости речь?)
   * Пилим асимптотическое неравенство и применяем первую часть теоремы на
     больше-меньше
** OK Признак Коши сходимости положительных рядов (lite)
   CLOSED: [2014-06-26 Thu 06:05]
   * Поскольку √an ≤ q, а ∑qⁿ сходится по определению 0 < q < 1
   * Расходимость следует из основного свойства рядов (a(n+1) > an)
** OK Признак Коши сходимости положительных рядов (pro)
   CLOSED: [2014-06-26 Thu 06:05]
   * Пусть этот верхний предел α, но ∃q: α < q < 1, тогда эта q – из lite
   * Если верхний предел больше единицы, то есть такие n, что Kn > 1, lite
** OK Признак Даламбера сходимости положительных рядов (lite)
   CLOSED: [2014-06-25 Wed 16:00]
   Берем по определению .. < q < 1, пишем k таких членов, перемножаем, получаем a{N0+k} ≤ a{N0}*qᵏ,
   переход по k, справа конст*сходится, слева сходится тому що справа сходится
** OK Признак Даламбера сходимости положительных рядов (pro)
   CLOSED: [2014-06-25 Wed 16:00]
   Вообще отсылки к lite по принципу (а начиная с некоторого места как раз
   выполняется то, что в lite)
** OK Признак Раабе сходимости положительных рядов
   CLOSED: [2014-06-26 Thu 06:05]
   * Лемма о том, что при выполнении a{n+1}/an < b{n+1}/bn НСНМ расходимость А
     приводит к расходимости Б и наоборот.
   * Лемма о том, что Rₙn для ряда Дирихле есть p (1/nᵖ)
   * Сравнили, пришли к 1 лемме, по 2 лемме больший ряд сходится.
** OK Интегральный признак Коши сходимости числовых рядов
   CLOSED: [2014-06-26 Thu 06:06]
   Вообще пушка а не теорема. Рисуем короче такую монотонную функцию, график,
   потом пирамидки и утверждаем что все ε помещаются в первый столбец этой
   пирамидки, а значит все ок
** OK Признак Лейбница
   CLOSED: [2014-06-26 Thu 06:07]
   Короче докажем, что существует конечный предел сумм частичных сумм:
   S{2n}: S{2n} = S{2n-2} + (C{2n-1}-C{2n}) – больше C{2n}, но меньше C1, потому
   что S{2n} = C1 - (C2 - C3) - (C4 - C5) - ...
** OK Признаки Дирихле и Абеля сходимости числового ряда
   CLOSED: [2014-06-26 Thu 10:50]
   Раскладываем нашу сумму по преобразованию Абеля:
   первый член стремится к нулю (огр*бескмал), второй сходится по какому-нибудь
   даламберу
** OK Теорема о группировке слагаемых
   CLOSED: [2014-06-26 Thu 06:12]
   * Отмечаем что частичная сумма S(B)N = S(A)M, делаем предельный переход
   * Второе тоже как-то. Не знаю как кстати. (Кохась сказал что изи, просто чет пописать)
** OK Теорема о перестановке слагаемых
   CLOSED: [2014-06-26 Thu 06:13]
   Берем эту нашу последовательность B, показываем что это то же самое что и
   A, только индексы другие. Вся эта сумма ≤ Sₘm, где m - максимальный из
   приведенных индексов. Значит S(b)_N ≤ S(a)ₘm, то есть Sb < Sa. Все ок
   Аналогично с A<B
** OK Теорема Стокса--Зайдля о непрерывности предела последовательности функций. Следствие для рядов
   CLOSED: [2014-06-26 Thu 10:50]
   .|f(x) - f(c)| ≤ |f(x) - fn(x)| + |fn(x)-fn(c)| + |fn(c)-f(c)|
   Из равномерной сходимости первое и последнее (как частное от 1) есть e/3,
   а второе верно из непрерывности в (.)c
   Насчет рядов – частичные суммы сходятся равномерно к S(x), они все непрерывны
   в точке x₀, значит S тоже
** OK Метрика в пространстве непрерывных функций на компакте, его полнота
   CLOSED: [2014-06-26 Thu 06:16]
   Короче у нас есть сходимость по Коши (через два индекса), а мы хотим обычную.
   Мы расписываем k штук таких определений, в каждом из которых фигурирует |fm(x)-f{n+k}(x)|<ε
   Устремляем k куда надо, выходит |fm(x)-f(x)| < ε, что и нужно
** OK Теорема о предельном переходе под знаком интеграла. Следствие для рядов
   CLOSED: [2014-06-26 Thu 10:51]
   ̣∫f{n}(x) -> ∫f(x) (f{n}̣̣⇉f):
   смотрим на разность |∫f{n}(x) - ∫f(x)| < |∫(fn(x)-f(x))| ≤ |sup(fn-f)*(b-a)| ≤ ρ(fn, f)(b-a) -> 0
   Для рядов – просто оборачиваем в предел частичных сумм, потому что
   интеграл аддитивен.
** X Теорема о предельном переходе под знаком производной. Следствие для рядов
   Типа докажем, что если fn' ⇉ φ, то f' = φ: возьмем у равномерной сход. интеграл
   по Ньютонолейбницу, получим fn(x)-fn(x0) = ∫φ, осталось сделать предельный переход по
   x и подиффиренцировать
   для рядов у меня нету
** OK Изучение равномерной сходимости ряда $\sum\frac{nx}{1+n^4x^2}$, $x\in [0,+\infty)$
   CLOSED: [2014-06-26 Thu 10:53]
   Мы проверяем отрицанием критерия Больцано-Коши, а конкретнее берем n = n, p = n (n, n + n),
   x = 1/n² и подберем ε (1/17 штоле)
** OK Теорема о предельном переходе в суммах
   CLOSED: [2014-06-26 Thu 10:55]
   * Тот факт, что последовательность an сходится (функциональная последов.
     для выделенного x0), сверяем по Больцано-Коши: |S{n+p}-Sn| ≤ |S{n+p} - S{n+p}(x)| +
     ... + ...; Средний член сходится по равномерной сходимости функ. ряда, а крайние
     из условия (lim{x→x₀}(Un) -> an)
   * Докажем, что не важно, сначала ли найти сумму ряда, а потом устремить x -> x₀
     или сначала устремить в каждом члене а потом найти сумму такого ряда:
     нам нужна просто непрерывность в этой точке, ну и заткнем плохую точку an
** 2 Теорема о перестановке двух предельных переходов
   В отличии от предыдущей теоремы, требуется доказать, что все равно,
   Сходится ли функция F равномерно к S, а потом смотрим предел S при x→x₀ или
   сначала впиливаем ряд состоящий из пределов функций F в x₀, а потом берем
   предел ряда:
   Блин, я не знаю. Вроде бы у нас fn сходится, ну глянем на ее частичные суммы, они Fn,
   нужно переопределить U,
** OK Признак Дирихле равномерной сходимости функционального ряда
   CLOSED: [2014-06-26 Thu 10:59]
   Тут все почти как в обычном дирихле, разница только в расширенной версии Абеля
   и все остальное так же
** OK Теорема о круге сходимости степенного ряда
   CLOSED: [2014-06-26 Thu 06:49]
   Просто берем по Коши все, что внутри ряда (верхний предел)
** 2 Теорема о непрерывности степенного ряда
   * Можем выбрать из круга сходимости круг поменьше, внутри которого все сходится
     равномерно: юзаем признак Вейерштрасса: подбираем ряд побльше и доказываем его
     сходимость по Коши – ∑|an|rⁿ, где |an(z-z₀)ⁿ|<r<R по условию.
   * Кривое доказательство, а разве не правда, что замкнутый шар радиусом R
     замкнут и ограничен, а значит компактен => любая сходящаяся в себе последовательность сходится
     значит можем найти там каждую точку непрерывной?
     Почти! Суть в том, что на каждом замкнутом круге есть равномерная сходимость, а значит
     по Стоксу-Зайдлю сходится на каждом компакте. Просто для каждой точки открытого круга возьмем компакт
     побольше.
** 0 Теорема о дифференцировании степенного ряда
   * Радиус сходимости не меняется – очевидно по формуле Адамара
   *
** OK Единственность разложения функции в ряд
   CLOSED: [2014-06-26 Thu 10:59]
   Ну дак это изи - конструктивно ищем эти члены, все заходит
   (дифференцируем сколько надо раз нашу функцию, новая функция = новый член ряда)
** 2 Разложение бинома в ряд Тейлора
   Что-то около пытаемся посчитать h'(x), где h(x) = S/(x-a)ⁿ – наш полином,
   в числителе получается S'(x-1) - αS, что так и есть, значит h – константа,
   посчитаем ее для 0 – s/(x-a)ⁿ = 1
** 0 Пример функции, у которой ряд Тейлора расходится при $x\ne0$
   e⁻ᵗ/(1-x²*t)
   Оно есть в тетради, но это не отменяет факта (нихуянепонел)
   А кохась пояснил, мы просто хотим показать, что эта штука расходится, оцениваем, получаем
   что там что-то типа с факториалом расходящееся + о(этого всего)
