#+TODO: X 0 1 2 | OK
#+TITLE: Notes on functional analysis (given by Dodonov)
#+DATE: 2015-16, term 5-6

* Tickets
  https://pp.vk.me/c624829/v624829650/b3de3/xDXw-F664tk.jpg
* Definitions list
  1. Метрика, метрическое пространство
  2. Предел по метрике
  3. Топологическое пространство, топология
  4. Открытое множество, замкнутое множество
  5. Предел в смысле ТП
  6. Открытый шар
  7. Метрика Урысона
  8. Внутренность, граница, замыкание
  9. МП полнота
  10. Всюду плотность, не плотность
  11. Категории по Бэру
  12. Компакты и предкомпакты
  13. Норма, нормированное пространство, предел в НП
  14. Эквивалентность норм
  15. Линейное подмножество и подпространство
  16. Банахово пространство
  17. Унитарное пространство, примеры
  18. Неравенство Шварца
  19. УП как частный случай НП
  20. Ортогональность, равенство пифагора
  21. Ортонормированная система векторов
  22. Ортогональный рфд
  23. Фурье: коэффициент, ряд
  24. Наилучшее приближение
  25. Гильбертово пространство, примеры
  26. Полная, замкнутая ОНС
  27. Сепарабельность
  28. Разложение в прямую сумму
  29. Счетно-нормированное пространство, предел
  30. Метрика в СНП
  31. Пример СНП
  32. Монотонная система полнунорм, эквивалентность и существенность
  33. Поглощение, радиальность, закругленность
  34. Функционал Минковского
  35. Фактор-множество, коразмерность
  36. Гиперплоскость, линейный функционал, ядро
  37. Топологическое векторное пространство, место в систематике
  38. База окрестностей нуля
  39. Линейный оператор (непр., огр., норма)
  40. Пространство линейных операторов
  41. Сопряженное пространство
  42. Непрерывно обратимый оператор
  43. Range, априорная оценка
  44. Резольвентный оператор, множество, cпектр
  45. Спектральный радиус
  46. Сопряженный оператор
  47. Ортогональные дополнения
  48. Вполне непрерывность, относительная компактность
* X Метрические пространства
** OK Метрика, метрическое пространство                          :definition:
   CLOSED: [2016-01-21 Thu 23:28]
   X, ρ: X×X → ℝ+ -- метрика, если:
   1. ρ(x, y) ≥ 0; ρ(x, y) = 0 ⇔ x = y
   2. ρ(x, y) = ρ(y, x)
   3. ρ(x, y) ≤ ρ(x, z) + ρ(z, y)

   Метрическое пространство -- пара <X, ρ>.
** OK Предел по метрике                                          :definition:
   CLOSED: [2016-01-21 Thu 23:29]
   x = lim(xₙ) ⇔ ρ(xₙ, x) → 0
** 2 Топологическое пространство, топология                      :definition:
   Топологическое пространство (ТП) -- пара <X, Τ>, где X --
   множество, T ⊃ 2ˣ -- топология, если выполнено:
   1. Замкнутость T по объединению
   2. Замкнутость T по конечному пересечению
   3. X, ∅ ∈ T
** 2 Открытое множество                                          :definition:
   Множество открыто, если принадлежит топологии T.
** 1 Предел в смысле ТП                                          :definition:
   <X,T>
   x = lim(xₙ) ⇔ ∀G ∈ T : x ∈ G, ∃N: ∀n > N xₙ ∈ G
** 2 Замкнутость через открытость                                :definition:
   G -- открытое в T, тогда F = X \ G замкнутое
** 1 Открытый шар, представимость T                              :definition:
   * Bᵣ открытый шар в центре a = {x: ρ(x, a) < r}
   * T = {∪Bᵣ(a)}
** 2 Связь МП и ТП                                                :statement:
#   b ∈ Bᵣ₁(a₁) ∩ Bᵣ₂(a₂) ⇒ ∃ r > 0, Bᵣ(b) ⊃ (Bᵣ₁(a) ∩ Bᵣ₂(a))
   Будем называть G открытым, если ∀x ∈ G, ∃Bᵣ(x) ⊂ G. Множество всех
   открытых множеств будет образовывать топологию. Открытые шары в МП
   -- открытые множества.

   В этом смысле метрические пространства оказываются частным случаем
   топологических.
** 2 Примеры МП (ℝ, ℝⁿ, ℝ∞, м.Урысона)                              :example:
   1. ℝ, ρ(x, y) = |x - y|
   2. ℝⁿ, x~ = (x₁...xₙ) ∈ ℝⁿ
      ρ(x~, y~) ≡ √(∑{n}(xᵢ - yᵢ)²)
      αx~ = (αx₁...αxₙ)
      x~ + y~ = (x₁ + y₁, ...)
      xₙ~ → x~ ⇔ ∀j=1..n xⱼᵐ → xⱼ
   3. ℝ∞, xₘ~ → x~ ≡ ∀i=1,2,3..., xⱼᵐ → xⱼ
      Метрика Урысона:
      ρ(x~, y~) ≡ ∑{∞}(1/2ⁿ * |xₙ - yₙ|/(1 + |xₙ - yₙ|), где
      φ(t) = t/(1+t), то есть ρ(x~, y~) = ∑{∞}(1/2ⁿ * φ(|xₙ-yₙ|)).

      Кстати, для φ верно:
      Φ(t₁ + t₂) ≤ φ(t₁) + φ(t₂)

      ρ(xₘ~, x~) → 0 ⇔ ∀j xⱼᵐ → xⱼ
      Таким образом ℝᵐ метризуемо.
   4. Дискретная метрика
      ρ(x,y) = if x = 0 then 0 else 1
      xₘ → x, ε = 1/2, ∃M : ∀m > M ⇒ ρ(xₘ,x) < 1/2 ⇒ ρ(xₘ, x) = 0 ⇒
      xₘ = x
      То есть в такой метрике сходятся только последовательности,
      стабилизирующиеся после некоторого элемента -- стационарные.
** OK Внутренность, замыкание, граница                           :definition:
   CLOSED: [2016-01-21 Thu 23:51]
   (X, T), ∀A ⊂ X:
   1. Int(A) ≡ ∪{G | G ⊂ A, G открытое}
   2. Cl(A)  ≡ ∩{F | F ⊃ A, F замкнутое}
   3. Fr(A)  ≡ Cl(A) \ Int(A)

   По аксиомам топологии ∀A Int(A) открытое, Cl(A) замкнутое
** 2 Расстояние до множества, между множествами                  :definition:
   ρ(x, A) ≡ inf{ρ(x, a) | a ∈ A}
   ρ(A, B} ≡ inf{ρ(a, b) | a ∈ A, b ∈ B}
** 1 Непрерывность расстояния до множества                            :lemma:
   Пусть f(x) ≡ ρ(x, A), x ∈ X.
   Тогда f непрерывно на X

*** Скетч
    Показать, что ∀x,y ∈ X, |f(x)-f(y)| ≤ ρ(x,y) с помощью ε → 0.
*** Доказательство
    ∀x, y ∈ X, a ∈ A: f(x) = ρ(x, A) ≤ ρ(x, a) ≤ ρ(x, y) + ρ(y, a)

    ∀ε > 0  ∃aₑ ∈ A : ρ(y, aₑ) < ρ(y, A) + ε = f(y) + ε

    f(x) < ρ(x, y) + f(y) + ε
    ε → 0,
    f(x) ≤ f(y) + ρ(x, y).

    Аналогично по симметричности
    f(y) ≤ f(x) + ρ(x, y)

    Отсюда: |f(x) - f(y)| ≤ ρ(x, y)
** X Связь Cl, ρ                                                  :statement:
   x ∈ Cl(A) ⇔ ρ(x, A) = 0

*** Доказательство
    Рассмотрим метрическое пространство с точки зрения отделимости
    множеств друг от друга открытыми множествами.
    x ≠ y, r = ρ(x, y) > 0
    B(x), B(y) -- 2/3, r/3 соответственно.
    Выполнена аксиома Хаусдорфа.
** 2 Нормальность МП                                                :theorem:
   Любое МП -- нормальное пространство.
   ∀ F₁, F₂ ∈ X (F₁ ∩ F₂ = ∅, оба замкнутые)
   ∃ открытые непересекающиеся G₁ G₂, что F₁ ⊂ G₁, F₂ ⊂ G₂.

*** Доказательство
    g(x) = ρ(x, F₁) / (ρ(x, F₁) + ρ(x, F₂))
    Их предыдущего утверждения понятно, что функция корректно
    определена. Ее непрерывность тоже можно как-то показать.

    x ∈ F₁, Cl(F₁) = F₁
    ρ(x, F₁) = 0, g(x) = 0
    x ∈ F₂, g(x) = 1
    (-∞, 1/3); (2/3, +∞)

    G₁ = g⁻¹(-∞, 1/3)
    G₂ = g⁻¹(2/3, ∞)

    Тогда G₁ G₂ -- требуемые открытые множества.
** OK МП-Полнота                                                 :definition:
   CLOSED: [2016-01-22 Fri 00:32]
   ρ(xₙ, xₘ) → 0 ⇒ ∃x = lim xₙ
** 2 Принцип вложенности шаров                                      :theorem:
   X -- полное МП, V_2m : V_2n+1 ⊂ V_2n, 2n → 0 -- система замкнутых
   шаров.

   Тогда ∩V_2n = {a}.

*** Доказательство
    ∃ bₙ -- центр V_2n шаров, тогда ∀m ≥ n, bₘ ∈ V_2n.
    Тогда ρ(bₙ,bₘ) ≤ 2ₙ → 0 по условию.

    Очевидно, что существует точка a ∈ шары (по полноте ℝ), одна
    единственная в силу замкнутости шаров.
** OK Всюду плотность, всюду не плотность                        :definition:
   CLOSED: [2016-01-22 Fri 00:50]
   * А всюду плотно в X если X -- МП, A ⊂ X, Cl(A) = X.
   * А нигде не плотно, если Int(Cl(A)) = ∅.

   Легко показать, что в МП нигде не плотность значит, что в любом
   шаре V ∃V' ⊂ V, что в V' нету точек множества A.

   Пример: Int(ℝ) = ∅.
** 2 Категории по Бэру                                           :definition:
   X -- множество 1 категории по Бэру, если его можно записать в виде
   не более чем счетного объединения Xₙ, где каждый xᵢ не плотен в X.
   Любой другой X -- множество 2 категории.
** 1 Теорема Бэра о категориях                                      :theorem:
   Полное МП является множеством 2 категории. (в себе).

*** Скетч
    От противного. Будем применять определение нигда не плотного
    каждый раз в предыдущем множестве Vᵢ. Найдем пересечение вложенных
    шаров a и поймем, что оно должно принадлежать хоть какому-то X_i.
*** Доказательство
    От противного: пусть X первой категории, тогда:
    X = ∪Xₙ, Xₙ нигде не плотно в X.
    Отсюда ∀V X₁, ∃V₁ ⊂ V, V₁ ∩ X₁ ≠ 0.
    X₂, V₂ ⊂ V₁ : V₂ ∩ X₂ ≠ 0, r₂ ≤ r₁/2.
    ...

    По индукции получаем {Vᵢ}, r(Vᵢ) → 0, тогда a = ∩Vᵢ по принципу
    вложенности шаров.

    Тогда ∃ N₀, что a ∈ X_N₀, который X_N₀ ∩ V_N₀ = ∅, a ∈ V_r₀, что
    приводит к противоречию, потому что a ∈ ∩.
** 2 Следствие из теоремы Бэра о категориях                           :lemma:
   Полное МП без изолированных точек несчетно

*** Доказательство
    Предположим обратное, то есть счетность множества. Тогда каждая
    точка нигда не плотна в нем ⇒ у него 1 категория, что протиоречит
    теореме Бэра. Этому выбору может помешать только изолированность,
    так как если все точки изолированны, то любая сходящаяся в себе
    посл. сходится.
** 1 Компакты и предкомпакты                                     :definition:
   Множество K, удовлетворяющее обеим аксиомам -- компакт, а только
   второй -- предкомпакт:
   1. K -- замкнуто (K = Cl(K))
   2. xₙ ∈ K, ∃ n₁ < n₂ < ...
      xₙⱼ -- сходится в K по метрике ρ
** 1 Теорема Хаусдорфа                                              :theorem:
   X -- полное МП, K ⊂ X, K замкнуто.
   Тогда:
   K компактно ⇔ K вполне ограничено

   Вполне ограниченность: ∀ε>0 ∃a₁..aₙ, что ∀b∈K ∃aⱼ ρ(b,aⱼ) < ε;
   построение для вполне ограниченности называется конечной ε-сетью.

*** Скетч
    Слева направо ищем шарики с беск. элементами и сужаем Kᵢ.

    Справа налево от противного по определению строим {xᵢ}
    инкрементально и она не сходится в себе
*** Доказательство
    1. Будем доказывать справа налево
       Пусть K вполне ограничено
       Хотим: xₙ ∈ K => xₙₖ сходится.

       Выберем одпоследовательность εₖ → 0.
       * Рассмотрим ε₁; по вполне ограниченности строим e₁-сеть, тогда
         из ее определения ясно:
         K покрыто конечной системой замкнутых шаров Vⱼ с радиусом ε₁.
         K ⊂ ∪Vⱼ

         Шаров конечное множество, тогда в каком-то ∞ элементов xₙ.
         Назовем такой шар Vⱼ₀.
         K₁ = Vⱼ₀ ∩ K, K₁ вполне ограниченный, diam(K₁) ≤ 2ε₁.
       * Аналогично строим:
         ε₂, K₁ ⊂ ∪Vⱼ, радиуса ε₂
         K₂ = Vⱼ₀ ∩ K₁, diam K₂ ≤ 2ε₂.
       * По индукции получаем {Kᵢ} -- систему вложенных замкнутых
         множеств, в силу полноты пространства с непустым
         пересечением.
         Тогда выберем подпоследовательность любую, в которой берем
         элементы из шаров.
    2. Слева направо.
       Пусть K -- компакт.
       Хотим: ∀ε ∃ конечная ε-сеть.

       От противного: ∃ε₀, что ∄конечной ε-сети.
       * ∀x₁ ∈ K, ∃x₂ ∈ K, ρ(x₁, x₂) > ε₀.
         Если это утверждение неверно, то система из x₁, x₂ --
         конечная ε₀-сеть.
       * {x₁,x₂} ∃x₃, ρ(x₃, xᵢ) > ε₀, i ∈ {1, 2}
       * Так по индукции получаем xₙ, из которой не выделить
         сходящейся подпоследовательности, а значит K не компакт.
* 1 Нормированные пространства
** 2 Нормированное пространство, норма                           :definition:
   Нормированное пространство -- (X, ∥ ∥), где второе -- норма:
   φ: X → ℝ -- норма на X (φ(x) = ∥x∥), если:
   1. φ(x) ≥ 0; φ(x) = 0 ⇔ x = ∅
   2. φ(αx) = |α|φ(x)
   3. φ(x+y) ≤ φ(x) + φ(y)

   Заметим, что в нормированных пространствах метрика порождается
   нормой, то есть:
   ρ(x, y) ‌≡ ∥x - y∥.
   Тогда НП -- частный случай МП.
** 2 Пределы в НП                                                :definition:
   x = lim(xₙ) ⇔ ρ(xₙ, x) → 0 ⇔ ∥xₙ - x∥ → 0.
** 2 Непрерывность линейных операций в топологии НП                   :lemma:
   В топологии НП линейные операции на X непрерывны.

*** Доказательство
    1. xₙ → x, yₙ → y,
       ∥(xₙ + yₙ) - (x + y)∥ ≤ ∥xₙ - x∥ + ∥yₙ - y∥ → 0
    2. αₙ → α, xₙ → x
       ∥αₙxₙ - αx∥ = ∥αₙ(xₙ - x) + x(αₙ - α)∥ ≤
       ≤ |αₙ|*∥xₙ - x∥ + (αₙ - α)∥x∥ → 0
** 1 Примеры НП (lₚ, Lₚ)                                            :example:
   1. ℝⁿ, метрики l₁, l₂, l∞ -- в общем случае по lₚ варианту:
      ∥x∥ₚ = (∑(xₖ)ᵖ)^(1/p).
      ∥x∥∞ = sup{x₁...xₙ}
   2. C[a, b] -- функции непрерывные на отрезке.
      ∥f∥ = max{x∈[a,b]}|f(x)|
   3. Lₚ(E) -- известный пример, метрика -- (∫X |f|ᵖ)^(1/p)
** 1 Эквивалентность норм                                        :definition:
   Нормы φ₁ и φ₂ экивалентны (φ₁ ~ φ₂), если у них одинаковая
   сходимость, то есть ∀{xₙ} (xₙ →φ₁ x) & (xₙ →φ₂ x).
   Проверка на экивалентность также можно сделать следующим образом:
   ∃a,b > 0, ∀x∈ X a∥x∥₁ ≤ ∥x∥₂ < b∥x∥₁, где нижний индекс -- номер
   метрики.
** 2 Пример эквивалентных метрик в ℝⁿ                               :example:
   Построим единичную окружность по метрикам l₁, l₂, l∞.
   Нетрудно проверить, что все они эквивалентны, то есть множества
   сходимых по ним последовательностей равны.
** 1 Теорема Рисса                                                  :theorem:
   dim(X) < +∞, тогда любые 2 нормы в X эквивалентны.

*** Скетч
    Покажем a∥x∥₁ ≤ ∥x∥ ≤ b∥x∥₁ для евкл. нормы. Правое ≤ по н-ву
    Коши. Левое через f(α₁...αₙ) ≡ ∥∑αₖeₖ∥, ед. сферу и Вейерштрасса.
*** Доказательство
    Возьмем {eᵢ} -- ЛНЗ базис из X.
    ∀x ↔ (α₁...αₙ) = α~ -- коээффициенты по базису.
    Пусть ∥ ∥ -- норма в X.

    ∥x∥₁ ≡ √(∑αₖ²)
    будем показывать a∥x∥₁ ≤ ∥x∥ ≤ b∥x∥₁ из определения экв. норм.

    1. ∥x∥ ≤ (неравенство треугольника) ≤ ∑∥eₖ∥*|αₖ| ≤ (Коши) ≤
       ≤ √(∑∥eₖ∥²) * √(∑αₖ²) = {первое константа b} = b*∥α~∥ =
       = b*∥x∥₁.

       ∥x∥ ≤ b*∥x∥₁.
    2. f(α₁...αₙ) ≡ ∥∑αₖeₖ∥;
       Тогда |f(α~ + Δα~) - f(α~)| = | ∥∑αₖeₖ + ∑Δαₖeₖ∥ - ∥∑αₖeₖ∥ | ≤
       ≤ ∥∑Δαₖeₖ∥ ≤ ∑∥eₖ∥*|Δαₖ| → 0.
       Значит f непрерывна в ℝⁿ.

       S₁ ≡ {x | ∑|αₙ|² = 1} -- единичная сфера.
       По теореме Вейерштрасса S₁ -- компакт.
       f непрерывна на S₁, тогда по теореме Вейерштрасса существует
       минимум: ∃α'~ ∈ S₁, что f(α'~) -- минимум, то есть все остальные
       f(α~) ≥ f(α'~).

       f(α'~) ≠ 0. Если бы была равна, тогда ∥∑α'ₖeₖ∥ = 0, а отсюда по
       ЛНЗ все αᵢ = 0, но α'~ ∈ S₁, там таких нету.

       Отсюда f(α'~) = m > 0, и тогда: ∥x∥ = ∥∑αₖeₖ∥ = f(α~) =
       √(∑αₖ²) * ∥ ∑(αₖ/√(∑αₖ²))eₖ ∥ ≥ m * ∥x∥₁. (то, что вынеслось
       под большой модуль, как раз в S₁).

       m и есть искомое a.
** 2 Линейное подмножество, линейное подпространство             :definition:
   1. Линейное подмножество -- множество точек замкнутых относительно
      операций умножения на скаляр и сложения.
   2. Линейное подпространство -- замкнутое линейное подмножество.
** 2 Следствие из теоремы Рисса о замкнутости                       :theorem:
   X -- НП, Y -- линейное подмножество X, dim Y < +∞.
   Тогда Y = Cl(Y), то есть Y замкнуто.

*** Скетч
    Сходимость эквивалентна сходимости по l₂, которая сходится
    покоординатно. Тогда предел -- это ЛО векторов.
*** Доказательство
    y = L(e₁...eₙ) -- ЛНЗ набор = {∑αᵢeᵢ | αᵢ ∈ ℝ}.
    yₘ ∈ Y.
    Хотим: yₘ → y ⇒ y ∈ Y.

    ∥yₘ - y∥ → 0 ⇒ ∥yₘ - yₚ∥ →{mp → ∞}→ 0.
    Y конечномерно, тогда по теореме Рисса все нормы эквивалентны.

    ∥y∥₀ ≡ √(∑αᵢ²) -- определим такую норму.
    По теореме Рисса ∥ ∥ ~ ∥ ∥₀.

    ∥yₘ - yₚ∥ → 0 ⇒ ∥yₘ - yₚ∥₀ → 0. Заметим, что ∥yₘ - yₚ∥ ∈ Y.
    Тогда пусть α~ = (α₁...αₙ) ∈ ℝⁿ.
    Отсюда yₘ = ∑αᵢ^(m) * eᵢ, где верхний индекс -- номер α~., а
    нижний -- координата α~.

    Тогда есть покоординатная сходимость:
    ∀i ∈ 1..n  |αᵢ^m - αᵢ^p| → 0.
    Тогда αₘ~ = (α₁^m...αₙ^m) → α*.
    y* = ∑αᵢ*eᵢ ∈ Y.

    ∥yₘ - y∥ → 0.
    ∥yₘ - y*∥ → 0 (следует из ∥yₘ - y*∥₀ → 0 по экв. норм).
    Тогда y = y*, и поскольку y* ∈ Y, y ∈ Y.
** 2 Банахово пространство                                       :definition:
   Банахово пространство -- НП, полное в смысле метрического
   пространства. Сокращенно -- B-пространство.
** 2 Абсолютная сходимость в B-пространствах                          :lemma:
   X -- B-пространство. Тогда ∑∥xₙ∥ → 0 ⇒ ∑xₙ сходится.

*** Доказательство
    ∥Sₙ - Sₘ∥ = ∥∑{m+1..n}xₖ∥ ≤ ∑∥xₖ∥ →{n,m → ∞}→ 0.
    Отсюда существует предел Sₙ. что значит сходимость ∑xₙ.
** 2 Лемма Рисса о перпендикуляре                                   :theorem:
   * X -- НП.
   * Y -- собственное подпространство (линейное замкнутое множество)

   Тогда ∀ε ∈ (0,1), ∃zₑ ∈ X:
   1. zₑ ∉ Y
   1. ∥zₑ∥ = 1
   2. ρ(zₑ, Y) > 1 - ε

*** Скетч
    zₑ = (x - yₑ)/∥x - yₑ∥. Остальное доказать через расстояние до
    множества.
*** Доказательство
    ∃x∉Y, d = ρ(x, Y). Тогда d > 0.
    * Если d = 0, то ∃yₙ ∈ Y: ∥x - yₙ∥ < 1/n.
      Y замкнутое, тогда x ∈ Y, что противоречит условию.

    Возьмем ε ∈ (0, 1), 1/(1 - ε) > 1.
    По определению расстояния:
    ∃yₑ ∈ Y: ∥x - yₑ∥ < d/(1 - ε)
    zₑ = (x - yₑ)/∥x - yₑ∥, ∥zₑ∥ = 1;
    ∀y ∈ Y, ∥zₑ - y∥ = ∥(x - yₑ)/∥x - yₑ∥ - y∥
    = (∥x - (yₑ + ∥x - yₑ∥ * y)∥ / ∥x - yₑ∥)
    В последнем выражени числитель ≥ d.
    Знаменатель < (1/1-ε)d.
    Отсюда: ∥zₑ - y∥ > 1 - ε.
** 1 Некомпактность единичное сферы в бесконечномерном пространстве :theorem:
   Пусть dimX = +∞.
   S -- единичная сфера.
   Тогда S -- не компакт.

*** Доказательство
    ∀x₁ ∈ S, Y₁ = L(x₁),
    Y -- конечномерное линейное множество, значит оно замкнуто в X и
    подпространство.
    По теореме Рисса ∃x₂ ∈ S, что ∥x₂ - x₁∥ > 1/2.

    Y₂ = L(x₁,x₂). Y₂ -- собственное подпространство.
    Тогда ∃x₃ ∥x₃ - xⱼ∥ > 1/2, j={1,2}.

    Процесс не остановится в силу dimX=+∞.

    Получим {xₙ ∈ S | ∥xₙ - xₘ∥ > 1/2, n ≠ m}.
    Тогда не можем выделить сходящуюся подпоследовательность.
    Тогда сфера -- не компакт.
* 2 Унитарные пространства
** 2 Унитарное пространство                                      :definition:
   X -- линейное множество над полем ℝ, φ: X×X → ℝ.
   φ удовлетворяет свойствам:
   1. φ(x, x) ≥ 0. φ = 0 ⇔ x = 0.
   2. φ(x, y) = φ(y, x)
   3. φ(αx + βy,z) = αφ(x, z) + βφ(y, z).

   φ называется скалярным произведением, нотация: <x,y> ≡ φ(x,y).
   Пара (X, <,>) -- унитарное пространство.
** 2 Пример унитарного пространства                                 :example:
   ℝⁿ: <x,y> = ∑{i=1..n}xᵢyᵢ.
** 2 Неравенство Шварца                                               :lemma:
   ∀x,y ∈ X, |<x,y>| ≤ √(<x,x>) * √(<y,y>).

   Отметим, что для ℝⁿ неравенство Шварца есть неравенство Коши для
   сумм:
   * |∑aᵢbᵢ| ≤ √(∑aᵢ²) * √(∑bᵢ²)

*** Доказательство
    ∀λ ∈ ℝ, f(λ) ≡ <λx + y, λx + y> ≥ 0 (по аксиоме).
    f(λ) = λ²<x,x> + 2λ<x,y> + <y,y>.
    У последней функции дискриминант ≤ 0.
    4<x,y>² - 4<x,x><y,y> ≤ 0.
    Это и есть неравенство Шварца.
** 2 Порождение нормы скалярным произведением                         :lemma:
   Определим ∥x∥ следующим образом:
   * ∥x∥ = √(<x,x>).
   * Доказательство аксиомы 3 (первые две тривиально):
     ∥x + y∥² = ∥x∥² + 2<x,y> + ∥y∥² ≤ {Шварц} ≤ (∥x∥ + ∥y∥)².
   * Отсюда УП -- частный случай НП. Заметим, что не всякая норма
     удовлетворяет свойству скалярного произведения, так что обратное
     неверно.
** 2 Ортогональность, р-во Пифагора                              :definition:
   Определим отношение ортогональности на векторах:
   * x ⊥ y ≡ <x,y> = 0.
   Отсюда мгновенно (с помощью Шварца) получаем:
   * x ⊥ y ⇒ ∥x+y∥² = ∥x∥² + ∥y∥².
** 1 Равенство параллелограмма                                        :lemma:
   ∀x,y ∥x+y∥² + ∥x-y∥² = 2∥x∥² + 2∥y∥².

   Отдельно отметим, что:
   * Метрика порождает скалярное произведение ⇔ для нее выполнено
     равенство параллелограмма.

*** Доказательство
    Тривиально. Раскрыть по определению <x+y, x+y>, дальше все само
    зайдет.
** 2 Ортонормированная система векторов, ЛНЗ                     :definition:
   {eᵢ...eₙ(...)} -- возможно бесконечный набор векторов со
   свойствами:
   1. ∥eᵢ∥ = 1.
   2. ∀i,j, i ≠ j ⇒ eᵢ ⊥ eⱼ

   Что такое ЛНЗ все знают. Напомним, что существует процесс
   нормализации Грамма-Шмидта (курс линейной алгебры 1-2 сем. КТ),
   который любой ЛНЗ набор превращает в ортонормированный.
** 2 Ортогональный ряд                                           :definition:
   ∑xⱼ ортогональный, если ∀i≠j xᵢ ⊥ xⱼ.
   Удобное свойства ортогонального ряда (Sₘ -- частичная сумма):
   ∥Sₘ∥² = <∑, ∑> = ∑∥xᵢ∥².
** 1 Коэффициент, ряд Фурье                                      :definition:
   Пусть x ∈ X, {eᵢ} -- ОНС.
   Тогда <x,eᵢ> -- коээфициент Фурье элемента x.
   ∑{eᵢ} <x,eᵢ>eᵢ -- ряд Фурье.
   Ряд фурье -- частный случай ортогональных рядов.
** 2 Наилучшее приближение                                       :definition:
   X -- НП, Y -- его подпространство.
   ∀x ∈ X, E_Y(x) ≡ ρ(x, Y) = inf{y ∈ Y}∥x-y∥.
   E_Y(x) -- наилучшее приближение x точками из Y.

   При этом элемент наилучшего приближения:
   ∀x ∈ X, E_Y(x) = ∥x - y*∥.
** 2 Теорема Бореля                                                 :theorem:
   dimX < +∞ ⇒ ∀x ∈ X, ∃y* ∈ Y -- элемент наилучшего приближения.

*** Скетч
    Y=ЛО, опр.f(α~), она будет большой вне шара + Вейерштрасс.
*** Доказательство
    Y = L(e₁...eₙ), тогда f(α₁...αₙ) = ∥x - ∑{n} αₖeₖ∥.

    Найдем минимум f, некоторый вектор α~. Из неравенства треугольника
    f(α~) непрерывна на ℝⁿ.

    f ≥ 0 по построению. E_Y(x) = inf{ℝⁿ}f(α~).

    Легко установить (тут нужно доказать), что можно найти шар B(0, r)
    ∈ ℝ², вне пределов которого f > 2E_Y(x).  Значит само лучшее
    приближение нужно искать в шаре.  Шар -- компакт, f непрерывна на
    нем, тогда по теореме Вейерштрасса f имеет минимум на шаре.
** 1 Экстремальное свойство частичных сумм ряда Фурье               :theorem:
   {eᵢ} -- ОНС. Hₙ = L(e₁...eₙ). Sₙ(x) -- частичная сумма ряда фурье
   до элемента N элемента x. Тогда E_Hₙ(x) = ∥x - Sₙ(x)∥.

*** Доказательство
    ∀y = ∑αᵢeᵢ ∈ Hₙ;
    ∥x-y∥² = <x - ∑αᵢeᵢ, x - ∑αᵢeᵢ> = ∥x∥² - 2∑<x,eᵢ>αᵢ + ∑αᵢ²
    = {последнее по ортогональности, выделили полный квадрат}
    = ∥x∥² + ∑(αᵢ - <x,eᵢ>)² - ∑<x,eᵢ>².
    В последнем выражении первый и последний член -- константы.
    Средняя сумма минимальна когда:
    αᵢ=<x,eᵢ>
    Отсюда элемент наилучшего приближения действительно сумма Фурье.
** 2 Неравенство Бесселя                                              :lemma:
   Для коэффициентов Фурье верно:
   1. ∑<x,eᵢ>² ≤ ∥x∥².
   2. Ряд из квадратов коэфф. Фурье сходится (д-во из 1 пункта).

*** Доказательство
    0 ≤ ∥x-y*∥² = ∥x-∑<x,eᵢ>∥² = ∥x∥² - ∑<x,eᵢ>².
    Это почти по Пифагору, только с разностью.
    Последннее больше нуля, от туда и неравенство Бесселя.
* 2 Пространства Гильберта
** 2 Гильбертово пространство                                    :definition:
   Пространство Гильберта (H) -- полное бесконечномерное унитарное
   пространство.
** 2 Примеры гильбертовых пространств (l₂, L₂)                      :example:
   * L₂(E), <f,g> = ∫E (f∙g)dμ.
   * l₂ - {{x₁...xₙ..} | ∑xₙ² < +∞}
     <x,y> = ∑xₙyₙ.
     l₂ -- частный случай L₂ при E = ℕ и μ(m} = 1 (считающая мера).
** 2 Теорема Рисса-Фишера                                           :theorem:
   Ряд фурье в Гильбертовом (полном унитарном, бесконечномерном)
   пространстве любой точки всегда сходится.

*** Доказательство
    По полноте нам необходимо доказать, что частичные суммы сходятся в
    смысле Коши. Квадрат нормы разности двух частичных сумм фурье --
    частичная сумма квадратов модулей, которая сходится по Бесселю.
** 2 Равенство Парсеваля                                            :theorem:
   ∥x∥² = ∑|<x,eᵢ>|².

*** Доказательство
    По непрерывности скалярного произведения:

    ∥x∥² = <x,x> = lim<Sₙ,Sₙ> = lim ∑|<x,eₖ>| = ∑|<x,eₖ>|.
** 2 Полная, замкнутая ОНС                                       :definition:
   1. ОНС {eᵢ} замкнута, если H = Cl(L({eᵢ})).
      (Замыкание тут необходимо, потому что по определению линейная
      оболочка L -- это конечная сумма).
   2. ОНС {eᵢ} полна, если: ∀x <x,eₘ> = 0 ⇒ x = 0.
** 1 Лемма о связи полноты и замкнутости                              :lemma:
   {eᵢ} полна ⇔ {eᵢ} замкнута.

*** Доказательство
    1. Сначала покажем общий факт, из которого будут верны оба
       утверждения:
       ∑yₙ в H ортогональны.
       ∥Sₙ - Sₘ∥² = ∑{∞}∥yₙ∥²;
       ∥Sₙ - Sₘ∥ → 0 ⇔ ∑{∞}∥yₙ∥² → 0;
       Отсюда в H сходится ряд, если сходится ∑∥yₙ∥².

       Если есть ОНС, то мы можем сопоставить:
       x → ∑<x,eₖ>eₖ =: ∑yₖ;
       ∑<x,eₖ>² ≤ ∥x∥² < +∞ по неравенству Бесселя.

       В H ряд Фурье у любой ОНС сходится. Поэтому если система
       полная, то:
       ∀x ∈ H , ∀ε > 0, ∃∑{j=1..p}αₖⱼeₖⱼ, что ∥x - ∑αₖⱼeₖⱼ∥ ≤ ε².

       Но частичные суммы ряда Фурье обладают экстремальным свойством:
       ∥x - ∑xₖⱼeₖⱼ∥² ≥ ∥x - ∑<x,eⱼ>eⱼ∥²

       Более того, если Sₘ частичная сумма, то:
       ∣x - Sₘ₊ₚ(x)∥² ≤ ∥x - Sₘ(x)∥² ≤ ε².

       Отсюда x действительно всегда раскладывается в ряд Фурье.
    2. Если ∀x <x,eₘ> = 0 то автоматически x = 0 (из свойства суммы).
    3. Аналогично, в H ряд по любой ОНС сходится.
       y = ∑<x,eⱼ>eⱼ, то есть <x,eⱼ> = <y,eⱼ>.
       Тогда по линейности скалярного произведения y - x = 0.
       Значит y = x, значит x = ∑∞ <x,eⱼ>eⱼ, значит система замкнута
       (содержит все свои пределы).
** 2 Сепарабельность топологического пространства                :definition:
   Топологическое пространство сепарабельно, если в нем существует
   счетное всюду полное множество точек.
   * X = Cl{a₁...aₙ..}.
** 2 Связь сепарабельности и существования базиса                     :lemma:
   H сепарабельно ⇔ ∃ базис в H.

*** Доказательство
    Из предыдущей леммы:
    1. Пусть H сепарабельно, тогда применим Грамма-Шмидта и оно будет
       базисом (тут что-то гарантирует предыдущая лемма).
    2. Если есть базис, то H сепарабельно -- возьмем в качестве aᵢ
       коээфициенты, суммы с αᵢ ∈ ℝ.
** 1 О наилучшем приближении в H                                    :theorem:
   H -- пространство, M -- замкнутое выпуклое подмножество.
   Тогда ∀x ∈ H ∃!y ∈ M, что ∥x-y∥ = inf{z∈M}∥x-z∥.
   То есть в M у любого элемента есть единственный элемент наилучшего
   приближения.

*** Доказательство
    d ≡ inf{z∈M}∥x-z∥.
    По определению нижней грани:
    ∀n ∈ ℕ, ∃yₙ ∈ M, d ≤ ∥x+yₙ∥ < d + 1/n.

    Пусть ∃y = lim yₙ. По замкнутости M y∈M и предельный переход в
    последнем неравенстве ∥x - y∥ = d.

    Покажем, что у yₙ есть предел.
    Возьмем yₙ,yₘ ∈ M. Из выпуклости (yₙ+yₘ)/2 ∈ M.
    Значит:
    d ≤ ∥(yₘ-yₙ)/2 - x∥² = 1/4 ∥yₘ - yₙ - 2x∥²
    = 1/4 ∥(yₘ - x) + (yₙ - x)∥².
    Рассмотрим равенство параллелограмма.
    ∥(yₘ - x) + (yₙ - x)∥² + ∥(yₘ - x) - (yₙ - x)∥
    = 2∥yₘ - x∥² + 2∥yₙ - x∥².
    Оценим второй член:
    ∥yₘ - y∥ ≤ 2∥yₘ - x∥² + 2∥yₙ - x∥² - 4(d + 1/n).
    ∥yₘ - y∥ → 0.

    Единственность вытекает из равенства параллелограмма (можно
    проверить).
** 2 Разложение в прямую сумму                                   :definition:
   H -- гильбертово пространство, H₁ -- замкнутое линейное
   подмножество H (подпространство).

   H₂ ≡ H₁⊥ (верхний индекс ⊥) = {y ∈ H | y ⊥ x, x ∈ H₁}.
   Тогда H = H₁ ⊕ H₂.
** 0 Следствие о приближении в прямой сумме                           :lemma:
   x ∈ H₁, H₂ = H₁⊥.
   ∃x₁ ∈ H₁ : ∥x - x₁∥ = inf{u ∈ H₁}∥x - u∥
   x₂ = x - x₁ ∈ H₂?
   ∀y ∈ H₁ y ⊥ x₁, λ > 0, x₁ + λy ∈ H₁
   Отсюда:
   ∀ λ > 0 ∥x - (x₁ + λy)∥² ≥ ∥x - x₁∥²
   <x - x₁ - λy, x - x₁ - λy> ≥ <x - x₁, x - x₁>
   <x₂ - λy, x₂ - λy> ≥ <x₂, x₂> ⇒
   <x₂, x₂> - 2<λy, x₂> + λ²<y, y> ≥ <x₂, x₂>
   Итого имеем: 2<y, x₂> ≤ λ<y, y>
   Устремим λ к нулю: <y, x₂> ≤ 0.
   В силу произвольности y также верно:
   <-y, x₂> ≤ 0.
   Отсюда <y, x₂> = 0.
* 2 Счетно-нормированные пространства
** 2 Счетно-нормированное пространство                           :definition:
   X -- линейное множество. Полунорма p на X -- это функционал,
   удовлетворяющий 2 и 3 условиям нормы, но имеющий ослабленное первое
   условие:
   1. p(x) ≥ 0. (не обязательно нулевая на нулевых элементах)

   Пусть на X задана {pᵢ} -- счетное множество полунорм, и они
   согласованы:
   * ∀n pₙ(x) = 0 ⇒ x = 0.
   Тогда <X, {pᵢ}> -- счетно-нормированное пространство.
** 2 Предел в СНП                                                :definition:
   x = lim{xₙ} ≡ ∀n ∈ ℕ lim{m→∞}(pₙ(xₘ - x)) = 0
** 2 Вложение СНП                                                 :statement:
   Нормированное пространство -- частный случай СЧП
   Согласованность {pᵢ} необходима для единственности предела.
   Можно показать, что без этого условия единственности не будет.
** 2 Метрика в СЧП (Урысона)                                     :definition:
   Если ρ(x, y) = ∑{inf}(1/2ⁿ)(pₙ(x - y) / (1 + pₙ(x - y))), то СНП
   метризуеммо всегда.
   Это, кстати, метрика в ℝ∞.
** 2 Непрервыность и топология                                    :statement:
   Сложение и умножение на скаляр непрерывны. В этом смысле СНП = ТВП
   (Топологическое векторное пространство).
** 2 Пример СНП                                                     :example:
   Возьмем C∞[a,b] = {x(t), t ∈ [a,b], бесконечно дифференцируемо}.
   Тогдa pₙ = max[a,b] |x⁽ⁿ⁾(t)|, n = 0,1,...
   Кстати, C∞ не нормируемо.
** 2 Монотонная система полунорм, эквивалентность, существенность :definition:
   1. {pₙ} монотонна, если ∀x ∈ X ∀n ∈ ℕ pₙ(x) ≤ pₙ₊₁(x)
   2. {pₙ} ~ {qₙ}, если в них одинаковая сходимость
   3. pₘ мажорирует pₙ, если ∃c ∀x∈X pₙ(x) ≤ c * pₘ(x)
   4. pᵢ ∈ {pₙ} существенна, если она не мажорируется любой pⱼ |j<n.
** 2 Сведение к монотонной                                            :lemma:
   Для любой системы полунорм существует эквивалентная ей монотонная
   система.

   Далее будем считать, что любая система полунорм монотонна.

*** Доказательство
    Пусть qₙ(x) = ∑{n}pₙ(x) : {qₙ} полунормы.
    Их монотонность очевидна. Насчет эквивалентности:
    pₙ(xₘ - x) → 0 ⇒ ∑pₖ(xₘ - x) → 0.
    Обратное аналогично.
** 2 Теорема об эквивалентности и мажорируемости                    :theorem:
   {pᵢ} ~ {qᵢ} ⇔ {pᵢ} мажорирует {qᵢ} и наоборот.
   ({qᵢ} мажорирует {pᵢ} := ∀i∃j qⱼ мажорирует pᵢ)

*** Доказательство
    1. Справа налево очевидно. Если мажорирование есть, то по
       определению эквивалентности полунорм сходимость будет
       совпадать.
    2. Хотим: ∀pₙ ∃pₙ', ∃c = const, ∀x ∈ X, pₙ(x) ≤ c*pₘ'(x).

       Докажем от противного, взяв константу c равную m. Тогда:

       ∃pₙ₀ ∀pₘ' ∃xₘ ∈ X : pₙ₀(xₘ) ≥ m * pₘ'(xₘ).

       Перепишем это неравенство:

       pₘ'(xₘ/pₙ₀(xₘ)) ≤ 1/m.

       Обозначим yₘ ≡ xₘ / pₙ₀(xₘ), для таких yₘ очевидно верно:

       pₘ'(yₘ) ≤ 1/m, pₙ₀(yₘ) = 1.

       Зафиксируем m₀, по монотонности нормы m ≥ m₀:

       pₘ₀'(yₘ) ≤ pₘ'(yₘ) ≤ 1/m.

       тогда при m → ∞: ∀m₀ p'ₘ₀(yₘ) → 0. Но ведь у нас есть pₙ₀(yₘ) =
       1, и тогда последовательность не может стремиться к нулю. →←
** 2 Критерий нормируемости                                         :theorem:
   X -- счетно-нормированное пространство с монотонной системой
   полунорм P. Тогда: X нормируется ⇔ в P конечное число существенных
   полунорм.

*** Доказательство
    1. ⇐. Пусть {pₙⱼ} -- существенные (конечное число
       полунорм). Найдем pₖ -- полунорму с максимальным номером. Она
       -- норма. pₖ(x) = 0 ⇒ pₙ(x) = 0 (n < k). Для полунорм с больших
       индексом это тоже верно, так как pₖ -- полнорма с
       макс. номером. Из согласованности, x = 0 и тогда pₖ -- норма.
    2. ⇒. Пусть X нормируемо и p -- норма. Тогда p ~ {p_i}, отсюда они
       мажорируют друг друга (по пред.теореме). То есть p мажорирует
       все p_i и есть какая-то p_k, которая мажорирует p. Отсюда ∀i
       p_k мажорирует p_i. То есть p_k -- существенна. Из определения
       существенности никакая p_r, r > k не может быть
       существенной. Возможно, какие-то p_i i < k
       существенны. Суммарно имеем конечное количество сущ. полунорм.
** 1 Ненормируемость ℝ∞                                           :statement:
   x~ = (x₁...xₙ..), pₙ(x~) = |xₙ|. Все полунормы существенны, отсюда
   ℝ∞ не нормируемо.
* 2 Функционал Минковского
** 2 Поглощение, радиальность, закругленность                    :definition:
   1. X -- линейное множество. M ⊂ X, M выпукло (∀x,y ∈ M αx+βy ∈ M,
      α+β = 1, α,β ≥ 0). М поглощает A ⊂ X, если ∃λ₀, что ∀λ |λ|≥λ₀ A
      ⊂ λM = {λx | x ∈ M}}.
   2. Если M поглощает любое конечное число точек, то M радиальное
      множество.
   3. М закругленное, если ∀λ |λ| < 1 λM ⊂ M.
** OK Шар как закругленное множество                                :example:
   CLOSED: [2016-01-23 Sat 04:22]
   X -- НП, V~ = {∥x∥ ≤ 1}, тогда V~ радиально и закругленно.
** 2 Функционал Минковского                                      :definition:
   М -- радиальное множество, тогда:
   * ∀x ∈ X, φₘ(x) = inf{λ ≥ 0 | x ∈ λM}.
   Такой функционал φₘ называется функционалом Минковского.
** 2 Норма как функционал Минковского                               :example:
   На шаре V~ φₘ(x) -- норма x = ∥x∥. Можно смотреть вообще
   на норму как на частный случай φₘ, так и делают обычно.
** 1 Функционал Минковского и полунорма                               :lemma:
   φₘ -- полунорма на X ⇔ M радиально, выпукло, закруглено.

*** Доказательство
    Очевидно проделать самим хех кек))))))))000000
* 2 Линейные функционалы и коразмерность
** 2 Фактор-множество, коразмерность                             :definition:
   1. X -- линейное множество, Y ⊂ X линейно.
      Введем эквивалентность на X:;
      ∀x, y ∈ X, x ~ y ⇔(def) x - y ∈ Y.
      [x] = {y : y ~ x} -- будем так обозначать класс эквивалентности.
   2. X / Y = {[x]} -- фактор-множество.
      Фактор-множество линейно, очевидно (достаточно ввести [x] + [y] =
      [x+y] и то же самое для умножения на константу).
   3. codimₓY ≡ dim(X/Y)
** 2 Связь конечности коразмерности и разложения по базису            :lemma:
   codimₓY = p < +∞, тогда ∃e₁...eₚ ∈ X, что ∀x ∈ X.

   x =! ∑αₖeₖ + y, где y ∈ Y.

   Доказательство очевидное по свойству линейности [x].
** 2 Гиперплоскость, линейный функционал, ядро                   :definition:
   1. Y -- гиперплоскость, если codimₓY = 1. Достаточно логичное
      определение -- чтобы выразить что угодно из икса, нам кроме
      вектора из Y нужен еще один вектор.
   2. Аналитическое описание гиперплоскости дается с помощью линейных
      функционалов.
      f: X → ℝ, f линейно ∀ x,y,α, f(0) = 0, тогда f линейный
      функционал
   3. Ker f = {x | f(x) = 0}.
      Если f линейно, то Ker f линейно.
** 2 Аналитическое задание гиперплоскости                           :theorem:
   Любая гиперплоскость может быть записана как Ker(f) для некоторого
   f.

*** Доказательство
    1. Пусть f -- нетривиальный линейный функционал (нетривиальность
       -- хотя бы для какой-то x f(x) ≠ 0).
       * Y := Ker(f).
       Проверим, что codim(Y) = 1.

       В силу нетривиальности f возьмум ту самую x₀, что f(x₀) ≠ 0.
       * e = x₀/f(x₀), f(e) = 1.

       ∀x ∈ X подберем t ∈ ℝ, что x - te ∈ Kerf. Тогда y := x - te, x
       = te - y, тогда codimY = 1.

       Подбор t прост: возьмем f(x-te) = 0, тогда f(x) = tf(e),
       отсюда t = f(x) подойдет.
    2. Если codimY = 1, то ∀x ∈ X, x = te + y, y ∈ Y. Определим тогда
       f(x) = t. Отсюда f(x) = 0 ⇒ x ∈ Y.
* 2 Теорема Колмогорова
** 2 Топологическое векторное пространство                       :definition:
   X -- множество, τ -- топология на X, операции умножения на
   константу и сумма непрерывны.

   E(x) -- окрестность x, если ∃G ∈ τ : x ∈ G ⊂ E(x).

   Тогда (X, τ) -- ТВП.

   * Непрерывность умножения на скаляр:
     * ∀E(α₀X₀) ∃δ>0, ∃E(x₀): |α-α₀|<δ, x ∈ E(x₀) ⇒ αx ∈ E(α₀x₀)
     Это то же самое, что и нотация: α₀x₀ = lim{α→α₀,x→x₀}αx.
   * Непрерывность суммы:
     ∀E(x₀+y₀) ∃E(x₀), E(y₀): x ∈ E(x₀), y ∈ E(y₀), x+y ∈ E(x₀+y₀)
** 2 Место ТВП в систематике                                      :statement:
   Нормированные и счетно-нормированные пространства -- частные
   случаи ТВП.
** 2 Лемма о сохранении открытости сдвига                             :lemma:
   Возьмем x₀, f(x) ≡ x + x₀, f -- очевидно биекция X на X.
   * f⁻¹(y) = y - x₀.
   В силу непрерывности сложения f и f⁻¹ непрерывны. Тогда f --
   гомеоморфизм (биекция, непрерывная в обе стороны).

   Так как непрерывные функции сохраняют открытость множеств,
   ∀G открытое, x₀ + G = {x₀ + x | x ∈ G} тоже открыто.
   Тогда сдвиг сохраняет открытость.
** 2 База окрестностей нуля                                      :definition:
   σ = {B, B -- окрестность нуля}, что ∀C -- окрестность нуля, C ∉ σ,
   C = ∪{Bᵢ}, Bᵢ ∈ σ.

   σ -- это база окрестностей нуля.

   Сдвигая элементы σ на константу, получаем базу окрестности любой
   другой точки.
** 2 Всякие свойства базы окрестности нуля                        :statement:
   x → 0, тогда x + x → 0 + 0 = 0.

   ∀V ∈ σ, ∃U ∈ σ, 2*U ⊂ U+U ⊂ V

   ∀V ∈ σ, ∃ε > 0, ∃U ∈ σ, |λ|≤ε ⇒ λU ⊂ V.

   Отсюда видно, что ⋃{|λ|≤ε} λU -- закругленное.


   Тогда система открытых множеств инварианта по сдвигу и всегда можно
   создать такое σ, что:
   1. ∀V ∈ σ, ∃U ∈ σ, U+U ⊂ V
   2. все элементы σ радиальные и закругленные

   Это все выводится исключительно из определения окрестности.

   Эти условия полностью характеризуют топологию векторного
   пространства, то есть обеспечивают непрерываность +, ∙.
** 2 Теорема Колмогорова                                            :theorem:
   Хаусдорфово ТВП нормируется ⇔ 0 имеет хотя бы одну ограниченную
   выпуклую окрестность.
   * Хаусдорфово -- для любых двух точек можно найти их
     непересекающиеся окрестности.
   * Ограниченная -- полглощается любой окрестностью нуля.

*** Доказательство
    1. (⇒)
       Очевидно, единичный шар будет ограниченной выпуклой
       окрестностью нуля.
    2. (⇐)
       Имея выпуклую ограниченную окрестность нуля, можно считать, что
       мы имеем радиальную закругленную окрестность.
       Построим функционал Минковского относительно этого множества.
       Согласно последней теореме в главе про функционал Минковского,
       мы можем считать, что φₘ -- полунорма.

       Докажем, что φₘ честная норма: φ(x) = 0 ⇒? x = 0

       φ(x) = 0, значит x = ∩{∞}(1/n V) = {0} по хаусдорфовости
       пространства (не может быть ничего кроме нуля).
** 0 ℝ∞ как ненормируемое пространство                              :example:
   Рассмотрим ℝ∞ = {(x₁, x₂, ...)}. Посмотрим на множество вида:

   {x~, xᵢ₁ ∈ (-δ₁, δ₁), ... xᵢₚ∈(-δₚ, δₚ)}, все дельты > 0.

   Тут нету ни одной ограниченной выпуклой окрестности нуля.

   От противного: если есть, то должна быть поглощена любым элементом
   базы. Возьмем такие элементы базы: {x~, -δ < x₁ < δ}. Они, очевидно,
   окрестности нуля, но не поглощают некоторые ограниченные
   окрестности ввиду того, что наши элементы базы определены только с
   констрейнтом для первого элемента вектора.
* 1 Непрерывные функционалы, теорема Хана-Банаха
** 2 Связь непрерывности л.функционала на X и в нуле.                 :lemma:
   X -- нормированное пространство, f -- непрерывный на X функционал
   (xₙ → x ⇒ f(xₙ) → f(x)).
   f непрерывна на X ⇔ f непрерывна в нуле.

   Доказательство тривиальное.
   В силу непрерывности умножения на скаляр и суммы в нормированном
   пространстве по линейности фукнционала имеем:

   f(xₙ) - f(x) = f(xₙ - x), xₙ → x ⇔ xₙ - x → 0. Тогда f(0) = 0.
** 2 Норма функционала, ограниченность                           :definition:
   1. ∥f∥ ≡ sup{∥x∥ < 1}|f(x)|.

      Заметим также, что очевидно из определения:

      ∀x ≠ 0, ∥x/∥x∥∥ = 1, отсюда |f(x/∥x∥)| ≤ ∥f∥ ⇒ |f(x)| ≤ ∥f∥*∥x∥.
   2. f ограничена ≡ ∥f∥ < +∞.
** 2 Ограниченность и непрерывность функционала                       :lemma:
   f -- линейный функционал. f ограничен ⇔ f непрерывен.
   1. (⇒)
      ∥f∥ < +∞, |f(x)| ≤ ∥f∥*∥x∥, xₙ → 0 ⇒ ∥xₙ∥ → 0.
      Тогда |f(xₙ)| ≤ ∥f∥*∥xₙ∥ ⇒ f(xₙ) → 0.
   2. (⇐) От противного.
      Пусть ∥f∥ = ∞ = sup{∥x∥≤1} |f(x)|. Раскроем определение
      супремума:

      ∀n ∈ ℕ ∃xₙ: ∥xₙ∥ ≤ 1, |f(xₙ)| > n. |f(xₙ/n)| > 1.

      ∥xₙ/n∥ =  ∥xₙ∥/n ≤ 1/n. Отсюда xₙ/n → 0.

      Тогда по непрерывности f(xₙ/n) → 0, что
      противоречит |f(xₙ/n)|>1.
** 1 Связь непрерывности функционала и замкнутости ядра             :theorem:
   Линейный функционал f непрерывен ⇔ Ker(f) замкнут в X.

*** Доказательство
    1. (⇒) Если f непрерывна, xₙ ∈ Ker(f), тогда по непрерывности
       f(xₙ) → f(x), но f(xₙ) = 0, значит f(x) = 0, тогда x ∈ Ker(f).
    2. (⇐) Ker(f) замкнуто.

       В силу того, что codim(Ker(f)) = 1, мы можем найти такую e ∈ X,
       что:

       ∀x, x = y + te, y ∈ Ker(f), t∈ℝ.

       Отсюда по линейности:

       f(x) = f(y) + tf(e) = tf(e), так как y ∈ Ker(f).

       Тогда если мы проверим, что tₙ → t, сможем показать, что tₙf(e)
       → tf(e) = f(x), а значит f(xₙ) → f(x).

       Выделим эти xₙ = yₙ + tₙe, x = y + te; xₙ → x; y, yₙ ∈ Ker(f).
       Если, следуя логике анализа, доказать, что все сходящиеся
       подпоследовательности tₙₖ → t, тогда и tₙ → t.

       tₙₖ → t~, yₙₖ = xₙₖ - tₙₖ*e → x - t~*e ∈ Ker(f) так как ядро
       замкнуто.
       Тем самым по единственности записи t~ будет единственно для
       всех таких подпоследовательностей.
** 0 Пример плотного всюду многообразия                             :example:
   Рассмотрим C[0, 1], теорему Вейерштрасса о равномерном приближении
   функции полиномами. Утверждается, что:

   ∀ε>0, ∃Pₙ(x), ∀x∈[0,1], |f(x)-Pₙ(x)|<ε.

   Теорема Вейетштрасса долгое время существовала исключительно в
   неконструктивном виде, но С.Н.Бернштейн в начале 20 века показал,
   как полиномы можно строить конструктивно:

   Bₙ(f,x) = ∑{k=0..n}Cᵏₙf(k/n)xᵏ(1-x)ⁿ⁻ᵏ -- на них реализуется
   теорема Вейерштрасса.

   С точки зрения функционального анализа Y = {Pₙ(x)} -- линейное
   множество в C[0,1]. Тогда ClY = C[0,1] -- пример плотного всюду
   многообразия.
** 1 Продолжение с непрерывного линейного множества                 :theorem:
   X -- НП, Y -- линейное множество в X, ClY = X. Y везде плотно в X.
   На Y задан f₀ -- непрерывный линейный функционал.

   Тогда существует непрерывный линейный фукнционал f на X, что:
   1. f|_y = f₀
   2. ∥f∥ₓ = ∥f₀∥_y

*** Скетч
    Единственность следует из единственности предела.

    f(x) определяется как предел f₀ исходя из полноты ℝ и критерия
    Коши. Сохранение нормы доказывается сложно.
*** Доказательство
**** Единственность
     f, g -- непрерывные на X функционалы, равны h на сужении Y.
     Тогда ∀x ∈ X, ClY = X, ∃yₙ ∈ Y: yₙ → x.

     h(yₙ) → f(x), h(yₙ) → g(x), значит по единственности предела
     f(x) = g(x).
**** Существование
     Так как Cl(Y) = X, то ∀x∈X, ∃yₙ∈Y, что yₙ → x.

     f₀ непрерывен на Y, значит ∥f₀∥_y < +∞.

     Тогда |f₀(yₘ) - f₀(yₙ)| = |f₀(yₘ-yₙ)| ≤ ∥f₀∥_y * ∥yₘ - yₙ∥ → 0.
     То есть {f₀(yₙ)} сходится в себе на ℝ.

     Тогда по критерию Коши исходя из полноты ℝ у f₀(yₙ) есть предел
     f(x). f(x) = lim(f₀(yₙ)).

     Проверим, что если yₙ → x, yₙ' → x, то lim(yₙ) = lim(yₙ').

     Тогда |f₀(yₙ) - f₀(yₙ')| ≤ ∥f₀∥_y * ∥yₙ-yₙ'∥ → 0. Отсюда предел
     единственный.

     В силу арифметики предела f(x) -- линейный функционал. Очевидно,
     что на Y f(x) = f₀(x).

     Докажем, что ∥f∥ₓ = ∥f₀∥_y.

     1. Так как Y ⊂ X, по определению ∥∙∥ и sup, получаем ∥f₀∥_y ≤ ∥f∥ₓ.
     2. Покажем обратное неравенство:
        * Sup достигается на единичной сфере
          Пусть это не так, и есть x, что ∥x∥ < 1. Тогда x' = x/∥x∥, и
          ∥x'∥ = 1.

          Оценим: |f(x)| = ∥x∥*|f(x/∥x∥)| ≤ |f(x')|.

        Возьмем x, ∥x∥ = 1. ∃yₖ ∈ Y, yₙ → x.
        Отнормируем: ∥yₙ∥ → ∥x∥ = 1, тогда определим
        yₙ' = yₙ/∥yₙ∥ → x/1 = x. ∥yₙ'∥ = 1. yₙ' ∈ Y.

        Не теряя общности, y := y'.

        По определению предела f₀(yₙ) → f(x).

        С другой стороны, |f₀(yₙ)| ≤ ∥f₀∥_y; ∥yₙ∥ = 1.
        Поскольку |f(x)| ≤ ∥f₀∥_y, то сразу ∥f∥ₓ ≤ ∥f₀∥_y.
** 1 Лемма Банаха                                                   :theorem:
   X -- линейное множество, p(x): X → ℝ -- полунорма, Y -- собственное
   линейное подмножество X.

   f₀: Y → ℝ линейно. |f₀(y)| ≤ p(y).

   e ∉ Y. Y₁ = L(Y,e).

   Тогда ∃f: Y₁ → ℝ, линейное, что:
   1. f|_y = f₀
   2. |f(y)| ≤ p(y) на Y₁

*** Скетч
    Покажем что f должно быть линейно, выберем f(e) любым и покажем,
    что оно подходит.
*** Доказательство
    Если хотим, чтобы f было линейным и f|_Y = f₀, то будем искать
    решение в виде f(αy + βe) = αf₀(y) + βf(e). Не будем писать α без
    потери общности.

    Тут f(e) единственная неизвестная, так как на Y f₀
    определена. Пусть c := f(e). Покажем, что выбрав это c любым,
    теорема будет доказана.

    В выборе 'c' воспользуемся условием продолжения, заменим y + te на
    y - te без потери общности.
    * |f₀(y) - tc| ≤ p(y + βe).
    * |f₀(y)| ≤ p(y) -- дано
    * f₀(y) - p(y-te) ≤ t*c ≤ f₀(y) + p(y-te), t > 0.

    Поделим все на t, раскроем по линейности и переобозначим y:=y/t.
    * f₀(y) - p(y-e) ≤ c ≤ f₀(y) + p(y-e).                          (1)

    * ∀y₁,y₂ ∈ Y, f₀(y₁)-p(y₁-e) ≤ f₀(y₂)+p(y₂-e).

      Это утверждение доказывается просто (правило треугольника +
      условие мажорирования первоначальное):

      * f₀(y₁ - y₂) ≤ p(y₁ - y₂ + e - e).
      * f₀(y₁) - f₀(y₂) ≤ p(y₁ - e) + p(y₂ - e).

    Тогда с помощью последнего правила получим:

    * sup{y∈Y}(f₀(y) - p(y-e)) ≤ f₀(y₂) + p(y₂ - e).
    * sup{y∈Y}(f₀(y) - p(y-e)) ≤ inf{y∈Y}(f₀(y) + p(y - e)).

    Рассмотрим (‌1). Обозначим a := sup(...), b := inf(...) из
    последнего утверждения. Тогда (1) истинна для любой c ∈ [a,b].
** 1 Теорема Хана-Банаха (полная, без д-ва)                       :statement:
   X, p(x) -- полунорма. Y -- линейное множество в X.
   f₀ -- линейный функционал, удовлетворяющий условию подчиненности
   полунорме (∀y∈Y, |f₀(y)| ≤ p(y)).

   Тогда мы можем продлить f₀ на X с сохранением условия
   подчиненности:

   ∃f: X → ℝ, что:
   1. f|_Y = f₀.
   2. ∀x ∈ X |f(x)| ≤ p(x)

   Доказательство не приведено, но оно существенно пользуется леммой
   Цорна, которую никто не хочет доказывать. С помощью леммы Банаха мы
   проводим этот итеративный процесс, а лемма Цорна гарантирует нам
   заполнение всего множества x.

   И без аксиомы выбора эта теорема тоже не доказывается.
** 2 Теорема Хана-Банаха для сепарабельных пр-в                     :theorem:
   X -- сепарабельно, нормировано (то есть содержит всюду плотное счетное
   подмножество).

   Y -- линейное множество в X, f₀ -- непрерывный линейный функционал
   на Y.

   Тогда ∃ непрерывный линейный функционал на x, что:
   1. f|_Y = f₀.
   2. ∥f∥ₓ = ∥f₀∥_Y

   Примечание: условие сепарабельности -- это самый частый юзкейс.

*** Скетч
    Продолжаем с помощью леммы Банаха пространства Lₙ=L(Y,a₁..aₙ).
*** Доказательство
    Раз X сепарабелен, то A = {a₁...aₙ..}, что Cl(A) = X.

    Будем считать, что в A все точки разные и линейно независимые
    (повыкидываем что-нибудь).

    Сепарабельность обеспечивает возможность создать:
    * Lₙ = L(Y, a₁...aₙ)
    * Lₙ ⊂ Lₙ₊₁.

    Тогда L = ⋃Lₙ -- тоже линейное множество + Cl(L) = X.

    Отсюда по лемме Банаха продолжаем с Y на L₁, с L₁ на L₂ и так
    дальше. Получим на L функционал и тогда по непрерывности продолжим
    его на X (по теореме о продолжении с линейного множества), так как
    L плотно в X.
** 2 Следствия из теоремы Х-Б                                         :lemma:
   1. ∀x₀ ≠ 0, ∃ линейный непрерывный функционал f, что:
      1. ∥f∥ = 1.
      2. f(x₀) = ∥x₀∥.

      Доказательство: возьмем Y = {tx₀, t∈ℝ}. Построим с помощью
      f₀(tx₀) = tf₀(x₀), где f₀(x₀) = ∥x₀∥, линейный функционал f₀.

      ∥f₀∥_Y = 1, f₀(x₀) = ∥x₀∥.

      Тогда по теореме Х-Б продолжим на X.
   2. ∀x₁ ≠ x₂ ∃ линейный функционал f(x₁) ≠ f(x₂).

      В качестве доказательства обратимся к предыдущему следствию с
      x₀ = x₂ - x₁.
   3. Два предыдущих следствия принадлежат категории "какой функцией
      можно записывать линейный ограниченный функционал в наперед
      заданном пространстве"

      Что бы это ни значило.
** 1 Теорема Рисса                                                  :theorem:
   H -- Гильбертово пространство, f -- линейный огр. функционал. Тогда
   существует y ∈ H, что:
   1. ∀x ∈ H  f(x) = <x,y>
   2. ∥f∥ = ∥y∥

   Эта теорема фактически отождествляет гильбертово пространство с его
   сопряженным (с пространством функционалов : X → ℝ).
*** Скетч
    Показываем 1 ⇒ 2 с помощью Шварца и определений. Доказываем первое
    через разложение на прямую сумму, выражаем f(x) как tf(e) и
    показываем y = f(e)/∥e∥²*e.
*** Доказательство
    * Сначала докажем, что из первого следует второе.

      f(x) = <x,y>. Тогда по неравенству Шварца: |f(x)| ≤ ∥y∥*∥x∥.
      Отсюда ∥f∥ ≤ ∥y∥.

      Возьмем x₀ = y/∥y∥. ∥x₀∥ = 1, |f(x₀)| = ∥y∥.

      Поскольку ∥f∥ = sup|f(x)|, ∥x₀∥ = 1, ∥f∥ ‌≤ ∥y∥, а
      значение |f(x)| может принимать ∥y∥, то верно также равенство
      ∥y∥ = ∥f∥.
    * H₁ = Ker(f) -- замкнуто. H₁ подпространство H. Возьмем H₂ как
      ортогональное дополнение к H₁.

      H₂ ≡ H₁⊥.

      Тогда H = H₁ ⊕ H₂. Codim(H₂) = Codim(H₁) = 1.

      Рассмотрим H₂ = {te, t∈ℝ, e∈H₂}. ∀x ∈ H, x = x₁ + te, где x₁ ∈
      H₁.

      f(x) = f(x₁) + tf(e) = tf(e).

      Рассмотрим y = αe, α∈ℝ; <x,αe> = <x₁+te,αe> = αt∥e∥².

      Тогда подберем такое α, чтобы ∀x ∈ H было верно f(x) = <x,αe>.

      Проверим tf(e) = αt∥e∥², откуда α = f(e)/∥e∥². Отсюда возьмем
      y = f(e)/∥e∥²*e. y будет искомым.
* Линейные ограниченные операторы
** 2 Линейный оператор, непрерывность, ограниченность, норма     :definition:
   * X, Y -- нормированные пространства, тогда A: X → Y называется
     линейным оператором, если A линейно. Если Y = ℝ, то A есть
     линенйый фукнционал.

     Все свойства функционала переносятся на оператор.
   * Следующие утверждения эквивалентны:
     1. A -- непрерывно
     2. ∀xₙ x, xₙ → x ⇒ Axₙ → Ax
     3. ∀xₙ, xₙ → 0 ⇒ Axₙ → 0 = A0.
   * А ограничен, если существует M, что ∀x ∈ X, ∥Ax∥ ≤ M∥x∥.
   * Ограниченность эквивалентна конечности ∥A∥ ≡ sup{∥x∥<1}∥Ax∥.
   * ∀x, ∥Ax∥ ≤ ∥A∥∥x∥. Доказательство эквивалентно тому для
     функцоналов.
   * Норма оператора -- норма.

     Проверяется руками. Например, ∥(A+B)(x)∥ ≤ ∥A∥∥x∥ + ∥B∥∥x∥ ≤
     ∥A∥ + ∥B∥ из линейности. Перейдем к sup, получим правило
     треугольника.
   * Непрерывность A эквивалентна ограниченности

     Доказательство копируется из предыдущего параграфа.
** 2 Пространство линейных операторов                            :definition:
   L(X,Y) -- линейное пространство линейных ограниченных операторов из
   X в Y, нормированное операторной нормой.
** 1 Банаховость в линейных операторах                              :theorem:
   Y -- B-пространство. Тогда L(X, Y) -- тоже B-пространство.

   В том числе верно и важное частное следствие:

   X -- нормированное пространство. ℝ -- полно. L(X, ℝ) -- тоже.

*** Скетч
    Куча тонких переходов :⌢(.
*** Доказательство
    Aₙ ∈ L(X, Y). ∥Aₙ - Aₘ∥ → 0, хотим показать, что ∃A ∈ L(X, Y):
    ∥Aₙ - A∥ → 0.

    Нам дана полнота (банаховость) Y: ∥Aₙ - A∥ → 0 ⇔ Aₙ ⇉V A,
    V = {x | ∥x∥ ≤ 1}.

    Напомним, что равномерная сходимость, это: ∀ε>0 ∃N, ∀n>N, ∀x ∈ V
    ∥Aₙx - Ax∥ < ε.

    ∀x ∈ X, ∥Aₙx - Ax∥ = ∥(Aₙ - A)x∥ ≤ ∥Aₙ - A∥∥x∥. Поскольку ∥Aₙ - A∥
    → 0, то Aₙx - Ax → 0. Отсюда по банаховости ∃limAₙx =: Ax.

    По арифметике предела A -- линейный оператор. Проверим, что он
    ограничен и является пределом Aₙ в L(X,Y).

    Возьмем x ∈ V. ∥Ax∥ ≤ ∥Aₙx - Ax∥ + ∥Aₙx∥, ∥Aₙx - Aₘx∥ ≤ ε (в силу
    сходимости в себе).

    Устремим тогда m → ∞. По непрерывности нормы и определению A
    имеем:

    ∥Aₙx - Ax∥ ≤ ε ⇒ ∥(Aₙ - A)x∥ ≤ ε. ∀x ∈ V.

    По открытости нормы оператора: ∀n > N, ∥Aₙ - A∥ ≤ ε.

    Отсюда Aₙ - A ограничен. Тогда A = Aₙ - (Aₙ - A). Разность
    ограниченых ограничена.

    Поскольку ∥Aₙ - A∥ ≤ ε и оба оператора ограничены, то A -- предел
    Aₙ.
** 2 Сопряженное пространство                                    :definition:
   X* = L(X, ℝ) -- пространство, сопряженное с X. В смысле предыдущей
   теоремы сопряжение любого пространства полно.
** Теорема Банаха-Штейнгауза                                        :theorem:
   X -- полное пространство. Y -- нормированное пространство. Aₙ ∈
   L(X,Y).

   ∀x∈X, sup{n}∥Aₙx∥ < +∞. -- последовательность операторов поточечно
   ограничена.

   Тогда sup{n}∥Aₙ∥ < +∞ -- равномерная ограниченность.

*** Доказательство
    По определению нормы покажем ∀x ∈ V, ∀n ∈ ℕ, ∥Aₙx∥ ≤ M.

    Пусть ∃Vᵣ(a): ∀x∈Vᵣ(a), n ∈ ℕ ⇒ ∥Aₙx∥ ≤ P.

    Тогда x = ry + a, y ∈ V, x ∈ Vᵣ(a), y = (x - a)/r.

    ∥Aₙy∥ = 1/r∥Aₙx - Aₙa∥ ≤ 1/r(∥Aₙx∥ + ∥Aₙa∥) ≤ 2P/r. Тогда теорема
    доказана. Нужно лишь показать факт с существованием сферы размера
    r.

    Докажем от противного: пусть такой сферы не существует, то есть
    для любой сферы значение ∥Aₙx∥ на ней неограничено.

    ∀Vᵣ₁(a₁) ∃n₁, ∃x₁∈Vᵣ₁(a), ∥Aₙ₁(x₁)∥ > 1. Но оператор Aₙ₁
    непрерывен. Тогда по непрерывности множество сохраняется в
    некотором шаре в x₁. Если же точка x₁ попала на границу множества,
    то немножко сузим шар, на котором мы ищем x₁, и тогда когда-нибудь
    он не будет на границе.

    ∃Vᵣ₂(x₁): ∀x ∈Vᵣ₂(x₁) ⇒ ∥Aₙ₁(x)∥ > 1.

    В нем тоже неверно, тогда ∃x₂∈Vᵣ₂(x₁): ∥Aₙ₂(x₂)∥ > 2, Vᵣ₃(x₂)...

    Можно считать, что радиусы уменьшаются всегда в два раза (все
    равно мы выбираем сами шары). По индукции получаем
    последовательность вложенных шаров с r → 0. Учитывая Банаховость
    пространства, есть принцип вложенности. Тогда на точке a = ∩Vᵢ
    выполняется:
    ∥Aₙₖ(a)∥ > k → ∞. Но sup∥Aₙx∥<+∞. Противоречие.
** Следствие                                                          :lemma:
   X, Y -- банаховы пространства. Aₙ ∈ L(X,Y). ∀x ∈ X Aₙx-Aₘx → 0.

   Тогда ∃A ∈ L(X,Y), что ∀x ∈ X Aₙx → Ax.

*** Доказательство
    Провести самостоятельно с помощью теоремы Б-Ш.
* Непрерывно обратимые операторы
** 2 Непрерывно обратимый оператор                               :definition:
   A ∈ L(X,Y), A:X → Y есть биекция. Тогда ∃A⁻¹:Y → X.
   Если A⁻¹ ограничен как оператор, то A -- непрерывно обратим.
** 2 Теорема Банаха о непрерывно обр. операторе                     :theorem:
   C ∈ L(X) := L(X,Y), ∥C∥ < 1. X -- банахово (тут и *далее*).

   Тогда I-C, где Ix = x непрерывно обратим.
*** Доказательство
    Рассмотрим ∑{∞}Cⁿ, Sₙ = ∑{k=0..n}Cᵏ. Sₙ(I-C) = Sₙ - Sₙ*C
    = I - Cⁿ⁺¹.

    Очевидно, если поменять местами множители, то ничего не изменится.

    ∥Cⁿ∥ ≤ ∥C∥ⁿ, ∑{∞}∥Cⁿ∥ ≤ ∑{∞}∥C∥ⁿ < +∞, так как ∥C∥ < 1.

    Тогда ∃S = ∑Cⁿ, S ограничен (по банаховости). Cⁿ → 0.
    Тогда рассмотрим равенство Sₙ(I-C)=I-Cⁿ⁺¹. Устремим n→∞.

    Получим S(I-C) = I. Аналогично (I-C)S = I.

    Тогда S = (I-C)⁻¹ ∈ L(X).
** Range, априорная оценка                                       :definition:
   * A: X → Y, тогда R(A) = {Ax, x ∈ X} -- линейное множество в Y.
   * Априорная оценка решения операторного уравнения.

     y ∈ R(A) ⇒ Ax = y имеет решение.

     Тогда говорят, что Ax = y допускает априорную оценку решений, если
     ∃α ∈ ℝ > 0, что ∥x∥ ≤ α∥y∥.
** Теорема об априорной оценке                                      :theorem:
   A непрерывен и имеет априорную оценку для своих решений, тогда множество
   R(A) замкнуто.
* X Спектр ограниченного оператора
  По умолчанию тут и далее все пространства банаховы (нормированы +
  полны в смысле метрики).
** 2 Резольвентный оператор, регулярная точка, спектр            :definition:
   Пусть A: X → X -- линейно ограничен (другими словами A ∈ L(X,X)), λ ∈
   ℂ, I -- единичная матрица (оператор).

   Рассмотрим A - λI.
   * Если при заданном λ, A - λI непрерывно обратим, то Rλ(A) =
     (A-λI)⁻¹ называется резольвентным оператором, а λ -- регулярной
     точкой оператора A.
   * ρ(A) = {все регулярный точки A} -- резольвентное множество.
   * σ(A) = ℂ\ρ(A) -- спектральное множество (спектр).
** 1 Открытость ρ(A)                                                :theorem:
   ρ(A) открыто в ℂ.

*** Доказательство
    Проверим открытость из определения: ∀λ₀ ∈ ρ(A), ∃δ>0 что ∀λ |λ-λ₀| <
    δ, λ∈ρ(A). Типа каждая точка входит с некоторой окрестностью,
    полностью принадлежащей этому множеству.

    (A - λI) =
    (A - λ₀I) - (λ - λ₀)I =
    {I = (A - λ₀I)Rλ₀(A)} =
    (A - λ₀I) - (λ - λ₀)(A - λ₀I)Rλ₀(A) =
    (A - λ₀I)(I - (λ - λ₀)Rλ₀(A)).

    В последнем выражении обозначим первый множитель за I, второй за
    II.

    I непрерывно обратим, так как λ₀∈ρ(A).

    Если |‌λ-λ₀|∥Rλ₀(A)∥ < 1, то II тоже непрерывно обратим по теореме
    Банаха об обратимом операторе. Это будет верно при δ=∥Rλ₀(A)∥⁻¹.

    Тогда произведение двух непрерывно обратимых множителей непрерывно
    обратимо, отсюда λ ∈ ρ(A).
** 1 Лемма о спектре                                                  :lemma:
   σ(A) ⊂ {λ: |λ| ≤ ∥A∥}.

*** Доказательство
    Пусть |λ| > ∥A∥. Покажем, что λ ∈ ρ(A).

    A - λI = -λ(I - A/λ). Поскольку ∥A/λ∥ < 1, то A - λI непрерывно
    обратимо и λ ∈ ρ(A).
** 2 Спектральный радиус                                         :definition:
   rσ(A) = inf{n∈ℕ}(∥Aⁿ∥)^{1/n} -- спектральный радиус оператора.

   Заметим, что ∥Aⁿ∥ ≤ ∥A∥ⁿ ⇒ rσ(A) ≤ ∥A∥ в общем случае.
** X Свойства спектрального радиуса                                 :theorem:
   1. rσ(A) = lim{n→∞}(∥Aⁿ∥)^{1/n}
   2. σ(A) ⊂ {λ: |λ| ≤ rσ(A) }

*** Доказательство
    1. По определению нижней грани ∀ε ∃n₀ : ∥Aⁿ⁰∥^{1/n₀} < rσ + ε.

       ∀n > n₀ n = pₙ∙n₀ + dₙ (dₙ -- остаток), причем dₙ ∈
       {0,1,...n₀-1}.

       : ∥Aⁿ∥^{1/n} = ∥A^{pₙ∙n₀+dₙ}∥^{1/n} ≤
       : ≤ (∥A^n₀∥^pₙ * ∥A∥^dₙ)^{1/n} =
       : = (∥A^n₀∥^(1/n₀))^(n₀pₙ/n) * ∥A∥^(dₙ/n) ≤ (rσ+ε)^(1+ε)
       :      ^ < rσ+ε        ^ ≤ 1    →1

       Также rσ ≤ ∥Aⁿ∥^{1/n}. Отсюда равенство выполнено.
    2. A - λI = -λ(I - A/λ). Операторный ряд -- ∑∞ Aⁿ/(λⁿ). Он же, но
       из норм: ∑∥Aⁿ∥/|λⁿ| -- сходится с радиусом сходимости
       1/lim{∥Aⁿ∥}^(1/n) (это какое-то тфкп).

       ??? Чего???? Где здесь вообще фигурирует единица из теоремы
       Банаха? Как вообще связаны радиусы сходимости?

       Тогда по теореме Банаха  |λ| < lim{∥Aⁿ∥^{1/n}} = rσ.
** 2 Пример грубой оценки спектра                                   :example:
   Рассмотрим l₂ и отображение A: (x₁,x₂,..) ↦
   (0,x₁,x₂,...). Очевидно, что ∥Ax∥ = ∥x∥ и ∥Aⁿx∥ = ∥x∥. ОТсюда ∥Aⁿ∥
   = 1, rσ = 1 по предыдущей теореме.

   Найдем теперь спектр непосредственно.

   * λ = 0 ∈ σ(A), потому что A не непрерывно обратим.
   * λ ≠ 0, тогда можно показать (достаточно легко по теореме Банаха о
     непрерывном операторе), что λ ∈ ρ(A), то есть σ(A) = {0}, хотя
     rσ=1.

   Оценка вышла достаточно грубой.
** 2 Лемма Абеля                                                      :lemma:
   Главная мысль -- это то, что во всех операторных рядах λ∈ℂ, поэтому
   к ним можно применять логику из ТФКП. Напомним одну из основных
   теорем ТФКП:

   Если ∑∞ Aₙλ₀ⁿ сходится, то ∀λ : |λ|<|λ₀| ∑∞ ∥Aₙ∥|λⁿ| сходится.

*** Доказательство
    ∥Aₙ∥|λ|ⁿ = ∥Aₙλ₀ⁿ∥(|λ|/|λ₀|)ⁿ < (|λ|/|λ₀|)ⁿ, потому что ∥Aₙλ₀ⁿ∥ → 0.
** 1 Теорема Лиувиля
   f(x) = ∑aₙλⁿ -- аналитическая функция с бесконечным радиусом
   сходимости, |f(λ)| ≤ M. Тогда f ≡ const.

   Без д-ва.
** 1 О спектре ограниченного оператора                              :theorem:
   ∀A ∈ L(x), σ(A) ≠ ∅.

*** Доказательство
    Рассмотрим Rλ(A) = (A-λI)⁻¹, λ∈ρ(A), A-λI = {преобразования из
    леммы про открытость ρ(A)} = (A-λ₀I)(I-(λ-λ₀)Rλ₀(A)).

    От противного. Пусть σ(A) = ∅.

    Тогда (I - (λ-λ₀)Rλ₀(A))⁻¹ = ∑∞ Rλ₀ⁿ(A)(λ-λ₀)ⁿ

    При больших λ рассмотрим Rλ(A) = (A-λI)⁻¹ = (λ(I-A/λ))⁻¹ = -λ∑Aₙ/λⁿ
    -- аналитическая в бесконечной точке функция. Тогда по теореме
    Лиувиля Rλ(A) = const, но это противоречие.

    Отсюда σ(A) ≠ ∅.
* Сопряженный оператор
** 1 Сопряженный оператор                                        :definition:
   1. X -- нормированное пространство, X* -- ему сопряженное,
      A ∈ L(X,Y),
      φ ∈ Y*, ∀x ∈ X f(x) = φ(Ax). Очевидно, что f ∈ X*.

      Получаем φ ∈ Y* ↦ f = φ∘A ∈ X*.

      Это отношение порождает A*: Y* → X*, A*(φ) = φ₀A.
   2. ∀x ∈ H*, f(x) = <x,y>, ∥f∥ = ∥y∥ (теорема Рисса для Гильбертовых пр-в)

      A: H₁ → H₂, A*: H₂* → H₁*: <Ax,y> = <x,A*y>.

      Оператор H₂ берет функцию f ∈ H₂*, возвращает f∘A -- оператор из H₁*.
** 1 Примеры сопряженных операторов                                 :example:
   1. ПТУшный пример. Поскольку Rⁿ является гильбертовым
      пространством, то для оператора A: Rⁿ → Rⁿ, A* = Aᵀ. Более того,
      если A симметрична, то A самосопряжен, так как A = A*.
   2. eₙ = (0,...1,..0) -- на n-м месте 1, все ост. нули.

      x~ = ∑∞ xₙeₙ, xₙ = <x~,eₙ>

      λₙ: |λₙ| ≤ M, Ax~ = ∑∞ λₙxₙeₙ  ∈ l₂.

      A: l₂ → l₂, A*y = ∑λₙ~yₙeₙ. (типа комплексное сопряжение λ).

      Тогда действительно <Ax,y> = <x,A*y>
** 1 Утверждение о равенстве норм сопряженного и обычного операторов :theorem:
   ∥A*∥ = ∥A∥

*** Доказательство
    f = A*φ = φ∘A, |f(x)| = |φ(Ax)| ≤ ∥φ∥∥Ax∥ ≤ ∥φ∥∥A∥∥x∥

    Тогда по определению ∥f∥ ≤ ∥A∥∥φ∥ или ∥A*φ∥ ≤ ∥A∥∥φ∥.
    Отсюда ∥A*∥ ≤ ∥A∥.

    Проверим обратное (∥A*∥ ≥ ∥A∥).

    A = sup{∥x∥≤1}∥Ax∥. По опреелению верхней грани ∀ε>0 ∃xₑ:∥xₑ∥ = 1:
    ∥A∥ - ε < ∥Axₑ∥.

    Тогда по следствию из теоремы Хана-Банаха можем подобрать φ:
    ∥φ∥ = 1, φ(Axₑ) = ∥Axₑ∥.

    ∥A∥ - ε < |φ(Axₑ)| = |A*φ(xₑ)| ≤ ∥A*φ∥∥xₑ∥ = ∥A*φ∥ ≤ {∥φ∥ = 1} ≤ ∥A*∥.

    И получили ∥A - ε∥ ≤ ∥A*∥. ε → 0 ⇒ ∥A∥ ≤ ∥A*∥.
** 2 Ортогональные дополнения                                    :definition:
   X,X*:
   1. ∀S ⊂ X, S⊥ = {f ∈ X*: ∀x ∈ S ⇒ f(x) = 0}
   2. ∀S ⊂ X*, S⊥ = {x ∈ X*: ∀f ∈ S ⇒ f(x) = 0}
** 2 Свойства ортогональных дополнений                                :lemma:
   1. ∅ ∈ X ⇒ {∅}⊥ = X*.
   2. const 0 ∈ X* ⇒ {const 0}⊥ = X.

   Утверждения очень очевидные и простые, достаточно лишь понять, что
   такое {∅}⊥ и {константная функция 0}⊥.

   1. {∅}⊥ = {f ∈ X* : f(∅) = 0} = {линейные операторы из X в ℝ} = X*;
   2. {const 0}⊥ = {x ∈ X : (const 0)(x) = 0} = {x ∈ X} = X;
** 1 Теорема о ортогональном сопр. ядра сопряженного оператора      :theorem:
   A: X → Y, R(A) (range) замкнут, тогда Cl(R(A)) = (Ker(A*))⊥.

*** Доказательство
    Поскольку R(A) = CL(R(A)), то y ∈ R(A) эквивалентно y = Ax.

    R(A) = (Ker(A*))⊥ означает, что ∀φ ∈ Ker(A*) A*φ = 0.

    f = A*φ, f = φ∘A, φ∘A = 0; ∀x ∈ X φ(Ax) = 0, y = Ax, φ(y) = 0.

    Итого R(A) ⊂ (Ker(A*))⊥. Проверим обратное включение.

    От противного -- предположим строгое включение R(A) ⊂
    (Ker(A*))⊥. Тогда y₀ ∈ (Ker(A*))⊥, y₀ ∉ R(A).

    Y~ = {y+αy₀, y∈R(A), α∈ℝ} -- линейное множество в Y (замкнутое
    подпространство).

    y ∈ Cl(R(A)), y = lim(yₙ), yₙ ∈ R(a), yₙ ∈ (Ker(A*))⊥ -- замкнутое
    множество. Тогда и y ∈ (Ker(A*))⊥.

    Определим на Y~ функционал: z=y+αy₀ ∈ Y~, φ₀(z) = α -- очевидный
    линейный функционал. По теореме Хана-Банаха продолжим непрерывно
    его на Y. Обозначим так же (φ₀). φ₀(y₀) = 1 по определению (y₀ =
    0 + 1*y₀).

    y ∈ R(A) ⇒ φ₀(y) = 0, то есть φ₀ ∈ Ker(A*). Но y₀ ∈ (Ker(A*))⊥,
    откуда φ₀(y₀) = 0, что противоречит φ₀(y₀) = 1.
** Теорема о range сопряженного оператора                           :theorem:
   A: X → Y, R(A) замкнут, тогда R(A*) = (Ker(A))⊥

*** Доказательство
    f ∈ R(A*) = A*φ, f(x) = φ(Ax).

    f ∈ (Ker(A))⊥, Ax = 0 ⇒ f(x) = 0.

    Если мы хотим показать f ∈ R(A*), запишем в виде f = φ∘A.

    ∀y ∈ R(A), y = Ax (в общем случае представление не
    единственно). Пусть φ(y) = f(x).

    Покажем, что формула корректна: при y = Ax', φ(y) = f(x') хотим
    получить f(x) = f(x'). Ax = Ax' ⇒ A(x-x') = 0 ⇒ (x-x') ∈ KerA,
    f(x-x') = 0, что и требовалось.

    Проверим, что φ ограничен на R(A): y = Ax, φ(y) = f(x), f ∈
    (Ker(A))⊥. Заметим, что из ограниченности f следует то, что
    нужно. Ограниченность покажем с помощью теоремы Банаха о
    гомоморфизме:

    Заметим, что |φ(y)| = |f(x)| ≤ ∥f∥∥x∥                   (*)

    (здесь и далее какие-то отсылки к последней лекции 5 семестра,
    которую Додонов не читал, а выслал сканы)

    Воспользуемся ассоциативным оператором:

    X →i→ X/Ker(A) →Uₐ→ Y. X →A→ Y. (тут /Ker -- это факторизация по ядру)

    A = Uₐ∘i ← непрерывная биекция факторпространства на Y.

    Тогда по теореме Банаха о гомоморфизме у него существует
    непрерывный обратный.

    ξ ∈ X|KerA|, [x] = i(x), ∥ξ∥ = inf{x∈ξ}∥x∥; ∀ε>0, ∃x∈ξ, ∥x∥<∥ξ∥+ε.

    φ(y) = f(x), правая часть одна и та же ∀x∈ξ.

    Возвращаясь к (*), |φ(y)| ≤ ∥f∥(∥ξ∥ + ε).

    ∃Uₐ⁻¹, |f(y)| ≤ ∥f∥M∥y∥ -- ограничен. f ∈ R(A*), f = φ∘A, Ax = 0.

    итого f(x) = φ(Ax) ⇒ φ(0) = 0.
* Теория Фредгольма-Шаудера
** Вполне непрерывный оператор                                   :definition:
   A: X → Y называется вполне непрерывным, если ∀M ограниченный в X
   переводится в относительно компактное в Y.

   X называется относительно компактным, если Cl(X) компактно.

   ∀M ограниченного в X, Cl(A(M)) -- компакт в Y. Легко понять, что
   любой вполне непрерывный оператор также непрерывен.
** Вполне непрерывность композиции                                    :lemma:
   A -- вполне непрерывен, B ограничен. Тогда AB, BA вполне
   непрерывны, если композиция имеет смысл вообще.

*** Доказательство
    1. A,B вполне непрерывны. M ограничен в X. AB(M) = A(B(M)). B(M)
       ограничен, а A(B(M)) тогда относительно компактен. Все супер.
    2. Что можно сказать про относительную компактность B(A(M))?

       A(M) -- относительно компактен. ∀ε > 0, ∃y₁..yₙ ∈ Y:
       ∀x ∈ M, ∃yⱼ ∥yⱼ - Ax∥ < ε.

       Пусть zⱼ = B(yⱼ). ∀z ∈ BA(M), z = B(Ax), x ∈ M.

       Тогда ∥z - zⱼ∥ = ∥B(Ax - yⱼ)∥ ≤ ∥B∥∥Ax - yⱼ∥ ≤ ∥B∥ε.

       Такая новая конечная ε-сеть подходит.
** Отсутствие обратного оператора у вполне непрерывного                :note:
   A -- вполне непрерывный. Тогда покажем, что не существует
   ограниченного обратного оператора к A.

   Помним, что S ⊂ X -- бесконечномерная сфера, не является
   компактом.

   От противного, пусть ∃A⁻¹, ограничен. I = A⁻¹∙A -- вполне
   непрерывный, IV = V. Противоречие.
** Предел вполне непрерывных операторов                               :lemma:
   Aₙ → A в L(X,Y), тогда из вполне непрерывности Aₙ следует вполне
   непрерывность A.

*** Доказательство
    Раз любое ограниченное множество можно поместить в шар, то вполне
    непрерывность можно проверять на единичном шаре в качестве
    входного значения для оператора.

    V, A(V) -- относительно компактно.

    ∀ε > 0, ∃n₀, (∥Aₙ₀ - A∥ ≤ ε ⇔ ∀x ∈ V, ∥Aₙ₀x - Ax∥ ≤ ε).

    y₁...yₙ -- ε-сеть для Aₙ₀(V). ∀y ∈ A(v), y = Ax, x ∈ V.

    Для Aₙ₀-yⱼ: ∥Aₙ₀x - yⱼ∥ ≤ ε, ∥yⱼ-Ax∥ ≤ ∥yⱼ - Aₙ₀x∥ + ∥Aₙ₀x-Ax∥ ≤
    2ε.

    yᵢ -- нормальная ε-сеть и для A.
** Пример вполне непрерывного оператора                             :example:
   C[0,1], K(u,v) -- непрерывен на [0,1]².

   A(f,x) = ∫{0,1} K(x,t)f(t)dt. |f(t)| ≤ 1, t ∈ [0,1].

   Есть такая теорема Арцелла-Асколи:
   M ⊂ C[0,1] эквивалентно следующим двум утверждениям:
   1. ∃m: ∀f∈M, ∀t∈[0,1], |f(t)| ≤ m.
   2. ∀ε>0, ∃δ>0, ∀f∈M, |t₂-t₁|<δ ⇒ |f(t₂)-f(t₁)| ≤ ε.

   Второе свойство теоремы -- равноступенная непрерывность.

   Так вот по этой теореме: |A(f,x)| ≤ ∫{0,1} |K(x,t)||f(t)|dt.
   Заметим, что |f(t)| ≤ 1, а |K(x,t)| ограничен m.

   Тогда |A(f,x₂)-A(f,x₁)| ≤ ∫{0,1} |K(x₂,t)-K(x₁,t)||f(t)|dt ≤ ε.

   (модуль разности K очень маленький в силу теоремы А-А)
** Размерность ядра оператора                                       :theorem:
   dim(Ker(T)) < +∞

*** Доказательство
    x ∈ KerT ⇒ X - Ax = 0 ⇒ x = Ax. Ядро совпадает с совокупностью
    непрерывных точек A.

    Раз A -- вполне непрерывен, то образ единичного шара относительно
    компактен, а тогда для бесконечномерного пространства шар не
    является компактом, то есть пересечение шара с множеством
    неподвижных точек -- компакт, значит пересечение конечномерно.
