#+TODO: X 0 1 2 | OK
#+TITLE: Укороченная версия конспекта, только определения и формулировки

* Definitions list
  |----------------------------------------------------------------+---+---+---+---+---+---|
  | Метрика, метрическое пространство                              |   |   |   |   |   |   |
  | Предел по метрике                                              |   |   |   |   |   |   |
  | Топологическое пространство, топология                         |   |   |   |   |   |   |
  | Открытое множество, замкнутое множество                        |   |   |   |   |   |   |
  | Предел в смысле ТП                                             |   |   |   |   |   |   |
  | Открытый шар                                                   |   |   |   |   |   |   |
  | Метрика Урысона                                                |   |   |   |   |   |   |
  | Внутренность, граница, замыкание                               |   |   |   |   |   |   |
  | МП полнота                                                     |   |   |   |   |   |   |
  | Всюду плотность, не плотность                                  |   |   |   |   |   |   |
  | Категории по Бэру                                              |   |   |   |   |   |   |
  | Компакты и предкомпакты                                        |   |   |   |   |   |   |
  | Норма, нормированное пространство, предел в НП                 |   |   |   |   |   |   |
  | Эквивалентность норм                                           |   |   |   |   |   |   |
  | Линейное подмножество и подпространство                        |   |   |   |   |   |   |
  | Банахово пространство                                          |   |   |   |   |   |   |
  | Унитарное пространство, примеры                                |   |   |   |   |   |   |
  | Неравенство Шварца                                             |   |   |   |   |   |   |
  | УП как частный случай НП                                       |   |   |   |   |   |   |
  | Ортогональность, равенство пифагора                            |   |   |   |   |   |   |
  | Ортонормированная система векторов                             |   |   |   |   |   |   |
  | Ортогональный рфд                                              |   |   |   |   |   |   |
  | Фурье: коэффициент, ряд                                        |   |   |   |   |   |   |
  | Наилучшее приближение                                          |   |   |   |   |   |   |
  | Гильбертово пространство, примеры                              |   |   |   |   |   |   |
  | Полная, замкнутая ОНС                                          |   |   |   |   |   |   |
  | Сепарабельность                                                |   |   |   |   |   |   |
  | Разложение в прямую сумму                                      |   |   |   |   |   |   |
  | Счетно-нормированное пространство, предел                      |   |   |   |   |   |   |
  | Метрика в СНП                                                  |   |   |   |   |   |   |
  | Пример СНП                                                     |   |   |   |   |   |   |
  | Монотонная система полнунорм, эквивалентность и существенность |   |   |   |   |   |   |
  | Поглощение, радиальность, закругленность                       |   |   |   |   |   |   |
  | Функционал Минковского                                         |   |   |   |   |   |   |
  | Фактор-множество, коразмерность                                |   |   |   |   |   |   |
  | Гиперплоскость, линейный функционал, ядро                      |   |   |   |   |   |   |
  | Топологическое векторное пространство, место в систематике     |   |   |   |   |   |   |
  | База окрестностей нуля                                         |   |   |   |   |   |   |
  | Линейный оператор (непр., огр., норма)                         |   |   |   |   |   |   |
  | Пространство линейных операторов                               |   |   |   |   |   |   |
  | Сопряженное пространство                                       |   |   |   |   |   |   |
  | Непрерывно обратимый оператор                                  |   |   |   |   |   |   |
  | Range, априорная оценка                                        |   |   |   |   |   |   |
  | Резольвентный оператор, множество, cпектр                      |   |   |   |   |   |   |
  | Спектральный радиус                                            |   |   |   |   |   |   |
  | Сопряженный оператор                                           |   |   |   |   |   |   |
  | Ортогональные дополнения                                       |   |   |   |   |   |   |
  | Вполне непрерывность, относительная компактность               |   |   |   |   |   |   |
  |----------------------------------------------------------------+---+---+---+---+---+---|
* Метрические пространства
** Метрика, метрическое пространство                             :definition:
   X, ρ: X×X → ℝ+ -- метрика, если:
   1. ρ(x, y) ≥ 0; ρ(x, y) = 0 ⇔ x = y
   2. ρ(x, y) = ρ(y, x)
   3. ρ(x, y) ≤ ρ(x, z) + ρ(z, y)

   Метрическое пространство -- пара <X, ρ>.
** Предел по метрике                                             :definition:
   x = lim(xₙ) ⇔ ρ(xₙ, x) → 0
** Топологическое пространство, топология                        :definition:
   Топологическое пространство (ТП) -- пара <X, Τ>, где X --
   множество, T ⊃ 2ˣ -- топология, если выполнено:
   1. Замкнутость T по объединению
   2. Замкнутость T по конечному пересечению
   3. X, ∅ ∈ T
** Открытое множество                                            :definition:
   Множество открыто, если принадлежит топологии T.
** Предел в смысле ТП                                            :definition:
   <X,T>
   x = lim(xₙ) ⇔ ∀G ∈ T : x ∈ G, ∃N: ∀n > N xₙ ∈ G
** Замкнутость через открытость                                  :definition:
   G -- открытое в T, тогда F = X \ G замкнутое
** Открытый шар, представимость T                                :definition:
   * Bᵣ открытый шар в центре a = {x: ρ(x, a) < r}
   * T = {∪Bᵣ(a)}
** Связь МП и ТП                                                  :statement:
#   b ∈ Bᵣ₁(a₁) ∩ Bᵣ₂(a₂) ⇒ ∃ r > 0, Bᵣ(b) ⊃ (Bᵣ₁(a) ∩ Bᵣ₂(a))
   Будем называть G открытым, если ∀x ∈ G, ∃Bᵣ(x) ⊂ G. Множество всех
   открытых множеств будет образовывать топологию. Открытые шары в МП
   -- открытые множества.

   В этом смысле метрические пространства оказываются частным случаем
   топологических.
** Примеры МП (ℝ, ℝⁿ, ℝ∞, м.Урысона)                                :example:
   1. ℝ, ρ(x, y) = |x - y|
   2. ℝⁿ, x~ = (x₁...xₙ) ∈ ℝⁿ
      ρ(x~, y~) ≡ √(∑{n}(xᵢ - yᵢ)²)
      αx~ = (αx₁...αxₙ)
      x~ + y~ = (x₁ + y₁, ...)
      xₙ~ → x~ ⇔ ∀j=1..n xⱼᵐ → xⱼ
   3. ℝ∞, xₘ~ → x~ ≡ ∀i=1,2,3..., xⱼᵐ → xⱼ
      Метрика Урысона:
      ρ(x~, y~) ≡ ∑{∞}(1/2ⁿ * |xₙ - yₙ|/(1 + |xₙ - yₙ|), где
      φ(t) = t/(1+t), то есть ρ(x~, y~) = ∑{∞}(1/2ⁿ * φ(|xₙ-yₙ|)).

      Кстати, для φ верно:
      Φ(t₁ + t₂) ≤ φ(t₁) + φ(t₂)

      ρ(xₘ~, x~) → 0 ⇔ ∀j xⱼᵐ → xⱼ
      Таким образом ℝᵐ метризуемо.
   4. Дискретная метрика
      ρ(x,y) = if x = 0 then 0 else 1
      xₘ → x, ε = 1/2, ∃M : ∀m > M ⇒ ρ(xₘ,x) < 1/2 ⇒ ρ(xₘ, x) = 0 ⇒
      xₘ = x
      То есть в такой метрике сходятся только последовательности,
      стабилизирующиеся после некоторого элемента -- стационарные.
** Внутренность, замыкание, граница                              :definition:
   (X, T), ∀A ⊂ X:
   1. Int(A) ≡ ∪{G | G ⊂ A, G открытое}
   2. Cl(A)  ≡ ∩{F | F ⊃ A, F замкнутое}
   3. Fr(A)  ≡ Cl(A) \ Int(A)

   По аксиомам топологии ∀A Int(A) открытое, Cl(A) замкнутое
** Расстояние до множества, между множествами                    :definition:
   ρ(x, A) ≡ inf{ρ(x, a) | a ∈ A}
   ρ(A, B} ≡ inf{ρ(a, b) | a ∈ A, b ∈ B}
** Непрерывность расстояния до множества                              :lemma:
   Пусть f(x) ≡ ρ(x, A), x ∈ X.
   Тогда f непрерывно на X
** Связь Cl, ρ                                                    :statement:
   x ∈ Cl(A) ⇔ ρ(x, A) = 0
** Нормальность МП                                                  :theorem:
   Любое МП -- нормальное пространство.
   ∀ F₁, F₂ ∈ X (F₁ ∩ F₂ = ∅, оба замкнутые)
   ∃ открытые непересекающиеся G₁ G₂, что F₁ ⊂ G₁, F₂ ⊂ G₂.
** МП-Полнота                                                    :definition:
   ρ(xₙ, xₘ) → 0 ⇒ ∃x = lim xₙ
** Принцип вложенности шаров                                        :theorem:
   X -- полное МП, V_2m : V_2n+1 ⊂ V_2n, 2n → 0 -- система замкнутых
   шаров.

   Тогда ∩V_2n = {a}.
** Всюду плотность, всюду не плотность                           :definition:
   * А всюду плотно в X если X -- МП, A ⊂ X, Cl(A) = X.
   * А нигде не плотно, если Int(Cl(A)) = ∅.

   Легко показать, что в МП нигде не плотность значит, что в любом
   шаре V ∃V' ⊂ V, что в V' нету точек множества A.

   Пример: Int(ℝ) = ∅.
** Категории по Бэру                                             :definition:
   X -- множество 1 категории по Бэру, если его можно записать в виде
   не более чем счетного объединения Xₙ, где каждый xᵢ не плотен в X.
   Любой другой X -- множество 2 категории.
** Теорема Бэра о категориях                                        :theorem:
   Полное МП является множеством 2 категории. (в себе).
** Следствие из теоремы Бэра о категориях                           :lemma:
   Полное МП без изолированных точек несчетно

** Компакты и предкомпакты                                     :definition:
   Множество K, удовлетворяющее обеим аксиомам -- компакт, а только
   второй -- предкомпакт:
   1. K -- замкнуто (K = Cl(K))
   2. xₙ ∈ K, ∃ n₁ < n₂ < ...
      xₙⱼ -- сходится в K по метрике ρ
** Теорема Хаусдорфа                                              :theorem:
   X -- полное МП, K ⊂ X, K замкнуто.
   Тогда:
   K компактно ⇔ K вполне ограничено

   Вполне ограниченность: ∀ε>0 ∃a₁..aₙ, что ∀b∈K ∃aⱼ ρ(b,aⱼ) < ε;
   построение для вполне ограниченности называется конечной ε-сетью.
* Нормированные пространства
** Нормированное пространство, норма                           :definition:
   Нормированное пространство -- (X, ∥ ∥), где второе -- норма:
   φ: X → ℝ -- норма на X (φ(x) = ∥x∥), если:
   1. φ(x) ≥ 0; φ(x) = 0 ⇔ x = ∅
   2. φ(αx) = |α|φ(x)
   3. φ(x+y) ≤ φ(x) + φ(y)

   Заметим, что в нормированных пространствах метрика порождается
   нормой, то есть:
   ρ(x, y) ‌≡ ∥x - y∥.
   Тогда НП -- частный случай МП.
** Пределы в НП                                                :definition:
   x = lim(xₙ) ⇔ ρ(xₙ, x) → 0 ⇔ ∥xₙ - x∥ → 0.
** Непрерывность линейных операций в топологии НП                   :lemma:
   В топологии НП линейные операции на X непрерывны.
** Примеры НП (lₚ, Lₚ)                                            :example:
   1. ℝⁿ, метрики l₁, l₂, l∞ -- в общем случае по lₚ варианту:
      ∥x∥ₚ = (∑(xₖ)ᵖ)^(1/p).
      ∥x∥∞ = sup{x₁...xₙ}
   2. C[a, b] -- функции непрерывные на отрезке.
      ∥f∥ = max{x∈[a,b]}|f(x)|
   3. Lₚ(E) -- известный пример, метрика -- (∫X |f|ᵖ)^(1/p)
** Эквивалентность норм                                        :definition:
   Нормы φ₁ и φ₂ экивалентны (φ₁ ~ φ₂), если у них одинаковая
   сходимость, то есть ∀{xₙ} (xₙ →φ₁ x) & (xₙ →φ₂ x).
   Проверка на экивалентность также можно сделать следующим образом:
   ∃a,b > 0, ∀x∈ X a∥x∥₁ ≤ ∥x∥₂ < b∥x∥₁, где нижний индекс -- номер
   метрики.
** Пример эквивалентных метрик в ℝⁿ                               :example:
   Построим единичную окружность по метрикам l₁, l₂, l∞.
   Нетрудно проверить, что все они эквивалентны, то есть множества
   сходимых по ним последовательностей равны.
** Теорема Рисса                                                  :theorem:
   dim(X) < +∞, тогда любые 2 нормы в X эквивалентны.
** Линейное подмножество, линейное подпространство             :definition:
   1. Линейное подмножество -- множество точек замкнутых относительно
      операций умножения на скаляр и сложения.
   2. Линейное подпространство -- замкнутое линейное подмножество.
** Следствие из теоремы Рисса о замкнутости                       :theorem:
   X -- НП, Y -- линейное подмножество X, dim Y < +∞.
   Тогда Y = Cl(Y), то есть Y замкнуто.
** Банахово пространство                                       :definition:
   Банахово пространство -- НП, полное в смысле метрического
   пространства. Сокращенно -- B-пространство.
** Абсолютная сходимость в B-пространствах                          :lemma:
   X -- B-пространство. Тогда ∑∥xₙ∥ → 0 ⇒ ∑xₙ сходится.
** Лемма Рисса о перпендикуляре                                   :theorem:
   * X -- НП.
   * Y -- собственное подпространство (линейное замкнутое множество)

   Тогда ∀ε ∈ (0,1), ∃zₑ ∈ X:
   1. zₑ ∉ Y
   1. ∥zₑ∥ = 1
   2. ρ(zₑ, Y) > 1 - ε
** Некомпактность единичное сферы в бесконечномерном пространстве :theorem:
   Пусть dimX = +∞.
   S -- единичная сфера.
   Тогда S -- не компакт.
* Унитарные пространства
** Унитарное пространство                                      :definition:
   X -- линейное множество над полем ℝ, φ: X×X → ℝ.
   φ удовлетворяет свойствам:
   1. φ(x, x) ≥ 0. φ = 0 ⇔ x = 0.
   2. φ(x, y) = φ(y, x)
   3. φ(αx + βy,z) = αφ(x, z) + βφ(y, z).

   φ называется скалярным произведением, нотация: <x,y> ≡ φ(x,y).
   Пара (X, <,>) -- унитарное пространство.
** Пример унитарного пространства                                 :example:
   ℝⁿ: <x,y> = ∑{i=1..n}xᵢyᵢ.
** Неравенство Шварца                                               :lemma:
   ∀x,y ∈ X, |<x,y>| ≤ √(<x,x>) * √(<y,y>).

   Отметим, что для ℝⁿ неравенство Шварца есть неравенство Коши для
   сумм:
   * |∑aᵢbᵢ| ≤ √(∑aᵢ²) * √(∑bᵢ²)
** Порождение нормы скалярным произведением                         :lemma:
   Определим ∥x∥ следующим образом:
   * ∥x∥ = √(<x,x>).
   * Доказательство аксиомы 3 (первые две тривиально):
     ∥x + y∥² = ∥x∥² + 2<x,y> + ∥y∥² ≤ {Шварц} ≤ (∥x∥ + ∥y∥)².
   * Отсюда УП -- частный случай НП. Заметим, что не всякая норма
     удовлетворяет свойству скалярного произведения, так что обратное
     неверно.
** Ортогональность, р-во Пифагора                              :definition:
   Определим отношение ортогональности на векторах:
   * x ⊥ y ≡ <x,y> = 0.
   Отсюда мгновенно (с помощью Шварца) получаем:
   * x ⊥ y ⇒ ∥x+y∥² = ∥x∥² + ∥y∥².
** Равенство параллелограмма                                        :lemma:
   ∀x,y ∥x+y∥² + ∥x-y∥² = 2∥x∥² + 2∥y∥².

   Отдельно отметим, что:
   * Метрика порождает скалярное произведение ⇔ для нее выполнено
     равенство параллелограмма.
** Ортонормированная система векторов, ЛНЗ                     :definition:
   {eᵢ...eₙ(...)} -- возможно бесконечный набор векторов со
   свойствами:
   1. ∥eᵢ∥ = 1.
   2. ∀i,j, i ≠ j ⇒ eᵢ ⊥ eⱼ

   Что такое ЛНЗ все знают. Напомним, что существует процесс
   нормализации Грамма-Шмидта (курс линейной алгебры 1-2 сем. КТ),
   который любой ЛНЗ набор превращает в ортонормированный.
** Ортогональный ряд                                           :definition:
   ∑xⱼ ортогональный, если ∀i≠j xᵢ ⊥ xⱼ.
   Удобное свойства ортогонального ряда (Sₘ -- частичная сумма):
   ∥Sₘ∥² = <∑, ∑> = ∑∥xᵢ∥².
** Коэффициент, ряд Фурье                                      :definition:
   Пусть x ∈ X, {eᵢ} -- ОНС.
   Тогда <x,eᵢ> -- коээфициент Фурье элемента x.
   ∑{eᵢ} <x,eᵢ>eᵢ -- ряд Фурье.
   Ряд фурье -- частный случай ортогональных рядов.
** Наилучшее приближение                                       :definition:
   X -- НП, Y -- его подпространство.
   ∀x ∈ X, E_Y(x) ≡ ρ(x, Y) = inf{y ∈ Y}∥x-y∥.
   E_Y(x) -- наилучшее приближение x точками из Y.

   При этом элемент наилучшего приближения:
   ∀x ∈ X, E_Y(x) = ∥x - y*∥.
** Теорема Бореля                                                 :theorem:
   dimX < +∞ ⇒ ∀x ∈ X, ∃y* ∈ Y -- элемент наилучшего приближения.
** Экстремальное свойство частичных сумм ряда Фурье               :theorem:
   {eᵢ} -- ОНС. Hₙ = L(e₁...eₙ). Sₙ(x) -- частичная сумма ряда фурье
   до элемента N элемента x. Тогда E_Hₙ(x) = ∥x - Sₙ(x)∥.

** Неравенство Бесселя                                              :lemma:
   Для коэффициентов Фурье верно:
   1. ∑<x,eᵢ>² ≤ ∥x∥².
   2. Ряд из квадратов коэфф. Фурье сходится (д-во из 1 пункта).
* Пространства Гильберта
** Гильбертово пространство                                    :definition:
   Пространство Гильберта (H) -- полное бесконечномерное унитарное
   пространство.
** Примеры гильбертовых пространств (l₂, L₂)                      :example:
   * L₂(E), <f,g> = ∫E (f∙g)dμ.
   * l₂ - {{x₁...xₙ..} | ∑xₙ² < +∞}
     <x,y> = ∑xₙyₙ.
     l₂ -- частный случай L₂ при E = ℕ и μ(m} = 1 (считающая мера).
** Теорема Рисса-Фишера                                           :theorem:
   Ряд фурье в Гильбертовом (полном унитарном, бесконечномерном)
   пространстве любой точки всегда сходится.
** Равенство Парсеваля                                            :theorem:
   ∥x∥² = ∑|<x,eᵢ>|².

** Полная, замкнутая ОНС                                       :definition:
   1. ОНС {eᵢ} замкнута, если H = Cl(L({eᵢ})).
      (Замыкание тут необходимо, потому что по определению линейная
      оболочка L -- это конечная сумма).
   2. ОНС {eᵢ} полна, если: ∀x <x,eₘ> = 0 ⇒ x = 0.
** Лемма о связи полноты и замкнутости                              :lemma:
   {eᵢ} полна ⇔ {eᵢ} замкнута.
** Сепарабельность топологического пространства                :definition:
   Топологическое пространство сепарабельно, если в нем существует
   счетное всюду полное множество точек.
   * X = Cl{a₁...aₙ..}.
** Связь сепарабельности и существования базиса                     :lemma:
   H сепарабельно ⇔ ∃ базис в H.
** О наилучшем приближении в H                                    :theorem:
   H -- пространство, M -- замкнутое выпуклое подмножество.
   Тогда ∀x ∈ H ∃!y ∈ M, что ∥x-y∥ = inf{z∈M}∥x-z∥.
   То есть в M у любого элемента есть единственный элемент наилучшего
   приближения.
** Разложение в прямую сумму                                   :definition:
   H -- гильбертово пространство, H₁ -- замкнутое линейное
   подмножество H (подпространство).

   H₂ ≡ H₁⊥ (верхний индекс ⊥) = {y ∈ H | y ⊥ x, x ∈ H₁}.
   Тогда H = H₁ ⊕ H₂.
** Следствие о приближении в прямой сумме                             :lemma:
   x ∈ H₁, H₂ = H₁⊥.
   ∃x₁ ∈ H₁ : ∥x - x₁∥ = inf{u ∈ H₁}∥x - u∥
   x₂ = x - x₁ ∈ H₂?
   ∀y ∈ H₁ y ⊥ x₁, λ > 0, x₁ + λy ∈ H₁
   Отсюда:
   ∀ λ > 0 ∥x - (x₁ + λy)∥² ≥ ∥x - x₁∥²
   <x - x₁ - λy, x - x₁ - λy> ≥ <x - x₁, x - x₁>
   <x₂ - λy, x₂ - λy> ≥ <x₂, x₂> ⇒
   <x₂, x₂> - 2<λy, x₂> + λ²<y, y> ≥ <x₂, x₂>
   Итого имеем: 2<y, x₂> ≤ λ<y, y>
   Устремим λ к нулю: <y, x₂> ≤ 0.
   В силу произвольности y также верно:
   <-y, x₂> ≤ 0.
   Отсюда <y, x₂> = 0.
* Счетно-нормированные пространства
** Счетно-нормированное пространство                           :definition:
   X -- линейное множество. Полунорма p на X -- это функционал,
   удовлетворяющий 2 и 3 условиям нормы, но имеющий ослабленное первое
   условие:
   1. p(x) ≥ 0. (не обязательно нулевая на нулевых элементах)

   Пусть на X задана {pᵢ} -- счетное множество полунорм, и они
   согласованы:
   * ∀n pₙ(x) = 0 ⇒ x = 0.
   Тогда <X, {pᵢ}> -- счетно-нормированное пространство.
** Предел в СНП                                                :definition:
   x = lim{xₙ} ≡ ∀n ∈ ℕ lim{m→∞}(pₙ(xₘ - x)) = 0
** Вложение СНП                                                 :statement:
   Нормированное пространство -- частный случай СЧП
   Согласованность {pᵢ} необходима для единственности предела.
   Можно показать, что без этого условия единственности не будет.
** Метрика в СЧП (Урысона)                                     :definition:
   Если ρ(x, y) = ∑{inf}(1/2ⁿ)(pₙ(x - y) / (1 + pₙ(x - y))), то СНП
   метризуеммо всегда.
   Это, кстати, метрика в ℝ∞.
** Непрервыность и топология                                    :statement:
   Сложение и умножение на скаляр непрерывны. В этом смысле СНП = ТВП
   (Топологическое векторное пространство).
** Пример СНП                                                     :example:
   Возьмем C∞[a,b] = {x(t), t ∈ [a,b], бесконечно дифференцируемо}.
   Тогдa pₙ = max[a,b] |x⁽ⁿ⁾(t)|, n = 0,1,...
   Кстати, C∞ не нормируемо.
** Монотонная система полунорм, эквивалентность, существенность :definition:
   1. {pₙ} монотонна, если ∀x ∈ X ∀n ∈ ℕ pₙ(x) ≤ pₙ₊₁(x)
   2. {pₙ} ~ {qₙ}, если в них одинаковая сходимость
   3. pₘ мажорирует pₙ, если ∃c ∀x∈X pₙ(x) ≤ c * pₘ(x)
   4. pᵢ ∈ {pₙ} существенна, если она не мажорируется любой pⱼ |j<n.
** Сведение к монотонной                                            :lemma:
   Для любой системы полунорм существует эквивалентная ей монотонная
   система.

   Далее будем считать, что любая система полунорм монотонна.
** Теорема об эквивалентности и мажорируемости                    :theorem:
   {pᵢ} ~ {qᵢ} ⇔ {pᵢ} мажорирует {qᵢ} и наоборот.
   ({qᵢ} мажорирует {pᵢ} := ∀i∃j qⱼ мажорирует pᵢ)
** Критерий нормируемости                                         :theorem:
   X -- счетно-нормированное пространство с монотонной системой
   полунорм P. Тогда: X нормируется ⇔ в P конечное число существенных
   полунорм.
** Ненормируемость ℝ∞                                           :statement:
   x~ = (x₁...xₙ..), pₙ(x~) = |xₙ|. Все полунормы существенны, отсюда
   ℝ∞ не нормируемо.
* Функционал Минковского
** Поглощение, радиальность, закругленность                    :definition:
   1. X -- линейное множество. M ⊂ X, M выпукло (∀x,y ∈ M αx+βy ∈ M,
      α+β = 1, α,β ≥ 0). М поглощает A ⊂ X, если ∃λ₀, что ∀λ |λ|≥λ₀ A
      ⊂ λM = {λx | x ∈ M}}.
   2. Если M поглощает любое конечное число точек, то M радиальное
      множество.
   3. М закругленное, если ∀λ |λ| < 1 λM ⊂ M.
** Шар как закругленное множество                                   :example:
   X -- НП, V~ = {∥x∥ ≤ 1}, тогда V~ радиально и закругленно.
** Функционал Минковского                                      :definition:
   М -- радиальное множество, тогда:
   * ∀x ∈ X, φₘ(x) = inf{λ ≥ 0 | x ∈ λM}.
   Такой функционал φₘ называется функционалом Минковского.
** Норма как функционал Минковского                               :example:
   На шаре V~ φₘ(x) -- норма x = ∥x∥. Можно смотреть вообще
   на норму как на частный случай φₘ, так и делают обычно.
** Функционал Минковского и полунорма                               :lemma:
   φₘ -- полунорма на X ⇔ M радиально, выпукло, закруглено.
* Линейные функционалы и коразмерность
** Фактор-множество, коразмерность                             :definition:
   1. X -- линейное множество, Y ⊂ X линейно.
      Введем эквивалентность на X:;
      ∀x, y ∈ X, x ~ y ⇔(def) x - y ∈ Y.
      [x] = {y : y ~ x} -- будем так обозначать класс эквивалентности.
   2. X / Y = {[x]} -- фактор-множество.
      Фактор-множество линейно, очевидно (достаточно ввести [x] + [y] =
      [x+y] и то же самое для умножения на константу).
   3. codimₓY ≡ dim(X/Y)
** Связь конечности коразмерности и разложения по базису            :lemma:
   codimₓY = p < +∞, тогда ∃e₁...eₚ ∈ X, что ∀x ∈ X.

   x =! ∑αₖeₖ + y, где y ∈ Y.

   Доказательство очевидное по свойству линейности [x].
** Гиперплоскость, линейный функционал, ядро                   :definition:
   1. Y -- гиперплоскость, если codimₓY = 1. Достаточно логичное
      определение -- чтобы выразить что угодно из икса, нам кроме
      вектора из Y нужен еще один вектор.
   2. Аналитическое описание гиперплоскости дается с помощью линейных
      функционалов.
      f: X → ℝ, f линейно ∀ x,y,α, f(0) = 0, тогда f линейный
      функционал
   3. Ker f = {x | f(x) = 0}.
      Если f линейно, то Ker f линейно.
** Аналитическое задание гиперплоскости                           :theorem:
   Любая гиперплоскость может быть записана как Ker(f) для некоторого
   f.
* Теорема Колмогорова
** Топологическое векторное пространство                       :definition:
   X -- множество, τ -- топология на X, операции умножения на
   константу и сумма непрерывны.

   E(x) -- окрестность x, если ∃G ∈ τ : x ∈ G ⊂ E(x).

   Тогда (X, τ) -- ТВП.

   * Непрерывность умножения на скаляр:
     * ∀E(α₀X₀) ∃δ>0, ∃E(x₀): |α-α₀|<δ, x ∈ E(x₀) ⇒ αx ∈ E(α₀x₀)
     Это то же самое, что и нотация: α₀x₀ = lim{α→α₀,x→x₀}αx.
   * Непрерывность суммы:
     ∀E(x₀+y₀) ∃E(x₀), E(y₀): x ∈ E(x₀), y ∈ E(y₀), x+y ∈ E(x₀+y₀)
** Место ТВП в систематике                                      :statement:
   Нормированные и счетно-нормированные пространства -- частные
   случаи ТВП.
** Лемма о сохранении открытости сдвига                             :lemma:
   Возьмем x₀, f(x) ≡ x + x₀, f -- очевидно биекция X на X.
   * f⁻¹(y) = y - x₀.
   В силу непрерывности сложения f и f⁻¹ непрерывны. Тогда f --
   гомеоморфизм (биекция, непрерывная в обе стороны).

   Так как непрерывные функции сохраняют открытость множеств,
   ∀G открытое, x₀ + G = {x₀ + x | x ∈ G} тоже открыто.
   Тогда сдвиг сохраняет открытость.
** База окрестностей нуля                                      :definition:
   σ = {B, B -- окрестность нуля}, что ∀C -- окрестность нуля, C ∉ σ,
   C = ∪{Bᵢ}, Bᵢ ∈ σ.

   σ -- это база окрестностей нуля.

   Сдвигая элементы σ на константу, получаем базу окрестности любой
   другой точки.
** Всякие свойства базы окрестности нуля                        :statement:
   x → 0, тогда x + x → 0 + 0 = 0.

   ∀V ∈ σ, ∃U ∈ σ, 2*U ⊂ U+U ⊂ V

   ∀V ∈ σ, ∃ε > 0, ∃U ∈ σ, |λ|≤ε ⇒ λU ⊂ V.

   Отсюда видно, что ⋃{|λ|≤ε} λU -- закругленное.


   Тогда система открытых множеств инварианта по сдвигу и всегда можно
   создать такое σ, что:
   1. ∀V ∈ σ, ∃U ∈ σ, U+U ⊂ V
   2. все элементы σ радиальные и закругленные

   Это все выводится исключительно из определения окрестности.

   Эти условия полностью характеризуют топологию векторного
   пространства, то есть обеспечивают непрерываность +, ∙.
** Теорема Колмогорова                                            :theorem:
   Хаусдорфово ТВП нормируется ⇔ 0 имеет хотя бы одну ограниченную
   выпуклую окрестность.
   * Хаусдорфово -- для любых двух точек можно найти их
     непересекающиеся окрестности.
   * Ограниченная -- полглощается любой окрестностью нуля.
** 0 ℝ∞ как ненормируемое пространство                              :example:
   Рассмотрим ℝ∞ = {(x₁, x₂, ...)}. Посмотрим на множество вида:

   {x~, xᵢ₁ ∈ (-δ₁, δ₁), ... xᵢₚ∈(-δₚ, δₚ)}, все дельты > 0.

   Тут нету ни одной ограниченной выпуклой окрестности нуля.

   От противного: если есть, то должна быть поглощена любым элементом
   базы. Возьмем такие элементы базы: {x~, -δ < x₁ < δ}. Они, очевидно,
   окрестности нуля, но не поглощают некоторые ограниченные
   окрестности ввиду того, что наши элементы базы определены только с
   констрейнтом для первого элемента вектора.
* Непрерывные функционалы, теорема Хана-Банаха
** Связь непрерывности л.функционала на X и в нуле.                 :lemma:
   X -- нормированное пространство, f -- непрерывный на X функционал
   (xₙ → x ⇒ f(xₙ) → f(x)).
   f непрерывна на X ⇔ f непрерывна в нуле.

   Доказательство тривиальное.
   В силу непрерывности умножения на скаляр и суммы в нормированном
   пространстве по линейности фукнционала имеем:

   f(xₙ) - f(x) = f(xₙ - x), xₙ → x ⇔ xₙ - x → 0. Тогда f(0) = 0.
** Норма функционала, ограниченность                           :definition:
   1. ∥f∥ ≡ sup{∥x∥ < 1}|f(x)|.

      Заметим также, что очевидно из определения:

      ∀x ≠ 0, ∥x/∥x∥∥ = 1, отсюда |f(x/∥x∥)| ≤ ∥f∥ ⇒ |f(x)| ≤ ∥f∥*∥x∥.
   2. f ограничена ≡ ∥f∥ < +∞.
** Ограниченность и непрерывность функционала                       :lemma:
   f -- линейный функционал. f ограничен ⇔ f непрерывен.
   1. (⇒)
      ∥f∥ < +∞, |f(x)| ≤ ∥f∥*∥x∥, xₙ → 0 ⇒ ∥xₙ∥ → 0.
      Тогда |f(xₙ)| ≤ ∥f∥*∥xₙ∥ ⇒ f(xₙ) → 0.
   2. (⇐) От противного.
      Пусть ∥f∥ = ∞ = sup{∥x∥≤1} |f(x)|. Раскроем определение
      супремума:

      ∀n ∈ ℕ ∃xₙ: ∥xₙ∥ ≤ 1, |f(xₙ)| > n. |f(xₙ/n)| > 1.

      ∥xₙ/n∥ =  ∥xₙ∥/n ≤ 1/n. Отсюда xₙ/n → 0.

      Тогда по непрерывности f(xₙ/n) → 0, что
      противоречит |f(xₙ/n)|>1.
** Связь непрерывности функционала и замкнутости ядра             :theorem:
   Линейный функционал f непрерывен ⇔ Ker(f) замкнут в X.
** 0 Пример плотного всюду многообразия                             :example:
   Рассмотрим C[0, 1], теорему Вейерштрасса о равномерном приближении
   функции полиномами. Утверждается, что:

   ∀ε>0, ∃Pₙ(x), ∀x∈[0,1], |f(x)-Pₙ(x)|<ε.

   Теорема Вейетштрасса долгое время существовала исключительно в
   неконструктивном виде, но С.Н.Бернштейн в начале 20 века показал,
   как полиномы можно строить конструктивно:

   Bₙ(f,x) = ∑{k=0..n}Cᵏₙf(k/n)xᵏ(1-x)ⁿ⁻ᵏ -- на них реализуется
   теорема Вейерштрасса.

   С точки зрения функционального анализа Y = {Pₙ(x)} -- линейное
   множество в C[0,1]. Тогда ClY = C[0,1] -- пример плотного всюду
   многообразия.
** Продолжение с непрерывного линейного множества                 :theorem:
   X -- НП, Y -- линейное множество в X, ClY = X. Y везде плотно в X.
   На Y задан f₀ -- непрерывный линейный функционал.

   Тогда существует непрерывный линейный фукнционал f на X, что:
   1. f|_y = f₀
   2. ∥f∥ₓ = ∥f₀∥_y
** Лемма Банаха                                                   :theorem:
   X -- линейное множество, p(x): X → ℝ -- полунорма, Y -- собственное
   линейное подмножество X.

   f₀: Y → ℝ линейно. |f₀(y)| ≤ p(y).

   e ∉ Y. Y₁ = L(Y,e).

   Тогда ∃f: Y₁ → ℝ, линейное, что:
   1. f|_y = f₀
   2. |f(y)| ≤ p(y) на Y₁
** Теорема Хана-Банаха (полная, без д-ва)                       :statement:
   X, p(x) -- полунорма. Y -- линейное множество в X.
   f₀ -- линейный функционал, удовлетворяющий условию подчиненности
   полунорме (∀y∈Y, |f₀(y)| ≤ p(y)).

   Тогда мы можем продлить f₀ на X с сохранением условия
   подчиненности:

   ∃f: X → ℝ, что:
   1. f|_Y = f₀.
   2. ∀x ∈ X |f(x)| ≤ p(x)

   Доказательство не приведено, но оно существенно пользуется леммой
   Цорна, которую никто не хочет доказывать. С помощью леммы Банаха мы
   проводим этот итеративный процесс, а лемма Цорна гарантирует нам
   заполнение всего множества x.

   И без аксиомы выбора эта теорема тоже не доказывается.
** Теорема Хана-Банаха для сепарабельных пр-в                     :theorem:
   X -- сепарабельно, нормировано (то есть содержит всюду плотное счетное
   подмножество).

   Y -- линейное множество в X, f₀ -- непрерывный линейный функционал
   на Y.

   Тогда ∃ непрерывный линейный функционал на x, что:
   1. f|_Y = f₀.
   2. ∥f∥ₓ = ∥f₀∥_Y

   Примечание: условие сепарабельности -- это самый частый юзкейс.
** Следствия из теоремы Х-Б                                         :lemma:
   1. ∀x₀ ≠ 0, ∃ линейный непрерывный функционал f, что:
      1. ∥f∥ = 1.
      2. f(x₀) = ∥x₀∥.

      Доказательство: возьмем Y = {tx₀, t∈ℝ}. Построим с помощью
      f₀(tx₀) = tf₀(x₀), где f₀(x₀) = ∥x₀∥, линейный функционал f₀.

      ∥f₀∥_Y = 1, f₀(x₀) = ∥x₀∥.

      Тогда по теореме Х-Б продолжим на X.
   2. ∀x₁ ≠ x₂ ∃ линейный функционал f(x₁) ≠ f(x₂).

      В качестве доказательства обратимся к предыдущему следствию с
      x₀ = x₂ - x₁.
   3. Два предыдущих следствия принадлежат категории "какой функцией
      можно записывать линейный ограниченный функционал в наперед
      заданном пространстве"

      Что бы это ни значило.
** Теорема Рисса                                                  :theorem:
   H -- Гильбертово пространство, f -- линейный огр. функционал. Тогда
   существует y ∈ H, что:
   1. ∀x ∈ H  f(x) = <x,y>
   2. ∥f∥ = ∥y∥

   Эта теорема фактически отождествляет гильбертово пространство с его
   сопряженным (с пространством функционалов : X → ℝ).
* Линейные ограниченные операторы
** Линейный оператор, непрерывность, ограниченность, норма     :definition:
   * X, Y -- нормированные пространства, тогда A: X → Y называется
     линейным оператором, если A линейно. Если Y = ℝ, то A есть
     линенйый фукнционал.

     Все свойства функционала переносятся на оператор.
   * Следующие утверждения эквивалентны:
     1. A -- непрерывно
     2. ∀xₙ x, xₙ → x ⇒ Axₙ → Ax
     3. ∀xₙ, xₙ → 0 ⇒ Axₙ → 0 = A0.
   * А ограничен, если существует M, что ∀x ∈ X, ∥Ax∥ ≤ M∥x∥.
   * Ограниченность эквивалентна конечности ∥A∥ ≡ sup{∥x∥<1}∥Ax∥.
   * ∀x, ∥Ax∥ ≤ ∥A∥∥x∥. Доказательство эквивалентно тому для
     функцоналов.
   * Норма оператора -- норма.

     Проверяется руками. Например, ∥(A+B)(x)∥ ≤ ∥A∥∥x∥ + ∥B∥∥x∥ ≤
     ∥A∥ + ∥B∥ из линейности. Перейдем к sup, получим правило
     треугольника.
   * Непрерывность A эквивалентна ограниченности

     Доказательство копируется из предыдущего параграфа.
** Пространство линейных операторов                            :definition:
   L(X,Y) -- линейное пространство линейных ограниченных операторов из
   X в Y, нормированное операторной нормой.
** Банаховость в линейных операторах                              :theorem:
   Y -- B-пространство. Тогда L(X, Y) -- тоже B-пространство.

   В том числе верно и важное частное следствие:

   X -- нормированное пространство. ℝ -- полно. L(X, ℝ) -- тоже.
** Сопряженное пространство                                    :definition:
   X* = L(X, ℝ) -- пространство, сопряженное с X. В смысле предыдущей
   теоремы сопряжение любого пространства полно.
** Теорема Банаха-Штейнгауза                                        :theorem:
   X -- полное пространство. Y -- нормированное пространство. Aₙ ∈
   L(X,Y).

   ∀x∈X, sup{n}∥Aₙx∥ < +∞. -- последовательность операторов поточечно
   ограничена.

   Тогда sup{n}∥Aₙ∥ < +∞ -- равномерная ограниченность.
** Следствие                                                          :lemma:
   X, Y -- банаховы пространства. Aₙ ∈ L(X,Y). ∀x ∈ X Aₙx-Aₘx → 0.

   Тогда ∃A ∈ L(X,Y), что ∀x ∈ X Aₙx → Ax.
* Непрерывно обратимые операторы
** Непрерывно обратимый оператор                               :definition:
   A ∈ L(X,Y), A:X → Y есть биекция. Тогда ∃A⁻¹:Y → X.
   Если A⁻¹ ограничен как оператор, то A -- непрерывно обратим.
** Теорема Банаха о непрерывно обр. операторе                     :theorem:
   C ∈ L(X) := L(X,Y), ∥C∥ < 1. X -- банахово (тут и *далее*).

   Тогда I-C, где Ix = x непрерывно обратим.
** Range, априорная оценка                                       :definition:
   * A: X → Y, тогда R(A) = {Ax, x ∈ X} -- линейное множество в Y.
   * Априорная оценка решения операторного уравнения.

     y ∈ R(A) ⇒ Ax = y имеет решение.

     Тогда говорят, что Ax = y допускает априорную оценку решений, если
     ∃α ∈ ℝ > 0, что ∥x∥ ≤ α∥y∥.
** Теорема об априорной оценке                                      :theorem:
   A непрерывен и имеет априорную оценку для своих решений, тогда множество
   R(A) замкнуто.
* Спектр ограниченного оператора
  По умолчанию тут и далее все пространства банаховы (нормированы +
  полны в смысле метрики).
** Резольвентный оператор, регулярная точка, спектр            :definition:
   Пусть A: X → X -- линейно ограничен (другими словами A ∈ L(X,X)), λ ∈
   ℂ, I -- единичная матрица (оператор).

   Рассмотрим A - λI.
   * Если при заданном λ, A - λI непрерывно обратим, то Rλ(A) =
     (A-λI)⁻¹ называется резольвентным оператором, а λ -- регулярной
     точкой оператора A.
   * ρ(A) = {все регулярный точки A} -- резольвентное множество.
   * σ(A) = ℂ\ρ(A) -- спектральное множество (спектр).
** Открытость ρ(A)                                                :theorem:
   ρ(A) открыто в ℂ.
** Лемма о спектре                                                  :lemma:
   σ(A) ⊂ {λ: |λ| ≤ ∥A∥}.
** Спектральный радиус                                         :definition:
   rσ(A) = inf{n∈ℕ}(∥Aⁿ∥)^{1/n} -- спектральный радиус оператора.

   Заметим, что ∥Aⁿ∥ ≤ ∥A∥ⁿ ⇒ rσ(A) ≤ ∥A∥ в общем случае.
** Свойства спектрального радиуса                                   :theorem:
   1. rσ(A) = lim{n→∞}(∥Aⁿ∥)^{1/n}
   2. σ(A) ⊂ {λ: |λ| ≤ rσ(A) }
** Пример грубой оценки спектра                                   :example:
   Рассмотрим l₂ и отображение A: (x₁,x₂,..) ↦
   (0,x₁,x₂,...). Очевидно, что ∥Ax∥ = ∥x∥ и ∥Aⁿx∥ = ∥x∥. ОТсюда ∥Aⁿ∥
   = 1, rσ = 1 по предыдущей теореме.

   Найдем теперь спектр непосредственно.

   * λ = 0 ∈ σ(A), потому что A не непрерывно обратим.
   * λ ≠ 0, тогда можно показать (достаточно легко по теореме Банаха о
     непрерывном операторе), что λ ∈ ρ(A), то есть σ(A) = {0}, хотя
     rσ=1.

   Оценка вышла достаточно грубой.
** Лемма Абеля                                                      :lemma:
   Главная мысль -- это то, что во всех операторных рядах λ∈ℂ, поэтому
   к ним можно применять логику из ТФКП. Напомним одну из основных
   теорем ТФКП:

   Если ∑∞ Aₙλ₀ⁿ сходится, то ∀λ : |λ|<|λ₀| ∑∞ ∥Aₙ∥|λⁿ| сходится.
** Теорема Лиувиля
   f(x) = ∑aₙλⁿ -- аналитическая функция с бесконечным радиусом
   сходимости, |f(λ)| ≤ M. Тогда f ≡ const.

   Без д-ва.
** О спектре ограниченного оператора                              :theorem:
   ∀A ∈ L(x), σ(A) ≠ ∅.
* Сопряженный оператор
** Сопряженный оператор                                        :definition:
   1. X -- нормированное пространство, X* -- ему сопряженное,
      A ∈ L(X,Y),
      φ ∈ Y*, ∀x ∈ X f(x) = φ(Ax). Очевидно, что f ∈ X*.

      Получаем φ ∈ Y* ↦ f = φ∘A ∈ X*.

      Это отношение порождает A*: Y* → X*, A*(φ) = φ₀A.
   2. ∀x ∈ H*, f(x) = <x,y>, ∥f∥ = ∥y∥ (теорема Рисса для Гильбертовых пр-в)

      A: H₁ → H₂, A*: H₂* → H₁*: <Ax,y> = <x,A*y>.

      Оператор H₂ берет функцию f ∈ H₂*, возвращает f∘A -- оператор из H₁*.
** Примеры сопряженных операторов                                 :example:
   1. ПТУшный пример. Поскольку Rⁿ является гильбертовым
      пространством, то для оператора A: Rⁿ → Rⁿ, A* = Aᵀ. Более того,
      если A симметрична, то A самосопряжен, так как A = A*.
   2. eₙ = (0,...1,..0) -- на n-м месте 1, все ост. нули.

      x~ = ∑∞ xₙeₙ, xₙ = <x~,eₙ>

      λₙ: |λₙ| ≤ M, Ax~ = ∑∞ λₙxₙeₙ  ∈ l₂.

      A: l₂ → l₂, A*y = ∑λₙ~yₙeₙ. (типа комплексное сопряжение λ).

      Тогда действительно <Ax,y> = <x,A*y>
** Утверждение о равенстве норм сопряженного и обычного операторов :theorem:
   ∥A*∥ = ∥A∥
** Ортогональные дополнения                                    :definition:
   X,X*:
   1. ∀S ⊂ X, S⊥ = {f ∈ X*: ∀x ∈ S ⇒ f(x) = 0}
   2. ∀S ⊂ X*, S⊥ = {x ∈ X*: ∀f ∈ S ⇒ f(x) = 0}
** Свойства ортогональных дополнений                                :lemma:
   1. ∅ ∈ X ⇒ {∅}⊥ = X*.
   2. const 0 ∈ X* ⇒ {const 0}⊥ = X.

   Утверждения очень очевидные и простые, достаточно лишь понять, что
   такое {∅}⊥ и {константная функция 0}⊥.

   1. {∅}⊥ = {f ∈ X* : f(∅) = 0} = {линейные операторы из X в ℝ} = X*;
   2. {const 0}⊥ = {x ∈ X : (const 0)(x) = 0} = {x ∈ X} = X;
** Теорема о ортогональном сопр. ядра сопряженного оператора      :theorem:
   A: X → Y, R(A) (range) замкнут, тогда Cl(R(A)) = (Ker(A*))⊥.
** Теорема о range сопряженного оператора                           :theorem:
   A: X → Y, R(A) замкнут, тогда R(A*) = (Ker(A))⊥
* Теория Фредгольма-Шаудера
** Вполне непрерывный оператор                                   :definition:
   A: X → Y называется вполне непрерывным, если ∀M ограниченный в X
   переводится в относительно компактное в Y.

   X называется относительно компактным, если Cl(X) компактно.

   ∀M ограниченного в X, Cl(A(M)) -- компакт в Y. Легко понять, что
   любой вполне непрерывный оператор также непрерывен.
** Вполне непрерывность композиции                                    :lemma:
   A -- вполне непрерывен, B ограничен. Тогда AB, BA вполне
   непрерывны, если композиция имеет смысл вообще.
** Отсутствие обратного оператора у вполне непрерывного                :note:
   A -- вполне непрерывный. Тогда покажем, что не существует
   ограниченного обратного оператора к A.

   Помним, что S ⊂ X -- бесконечномерная сфера, не является
   компактом.

   От противного, пусть ∃A⁻¹, ограничен. I = A⁻¹∙A -- вполне
   непрерывный, IV = V. Противоречие.
** Предел вполне непрерывных операторов                               :lemma:
   Aₙ → A в L(X,Y), тогда из вполне непрерывности Aₙ следует вполне
   непрерывность A.
** Пример вполне непрерывного оператора                             :example:
   C[0,1], K(u,v) -- непрерывен на [0,1]².

   A(f,x) = ∫{0,1} K(x,t)f(t)dt. |f(t)| ≤ 1, t ∈ [0,1].

   Есть такая теорема Арцелла-Асколи:
   M ⊂ C[0,1] эквивалентно следующим двум утверждениям:
   1. ∃m: ∀f∈M, ∀t∈[0,1], |f(t)| ≤ m.
   2. ∀ε>0, ∃δ>0, ∀f∈M, |t₂-t₁|<δ ⇒ |f(t₂)-f(t₁)| ≤ ε.

   Второе свойство теоремы -- равноступенная непрерывность.

   Так вот по этой теореме: |A(f,x)| ≤ ∫{0,1} |K(x,t)||f(t)|dt.
   Заметим, что |f(t)| ≤ 1, а |K(x,t)| ограничен m.

   Тогда |A(f,x₂)-A(f,x₁)| ≤ ∫{0,1} |K(x₂,t)-K(x₁,t)||f(t)|dt ≤ ε.

   (модуль разности K очень маленький в силу теоремы А-А)
** Размерность ядра оператора                                       :theorem:
   dim(Ker(T)) < +∞
