#+TODO: X 0 1 2 | OK
#+TITLE: Notes on functional analysis (given by Dodonov)
#+DATE: 2015, term 5

* Векторные пространства
** Метрические пространства
*** Метрика, метрическое пространство                            :definition:
    X, ρ: X×X → ℝ+ -- метрика, если:
    1. ρ(x, y) ≥ 0; ρ(x, y) = 0 ⇔ x = y
    2. ρ(x, y) = ρ(y, x)
    3. ρ(x, y) ≤ ρ(x, z) + ρ(z, y)

    Метрическое пространство -- пара <X, ρ>.
*** Предел по метрике                                            :definition:
    x = lim(xₙ) ⇔ ρ(xₙ, x) → 0
*** Топологическое пространство, топология                       :definition:
    Топологическое пространство (ТП) -- пара <X, Τ>, где X --
    множество, T ⊃ 2ˣ -- топология, если выполнено:
    1. Замкнутость T по объединению
    2. Замкнутость T по конечному пересечению
    3. X, ∅ ∈ T
*** Открытое множество                                           :definition:
    Множество открыто, если принадлежит топологии T
*** Предел в смысле ТП                                           :definition:
    <X,T>
    x = lim(xₙ) ⇔ ∀G ∈ T : x ∈ G, ∃N: ∀n > N xₙ ∈ G
*** Замкнутость через открытость                                 :definition:
    G -- открытое в T, тогда F = X \ G замкнутое

*** Открытый шар, представимость T                               :definition:
    * Bᵣ открытый шар в центре a = {x: ρ(x, a) < r}
    * T = {∪Bᵣ(a)}
*** X Связь МП и ТП                                               :statement:
    b ∈ Bᵣ₁(a₁) ∩ Bᵣ₂(a₂) ⇒ ∃ r > 0, Bᵣ(b) ⊃ (Bᵣ₁(a) ∩ Bᵣ₂(a))
    В этом смысле метрические пространства оказываются частным случаем
    топологических.
    ??? не вижу перехода
*** Примеры МП                                                      :example:
    1. ℝ, ρ(x, y) = |x - y|
    2. ℝⁿ, x~ = (x₁...xₙ) ∈ ℝⁿ
       ρ(x~, y~) ≡ √(∑{n}(xᵢ - yᵢ)²)
       αx~ = (αx₁...αxₙ)
       x~ + y~ = (x₁ + y₁, ...)
       xₙ~ → x~ ⇔ ∀j=1..n xⱼᵐ → xⱼ
    3. ℝ∞, xₘ~ → x~ ≡ ∀i=1,2,3..., xⱼᵐ → xⱼ
       Метрика Урысона:
       ρ(x~, y~) ≡ ∑{∞}(1/2ⁿ * |xₙ - yₙ|/(1 + |xₙ - yₙ)), где
       φ(t) = t/(1+t), то есть ρ(x~, y~) = ∑{∞}(1/2ⁿ * φ(|xₙ-yₙ|)).

       Кстати, для φ верно:
       Φ(t₁ + t₂) ≤ φ(t₁) + φ(t₂)

       ρ(xₘ~, x~) → 0 ⇔ ∀j xⱼᵐ → xⱼ
       Таким образом ℝᵐ метризуемо.
    4. Дискретная метрика
       ρ(x,y) = if x = 0 then 0 else 1
       xₘ → x, ε = 1/2, ∃M : ∀m > M ⇒ ρ(xₘ,x) < 1/2 ⇒ ρ(xₘ, x) = 0 ⇒
       xₘ = x
       То есть в такой метрике сходятся только последовательности,
       стабилизирующиеся после некоторого элемента -- стационарные.
*** Внутренность, замыкание, граница                             :definition:
    (X, T), ∀A ⊂ X:
    1. Int(A) ≡ ∪{G | G ⊂ A, G открытое}
    2. Cl(A)  ≡ ∩{F | F ⊃ A, F замкнутое}
    3. Fr(A)  ≡ Cl(A) \ Int(A)

    По аксиомам топологии ∀A Int(A) открытое, Cl(A) замкнутое
*** Расстояние до множества, между множествами                   :definition:
    ρ(x, A) ≡ inf{ρ(x, a) | a ∈ A}
    ρ(A, B} ≡ inf{ρ(a, b) | a ∈ A, b ∈ B}
*** Непрерывность расстояния до множества                             :lemma:
    Пусть f(x) ≡ ρ(x, A), x ∈ X.
    Тогда f непрерывно на X

**** Доказательство
     ∀x, y ∈ X:
     f(x) = ρ(x, A) ≤ ρ(x, a) ≤ ρ(x, y) + ρ(y, a)
     ∀ε > 0  ∃aₑ ∈ A : ρ(y, aₑ) < ρ(y, A) + ε = f(y) + ε
     f(x) < ρ(x, y) + f(y) + ε
     ε → 0,
     f(x) ≤ f(y) + ρ(x, y)
     Аналогично по симметричности
     f(y) ≤ f(x) + ρ(x, y)
     Отсюда: |f(x) - f(y)| ≤ ρ(x, y)
*** X Связь Cl, ρ                                                 :statement:
    x ∈ Cl ⇔ ρ(x, A) = 0

**** Доказательство
     Рассмотрим метрическое пространство с точки зрения отделимости
     множеств друg от друга открытыми множествами.
     x ≠ y, r = ρ(x, y) > 0
     B(x), B(y) -- 2/3, r/3 соответственно.
     Выполнена аксиома Хаусдорфа.
*** Нормальность МП                                                 :theorem:
    Любое МП -- нормальное пространство.
    ∀ F₁, F₂ ∈ X (F₁ ∩ F₂ = ∅, оба замкнутые)
    ∃ открытые непересекающиеся G₁ G₂, что F₁ ⊂ G₁, F₂ ⊂ G₂.

**** Доказательство
     g(x) = ρ(x, F₁) / (ρ(x, F₁) + ρ(x, F₂))
     Их предыдущего утверждения понятно, что функция корректно
     определена.

     x ∈ F₁, Cl(F₁) = F₁
     ρ(x, F₁) = 0, g(x) = 0
     x ∈ F₂, g(x) = 1
     (-∞, 1/3); (2/3, +∞) G₁ = g⁻¹(-∞, 1/3)
     G₂ = g⁻¹(2/3, ∞)
     Тогда G₁ G₂ -- требуемые открытые множества.
*** МП-Полнота                                                   :definition:
    ρ(xₙ, xₘ) → 0 ⇒ ∃x = lim xₙ
*** Принцип вложенности шаров                                       :theorem:
    X -- полное МП, V_2m : V_2n+1 ⊂ V_2n, 2n → 0 -- система замкнутых
    шаров.
    тогда ∩V_2n = {a}

**** Доказательство
     ∃ bₙ -- центр шаров V_2n, тогда ∀ m ≥ n bₘ ∈ V_2m
     Тогда ρ(bₙ,bₘ) ≤ 2ₙ → 0 по условию.
     Очевидно, что a ∈ шары, одна единственная в силу замкнутости
     шаров.
*** Всюду плотность, всюду не плотность                          :definition:
    А всюду плотно в X если X -- МП, Cl(A) = X, A ⊂ X.
    А нигде не плотно, если IntClA = ∅.

    Легко показать, что в МП нигде не плотность значит, что в любом
    шаре V ∃V' ⊂ V, что в V' нету точек множества A.

    Пример: Int(ℝ) = ∅.
*** Категории по Бэру                                            :definition:
    X -- множество 1 категории по Бэру, если его можно записать в виде
    не более чем счетного объединения Xₙ, где каждый xᵢ не плотен в X.
    Любой другой X -- множество 2 категории.
*** Теорема Бэра о категориях                                       :theorem:
    Полное МП является множеством 2 категории. (в себе).

**** Доказательство
     От противного: пусть X первой категории, тогда:
     X = ∪Xₙ, Xₙ нигде не плотно в X.
     Отсюда ∀V, X₁ V₁ ⊂ V, V₁ ∩ X₁ ≠ 0.
     X₂, V₂ ⊂ V₁ : V₂ ∩ X₂ ≠ 0, r₂ ≤ r₁/2.
     ...
     По индукции получаем {Vᵢ}, r(Vᵢ) → 0,
     Тогда a = ∩Vᵢ по принципу вложенности шаров.
     Тогда ∃ N₀, что a ∈ X_N₀, который X_N₀ ∩ V_N₀ = ∅, a ∈ V_r₀,
     что приводит к противоречию, потому что a ∈ ∩.
*** Следствие из теоремы Бэра о категориях                            :lemma:
    Полное МП без изолированных точек несчетно.

**** Доказательство
     По условию у множества X нету изолированных точек.
     Предположим обратное.
     Тогда каждая точка нигда не плотна в нем ⇒
     у него 1 категория, что протиоречит теореме Бэра.
*** Компакты и предкомпакты                                      :definition:
    Множество K, удовлетворяющее обеим аксиомам -- компакт, а только
    второй -- предкомпакт:
    1. K -- замкнуто (K = Cl(K))
    2. xₙ ∈ K, ∃ n₁ < n₂ < ...
       xₙⱼ -- сходится в K по метрике ρ
*** Теорема Хаусдорфа                                               :theorem:
    X -- полное МП, K ⊂ X, K замкнуто.
    Тогда:
    K компактно ⇔ K вполне ограничено
    (вполне ограниченность: ∀ε>0 ∃a₁..aₙ, что ∀b∈K ∃aⱼ ρ(b,aⱼ) < ε)
    (построение для вполне ограниченности называется конечной ε-сетью)

**** Доказательство
     1. Будем доказывать справа налево
        Пусть K вполне ограничено
        Хотим: xₙ ∈ K => xₙₖ сходится.

        Выберем одпоследовательность εₖ → 0.
        * Рассмотрим ε₁; по вполне ограниченности строим e₁-сеть, тогда
          из ее определения ясно:
          K покрыто конечной системой замкнутых шаров Vⱼ с радиусом ε₁.
          K ⊂ ∪Vⱼ

          Шаров конечное множество, тогда в каком-то ∞ элементов xₙ.
          Назовем такой шар Vⱼ₀.
          K₁ = Vⱼ₀ ∩ K, K₁ вполне ограниченный, diam(K₁) ≤ 2ε₁.
        * Аналогично строим:
          ε₂, K₁ ⊂ ∪Vⱼ, радиуса ε₂
          K₂ = Vⱼ₀ ∩ K₁, diam K₂ ≤ 2ε₂.
        * По индукции получаем {Kᵢ} -- систему вложенных замкнутых
          множеств, в силу полноты пространства с непустым
          пересечением.
          Тогда выберем подпоследовательность любую, в которой берем
          элементы из шаров.
     2. Слева направо.
        Пусть K -- компакт.
        Хотим: ∀ε ∃ конечная ε-сеть.

        От противного: ∃ε₀, что ∄конечной ε-сети.
        * ∀x₁ ∈ K, ∃x₂ ∈ K, ρ(x₁, x₂) > ε₀.
          Если это утверждение неверно, то система из x₁, x₂ --
          конечная ε₀-сеть.
        * {x₁,x₂} ∃x₃, ρ(x₃, xᵢ) > ε₀, i ∈ {1, 2}
        * Так по индукции получаем xₙ, из которой не выделить
          сходящейся подпоследовательности, а значит K не компакт.
** Нормированные пространства
*** Нормированное пространство, норма                            :definition:
    Нормированное пространство -- (X, ∥ ∥), где второе -- норма:
    φ: X → ℝ -- норма на X (φ(x) = ∥x∥), если:
    1. φ(x) ≥ 0; φ(x) = 0 ⇔ x = ∅
    2. φ(αx) = |α|φ(x)
    3. φ(x+y) ≤ φ(x) + φ(y)

    Заметим, что в нормированных пространствах метрика порождается
    нормой, то есть:
    ρ(x, y) ‌≡ ∥x - y∥.
    Тогда НП -- частный случай МП.
*** Пределы в НП                                                 :definition:
    x = lim(xₙ) ⇔ ρ(xₙ, x) → 0 ⇔ ∥xₙ - x∥ → 0.
*** Непрерывность линейных операций в топологии НП                    :lemma:
    В топологии НП линейные операции на X непрерывны.

**** Доказательство
     1. xₙ → x, yₙ → y,
        ∥(xₙ + yₙ) - (x + y)∥ ≤ ∥xₙ - x∥ + ∥yₙ - y∥ → 0
     2. αₙ → α, xₙ → x
        ∥αₙxₙ - αx∥ = ∥αₙ(xₙ - x) + x(αₙ - α)∥ ≤
        ≤ |αₙ|*∥xₙ - x∥ + (αₙ - α)∥x∥ → 0
*** Примеры НП                                                      :example:
    1. ℝⁿ, метрики l₀, l₁, l∞ -- в общем случае по lₚ варианту:
       ∥x∥ₚ = (∑(xₖ)ᵖ)^(1/p).
       ∥x∥∞ = sup{x₁...xₙ}
    2. C[a, b] -- функции непрерывные на отрезке.
       ∥f∥ = max{x∈[a,b]}|f(x)|
    3. Lₚ(E) -- известный пример, метрика -- (∫X |f|ᵖ)^(1/p)
*** Эквивалентность норм                                         :definition:
    Нормы φ₁ и φ₂ экивалентны (φ₁ ~ φ₂), если у них одинаковая
    сходимость, то есть ∀{xₙ} (xₙ →φ₁ x) & (xₙ →φ₂ x).
    Проверка на экивалентность также можно сделать следующим образом:
    ∃a,b > 0, ∀x∈ X a∥x∥₁ ≤ ∥x∥₂ < b∥x∥₁, где нижний индекс -- номер
    метрики.
*** Пример эквивалентных метрик в ℝⁿ                                :example:
    Построим единичную окружность по метрикам l₁, l₂, l∞.
    Нетрудно проверить, что все они эквивалентны, то есть множества
    сходимых по ним последовательностей равны.
*** Теорема Рисса                                                   :theorem:
    dim(X) < +∞, тогда любые 2 нормы в X эквивалентны.

**** Доказательство
     Возьмем {eᵢ} -- ЛНЗ базис из X.
     ∀x ↔ (α₁...αₙ) = α~ -- коээффициенты по базису.
     Пусть ∥ ∥ -- норма в X.

     ∥x∥₁ ≡ √(∑αₖ²)
     будем показывать a∥x∥₁ ≤ ∥x∥ ≤ b∥x∥₁ из определения экв. норм.

     1. ∥x∥ ≤ (неравенство треугольника) ≤ ∑∥eₖ∥*|αₖ| ≤ (Коши) ≤
        ≤ √(∑∥eₖ∥²) * √(∑αₖ²) = {первое константа b} = b*∥α~∥ =
        = b*∥x∥₁.
        ∥x∥ ≤ b*∥x∥₁.

     2. f(α₁...αₙ) ≡ ∥∑αₖeₖ∥;
        Тогда |f(α~ + Δα~) - f(α~)| = | ∥∑αₖeₖ + ∑Δαₖeₖ∥ - ∥∑αₖeₖ∥ | ≤
        ≤ ∥∑Δαₖeₖ∥ ≤ ∑∥eₖ∥*|Δαₖ| → 0.
        Значит f непрерывна в ℝⁿ.

        S₁ ≡ {x | ∑|αₙ|² = 1} -- единичная сфера.
        По теореме Вейерштрасса S₁ -- компакт.
        f непрерывна на S₁, тогда по теореме Вейерштрасса существует
        минимум: ∃α'~ ∈ S₁, что f(α'~) -- минимум, то есть все остальные
        f(α~) ≥ f(α'~).

        f(α'~) ≠ 0. Если бы была равна, тогда ∥∑α'ₖeₖ∥ = 0, а отсюда по
        ЛНЗ все αᵢ = 0, но α'~ ∈ S₁, там таких нету.

        Отсюда f(α'~) = m > 0, и тогда:
        ∥x∥ = ∥∑αₖeₖ∥ = f(α~) = √(∑αₖ²) * ∥ ∑(αₖ/√(∑αₖ²))eₖ ∥ ≥ m * ∥x∥₁.
        m и есть искомое a.
*** Линейное подмножество, линейное подпространство              :definition:
    1. Линейное подмножество -- множество точек замкнутых относительно
       операций умножения на скаляр и сложения.
    2. Линейное подпространство -- замкнутое линейное подмножество.
*** Следствие из теоремы Рисса о замкнутости                        :theorem:
    X -- НП, Y -- линейное подмножество X, dim Y < +∞.
    Тогда Y = Cl(Y), то есть Y замкнуто.

**** Доказательство
     y = L(e₁...eₙ) -- ЛНЗ набор = {∑αᵢeᵢ | αᵢ ∈ ℝ}.
     yₘ ∈ Y.
     Хотим: yₘ → y ⇒ y ∈ Y.

     ∥yₘ - y∥ → 0 ⇒ ∥yₘ - yₚ∥ →{mp → ∞}→ 0.
     Y конечномерно, тогда по теореме Рисса все нормы эквивалентны.

     ∥y∥₀ ≡ √(∑αᵢ²) -- определим такую норму.
     По теореме Рисса ∥ ∥ ~ ∥ ∥₀.

     ∥yₘ - yₚ∥ → 0 ⇒ ∥yₘ - yₚ∥₀ → 0. Заметим, что ∥yₘ - yₚ∥ ∈ Y.
     Тогда пусть α~ = (α₁...αₙ) ∈ ℝⁿ.
     Отсюда yₘ = ∑αᵢ^(m) * eᵢ, где верхний индекс -- номер α~., а
     нижний -- координата α~.

     Тогда есть покоординатная сходимость:
     ∀i ∈ 1..n  |αᵢ^m - αᵢ^p| → 0.
     Тогда αₘ~ = (α₁^m...αₙ^m) → α*.
     y* = ∑αᵢ*eᵢ ∈ Y.

     ∥yₘ - y∥ → 0.
     ∥yₘ - y*∥ → 0 (следует из ∥yₘ - y*∥₀ → 0 по экв. норм).
     Тогда y = y*, и поскольку y* ∈ Y, y ∈ Y.
*** Банахово пространство                                        :definition:
    Банахово пространство -- НП, полное в смысле метрического
    пространства.
    Сокращенно -- B-пространство.
*** Абсолютная сходимость в B-пространствах                           :lemma:
    X -- B-пространство. Тогда ∑∥xₙ∥ → 0 ⇒ ∑xₙ сходится.

**** Доказательство
     ∥Sₙ - Sₘ∥ = ∥∑{m+1..n}xₖ∥ ≤ ∑∥xₖ∥ →{n,m → ∞}→ 0.
     Отсюда существует предел Sₙ. что значит сходимость ∑xₙ.
