#+TODO: X 0 1 2 | OK
#+TITLE: Notes on functional analysis (given by Dodonov)
#+DATE: 2015, term 5

* Векторные пространства
** Метрические пространства
*** Метрика, метрическое пространство                            :definition:
    X, ρ: X×X → ℝ+ -- метрика, если:
    1. ρ(x, y) ≥ 0; ρ(x, y) = 0 ⇔ x = y
    2. ρ(x, y) = ρ(y, x)
    3. ρ(x, y) ≤ ρ(x, z) + ρ(z, y)

    Метрическое пространство -- пара <X, ρ>.
*** Предел по метрике                                            :definition:
    x = lim(xₙ) ⇔ ρ(xₙ, x) → 0
*** Топологическое пространство, топология                       :definition:
    Топологическое пространство (ТП) -- пара <X, Τ>, где X --
    множество, T ⊃ 2ˣ -- топология, если выполнено:
    1. Замкнутость T по объединению
    2. Замкнутость T по конечному пересечению
    3. X, ∅ ∈ T
*** Открытое множество                                           :definition:
    Множество открыто, если принадлежит топологии T
*** Предел в смысле ТП                                           :definition:
    <X,T>
    x = lim(xₙ) ⇔ ∀G ∈ T : x ∈ G, ∃N: ∀n > N xₙ ∈ G
*** Замкнутость через открытость                                 :definition:
    G -- открытое в T, тогда F = X \ G замкнутое

*** Открытый шар, представимость T                               :definition:
    * Bᵣ открытый шар в центре a = {x: ρ(x, a) < r}
    * T = {∪Bᵣ(a)}
*** X Связь МП и ТП                                               :statement:
    b ∈ Bᵣ₁(a₁) ∩ Bᵣ₂(a₂) ⇒ ∃ r > 0, Bᵣ(b) ⊃ (Bᵣ₁(a) ∩ Bᵣ₂(a))
    В этом смысле метрические пространства оказываются частным случаем
    топологических.
    ??? не вижу перехода
*** Примеры МП                                                      :example:
    1. ℝ, ρ(x, y) = |x - y|
    2. ℝⁿ, x~ = (x₁...xₙ) ∈ ℝⁿ
       ρ(x~, y~) ≡ √(∑{n}(xᵢ - yᵢ)²)
       αx~ = (αx₁...αxₙ)
       x~ + y~ = (x₁ + y₁, ...)
       xₙ~ → x~ ⇔ ∀j=1..n xⱼᵐ → xⱼ
    3. ℝ∞, xₘ~ → x~ ≡ ∀i=1,2,3..., xⱼᵐ → xⱼ
       Метрика Урысона:
       ρ(x~, y~) ≡ ∑{∞}(1/2ⁿ * |xₙ - yₙ|/(1 + |xₙ - yₙ)), где
       φ(t) = t/(1+t), то есть ρ(x~, y~) = ∑{∞}(1/2ⁿ * φ(|xₙ-yₙ|)).

       Кстати, для φ верно:
       Φ(t₁ + t₂) ≤ φ(t₁) + φ(t₂)

       ρ(xₘ~, x~) → 0 ⇔ ∀j xⱼᵐ → xⱼ
       Таким образом ℝᵐ метризуемо.
    4. Дискретная метрика
       ρ(x,y) = if x = 0 then 0 else 1
       xₘ → x, ε = 1/2, ∃M : ∀m > M ⇒ ρ(xₘ,x) < 1/2 ⇒ ρ(xₘ, x) = 0 ⇒
       xₘ = x
       То есть в такой метрике сходятся только последовательности,
       стабилизирующиеся после некоторого элемента -- стационарные.
*** Внутренность, замыкание, граница                             :definition:
    (X, T), ∀A ⊂ X:
    1. Int(A) ≡ ∪{G | G ⊂ A, G открытое}
    2. Cl(A)  ≡ ∩{F | F ⊃ A, F замкнутое}
    3. Fr(A)  ≡ Cl(A) \ Int(A)

    По аксиомам топологии ∀A Int(A) открытое, Cl(A) замкнутое
*** Расстояние до множества, между множествами                   :definition:
    ρ(x, A) ≡ inf{ρ(x, a) | a ∈ A}
    ρ(A, B} ≡ inf{ρ(a, b) | a ∈ A, b ∈ B}
*** Непрерывность расстояния до множества                             :lemma:
    Пусть f(x) ≡ ρ(x, A), x ∈ X.
    Тогда f непрерывно на X

**** Доказательство
     ∀x, y ∈ X:
     f(x) = ρ(x, A) ≤ ρ(x, a) ≤ ρ(x, y) + ρ(y, a)
     ∀ε > 0  ∃aₑ ∈ A : ρ(y, aₑ) < ρ(y, A) + ε = f(y) + ε
     f(x) < ρ(x, y) + f(y) + ε
     ε → 0,
     f(x) ≤ f(y) + ρ(x, y)
     Аналогично по симметричности
     f(y) ≤ f(x) + ρ(x, y)
     Отсюда: |f(x) - f(y)| ≤ ρ(x, y)
