#+TITLE: Lectures on philosophy IFMO 6th term

* Курс лекций от Ломовой
** Декарт/Бэкон -- материализм
   Почему декарт различает познание на чувственное и рациональное?

   Декарт -- скептик. Скептицизм -- отрицание того, что кажется
   непонятным и недоказуемым. В средневековии характерен авторитаризм,
   но Декарт его отрицает (учителя -- не авторитет, потому что все
   говорят разное, ..). Декарт ищет основание, не ища авторитетов --
   наука должна быть автономна от церкви.

   Чувственное познание обманывает Декарта, потому что он не может
   отличить сон от яви -- предполагает, что все может быть
   вымышленным. Реальность материи и вещей в науке аксиоматизирована,
   то есть идея "все -- воображение" не рассматривается. Чувственное
   познание Декарта принимается на веру, а крайняя степень эмпиризма
   -- это собственно и понимание чувственности как таковой. Декарт в
   предположении, что чувственное познание обманывает, оставляеет к
   нему доверие.

   Дуализм декарта -- это разделение человека на две составляющие --
   телесная (протяженная) и духовная (мыслящая). Таким образом,
   телесную часть он откитывает. Почему "я мыслю, значит я существую"
   применимо к Богу, но не применимо к чему-либо еще? Декарт был
   верующим, хотя не пытался связать свои логические/философские
   рассуждения с верой. Декарт не отрицает религию, как и
   Бэкон. Нельзя было просто не вписать Бога в идеологию, поэтому это
   было сделано.

   Как Декарт из предположения, что все ему кажется, приходит к
   выводу, что существуют физические тела и другие люди? Очевидно,
   рациональное познание чисто изначально, поэтому заблуждения
   приходят из телесной субстанции. Бог -- это исключительно духовная
   составляющая, без физической.

   Бог -- это вообще только мысль, а не то, что в привычном понимании.

   Доказательство существования бога:
   1. Исходя из того, что бог -- это только мысль и из того, что тело
      не может существовать и все мыслящее существует ⇒ бог тоже существует
   2. Если есть представление о себе как о несовершенном человеке, то
      существует нечто более совершенное и этим есть Бог -- гарантия
      совершенности.

   В общем случае существование бога необходимо для Декарта, чтобы
   доказать существование других людей, тел.

   Метод дедукции состоит из: отвержения авторитетов, разделение
   сложных вещей на более простые и переход к более общим вещам, как
   только более частные решены.

   Происхождение заблуждений по Декарту -- это телесное познание, а
   конкретно человеческая воля -- она же и движет его к познанию, она
   же и производит ошибки.


   Бэкон -- родоначальник индукции. Что такое индукция -- очевидно.

   У бэкона есть учение об идолах. Идол -- это причина
   несовершенства. Идолы бывают рода (заложенные в человеке), пещеры
   (личные заблуждения, мнения, необъективность), рынка (заблуждения
   связанные с речью), театра (неправильное толкование теорий или
   вообще восприятие идеологически неверных теорий).

   Бэкон критиковал Аристотеля за то, что его теория пронизана
   проблемой идола пещеры -- опыты Аристотеля подбивались под
   теорию. По поводу идола театра -- критиковалась схоластика,
   теология.

   Идолы необходимы, потому что с их помощью (устраняя их), можно идти
   к истине.

   Пути: муравей/паук/пчела. TODO
** Материя
   В основе предыдущих идеологий лежит понимание идей и материального
   мира, но материя зачастую не описывается.

   Происхождение и развитие категории материя:

   Материя -- это совокупность вещей и физических полей, а также
   других образований, имеющих субстрат -- материал, из которого они
   состоят. Некоторый вещественный или энергетический
   субстрат. Материя может быть объективной или субъективной.

   Любое определение дается через род и родовое отличие. У материи
   нету рода, потому определение такое, какое есть -- через некоторые
   свойства.

   Материалистический подход утверждает, что материя -- это основа
   бытия, а все иные бытийные формы (дух, человек, общество) --
   порождение материи. Материя первична. Материализм отвергает
   теологию, так как согласно материализму ни духовного Бога, ни
   рождения ниоткуда.

   Объективно-идеалистический подход -- материя объективно существует
   как порождение (объективизация) независимо от всего сущего
   первичного идеального духа. Это онтологии Платона, Гегеля,
   средневековья.

   Субъективно-идеалистический подход -- материи как самостоятельной
   реальности не существует вовсе, она лишь продукт (феномен)
   субъективного (существующего в виде сознания) духа. Это Кант.

   Позитивистский -- понятие "материя" ложно, так как его нельзя
   доказать и изучать эмпирически/опытно/научно.

   Категория материя развивалась следующий образом:
   1. Материя как вещь -- поиск первоосновы в античности. Это
      субстрат, субстанция. Демокритовский атом, Фалесовская вода,
      Анаксимандр и "апейрон".
   2. Материя как свойство -- целью есть дать картину природы как
      таковой (новое время). Механический подход рассматривал материю
      как относительно устойчивое тело, перемещающееся в пространстве
      с течением времени. Всеобщая суность состоит из атрибутов вроде
      массы, протяженности, непроницаемость. Качественно материя
      определяется массой.

      Из статических законов механики Ньютона и электродинамики
      Максвелла рождается детерминизм -- учение о причинной
      материальной обусловленности явлений (природных, социальных).
   3. У Маркса материя -- это естественно-научное понимание,
      единственно существующая реальность и помимо и вне ее ничего не
      существует. Материя постоянно движется (во времени
      пространстве), причем движение -- это способ ее
      существования. Формы движения: механическая, физическая,
      химическая, биологическая и социальная. Между тими формами
      существует диалектическая связь (диалектика как наука о познании
      движущихся объектов).

      Рациональность по Декарту -- это разум, отношение человека к
      собственному разуму. Текущее значение этого слова -- это
      практичность, то есть современность ставит разум после материи,
      материя порождает сознательность.

      В материализме движение (диалектика) порождает материю.

      Помимо движения, есть понятия пространства и времени: время --
      форма бытия материи, которая выражает длительность существования
      материальных объектов и последовательность смены их состояний.c

      Пространство -- форма существования материи.
   4. Материя как отношение.

      Отношение пространства и времени к материи.
      * Субстанциональная концепция (Демокрит, Эпикур, Ньютон)
        трактовали пространство и время как самостоятельные сущности,
        существующие наряду с материей и независимо от нее. Причем у
        Ньютона время делится на относительное (субъективное) --
        время, к которому мы привыкли (промежутки, интервалы) и
        абсолютное (время как таковое, его сущность).
      * Реляионная концепция (Аристотель, Лейбниц, Гегель) понимали
        пространство и время не как самостоятельные сущности, а как
        отношения, образуемые взаимодействием материальных
        объектов. Вне взаимодействия пространство и время не
        существуют.

      СТО Эйнштейна и геометрия Лобачевского изменяют понимание
      геометрии и материи, времени и пространства. Время становится
      зависимым от размеров, от пространства. Любой материальный объкт
      рассматривается как двиижение.
** Сознание
   Сознание как философское понятие определяет анализ всех форм
   проявления духовной и душевной жизни человека в их единстве и
   целостности, а также способов контроля и регуляции его
   взаимоотношений с действительносью, управления этими
   взаимоотношениями.

   Сознание делится (кем?) на:
   1. Душа (трансцендентное).
   2. Психика (иманентное).
   3. Мышление и разум (мир).

   Исторически:
   * В античной философии сознание направлено на объект.
   * Платон выделяет понятие идеального как противоположность
     материальному.
   * Средние века -- сознание как надмировое начало (Бог), разум --
     атрибут Бога.
   * Новое время -- осознание ценности человеческой личности, переход
     от "души" к "сознанию". Нет сознания без самосознания. Декарт --
     сознание как субстанция открытое для субъекта. Кант --
     трансцендентальное единство апперцепции.
   * Абсолютный идеализм Гегеля обосновывает социально-историческую
     природу сознания. Есть абсолютный дух, который создает сознание
     впоследствии, причем сознание не зависит от материи, не
     порождается даже. Идеальность -- основной атрибут сознания.
   * Абсолюное самосознание -- надличностное, всеобщее начало,
     движущееся по внутренним законам.
   * Материалистическая философия исходила из принципов признания
     сознания функцией мозга и отражения внешних воздействий. (с 18
     века материализм).

   История развития взглядов на природу сознания (Маркс):
   1. Диалектико-материалистическая концепция сознания
   2. Сознание вторично, детерминировано экономическими факторами.
   3. Сознание есть осознанное бытие.

   Маркс отрицает сознание у не-людей, у детей до 3х лет (примерно), у
   людей, которые не могут говорить.

   По Марксу сознание есть высшая форма психического отражения и
   саморегуляции, присущая человеку, то, что отличает его от
   животных. Этими особенностями являются:
   * Наличие речи
   * Умение логически мыслить
   * Умение планировать свою деятельность
   * Наличие мира внутренних переживаний
   * Наличие отношения к миру
   * Умение моделировать в сознании по своему усмотрению
   * Появление мышления как самостоятельной внутренней деятельности.

   Сознание как отражение -- всеобщее свойство материи, связанное с
   потенциальной информацией, заключенной в эффектах материального
   взаимодействия и информационное взаимодействие, появляющееся на
   стадии живой природы.

   Генезис сознания как информационного взаимодействия:
   1. Отражение -- свойство взаимодействующих тел воспросизводить в
      своей внутренней структуре особенности друг друга.
   2. Раздражимость -- реакция на раздражители.
   3. Возбудимость
   4. Психика

   Разговор зашел о идеомоторике, о контроле над человеческим телом
   (собственным).

   По Марксу сознание связано с формированием культуры на основе
   общественной деятельности людей. Сознание -- общественная
   надстройка.

   # было сказано, что в мире все названо, а я пытался сказать, что
   # это херь

   Язык -- система знаков, служащая для объективации человеческого
   общения. Существование знаковых систем является одним из признаком
   сознания.

   Этапы самосознания:
   1. Самочувствие, выделение себя из предметного мира.
   2. Осознание принадлежности к обществу.
   3. Возникновение сознания "Я" -- понимание "знание о наличии
      собственного знания". Самокритика.

   # Это "самосознательность" подгоняется к любой горилле (к какой-то
   # частной, вернее).
   # https://en.wikipedia.org/wiki/Washoe_(chimpanzee)
   # https://en.wikipedia.org/wiki/Koko_(gorilla)

   Бессознательное:
   1. Шеллинг, Шопенгауэр -- бессознательное как первоисточник всего
      сущего.
   2. Эдуард фон Гартман -- отрицание главенствующей роли разума и
      утверждение примата воли.
   3. Ницше -- бессознательное как условие всякого совершенства.

   У Ницше сознательное -- ненужная некоторая вещь, параллельная с
   бессознательным.

   У Маркса бессознательное -- это проблема наличия скрытых
   детерминант в сознании. Процесс детерминации скрыт от сознания, не
   представлен в опыте. Бессознательное Маркса коллективно -- это не
   осознавание обществом своего положения в нем же.

   Маркс считает, что сущность человека в труде, поэтому, скажем,
   крестьянин, продающий хлеб, не осознавая экономической структуры
   рынка, несчастен, так как счастье есть коллективный труд.

   По Фрейду бессознательное не доступно свободному осознанию, причем
   оно первично. Психика по Фрейду делится на 3 компоненты:
   1. Оно (id) -- глубинный слой инстинктов, руководствуется
      "принципом удовольствия".
   2. Я (ego) -- сфера сознательного. Проводник между "оно" и внешним
      миром.
   3. Сферх-Я (super ego) -- внутренний цензор, содержит
      фундаментальные для общества и культуры запреты.

   Личность по Фрейду разорвана изначально. Культура, ограничивающее
   "id", и порождает человека. Без культуры не может существовать
   ограничивающего сверх-я.

   Критика Фрейда:
   1. Человек по своей природе враг своей культуры.
   2. Противопоставляется человеческая природа и культура.

   Карл Густав Юнг:
   * Структура бессознательного.
   * Сознание включает "персону" и "эго".
   * Личное бессознательное включает "тень", "аниму", "самость".
   * Коллективное бессознательное -- архетипы (некоторые родовые
     паттерны).

   Подробнее:
   * Персона -- особенности личности и формы поведения в социальных
     ситуациях, маска для социума.
   * Эго -- центр, управляемый персоной.
   * Тень -- обратная сторона "Персоны", то, что человек знать о себе
     не хочет.
   * Анима или анимус -- образ женщины в психике мужчины или наоборот.
   * Самость -- глубинный центр психики, связанный с го, не
     проявляемый на сознательном уровне. Интуиция.
** Человек как проблема философии, сущность человека
   1. Три подхода к анализу сущности человека.
   2. Историко-философское: восточная философия, антропологический
      поворот в греческой философии, эллинистическая философия --
      стоицизм, скептицизм, эпикуреизм.

   Сущность человека. Сущность называется то, благодаря чему нечто
   есть то, что оно есть. Сущность человека -- это те из его свойств,
   которые нельзя изменить, чтобы он не перестал быть собой.

   Сущность:
   1. Родовая -- качества, присущие человеку, как роду (биологические
      и социальные).
   2. Социально-историческая сущность -- self-documented.
   3. Индивидуальная сущность -- память, психика.

   Три подхода к пониманию сущности:
   1. Субстратный -- вещь есть то, из чего она состоит. Все ее
      качества определяются этим субстратом. Если это камень, то
      материал -- его сущность.
   2. Функциональный -- существование связано с целевой причиной, с
      внешней целью. Функция -- соответствие между назначением объекта
      и его бытием.
   3. Субстанциональный -- вещи определяются способом самоцельного
      существования в среде. Отвечает на вопрос "почему?".

   Древняя Индия:
   1. Ведические тексты, источник жизни -- пуруша (космический
      великан, распадаясь, дарующий жизнь).
   2. Сословия (варны): брахманы (проповедователи), кшатрии (воины),
      вайшьи (ремесленники), шудры (слуги).
   3. Безлично сущее (брахма), духовно сущее (атман).
   4. Сансара и карма.

   В древней Индии проповедуется аскетизм.

   # было сказано что-то про буддизм, что не сильно коррелирует с
   # реальностью

   Даосизм -- учение о пути. "Дао" -- путь. Есть мировой порядок, ему
   нуно соответствовать. В китае очень много разных школ.

   Согласно Конфуцию, лучший человек -- гуманный и
   милосердный. Представления о личности в китайской философии нету,
   зато есть дух, мировой баланс.

   Самые известные софисты: Протагор и Горгий. Как и все софисты,
   Протагор проповедует дуализм мнений, объективность мнения. Сказ о
   Протагоре и Эватле. Горгий истинность вообще отрицал.

   Сократ рассматривает добро, зло, благо как сущность человека, а не
   какие-то внешние вещи. Поэтому добродетель существует у него сама
   по себе.

   Эпикуры, скептики, стоики.

   Пирон (скептик) -- чтобы достичь счастья, следует отказаться от
   суждений. Гераклит тоже про это говорил, в контексте "все течет,
   все непостоянно".

   Демокрит -- предопределенность, все движется по строго определенным
   траекториям. Фатализм. Эпикур говорит, что это неверно. Эпикур
   понимает идеального философа как человека, ведущего свободную от
   страданию жизнь. Атараксия -- цель жизни с точки зрения
   эпикурийцев.

   Стоики -- опираются на материалистическое учение Демокрита,
   Героклита. Связывают свободу с необходимостью.

   Платон и его представление о человеке -- в объективном идеализме
   человек дуален. Делится на материальное и идеальное (душа). Душа и
   тело помогают человеку обретать знания как припоминания, познавать
   эти идеи.

   Душа у Платона:
   1. Аффективная -- воины
   2. Разумная -- правители и философы
   3. Вожделеющая -- крестьяне
** Антропология древней греции
   У Платона человек -- душа вечная и тело смертное. Души не творятся
   постоянно, они пребывают на звездах. Души -- это идеи жизни. Душа
   различается на разумную, неразумную, в неразумной на аффективную и
   яростную. Благо -- высшая идея. Зло -- отсутствие
   блага. Метемпсихоз -- переселение душ.

   Аристотель -- душа есть причина и начало живого тела. Соотносится с
   телом как материя и форма. Имеет три уровня: вегетативный,
   чувственный, разуменый. Душа есть причина как то, откуда движение,
   как цель и как сущность. Разумная душа та, которая мыслит и
   познает.
** Антропология средневековья
   Человек и бог в христианской философии. Творение человека,
   грехопадение. Боговоплощение. Проповеди Иисуса Христа. Распятие и
   воскресение. Человек -- богоподобное существо с чистой душой.

   Человек свободен был только до того, как бы изгнан из рая. Без
   этого все определено. Августин определяет линейное время (прошлое,
   настоящее, будущее). Августин фаталист.

   Фома Аквинский критикует идею доказательства бога Августина,
   утверждая что доказательство бога истекает из его (бога)
   творений. Фома -- умеренный реализм (христос -- не бог, потому что
   бог не может быть человеком). Вера и знание -- объединение
   интеллекта и чувственности, в то время как бог -- только
   интеллект. Однако не настаивает на главенстве разума (любовь к Богу
   важнее). Фатализма нету -- если человек делает зло, то это не воля
   Бога, а человеческая деятельность. Молитва, исповедь и покаяние --
   техники гуманизации, потому что только в этих актах человек
   постигает глубину своей души.
** Антропология разума
   Кант. Человек -- это цель в себе. Одновременно номен и
   феномен. Разум нужен человеку для того, чтобы выходить за границы
   познания. Там он впадает в антиномии. Человеческая воля автономна,
   фатализма нету. Определяется воля через категорический императив.
   Категорический императив -- "поступай так, чтобы максима твоего
   поведения на основе твоей воли могла бы стать общим естественным
   законом". Это потом повторяется Сартром.

   Эстетика Канта -- эстетика бесполезности. Мы никогда не
   рассматриваем полезные вещи эстетическими. Все эстетические вещи
   бесполезны.

   Гегель. Сущность человека -- дух, не индивидуальность. Человек,
   прежде всего, это человеческий род, разделение на расы.
   Индивидуальные качества происходят из родовых сущностей -- труда и
   общества. Абсолютный дух движется к своему самопознанию.
** Сущность человека в марксистской философии
   У Маркса человек -- часть природы. Благодаря труду человек
   выделился из животных в мир природы. Изменение материальному
   производству человек начинает обретать некоторые социальные
   общности. Потребности человека -- реализация и осуществление
   социальных отношений. Индивидуальное сознание -- продукт
   общественных отношений. Только социум и общ. сознание говорит о
   наличие в человеке сознания.
** Экзистенциализм
   Сущность человека в экзистенциализме не существует. У Хайдегера
   человек -- преступление (переступление через себя). Суть --
   движение к смерти (нельзя это преодолеть). Попытки себя превзойти
   исходят из понимания смертности. В движении к смерти Хайдегер видит
   смысл. Человек пытается избежать идеи смерти. Страх как постоянная
   боязнь смерти, Ужас как понимание смерти на ее рубеже.

   Камю. Миф о сизифе отражает сущность современного общества и
   человека в частности -- существование абсурдно. Потом еще
   поговорим.

   Сартр -- тоже потом обсудим.
** Философская аксиология
   Аксиология -- теория ценности.

   Ценности. Концепции ценностей:
   1. Объективно-идеалистический подход. Ценность -- идея.
   2. Теологические. Ценности имеют божественное происхождение. Бог --
      справедливость, добро, разум, красота.
   3. Феноменологичечкие. Сознание порождает ценности.
   4. Экзистенциальный. Ценность субъективна -- акт индивидуального
      выбора.
   5. Биолого-натуралистический. Ценность -- полезное. То, что
      приносит удовольствие.
   6. Социологический. Ценности порождаются социальной средой.

   Высшая и абсолютная ценность -- это сам человек, его жизнь.

   Нельзя путать цель и смысл жизни -- цели можно ставить и без
   осмысления своего предназначения.

   Проблема смысла жизни:
   1. Теоцентрический -- рассматривает человека как сотворенного для
      реализации божьего замысла.
   2. Космоцентристский. Человек -- сущность, воплощающая в себе, как
      в микрокосме, законы космоса.
   3. Социоцентристский подход. Смысл жизни -- деятельность.
   4. Антропоцентристский -- смысл жизни есть ??

   Наука -- это не добро или зло, наука -- это истина.
** Сартр "Экзистенциализм -- это гуманизм". Тезисы
   * Критика со стороны христиан, коммунистов
   * Люди, которые критикуют, сами часто считают правильными
     пессимистические мудрости, оправдывают человеческие пороки
   * Экзистенциалисты -- христиане (ясперс, марсель) и атеисты.
   * Сравнение с ножом -- изготовление предшествует
     существованию. Аналогично Декарт, Лейбниц и их Бог. Аналогичног
     атеисты 17-18-19 веков (Кант)
   * Экзистенциализм -- обратное.
   * Первый принцип -- человек сначала существует, а потом уже создает
     сам себя. Экзистенциализм возлагает на человека полную
     ответственность за свое существование.
   * Субъективизм -- индивидуальный субъект сам себя выбирает. Или что
     он не может выйти за рамки человеческой субъективности. Второе --
     глубокий смысл экзистенциализма.
   * Создавая себя субъективно, мы создаем себя в сознании других,
     поэтому создаем других. Совершая поступки, мы выбираем благо,
     благо для всех (потому что добро должно быть всеобщим). Пример с
     христианским союзом и женитьбой как пропагандой моногамии.
   * Тревога -- чувство отвестственности за свои поступки (они
     задевают все человечество). Многие скрывают тревогу и лгут "все
     так делают". Кьеркегоровская тревога Авраама -- "действительно ли
     это Ангел а я Авраам?". Действительно ли человек имеет право
     действовать так, чтобы человечество брало пример с его поступков?
     Не думать об этом -- скрывать тревогу.
   * Заброшенность -- бога нет, беспокойство по поводу того, как
     вывести ценности без него. "Если бога нет, то все дозволено". Нет
     детерменизма, человек -- свобода. С другой стороны, нету и
     ценностей, нет оправданий и извинений.
   * Пример с младшим братом, который не хотел бросать мать, но имел
     целью отомстить за старшего брата. Выбор между пользой для
     конкретного человека и для нации. Мораль симпатии и личной
     преданности, мораль широкая но менее действенная (месть,
     война). Какой выбор сделать? Парадокс с целью и средством (любой
     выбор делает кого-то средством, а кого-то целью). Доверие
     инстинктам и порочный круг "нужно сделать поступок, чтобы его
     оценить". С другой стороны, можно разыграть поступок, что будет
     тем же, или обратиться за советом, но выбор советчика и
     интерпретация знамения -- выбор. Заброшенность -- мы сами
     выбираем наше бытие.
   * Отчаяние -- принятие во внимание того, что зависит от нашей воли,
     или сумму вероятностей, которое делает возможным действие. Можно
     более-менее рассчитывать на партию, действия которой ты можешь
     более-менее контролировать. Нельзя рассчитывать на людей, которых
     не знаешь, на их качества, ведь человек свободен. "Нет нужды
     надеяться, чтобы что-то предпринимать" -- нужно решить, а затем
     действовать.
   * Человек -- проект себя, экзистенциализм отрицает утверждения вида
     "я не сделал чего-то, потому что не получилось". Вне облика
     ничего нет. Человек есть только ряд его поступков -- совокупность
     отношений, из которых составляются эти поступки.
   * Трус определяется по поступку, а не по темпераменту. Не бывает
     "трусливых" людей априори.
   * Экзистенциализм -- не квиетизм.
   * Экзистенциализм -- единственная теория, не делающая человека
     объектом. Познать себя можно только через другого. Мир, созданный
     этим пониманием -- интерсубъективность.
   * Моральный выбор -- это произведение искусства. Упрекать человека
     за выбор то же, что упрекать художника за то, что он не следует
     художетсвенным стандартам.
   * ? Бессмысленно упрекать кого-то в произвольности выбора -- но
     выбор действительно можно делать произвольно (это уже мое
     наблюдение и вопрос)
   * Судить человека за выбор нельзя, потому что обычно каким бы не
     был проект, ему невозможно предпочесть другой. Но можно судить,
     какой выбор основан на заблуждении (логическое, а не оценочное
     суждение). Можно судить о нечестности человека. Нечестность --
     это тоже выбор, но нечестность противоречит последовательности и
     логике.
   * Сартр называет тех, кто стремится скрыть от себя полную свободу:
     1. С помощью детерминизма -- трусами.
     2. С помощью априрорной необходимост существования -- сволочами.
     Судить эти две категории можно только с точки зрения полной
     аутентичности.
   * Пример с "мельницей на флоссе" и "Пармской обителью" --
     отказаться от любви или объявить ее максимальной ценностью значит
     ставить целью свободу. Таким образом, выбирать можно все, что
     угодно, если речь идет о свободе решать.
   * Выбирать ценности самостоятельно приходится, потому что нету
     априорной морали.
   * Гуманизм имеет два определения.
     1. Плохое -- человек есть высшая ценность и цель.
     2. Человек находится в сердцевине проектирования себя во
        вне. Гуманизм -- это связь констатирующей трансцендентности
        (в смысле выхода за свои пределы) и субъективности (человек не
        замкнут, а присутствует в человеческом мире).
   * Экзистенциализм -- попытка сделать выводы из последовательного
     атеизма. Не попытка, доказывающая отсутствие бога, а доказывающая
     индифферентность божественного влияния.
* Классификация per-philosopher
** Кант
   * Материализм, трансцендентальный идеализм
   * Гносеология, невозможность познания "вещей в себе".
   * Знание -- совершенное и несовершенное. Совершенное знание имеет
     исключительно априорный (не эмпирический) характер.
   * Чистый разум -- разум, наделенный априорным знанием.
   * Трансцендентальная эстетика -- учение об априорных формах
     чувственности. Трансцендентальная логика -- об априорных формах
     рассудка.
   * "Критика чистого разума" отвечает на три вопроса -- "как возможна
     чистая математика", "как возможно чистое естествознание" и "как
     возможна метафизика как наука".
   * Предметом трансцендентальной эстетики есть рассмотрение
     пространства и времени как априорных форм чувственности (чистые
     созерцания).
   * Чувственность пассивна, рассудок активен.
   * Познание -- это конструирование с помощью чувственности и
     рассудка, а не интуиции.
   * Трансцендентальная логика -- это трансцендентальная аналитика
     (рассудок и его априорные принципы) и трансцендентальная
     диалектика (исследование разума, как высшей познавательной
     способности).
   * Рассудок имеет дело с априорными категориями. Категории:
     1. По количеству: единство, множество, целокупность.
     2. По качеству: реальность, отрицание и ограничение.
     3. По отношению:
        1. Присущность и самостоятельное существование (субстанция и
           акциденция).
        2. Причина и действие.
        3. Общение (действие и подвергающиеся действию).
     4. По модальности: возможность-невозможность,
        существование-несуществование, необходимость-случайность.
   * Категории доступны рассудку априори.
   * Трансцендентальная апперцепция -- априорное самовосприятие, то
     есть самосознание.
   * Трансцендентальная схема -- априорная форма, однородная с
     категориями и явлениями (и интеллектуальное, и чувственное).
   * Естествознание есть наука, обусловленная априорной необходимостью
     (категория), с помощью схемы рассматривает суждения
     (чувственность).
   * Разум -- способность давать принципы, а рассудок -- способность
     давать правила. Рассудок аппелирует к опыту, а разум анализирует
     рассудок и ничего больше.
   * Трансцендентальные идеи (чистые понятие разума) -- то, что
     создает разум. Рассудок создать не может. Выделяется три:
     1. Идея о душе или об абсолютном безусловном единстве мыслящего
        субъекта. Психология.

        Душа недоказуема и неопровержима, как "вещь в себе", поскольку
        эмпирический опыт субъективен, категории "субстанция", а также
        понятия "простота и неделимость" не применимы к
        трансцендентальному субъекту, а также бессмертие души не
        наблюдается в опыте.
     2. Идея о мире или об абсолютном единстве условий
        явлений. Космология.

        Набор антиномий (тезисы и антитезисы) о космосе, доказывающих
        его непознаваемость.

        * Выводы из антиномичности космоса:
          1. Рассудку следует ограничиться регулятивной деятельностью
             упорядочения опыта.
          2. Разуму следует истолковывать решения, касающиеся тезисов
             и антитезисов антиномий только в регулятивном смысле.
          3. Понимать саму косологическую идею следует как регулятор
             мысли о природе -- что-то, что можно рассматривать, хотя
             невозможно познать.
     3. Идея об абсолютном единстве всех предметов мышления вообще или
        о боге. Теология.

        Попытки применения разума к теологии бесплодны и
        никчемны. Применения разума к природе не ведут к
        теологии. Значит, бог тоже есть "вещь в себе".
   * Польза философии чистого разума -- предохранение от заблуждений,
     методология определения границ. Истина непостижима.
   * Рациональная психология, космология и теология -- не науки,
     поскольку пытаются рационализировать вещи в себе. Поскольку из
     них состоит метафизика, то она тоже не наука.
   * Метафизика возможна как наука об априорных фофрмах познания,
     следующая из естественного стремления человека к познанию. Ей
     следует также быть критикой всех претензий на познавание
     недоказуемого. Также метафизика должна стать этической
     онтологией.
   * Метафизика в смысле онтологии должна отвечать на вопросы "что я
     могу знать?", "что я должен делать?", "на что я могу надеяться?".
   * Примат разума практического над теоретическим -- необходимость
     человека познать сверхчувственный мир.
   * "Критика практического разума" показывает, что развитая личностью
     нуждается только в знании, а не в его опеке, ибо цель и ориентир
     познавания априорны.
   * Этика Канта априорна и автономна (независимость моральных
     постулатов от внешней морали). Этика есть долг.
   * Нравственные, моральные законы (или императивы) -- законы
     долженствования, но законы природы -- законы необходимости.
   * Императив: гипотетический (гетерономная этика, сообразность с
     долгом, легальность) и категорический (бесусловный, из чувства
     долга, моральность).
   * Категорический императив вытекает из трансцендентной природы
     человека.
   * Вера -- необходимый элемент для априорности нравственного
     закона, трансцендентального. Мнение -- признание истинности
     чего-либо потенциально субъективно или объективно
     недостаточного.
   * Свобода трансцендентна и может быть только в сверхчувственном
     мире "вещей в себе". Требует веры в себя.
   * Свидетельством соединения в человеке чувственного и
     сверхчувственного есть антагонизм между естественными и
     нравственными стремлениями. Единство человека требует синтеза
     нравственности (добродетели) и благополучия. Следовательно, для
     нравственного сознания лишь добродетель достойна благополучия. С
     другой стороны, это на практике не наблюдается. Поскольку
     благополучие не нужно искать в сфере сверхчувственного, но его
     достижимость необходима, то необходимо признавать Бога и
     бессмертную душу.
** Фихте
   * Развивался от Канта, изменил его с точки зрения субъективного
     материализма.
   * Выведение всего сущего из абсолютного чистого "Я".
   * Я -- это понятие человеческого духа, выражающее единство разума и
     воли, познания и нравственности, действия и страдания.
   * Наукоучение:
     1. Я полагает само себя и оно есть только из-за
        этого положения.
     2. Я полагает не-Я.
     3. Я противополагает делимому Я делимое не-Я.
   * Признает диалектику.
** Шеллинг
   * Кант с объективным идеализмом.
   * Развивает наукоучение Фихте, но принимает в качестве первоосновы
     сущего не "Я", а более общий абсолют, в котором растовряется как
     "Я", так и "не-Я".
   * Монизм в виде тождества мышления и бытия.
** Гегель
   * Известные произведения -- "Феноменология духа", "Логика",
     "Энциклопедия философских наук", "Философия права".
   * Исходил из монистических идей Шеллинга, но видел различие в бытие
     и сознании, не отрицая тождество (как не абсолютное). Это
     различие -- побудительная причина существования мира. Также
     абсолют сознательный, а не случайный как у Шеллинга.
   * Признает познавание бытия, отрицает непознаваемость "вещи в
     себе".
   * Принцип развития -- абсолют (мировой дух, абсолютная идея)
     непрерывно развивается. Саморазвитие абсолюта и его самопознание
     -- одно и то же.
   * Абсолют похож на субстанцию Спинозы, за исключением постоянного
     движения. Абсолют -- синтез шеллинго-фихтеанского "я" и
     субстанции Спинозы.
   * Абсолютная идея проходит 3 этапа -- логический, природный и
     духовный. Деление философии на философию логики, природы и духа.
   * Задача философии -- показать, что все конкретныме эмпирические
     формы жизни природной/животной/общественной есть исторически
     различные ступени абсолютного духа.
   * Первая стадия абсолюта (логика) делится на бытие, сущность,
     понятие. Рассматривается в "науке логики".
     * Бытие -- качество, количество, мера.
     * Сущность -- полагание сущности самой собой, утверждение
       самосуществования (явления), снимание абстрактых определений.
     * бытие → качество → количество → мера → сущность → явление →
       действительность.
     * Понятие -- подлинное развитие, диалектический процесс.
   * Наука логики определяет идеалистическую диалектику Гегеля:
     1. Принцип перехода качества в количество
     2. Принцип противоречия как источника движения
     3. Принцип двоного отрицания
        (тезис-антитезис-синтез). Спиралевидная форма развития.
   * Понятие проходит три ступении -- субъективное понятие,
     объективность, идею (единство понятия и объективности, истину).
   * Идея проходит жизнь, познание и абсолютную идею.
     * В качестве процесса идея -- чувственность, раздражимость и
       воспроизведение.
     * Познание -- стремление к истине, теоретическая деятельность
       (но воление -- практическая деятельность идеи).
     * Абсолютная идея -- единство теоретической и практической
       идей. Она начинает созерцать свое собственное содержание. Но
       созерцающая идея -- это природа, то есть бытие. Вернулись к
       бытию, но в виде природы, себя осознающей.
   * Исследование природы -- вторая составляющая гегелевской
     философской системы.
   * Природа -- материальное. Развивается ступенчато, но метаморфоза
     только в виде живых существ, так как метаморфоза в полной мере
     доступна лишь в сфере понятия.
   * Переход между ступенями природы -- эманация или
     эволюция. Эманация рассматривается как переход от более
     совершенного к менее, эволюция -- наоборот.
   * Идея обнаруживает себя в виде механики, физики и органики.
     1. Механика -- пространство, время, материя, движение. Материя
        качественно неопределена тут.
     2. Физика определяет материю в виде физических и химических
        свойств.
     3. Органика есть верх развития химии.
   * Органическая природа -- минеральная, растительная и животная.
   * Дух -- наивысшая форма существования идеи. Свобода духа -- власть
     над всем имеющемся в нем содержанием.
   * Дух развивается как субъективный → объективный → абсолютный.
   * Нравственность (конец объективного духа) -- семья, гражданское
     общество, государство.
   * Одобряет монархию.
   * Государство находит свое полное развитие во всемирной истории.
   * Всемирная история -- имеет своей целью и содержанием развитие
     свободы путем ее осознания.
   * Европоцентризм -- развитие истории с Азии на запад (азиатская
     философия и рабство, греческая и и римская с частичным рабством,
     германо-западная как свобода всех людей). Христианство --
     идеальная религия.
   * Абсолютный дух -- искусство, религия, философия.
   * Диалектика Гегеля -- переход тезиса в антитезис, синтез, и снова по
     новой (третий закон диалектики). По большей части относится к
     познанию, но можно применять и к истории.
** Фейербах
   * Антропологический материализм.
   * Прочитал Гегеля и сказал, что это полный бред.
** Маркс, Энгельс
   * Критический материализм, основанный на критике Гегеля и
     переосмысления Фейербаха.
   * Диалектика основана на Гегелевской, но в намного более
     материалистическом стиле.
   * Первичность бытия, вторичность духа. Признается творческий момент
     в сознании (в отличии от Фейербаха).
   * Материя -- единственное, что существует. Она пребывает в
     постоянном движении. Движение определяется как атрибут материи.
   * Формы движения материи: механическая, физическая, химическая,
     биологическая, социальная. Порядок соответствует развитию. Между
     формами есть диалектическая связь так как все последующее было
     создано из предыдущего.
   * Пространство и время -- основные формы бытия.
   * Материя, движение, пространство и время -- аксиоматика
     (неразделимы).
   * Материя познаваема. Критика Канта.
   * Сознание -- сложный диалектический процесс. Делится на
     чувственно-эмперический и мысленно-теоретический.
   * Человек стремится познать бесконечный мир, но его возможности
     ограничены. Познание есть приближение к абсолютному знанию
     (предел).
   * Также человек ограничен конечным сознанием, поэтому понимание
     бесконечного возможно лишь частично.
   * Истина всегда относительна, поскольку существует
     заблуждение. Достижение абсолютной истины значило бы завершению
     природного процесса, что противоречило бы основным законам
     диалектического мышления.
   * Истина -- знание, адекватно отображающее
     действительность. Практика -- важнейшая компонента
     познания. Только через практику сознание творит и отражает мир.
   * Диалектика делится на объективную (природа, общество) и
     субъективную (мышление и познание).
   * Законы диалектики (3 штуки) -- такие же как у Гегеля.
   * Материальное производство -- основа жизни и развития общества. Из
     производства следует общение (гражданское общество), которое
     яесть часть государственной жизни. Последняя порождает
     теоретические порождения и формы сознания, религию, философию,
     мораль. Из всего этого следует история.
   * Материальные отношения -- производственные (экономические),
     бытовые, семейные и национальные.
   * Общественное бытие -- совокупность отношений, в которых
     производственное играет основную роль.
   * Сознание -- осознанное бытие, а бытие людей есть общественное
     бытие. Общественное бытие определяет сознание.
   * Естественноисторический процесс -- результат деятельности людей,
     преследующих свои цели.
   * Социальные законы. Много их. В том числе закон о роли базиса и
     надстройки. Бывают законы независимые от периода общественного
     развития (структура производства), зависимые (разбиение на классы
     и закон классовой борьбы).
   * Собственность -- реальная совокупность отношений между людьми.
   * Общественное производство -- производственные силы (содержание) и
     производственные отношения (форма). Производственные отношения
     развиваются, пока не представится достаточно простора для
     развития производственных сил. Тогда отношения становятся оковами
     и происходит революция. Все продолжается заново.
   * Исторический материализм -- история рассматривается как смена
     способов производства.
   * Общественно-экономические формации -- типы общества в истории.
   * По Марксу пять формаций -- первобытнообщинна, рабовладельческая,
     феодальная, капиталистическая и коммунистическая. (и еще
     азиатская?)
   * Базис -- совокупность производственных, экономических
     отношений. Надстройка -- система политических, юридических,
     идеологических отношений и институтов. Каждое историческое
     общество имеет специфичный базис и надстройку.
   * Функция надстройки -- охрана базиса. Базис первичен.
   * Понятие эпохи.
   * Отчуждение:
     1.
** Шопенгауэр
   С начала 17 века и до второй половины 19 века самым популярным
   движением в философии был рационализм. Рационализм прославлял разум
   и знание. Яркими представителями были:
   * Декарт, ставящий мыслящее "я" на первый план. Его метод познания
     из четырех пунктов: первенство интуиции, индукция в частных
     вопросах, дедукция всего метода познания, цель -- полнота
     знания. Знаменитое cogito ergo sum -- основатель базы
     солипсизма. Скептицизм.
   * Спиноза, пути познания (произвольное знание, чувственное, знание
     из рассуждения и интуиция). Познаваемость мира.
   * Лейбниц вообще был логиком, признавал делил истины на истины
     разума (то, что можно придумать) и факта (единичные кванты
     информации). Правила -- принцип противоречия (противоречивые
     системы рассматривать нет смысла) и принцип достаточного
     основания.
   * Кант с путями познания, вещами в себе, трансцендентальной
     эстетикой и логикой. Разум и рассудок. Императивы, категорический
     и гипотетический.
   * Фихте, субъективный идеализм, вопросы вокруг "Я".
   * Гегель, который отрицал Канта с точки зрения
     познаваемости. Диалектика гносеологии -- принципы диалектики
     (качество в количество, противоречие как источник движения,
     тезис-антитезис-синтез).
   * Энгельс, Маркс (без комментариев)

   Но рационализм постепенно начал терять свою
   популярность. Во-первых, людям свойственно интересоваться более
   практическими вещами, наблюдениями, связанными с индивидуальными
   переживаниями человека. Во-вторых, стало ясно, что знание не
   является спасением от всех проблем -- мир по-прежнему не может
   справиться с насилием, войнами, коррупцией, другими социальными
   проблемами.

   Одними из первых, кто начал серьезно развивать иррационалистические
   идеи были Фридрих Шеллинг (развивал Фихте, от него отталкивался
   Гегель) и Сёрен Кьеркегóр (первым работал над понятием
   экзистенциализма, есть на фоточке статьи на википедии про
   экзистенциализм).

   Артур Шопенгауэр (1788 год) развивал философские рассуждения на
   основе иррационализма, то есть отрицания концепции преобладания
   разума, предлагая решать проблему отношения субъекта и объекта с
   точки зрения индивидуальной, то есть рассматривать его в первую
   очередь как нечто, порожденное представлением человека. Первичность
   индивидуального рассмотрения над рациональным знанием -- главная
   идея иррационализма.

   Шопенгауэр соглашается с тезисом Канта о "вещи в себе", утверждая,
   что это вообще есть "граница рационального познания", но приходит к
   выводу, из невозможности познания рационального, к возможности
   познания интуитивного. Под интуицией тут понимается не
   рационалистическая, а интуиция, истекающая из "бытия в себе
   познающего".

   В поисках фиксированной точки сознания и самосознания Шопенгауэр
   приходит к выбору, что основой для познания есть ни что иное, как
   воля. Не может быть познающего без познаваемого и наоборот,
   следовательно в основе всего лежит нерациональное нечто, что он и
   называет хотением или волей. Воля выступает у Шопенгауэра
   кантовской вещью в себе, которая лежит в основе всего. Причем
   сознание, конечно, не отвергается, но является вторичным, зависимым
   от внутренней воли. Причем важно понимать, что эта зависимость есть
   больше "средство", чем "данность" -- единственной целью сознания
   есть то, что диктует воля.

   Воля подразделяется на три ступени: механическая причина,
   раздражение и мотив. Природа раскрывает переход воли, обретение ей
   сознательности. Насчет позиций материализма, множество вещей в
   природе есть тоже проявление воли, причем пространство и время
   присущи только представлению, а не вещам в себе как таковым.

   Большую роль в учении Шопенгауэра играет этика, занимающая
   центральное место в его философии. Категорический императив Канта
   отвеграется, поскольку он выводится из первичности сознания. По
   Шопенгауэру поступки добродетельные и разумные -- категории
   различные. Логично.

   Свобода воли не существует, поскольку любая мотивация проистекает
   напрямую из воли, оттуда же, откуда проистекают все причины. В
   процессе выбора более сильный мотив с необходимостью овладевает
   волей. Воля имеет свою собственную необходимость, цель, ориентир,
   некоторую per-user настройку. Такой необходимостью является
   характер. Характер лежит в основе всех актов, вызываемых
   мотивацией, он индивидуален и неизменен. Разница в характерах по
   Шопенгауэру врождена и необходима. Именно характер придает
   необходимость воле, лишая ее свободы (свобода воли -- возможность
   воли действовать независимо). Но отрицание свободы воли значимо
   только в контексте ее объективизации через человека, воля-то сама
   по себе свободна.

   Основная и едининственная цель воли -- воля к жизни. Инстинкт
   самосохранения, стремление к счастью и благу есть выражение этой
   цели. Так рождается понимание эгоизма как основного проявления
   двигателя воли.

   Основой любых стремлений и желаний человека является
   неудовлетворенность, недовольство своим состоянием, страдание в
   буддистском смысле. Страдание -- термин достаточно перегруженый, но
   тут оно используется в контексте духовного, психологического
   неудовлетворения -- любой психологический дискомфорт есть всегда
   конфликт некоторых внутренних интересов, и вот совокупность таких
   явлений и есть страдание. Страдание есть первичным относительно к
   наслаждению. Оно усугубляется, если неудовлетворено, а если
   удовлетворено, то оно тоже усиливается, но в другом направлении,
   поскольку это следует напрямую из понимании цели воли. Усилие для
   достижения новых целей пораждает непрерывную неудовлетворенность,
   поэтому человек не может быть счастлив, совершая поступки согласно
   своим мотивам. Желания человека есть причина страданий.

   Итогом рассуждения о страдании является этика, основанная на
   резигнации, самоотрицании, отверждении воли к жизни, квиетизмом в
   смысле следования мотивации. Причем такое самоотрешение не может
   даваться легко по умолчанию, поэтому только усилием можно достичь
   добродетели. Этическому поведению добродетель
   сопутствует. Отрицание самолюбия, воли к жизни есть у Шопенгауэра
   возможным несмотря на встроенную причинность воли, причем наличие
   конфликта он не отрицает, но объяснение его рационально невозможно.

   Вторым важным выводом из понимания воли есть учение о сострадании,
   необходимость которого следует напрямую из эгоизма. Живое существо,
   руководствующееся эгоизмом, не может усмотреть в другом живом
   существе единую волю и причинность всех поступков. На деле же
   индивидуальность лежит не в сущности, а в проявлении, поэтому
   внутренне все источники воли равны. Понимая учение и природу воли,
   человек обладает уникальным шансом, в отличии от других источников
   воли, осознанно менять свое жизненное поведение. Кроме резигнации
   это поведение следует также выражать в сострадании, поскольку
   страдание есть основа всего мироздания и любого живого существа в
   частности, а сострадание -- понимание и принятие этой истины,
   единственно добродетельная реакция на него. Любая дружба или любовь
   не есть добродетельна, пока ей не сопутствует сострадание. Любовь
   -- одно из центральны проявлений хитрости воли, как тяги к
   продолжению рода, поскольку она полностью затмевает сознание и
   интуицию. Сострадание неразделимо и неизбежно, поэтому сострадание
   -- единственное, что можно предпринять в отношении других.

   В чем конечное решение проблемы воли? Им не может быть смерть, так
   как самоубийство в большинстве случаев есть выражение эгоизма и
   страдания, неудовлетворенности понимания чего-либо. Пределом
   добродетельных действий есть нирвана, учение о нирване -- небытие
   воли.

   Злоба, эгоизм и сострадания являются тремя главными двигателями
   человеческой деятельности. Счастье рассматривается только в
   понимании субъективности восприятия и воли.

   А еще он был сексистом и говорил, что ТНН. Не оправдывая это, стоит
   отметить, что, во-первых, шовинизм и сексизм были духом того
   времени (основная причина, на самом деле), а во-вторых, Шопенгауэр
   был очень закомплексованым одиноким параноиком и короче у него
   просто бахало. Еще нагуглил в каком-то ЖЖ утверждение на уровне
   "был в плохих отношениях с матерью и с соседкой, которой должен был
   платить по суду пособие" В любом случае, это понимание достаточно
   отчуждено от главных идей его философии.
** Ницше
   Ницше копирует Шопенгауэра, но определял жизнь как волю к
   власти. Воля к власти -- это господство, в первую очередь над
   собой. Жизнь -- это то, что определяется через господство.

   Нигилизм -- плохо, активный нигилизм -- хорошо. Сверхчеловек -- это
   такой нравственный идеал человека, который находится в полной
   власти самого себя.

   Ницше критикует христианство с точки зрении того, что христианство
   -- религия сострадания. И еще обсуждения ИРЛ.
