#+TITLE: Lectures on philosophy IFMO 6th term

* Курс лекций от Ломовой
** Декарт/Бэкон -- материализм
   Почему декарт различает познание на чувственное и рациональное?

   Декарт -- скептик. Скептицизм -- отрицание того, что кажется
   непонятным и недоказуемым. В средневековии характерен авторитаризм,
   но Декарт его отрицает (учителя -- не авторитет, потому что все
   говорят разное, ..). Декарт ищет основание, не ища авторитетов --
   наука должна быть автономна от церкви.

   Чувственное познание обманывает Декарта, потому что он не может
   отличить сон от яви -- предполагает, что все может быть
   вымышленным. Реальность материи и вещей в науке аксиоматизирована,
   то есть идея "все -- воображение" не рассматривается. Чувственное
   познание Декарта принимается на веру, а крайняя степень эмпиризма
   -- это собственно и понимание чувственности как таковой. Декарт в
   предположении, что чувственное познание обманывает, оставляеет к
   нему доверие.

   Дуализм декарта -- это разделение человека на две составляющие --
   телесная (протяженная) и духовная (мыслящая). Таким образом,
   телесную часть он откитывает. Почему "я мыслю, значит я существую"
   применимо к Богу, но не применимо к чему-либо еще? Декарт был
   верующим, хотя не пытался связать свои логические/философские
   рассуждения с верой. Декарт не отрицает религию, как и
   Бэкон. Нельзя было просто не вписать Бога в идеологию, поэтому это
   было сделано.

   Как Декарт из предположения, что все ему кажется, приходит к
   выводу, что существуют физические тела и другие люди? Очевидно,
   рациональное познание чисто изначально, поэтому заблуждения
   приходят из телесной субстанции. Бог -- это исключительно духовная
   составляющая, без физической.

   Бог -- это вообще только мысль, а не то, что в привычном понимании.

   Доказательство существования бога:
   1. Исходя из того, что бог -- это только мысль и из того, что тело
      не может существовать и все мыслящее существует ⇒ бог тоже существует
   2. Если есть представление о себе как о несовершенном человеке, то
      существует нечто более совершенное и этим есть Бог -- гарантия
      совершенности.

   В общем случае существование бога необходимо для Декарта, чтобы
   доказать существование других людей, тел.

   Метод дедукции состоит из: отвержения авторитетов, разделение
   сложных вещей на более простые и переход к более общим вещам, как
   только более частные решены.

   Происхождение заблуждений по Декарту -- это телесное познание, а
   конкретно человеческая воля -- она же и движет его к познанию, она
   же и производит ошибки.


   Бэкон -- родоначальник индукции. Что такое индукция -- очевидно.

   У бэкона есть учение об идолах. Идол -- это причина
   несовершенства. Идолы бывают рода (заложенные в человеке), пещеры
   (личные заблуждения, мнения, необъективность), рынка (заблуждения
   связанные с речью), театра (неправильное толкование теорий или
   вообще восприятие идеологически неверных теорий).

   Бэкон критиковал Аристотеля за то, что его теория пронизана
   проблемой идола пещеры -- опыты Аристотеля подбивались под
   теорию. По поводу идола театра -- критиковалась схоластика,
   теология.

   Идолы необходимы, потому что с их помощью (устраняя их), можно идти
   к истине.

   Пути: муравей/паук/пчела. TODO
** Материя
   В основе предыдущих идеологий лежит понимание идей и материального
   мира, но материя зачастую не описывается.

   Происхождение и развитие категории материя:

   Материя -- это совокупность вещей и физических полей, а также
   других образований, имеющих субстрат -- материал, из которого они
   состоят. Некоторый вещественный или энергетический
   субстрат. Материя может быть объективной или субъективной.

   Любое определение дается через род и родовое отличие. У материи
   нету рода, потому определение такое, какое есть -- через некоторые
   свойства.

   Материалистический подход утверждает, что материя -- это основа
   бытия, а все иные бытийные формы (дух, человек, общество) --
   порождение материи. Материя первична. Материализм отвергает
   теологию, так как согласно материализму ни духовного Бога, ни
   рождения ниоткуда.

   Объективно-идеалистический подход -- материя объективно существует
   как порождение (объективизация) независимо от всего сущего
   первичного идеального духа. Это онтологии Платона, Гегеля,
   средневековья.

   Субъективно-идеалистический подход -- материи как самостоятельной
   реальности не существует вовсе, она лишь продукт (феномен)
   субъективного (существующего в виде сознания) духа. Это Кант.

   Позитивистский -- понятие "материя" ложно, так как его нельзя
   доказать и изучать эмпирически/опытно/научно.

   Категория материя развивалась следующий образом:
   1. Материя как вещь -- поиск первоосновы в античности. Это
      субстрат, субстанция. Демокритовский атом, Фалесовская вода,
      Анаксимандр и "апейрон".
   2. Материя как свойство -- целью есть дать картину природы как
      таковой (новое время). Механический подход рассматривал материю
      как относительно устойчивое тело, перемещающееся в пространстве
      с течением времени. Всеобщая суность состоит из атрибутов вроде
      массы, протяженности, непроницаемость. Качественно материя
      определяется массой.

      Из статических законов механики Ньютона и электродинамики
      Максвелла рождается детерминизм -- учение о причинной
      материальной обусловленности явлений (природных, социальных).
   3. У Маркса материя -- это естественно-научное понимание,
      единственно существующая реальность и помимо и вне ее ничего не
      существует. Материя постоянно движется (во времени
      пространстве), причем движение -- это способ ее
      существования. Формы движения: механическая, физическая,
      химическая, биологическая и социальная. Между тими формами
      существует диалектическая связь (диалектика как наука о познании
      движущихся объектов).

      Рациональность по Декарту -- это разум, отношение человека к
      собственному разуму. Текущее значение этого слова -- это
      практичность, то есть современность ставит разум после материи,
      материя порождает сознательность.

      В материализме движение (диалектика) порождает материю.

      Помимо движения, есть понятия пространства и времени: время --
      форма бытия материи, которая выражает длительность существования
      материальных объектов и последовательность смены их состояний.c

      Пространство -- форма существования материи.
   4. Материя как отношение.

      Отношение пространства и времени к материи.
      * Субстанциональная концепция (Демокрит, Эпикур, Ньютон)
        трактовали пространство и время как самостоятельные сущности,
        существующие наряду с материей и независимо от нее. Причем у
        Ньютона время делится на относительное (субъективное) --
        время, к которому мы привыкли (промежутки, интервалы) и
        абсолютное (время как таковое, его сущность).
      * Реляионная концепция (Аристотель, Лейбниц, Гегель) понимали
        пространство и время не как самостоятельные сущности, а как
        отношения, образуемые взаимодействием материальных
        объектов. Вне взаимодействия пространство и время не
        существуют.

      СТО Эйнштейна и геометрия Лобачевского изменяют понимание
      геометрии и материи, времени и пространства. Время становится
      зависимым от размеров, от пространства. Любой материальный объкт
      рассматривается как двиижение.
** Сознание
   Сознание как философское понятие определяет анализ всех форм
   проявления духовной и душевной жизни человека в их единстве и
   целостности, а также способов контроля и регуляции его
   взаимоотношений с действительносью, управления этими
   взаимоотношениями.

   Сознание делится (кем?) на:
   1. Душа (трансцендентное).
   2. Психика (иманентное).
   3. Мышление и разум (мир).

   Исторически:
   * В античной философии сознание направлено на объект.
   * Платон выделяет понятие идеального как противоположность
     материальному.
   * Средние века -- сознание как надмировое начало (Бог), разум --
     атрибут Бога.
   * Новое время -- осознание ценности человеческой личности, переход
     от "души" к "сознанию". Нет сознания без самосознания. Декарт --
     сознание как субстанция открытое для субъекта. Кант --
     трансцендентальное единство апперцепции.
   * Абсолютный идеализм Гегеля обосновывает социально-историческую
     природу сознания. Есть абсолютный дух, который создает сознание
     впоследствии, причем сознание не зависит от материи, не
     порождается даже. Идеальность -- основной атрибут сознания.
   * Абсолюное самосознание -- надличностное, всеобщее начало,
     движущееся по внутренним законам.
   * Материалистическая философия исходила из принципов признания
     сознания функцией мозга и отражения внешних воздействий. (с 18
     века материализм).

   История развития взглядов на природу сознания (Маркс):
   1. Диалектико-материалистическая концепция сознания
   2. Сознание вторично, детерминировано экономическими факторами.
   3. Сознание есть осознанное бытие.

   Маркс отрицает сознание у не-людей, у детей до 3х лет (примерно), у
   людей, которые не могут говорить.

   По Марксу сознание есть высшая форма психического отражения и
   саморегуляции, присущая человеку, то, что отличает его от
   животных. Этими особенностями являются:
   * Наличие речи
   * Умение логически мыслить
   * Умение планировать свою деятельность
   * Наличие мира внутренних переживаний
   * Наличие отношения к миру
   * Умение моделировать в сознании по своему усмотрению
   * Появление мышления как самостоятельной внутренней деятельности.

   Сознание как отражение -- всеобщее свойство материи, связанное с
   потенциальной информацией, заключенной в эффектах материального
   взаимодействия и информационное взаимодействие, появляющееся на
   стадии живой природы.

   Генезис сознания как информационного взаимодействия:
   1. Отражение -- свойство взаимодействующих тел воспросизводить в
      своей внутренней структуре особенности друг друга.
   2. Раздражимость -- реакция на раздражители.
   3. Возбудимость
   4. Психика

   Разговор зашел о идеомоторике, о контроле над человеческим телом
   (собственным).

   По Марксу сознание связано с формированием культуры на основе
   общественной деятельности людей. Сознание -- общественная
   надстройка.

   # было сказано, что в мире все названо, а я пытался сказать, что
   # это херь

   Язык -- система знаков, служащая для объективации человеческого
   общения. Существование знаковых систем является одним из признаком
   сознания.

   Этапы самосознания:
   1. Самочувствие, выделение себя из предметного мира.
   2. Осознание принадлежности к обществу.
   3. Возникновение сознания "Я" -- понимание "знание о наличии
      собственного знания". Самокритика.

   # Это "самосознательность" подгоняется к любой горилле (к какой-то
   # частной, вернее).
   # https://en.wikipedia.org/wiki/Washoe_(chimpanzee)
   # https://en.wikipedia.org/wiki/Koko_(gorilla)

   Бессознательное:
   1. Шеллинг, Шопенгауэр -- бессознательное как первоисточник всего
      сущего.
   2. Эдуард фон Гартман -- отрицание главенствующей роли разума и
      утверждение примата воли.
   3. Ницше -- бессознательное как условие всякого совершенства.

   У Ницше сознательное -- ненужная некоторая вещь, параллельная с
   бессознательным.

   У Маркса бессознательное -- это проблема наличия скрытых
   детерминант в сознании. Процесс детерминации скрыт от сознания, не
   представлен в опыте. Бессознательное Маркса коллективно -- это не
   осознавание обществом своего положения в нем же.

   Маркс считает, что сущность человека в труде, поэтому, скажем,
   крестьянин, продающий хлеб, не осознавая экономической структуры
   рынка, несчастен, так как счастье есть коллективный труд.

   По Фрейду бессознательное не доступно свободному осознанию, причем
   оно первично. Психика по Фрейду делится на 3 компоненты:
   1. Оно (id) -- глубинный слой инстинктов, руководствуется
      "принципом удовольствия".
   2. Я (ego) -- сфера сознательного. Проводник между "оно" и внешним
      миром.
   3. Сферх-Я (super ego) -- внутренний цензор, содержит
      фундаментальные для общества и культуры запреты.

   Личность по Фрейду разорвана изначально. Культура, ограничивающее
   "id", и порождает человека. Без культуры не может существовать
   ограничивающего сверх-я.

   Критика Фрейда:
   1. Человек по своей природе враг своей культуры.
   2. Противопоставляется человеческая природа и культура.

   Карл Густав Юнг:
   * Структура бессознательного.
   * Сознание включает "персону" и "эго".
   * Личное бессознательное включает "тень", "аниму", "самость".
   * Коллективное бессознательное -- архетипы (некоторые родовые
     паттерны).

   Подробнее:
   * Персона -- особенности личности и формы поведения в социальных
     ситуациях, маска для социума.
   * Эго -- центр, управляемый персоной.
   * Тень -- обратная сторона "Персоны", то, что человек знать о себе
     не хочет.
   * Анима или анимус -- образ женщины в психике мужчины или наоборот.
   * Самость -- глубинный центр психики, связанный с го, не
     проявляемый на сознательном уровне. Интуиция.
** Человек как проблема философии, сущность человека
   1. Три подхода к анализу сущности человека.
   2. Историко-философское: восточная философия, антропологический
      поворот в греческой философии, эллинистическая философия --
      стоицизм, скептицизм, эпикуреизм.

   Сущность человека. Сущность называется то, благодаря чему нечто
   есть то, что оно есть. Сущность человека -- это те из его свойств,
   которые нельзя изменить, чтобы он не перестал быть собой.

   Сущность:
   1. Родовая -- качества, присущие человеку, как роду (биологические
      и социальные).
   2. Социально-историческая сущность -- self-documented.
   3. Индивидуальная сущность -- память, психика.

   Три подхода к пониманию сущности:
   1. Субстратный -- вещь есть то, из чего она состоит. Все ее
      качества определяются этим субстратом. Если это камень, то
      материал -- его сущность.
   2. Функциональный -- существование связано с целевой причиной, с
      внешней целью. Функция -- соответствие между назначением объекта
      и его бытием.
   3. Субстанциональный -- вещи определяются способом самоцельного
      существования в среде. Отвечает на вопрос "почему?".

   Древняя Индия:
   1. Ведические тексты, источник жизни -- пуруша (космический
      великан, распадаясь, дарующий жизнь).
   2. Сословия (варны): брахманы (проповедователи), кшатрии (воины),
      вайшьи (ремесленники), шудры (слуги).
   3. Безлично сущее (брахма), духовно сущее (атман).
   4. Сансара и карма.

   В древней Индии проповедуется аскетизм.

   # было сказано что-то про буддизм, что не сильно коррелирует с
   # реальностью

   Даосизм -- учение о пути. "Дао" -- путь. Есть мировой порядок, ему
   нуно соответствовать. В китае очень много разных школ.

   Согласно Конфуцию, лучший человек -- гуманный и
   милосердный. Представления о личности в китайской философии нету,
   зато есть дух, мировой баланс.

   Самые известные софисты: Протагор и Горгий. Как и все софисты,
   Протагор проповедует дуализм мнений, объективность мнения. Сказ о
   Протагоре и Эватле. Горгий истинность вообще отрицал.

   Сократ рассматривает добро, зло, благо как сущность человека, а не
   какие-то внешние вещи. Поэтому добродетель существует у него сама
   по себе.

   Эпикуры, скептики, стоики.

   Пирон (скептик) -- чтобы достичь счастья, следует отказаться от
   суждений. Гераклит тоже про это говорил, в контексте "все течет,
   все непостоянно".

   Демокрит -- предопределенность, все движется по строго определенным
   траекториям. Фатализм. Эпикур говорит, что это неверно. Эпикур
   понимает идеального философа как человека, ведущего свободную от
   страданию жизнь. Атараксия -- цель жизни с точки зрения
   эпикурийцев.

   Стоики -- опираются на материалистическое учение Демокрита,
   Героклита. Связывают свободу с необходимостью.

   Платон и его представление о человеке -- в объективном идеализме
   человек дуален. Делится на материальное и идеальное (душа). Душа и
   тело помогают человеку обретать знания как припоминания, познавать
   эти идеи.

   Душа у Платона:
   1. Аффективная -- воины
   2. Разумная -- правители и философы
   3. Вожделеющая -- крестьяне
** Антропология древней греции
   У Платона человек -- душа вечная и тело смертное. Души не творятся
   постоянно, они пребывают на звездах. Души -- это идеи жизни. Душа
   различается на разумную, неразумную, в неразумной на аффективную и
   яростную. Благо -- высшая идея. Зло -- отсутствие
   блага. Метемпсихоз -- переселение душ.

   Аристотель -- душа есть причина и начало живого тела. Соотносится с
   телом как материя и форма. Имеет три уровня: вегетативный,
   чувственный, разуменый. Душа есть причина как то, откуда движение,
   как цель и как сущность. Разумная душа та, которая мыслит и
   познает.
** Антропология средневековья
   Человек и бог в христианской философии. Творение человека,
   грехопадение. Боговоплощение. Проповеди Иисуса Христа. Распятие и
   воскресение. Человек -- богоподобное существо с чистой душой.

   Человек свободен был только до того, как бы изгнан из рая. Без
   этого все определено. Августин определяет линейное время (прошлое,
   настоящее, будущее). Августин фаталист.

   Фома Аквинский критикует идею доказательства бога Августина,
   утверждая что доказательство бога истекает из его (бога)
   творений. Фома -- умеренный реализм (христос -- не бог, потому что
   бог не может быть человеком). Вера и знание -- объединение
   интеллекта и чувственности, в то время как бог -- только
   интеллект. Однако не настаивает на главенстве разума (любовь к Богу
   важнее). Фатализма нету -- если человек делает зло, то это не воля
   Бога, а человеческая деятельность. Молитва, исповедь и покаяние --
   техники гуманизации, потому что только в этих актах человек
   постигает глубину своей души.
** Антропология разума
   Кант. Человек -- это цель в себе. Одновременно номен и
   феномен. Разум нужен человеку для того, чтобы выходить за границы
   познания. Там он впадает в антиномии. Человеческая воля автономна,
   фатализма нету. Определяется воля через категорический императив.
   Категорический императив -- "поступай так, чтобы максима твоего
   поведения на основе твоей воли могла бы стать общим естественным
   законом". Это потом повторяется Сартром.

   Эстетика Канта -- эстетика бесполезности. Мы никогда не
   рассматриваем полезные вещи эстетическими. Все эстетические вещи
   бесполезны.

   Гегель. Сущность человека -- дух, не индивидуальность. Человек,
   прежде всего, это человеческий род, разделение на расы.
   Индивидуальные качества происходят из родовых сущностей -- труда и
   общества. Абсолютный дух движется к своему самопознанию.
** Сущность человека в марксистской философии
   У Маркса человек -- часть природы. Благодаря труду человек
   выделился из животных в мир природы. Изменение материальному
   производству человек начинает обретать некоторые социальные
   общности. Потребности человека -- реализация и осуществление
   социальных отношений. Индивидуальное сознание -- продукт
   общественных отношений. Только социум и общ. сознание говорит о
   наличие в человеке сознания.
** Экзистенциализм
   Сущность человека в экзистенциализме не существует. У Хайдегера
   человек -- преступление (переступление через себя). Суть --
   движение к смерти (нельзя это преодолеть). Попытки себя превзойти
   исходят из понимания смертности. В движении к смерти Хайдегер видит
   смысл. Человек пытается избежать идеи смерти. Страх как постоянная
   боязнь смерти, Ужас как понимание смерти на ее рубеже.

   Камю. Миф о сизифе отражает сущность современного общества и
   человека в частности -- существование абсурдно. Потом еще
   поговорим.

   Сартр -- тоже потом обсудим.
** Философская аксиология
   Аксиология -- теория ценности.

   Ценности. Концепции ценностей:
   1. Объективно-идеалистический подход. Ценность -- идея.
   2. Теологические. Ценности имеют божественное происхождение. Бог --
      справедливость, добро, разум, красота.
   3. Феноменологичечкие. Сознание порождает ценности.
   4. Экзистенциальный. Ценность субъективна -- акт индивидуального
      выбора.
   5. Биолого-натуралистический. Ценность -- полезное. То, что
      приносит удовольствие.
   6. Социологический. Ценности порождаются социальной средой.

   Высшая и абсолютная ценность -- это сам человек, его жизнь.

   Нельзя путать цель и смысл жизни -- цели можно ставить и без
   осмысления своего предназначения.

   Проблема смысла жизни:
   1. Теоцентрический -- рассматривает человека как сотворенного для
      реализации божьего замысла.
   2. Космоцентристский. Человек -- сущность, воплощающая в себе, как
      в микрокосме, законы космоса.
   3. Социоцентристский подход. Смысл жизни -- деятельность.
   4. Антропоцентристский -- смысл жизни есть ??

   Наука -- это не добро или зло, наука -- это истина.
** Сартр "Экзистенциализм -- это гуманизм". Тезисы
   * Критика со стороны христиан, коммунистов
   * Люди, которые критикуют, сами часто считают правильными
     пессимистические мудрости, оправдывают человеческие пороки
   * Экзистенциалисты -- христиане (ясперс, марсель) и атеисты.
   * Сравнение с ножом -- изготовление предшествует
     существованию. Аналогично Декарт, Лейбниц и их Бог. Аналогичног
     атеисты 17-18-19 веков (Кант)
   * Экзистенциализм -- обратное.
   * Первый принцип -- человек сначала существует, а потом уже создает
     сам себя. Экзистенциализм возлагает на человека полную
     ответственность за свое существование.
   * Субъективизм -- индивидуальный субъект сам себя выбирает. Или что
     он не может выйти за рамки человеческой субъективности. Второе --
     глубокий смысл экзистенциализма.
   * Создавая себя субъективно, мы создаем себя в сознании других,
     поэтому создаем других. Совершая поступки, мы выбираем благо,
     благо для всех (потому что добро должно быть всеобщим). Пример с
     христианским союзом и женитьбой как пропагандой моногамии.
   * *Тревога* -- чувство отвестственности за свои поступки (они
     задевают все человечество). Многие скрывают тревогу и лгут "все
     так делают". Кьеркегоровская тревога Авраама -- "действительно ли
     это Ангел а я Авраам?". Действительно ли человек имеет право
     действовать так, чтобы человечество брало пример с его поступков?
     Не думать об этом -- скрывать тревогу.
   * *Заброшенность* -- бога нет, беспокойство по поводу того, как
     вывести ценности без него. "Если бога нет, то все дозволено". Нет
     детерменизма, человек -- свобода. С другой стороны, нету и
     ценностей, нет оправданий и извинений.
   * Пример с младшим братом, который не хотел бросать мать, но имел
     целью отомстить за старшего брата. Выбор между пользой для
     конкретного человека и для нации. Мораль симпатии и личной
     преданности, мораль широкая но менее действенная (месть,
     война). Какой выбор сделать? Парадокс с целью и средством (любой
     выбор делает кого-то средством, а кого-то целью). Доверие
     инстинктам и порочный круг "нужно сделать поступок, чтобы его
     оценить". С другой стороны, можно разыграть поступок, что будет
     тем же, или обратиться за советом, но выбор советчика и
     интерпретация знамения -- выбор. Заброшенность -- мы сами
     выбираем наше бытие.
   * *Отчаяние* -- принятие во внимание того, что зависит от нашей воли,
     или сумму вероятностей, которое делает возможным действие. Можно
     более-менее рассчитывать на партию, действия которой ты можешь
     более-менее контролировать. Нельзя рассчитывать на людей, которых
     не знаешь, на их качества, ведь человек свободен. "Нет нужды
     надеяться, чтобы что-то предпринимать" -- нужно решить, а затем
     действовать.
   * Человек -- проект себя, экзистенциализм отрицает утверждения вида
     "я не сделал чего-то, потому что не получилось". Вне облика
     ничего нет. Человек есть только ряд его поступков -- совокупность
     отношений, из которых составляются эти поступки.
   * Трус определяется по поступку, а не по темпераменту. Не бывает
     "трусливых" людей априори.
   * Экзистенциализм -- не квиетизм.
   * Экзистенциализм -- единственная теория, не делающая человека
     объектом. Познать себя можно только через другого. Мир, созданный
     этим пониманием -- интерсубъективность.
   * Моральный выбор -- это произведение искусства. Упрекать человека
     за выбор то же, что упрекать художника за то, что он не следует
     художетсвенным стандартам.
   * ? Бессмысленно упрекать кого-то в произвольности выбора -- но
     выбор действительно можно делать произвольно (это уже мое
     наблюдение и вопрос). Ответ -- произвольность выбора физического
     не соответствует свободе выбора морального.
   * Судить человека за выбор нельзя, потому что обычно каким бы не
     был проект, ему невозможно предпочесть другой. Но можно судить,
     какой выбор основан на заблуждении (логическое, а не оценочное
     суждение). Можно судить о нечестности человека. Нечестность --
     это тоже выбор, но нечестность противоречит последовательности и
     логике.
   * Сартр называет тех, кто стремится скрыть от себя полную свободу:
     1. С помощью детерминизма -- трусами.
     2. С помощью априрорной необходимост существования -- сволочами.
     Судить эти две категории можно только с точки зрения полной
     аутентичности.
   * Пример с "мельницей на флоссе" и "Пармской обителью" --
     отказаться от любви или объявить ее максимальной ценностью значит
     ставить целью свободу. Таким образом, выбирать можно все, что
     угодно, если речь идет о свободе решать.
   * Выбирать ценности самостоятельно приходится, потому что нету
     априорной морали.
   * Гуманизм имеет два определения.
     1. Плохое -- человек есть высшая ценность и цель.
     2. Человек находится в сердцевине проектирования себя во
        вне. Гуманизм -- это связь констатирующей трансцендентности
        (в смысле выхода за свои пределы) и субъективности (человек не
        замкнут, а присутствует в человеческом мире).
   * Экзистенциализм -- попытка сделать выводы из последовательного
     атеизма. Не попытка, доказывающая отсутствие бога, а доказывающая
     индифферентность божественного влияния.
** Ясперс "Духовная ситуация времени.2"
   * Технократия
     * Человек поднялся над миром животных (особенно западный) за счет:
       1. Рациональность (от греков, от римлян)
       2. Субъективность самобытия (еврейские пророки, греки и римляне)
       3. Восприятие мира как фактической действительности.
     * Большая роль рационализации и механизации
     * Вещи становятся данностью, теряют личность. Продукты изнашиваются и
       выбрасываются. Вместе с этим увеличивается ощущение недостатка
       (полезность вещей игнорируется и заметна только в отсутствии
       вещей)
   * Аппарат
     * Деловитость как позиция человека в техническом мире. Индивид
       распадается на функции, живет как сознание социального бытия.
     * Бытие сводится к всеобщему. Разделение труда и развлечений лишает
       существование возможного веса.
     * Существование теряет свою историческую особенность.
     * Общество жаждет молодости как эталона энергии. Молодость видит
       старость с точки зрения масштаба.
     * Цель человека -- место в аппарате.
     * Бюрократия главенствует аппаратом
   * Масса
     * Масса -- толпа не связаных людей. Как публика, как совокупность
       людей в аппарате.
     * Общественное мнение не совпадает с мнением ни одного человека --
       фикция.
     * Фикция равенства -- каждый сравнивает себя с другим, заведомо
       бессмысленно.
     * Каждый должен удовлетворять массу, чтобы находится в
       аппарате. Для воздействия на массу необходима реклама.
   * Кризис
     * Всему грозит опасность, потому что одно осознается всеми и есть
       неблагополучно. Сущность кризиса в недостатке доверия. Кризис
       государственный.
     * Исчезновение авторитета -- появление цинизма.
     * Нивелирование -- обобщение, мнимое единение людей.
     * Осталось только сознание опасности и утраты.
     * Новый мир может возникнуть только в условии осознания человеком
       своего бытия, возвращения к бытию.
   * Упадок духа и его возможность
** Абсурдизм Камю
   Абсурдизм -- продолжение экзистенциализма. Основателем можно
   считать камю. Познание происходит не логикой, а
   интуицией. Конкретно у Камю это абсурд.

   Главный вопрос на который отвечает Камю -- "правда ли, что жизнь
   стоит того, чтобы ее прожить?". Выходы из абсурда -- самоубийство
   (тоже абсурдно, отвергается Камю), прыжок веры (уход в религию,
   тоже отвергается), принятие абсурда.

   Пример с мифом о Сизифе -- самая главная цель есть быть счастливым,
   пока идешь вниз за камнем. Миф о сизифе очень схож с жизнью
** Хайдегер
   Было два периода -- систематизация и другое видение, отличное от
   первого. Пытался высказывать свои мысли точностью слов. Нужно было
   хорошо понимать понятия, чтобы разбираться в мыслях.

   Человек -- высшая цель экзистенции, в отличии от лошади или горы,
   потому что он может осмыслить свое существование. Изучал
   европейское общество с точки зрения "ради чего мы идем, куда, как
   так вышло?". Считал, что европейское общество движется в
   неправильную сторону, принимая "сущее" и "бытие" за
   единое. Человека окружает масса вопросов, но он их
   игнорирует. Сущее -- человеческое, физическое существование, когда
   бытие -- это экзист.

   Экзистенциализм недопонимают. Еще раз выделяется разница между
   бытием (мета-...) и сущим. Бытие -- существование во времени. Бытие
   и время -- одно и то же.

   *Забота* -- бытие в мире, забегание вперед и бытия во внутримировом
   сущем.

   Прошлое -- *заброшенность*, настоящее -- *обреченность*, будущее --
   *проект*. В зависимости от расстановки приоритетов человек может
   понимать или не понимать существование.

   Подлинное существование -- концентрация на будущем, а не на
   настоящем. Истина и ее понимание возможно только в осознавании
   собственной свободы.

   Свобода у Хайдегера -- абстрактное понятие, без примеров, оч
   сложно.

   *Дазайн* -- человек, являющийся бытием (человек-личность). *Дазман*
   -- общий, безликий.
** Философия государства
   Утопия -- понятие, использующееся для обозначения идеалистического
   политического строя или трудов, которые его могут строить.
*** Платон
    Платон -- пионер этого направления. Написал трактат
    "Государство", диалоги "Законы", "Политик". Трактат пишет, что
    главная причина порчи обществ и государств заключена в госуодстве
    корыстных интересов.

    Его классификация (возрастание корыстных интересов):
    * Аристократия -- справедливая власть.
    * Тимократия -- то же, но переплывает в олигархию.
    * Олигархия -- разделение на бедных и богатых.
    * Демократия -- возникают бунты, захваты, хаос.
    * Тирания -- несправедливая власть одного человека.

    Полис -- необходимое условие для государства в целом. Идеальное
    государство должно:
    * Обладать силой собственной организации и средствами ее защиты.
    * Осуществление систематическое и достаточное снабжение всех
      членов общества благами (необходимыми).
    * Руководить духовной деятельностью и творчеством.

    Совершенное благо обладает четырьмя главными добродетелями:
    1. Мудрость -- то, что доступно философам.
    2. Мужество.
    3. Благоразумие -- сдерживающая мера.
    4. Справедливость -- главная добродетель.

    Чтобы государство стало идеальным, необходимо свергнуть всех
    корыстных владителей, заменив их философами.

    Сословия в государствах:
    * Высшее (правители, философы).
    * Стражи (силовая структура).
    * Прочие граждане (ремесленники, дельцы, крестьяне).

    Все три класса необходимы. Способ отбора -- экзамен. Главный
    социальный лифт -- школа. Частная собственность не нужна. Жены
    стражей общие, дети тоже. Неупорядочные половые связи
    запрещены. Особые лица воспитывают детей.

    В идеальном государстве все строят государство, ничего сугубо
    личного нету.

    Аристотель рассматривает государство не идеальное, а
    реальное. Рассматривает хорошие (монархия, аристократия) и плохие
    (демократия, тирания). Основная ячейка социума = госурарства есть
    семья.
*** Томас Мор
    Кризис идей гуманизма, прозаичность складывающегося буржуазного
    общества. Томас Мор (1478-1535, англия) пишет на латинском
    "Утопию". Переход от феодализма к капитализму.

    Первая часть описыват Англию 16 века как бедную, нищую
    страну. Вторая более идеалистична, показывает идею. Ссылается на
    Платона.

    Общие положения:
    * Демократия с королем, но есть приоритет интеллегенции.
    * Отменена частная собственность.
    * Распределение продуктов по потребностям.
    * Господствует ручной труд (6 часов в день).
    * Запрещен атеизм, ко всем остальным религиям отношение терпимое.
*** Томмазо Кампанелла
    Утопия "Город Солнца". Стремился к революционной перестройке
    общественных отношений.

    Город Солнца -- теократическая республика, организованная по
    образцу монашеского Ордена.

    Во главе стоит мудрейший и всезнающий первосвященник Солнце.

    Устройство:
    * Эмпирическое, рационалистическое и мистическое.
    * Полное уничтожение частной собственности
    * Роль государства очень велика
    * Отрицает семью
    * Источник человеческих зол -- эгоизм
    * Рабочий день сокращен до четырех часов
*** Индустриализм Сен-Симона
    Анри Сен-Симон родился в Париже в знатной, но обедневшей семье
    (1848), нажил богатство на спекуляциях.

    По мнению Сен-Симона строй связан с эпохой и связан с прогрессом,
    моралью и религией. На рубеже 19 века происходит развитие идей
    социализма.

    Стадии:
    * Теологическая -- управление священниками и феодалами.
    * Метафизическая -- управление юристами-метаизиками.
    * Позитивная -- ученые.

    Новая социальная система -- индустриализм.

    Выделял два класса:
    * Промышленники -- рабочие, индустриалы.
    * Паразиты -- военные, управляющие.

    Реформа будет производится сверху вниз. Останется монарх,
    сохранятся правительство и двухпалатный парламент. Их функция --
    поддержание порядка.
*** Герберт Уэллс
    Утопия приобретает технический уклон в конце 19 века. Автор
    трактата "Современная утопия". Состоит из 11 частей. Фантастика.

    Характеристики:
    1. Утопия должна быть многообразным человечеством, земные людьми.
    2. Денежное обращение на основе золотого стандарта.
    3. Всемирное государство является верховным собственником, а
       каждому жителю Утопии принадлежат лишь вещи личного пользования.

    Еще какой-то треш про Сергея Снегова рассказал.
* Классификация per-philosopher
** Гераклит
   * Различие чувственного и рационального
   * Текучесть, изменяемость всего
   * Был прототипом для логики Гегеля
   * Бытие как процесс борьбы противоположностей
** Демокрит
   * Атомистическая концепция восприятия мира (вместе с Левкиппом)
   * Мир состоит из бесконечного числа неизменных, вечных
     атомов. Атомы различаются формой, поворотом и положением
   * Отождествление причины и необходимости, единственная беспричинная
     ситуация -- возникновение атомов.
   * Правильный путь -- поиск причины, знание причин, что ведет к
     избавлению от страхов и иллюзий.
   * Счастье -- безмятежное состояние души, не волнуемое страхами и
     суевериями.
   * Отрицал случайность, фаталист.
** Протагор
   * Софист (есть две точки зрения, истина относительна, все истинно).
   * Становление антропоцентризма как переход от натурфилософии с
     помощью перенесения акцента на человека в выборе ситуации (потому
     что во всем есть противоположность, значит человек сам творит
     все).
   * Как результат, отсутствует различие между злом и добром. Отсюда
     кому что выгодно, то и благо.
** Горгий
   * Софист, отрицает Протагора с его чувственным познанием.
   * Все является ложным.
   * Сочинение "о не-сущем", которое доказывает:
     1. Ничего не существует. Доказывался из атомизма (существование
        есть единое и множественное, а это противоречие).
     2. Если что-то существует, то оно непостижимо.
     3. Если постижимо, то невыразимо и необъяснимо для других.
   * Софизм имел дурную славу, но положительной его стороной было
     разрушение догматизма (антидогматизм) среди философов того
     времени, поскольку софисты могли опровергать многие тезисы, тем
     самым запутывая оппонентов, подталкивая их к размышлениям о
     поиске истины.
** Сократ
   * Отрицал софизм, утверждая первичность общего блага перед
     правильностью субъективного решения, но был антидогматичен как
     софист.
   * Ничего не записывал, вел диалоги. Отрицал собственный гений
     крылатой фразой "знаю, что ничего не знаю".
   * Очень важно не путаться в понятиях. Знание без понятий невозможно.
   * Требования отсутствие противоречия в рассуждении.
   * Ставил главной целью определение блага, нравственного, этики.
   * Майевтика -- диалогический метод рассуждений Сократа.
** Киники
   * Основана Антисфеном, продолжена Диогеном.
   * Отрицание ценностей полноправного гражданина, аскетизм
   * Основные идеи -- равенство всех людей, индивидуализм,
     космополитизм, опрощение, бедность.
   * Добродетель выражается через поступки, они первичны.
   * Этика основывается на самоограничении, минимальном уровне
     потребностей.
   * Ориетир человека -- счастье, которое может быть достигнуто только
     в бедности и умеренности, не в погоне за богатством и роскошью.
   * Природа -- единственный учитель и критерий жизни.
   * Добродетельная и счастливая жизнь -- свободная. Но свобода -- не
     свобода в смысле "не быть рабом", а быть свободным и от лишних
     потребностей, излишних желаний, вожделений, страстей.
   * Диоген был знатным толстым троллем, делал перформансы.
   * Три основных принципа философии:
     1. Аскезис -- образ жизни, мысли. Опрощение, ограничение, отказ
        от надуманных потребностей.
     2. Айпайдеусея -- необразованность, невоспитанность. Не то, чего
        стоит стыдиться, потому что разум без знаний чист.
     3. Автаркия -- независимость, самодостаточность,
        свобода. Космополитизм. Как следствие, отречение от поклонения
        богам (богов все же признавали).
** Платон
   * Ученик Сократа, записывал диалоги.
   * Мир идей как выход из субъективности наблюдающего -- любое
     определение субъективно, потому что формулизовано изменяющимся
     человеком.
   * Понятия не возникают из процесса объективизации, сравнения, а
     существуют сами по себе -- объективный идеализм.
   * Идея (эйдос) -- это идеальный образец, к которой стремится
     объект. Но сами по себе материальые объекты рассматриваются как
     проекции идей, как их абстракции.
   * Миф о пещере из диалога "государство" приводит в пример тени на
     стенах от солнца в пещере как вещи, в то время как солнце и мир
     -- это идеи.
   * Мир идей умопостигаем. "теория" с греческого --
     рассмотрение. Философ -- это теоретик, созерцающий мир идей.
   * Душа человека -- это идея, воплощенная во плоть. Поэтому все идеи
     содержатся внутри человека. Поэтому знание -- это припоминание
     (анамнезис).
   * Иерархия идей признается. Наиболее общая идея -- идея Блага.
   * В более поздних диалогах Платон признает диалектику идей и их
     взаимоизменямость.
   * Опираясь на Пифагора, Платон выводит из Единого принцип
     двойственности (Диаду). Единое и Диада создают множественность.
   * Материя у платона -- хора, которая характеризуется изменчивостью,
     хаосом, неопределенностью. Противостоит миру идей.
   * Душа бессмертна, дает телу жизнь, умеет перерождаться. Сами по
     себе души -- тоже идеи из мира идей.
   * Философия -- это приготовление к смерти, поскольку человек должен
     отрекаться от эмоционального и чувственного, а смерть есть самый
     радикальный способ такого отречения.
   * В позднем Платоне душа состоит из частей: разумной (мудрость),
     аффективной (страстной, мужество) и вожделеющей
     (умеренность). Четвертая добродетель -- справедливость, которая
     является гармонией души.
   * В диалоге "Государство" Платон предлагает:
     1. Делить людей на сословия (крестьяне, ремесленники, торговцы,
        воины, правители-философы), которые соотносятся по строению
        души (разум, аффекты, вожделение). Рабы не входят в сословия.
     2. Отказаться от частной собственности, чтобы уравнить бедных и
        богатых.
     3. Аналогично отказаться от семей, так как они тоже вносят
        неравенство (и практиковать евгенику).
     4. Брать роль воспитания на государство.
   * Также описывается следующая иерархия плохих государств:
     1. Тимократия -- власть честолюбцев
     2. Олигархия -- власть, основанная на богатстве и обогащении
        олигархов.
     3. Демократия -- власть народа, в которой народ имеет волю делать
        все, что хочет. Платон именует демократию охлократией. Сам
        платон -- аристократ по происхождению. У него есть
        субъективные причины смешивать демократию и охлократию.
     4. Тирания как продолжение демократии.
   * В эту иерархию не входит монархия и аристократия, они являются
     хорошими госурадствами.
** Аристотель
   * Ученик Плаона
   * Критикует платонизм как раздваивающую мир без
     надобности. Идеалист. Сам не разделяет идеи (формы) и материю.
   * Разделяет методы познания на:
     1. Первую философию/теологию -- науку о первопричинах и создании
        сущего.
     2. Метафизику -- исследовании сущего как такового
     3. Вторую философию/физику -- исследование чувственного
        восприятия мира.
   * Учение Аристотеля рассматривает две основные причины:
     материальная (из чего все?), формальная (сущность, что это
     есть?).
   * Материя -- неподвижная, пассивная, неоформленная масса, требующая
     отличного от нее источника движения (эта формулировка, в отличии
     от ранней (материя есть движение) будет господствовать до 18
     века).
   * Чувственная душа дуальна -- разумное и чувственное.
   * Добродетели делятся соответственно на:
     1. Этические", которые являются "золотой серединой" между двумя
        порочными крайностями (мужество -- между трусостью и
        безрассудной храбростью).
     2. Дианоэтические -- мудрость и познание ради познания.
   * Разум должен подчинять чувственное.
   * Правильные формы правления -- аристократия, монархия, царство,
     полития (власть большинства). Неправильные -- тирания, олигархия,
     демократия.
   * Полития -- самая оптимальная форма правления, в которой власть
     осуществляют средние собственники (нечто среднее между нижними и
     верхними сословия, умеренность и середина -- лучшее). Причем
     середина должна быть достаточно большая.
** Эпикур
   * Материализм на основе атомизма Демокрита
   * Ставит в центр философии человеческое счастье. Основная задача --
     указать путь к счастью.
   * Добавляет в атомизм Демокрита случайность -- атомы могут случайно
     отклоняться от траекторий своего движения. Отрицает фатализм.
   * Смерть есть ничто, поскольку когда мы есть, то смерти нет, а
     когда есть смерть, то нет нас.
   * Удовольствие есть счастье есть отсутствие страдания. Но это
     удовольствие не имеет ничего общего с гедонизмом. Страдание --
     свобода от телесных страданий и душевных тревог, то есть
     безмятежность.
   * Душа страдает больше, чем тело, посольку страдает не только в
     "сейчас", но и в прошлом и дубущем.
   * Общий тезис жизни -- "знать и уклоняться", то есть выбирать среди
     удовольствией правильные, которые будут идти на пользу
     свободе. Уклоняться от неправильных.
** Стоицизм
   * Делится на три части: логика, физика, этика. Поздний стоицизм
     (римский) занимается только этикой.
   * Логика -- учение о доказательствах, "логос" -- инструмент
     познания. У человека есть, у бога есть, а у животных нет.
   * Все знание проистекает исключительно из чувственного опыта.
   * В физике сочетают Гераклита и Аристотеля. Два начала --
     страдательное и деятельное. Страдательное есть бескачественная
     сущность, а деятельное -- разум, то есть бог. Он вечен и является
     двигателем материи, смешан с ней.
   * Действия имеют причину движения (виды движения). Неорганическое
     тело имеет импульс от другого теда, для животного причина
     внутренняя, у человека причиной есть логика.
   * Судьба как движение неотвратноа, следует "знать и подчиняться".
   * Высшее благо -- счастье, стремление к самосохранению. Но
     самосохранение есть стремление к природе, а жить сообразно с
     природой -- жить сообразно с разумом, таким образом добродетель
     -- это высшее благо.
   * Все сущее -- благо, зло и безразличное.
   * Главная проблема -- это аффекты: скорбь, страх, желание и
     наслаждение. Их надо полностью искоренять. Мудрец всегда должен
     находиться в умеренно-радостном настроении духа.
** Скептицизм
   * Не сомневаться, а быть уверенным в неистинности и равнодушен к
     любому решению вопроса.
   * Не знать, но жить сообразно обычаю, традици или здравому смыслу.
   * Первые зачатки иррацинализма.
   * Энесидемские тропы (рассуждения против суждений о реальности):
     * Разнообразие живых существ, откуда вывод "одинаковые вещи
       вызываают неодинаковые образы". Можно говорить тлько о том, что
       нам кажется.
     * Различие у одного человека в устройстве органов чувственного
       восприятия.
     * Разные состояния (бодроствование, сон, опьянение, болезнь или
       здравость) вызывают разные восприятия.
     * Зависимость суждений от положения. расстояния и места.
     * Зависимость суждений от примесей, то есть суждения
       взаимодействуют с другими.
     * Суждения зависят от величины и устройства предмета.
     * Относительность явлений -- каждая вещь существует всегда по
       отношению к чему-то, и скорее всего кажется таковой, чем есть
       таковой поистине.
     * Зависимость суждения от частоты его рассмотрения.
     * Зависимость суждений от верований, догматов, обычаев.
** Фрэнсис Бэкон
   * Эмпирист, родоначальник интуиции
   * Учение об идолах (призраках) -- причинах несовершенства человека.
   * Виды идолов:
     1. Рода (заложенные в человеке).
     2. Пещеры (личные заблуждения, мнения, необъективность).
     3. Рынка (заблуждения связанные с речью).
     4. Театра (неправильное толкование теорий или вообще восприятие
        идеологически неверных теорий).
   * Утверждал, что научное знание может проистекать только из
     целенаправленно организованного опыта, а не из чувственных
     данных.
** Рене Декарт
   * Рационалист, признает познаваемость всего
   * Единственный авторитет и основание -- мыслящее "Я".
   * Правила метода постижения Декарта:
     1. Принимать за истинное только то, что воспринимается в ясном и
        отчетливом виде, самоочевидное. Исходным моментом познания
        можно считать интуицию (разумную).
     2. Делить сложную вещь на составляющие, пока не дойдем до
        интуитивно понятных.
     3. Все понятные вещи объединять и понимать новое.
     4. Должна быть полнота знания, всесторонне исследование объекта.
   * Самое интуитивно понятное -- то, что сомневается в том,
     интуитивно ли оно понятно -- это "я". Отсюда принцип cogito, ergo
     sum. Это достоверная интуиция.
   * Декарт отвергает солипсизм.
   * Доказательства существования Бога достаточно слабые и
     несостоятельные. Бог дуален
   * Дуализм Декарта -- это разделение человека на две составляющие:
     телесная (протяженная) и духовная (мыслящая). Субстанциональный
     дуализм.
   * Считает, что истины первоначально содержатся в разуме.
** Барух Спиноза
   * Рационалист, признает монизм
   * Формулирует "этику" с помощью дедуктивно-аксиоматического
     метода.
   * Единая сущность Спинозы -- это causa si, причина самой себя --
     такой объект, сущность которого заключает в себе
     существование. Еще "субстанция". Обладает бесконечной
     способностью существования.
   * Субстанция абсолютна, вечна, неделима, необходима
     (субстанциональный монизм).
   * Атрибут -- это нечто, выржающее или составляющее сущность
     субстанции. Атрибутов у субстанции бесконечно, но можно найти
     фиксированный набор, который будет ее характеризовать полно.
   * Такой набор атрибутов -- мышление и протяженность. Субстанция
     протяженна и мыслит.
   * Модус -- это состояние субстанции -- то, что существует в другом
     и представляется через другое. Любое "относительное
     отношение". То, что не замыкается в самом себе.
   * Модусы выражают многообразие мира, то есть природа порождается, а
     не порождает.
   * Пантеизм -- бог и природа есть одно и то же.
   * Не признает случайность, детерминист. Но против фатализма
     (немного противоречит сам себе). Типа природа не преследует
     никаких целей, потому что она есть суть своего же существования.
   * Субстанци неподвижна, а движение ее есть модус.
   * Свобода по Спинозе -- это отсутствие принуждения. То есть
     свободна лишь сама субстанция, Бог.
   * Все познаваемо. Вот пути познания:
     1. Случайный, понаслышке -- знание религиозное.
     2. Неорганизованный чувственный опыт -- случайные знания.
     3. Логический путь познания, который основывается на других
        знанияях, выведение сущности из других.
     4. Познание непосредственно из сути (интуиция).
** Готфрид Лейбниц
   * Субстанциональный плюрализм -- субстанция состоит из монад.
   * Монада -- простая неделящаяся субстанция. Не является
     материальным, потому что материя делится. То есть монады -- это
     истинные атомы мира.
   * Монады изменяются только в себе и только благодаря себе, изнутри.
   * Делит восприятие на низшее (существование), среднее
     (чувственное), высшее (мышление).
   * Аналогично:
     1. Простые монады -- из них состоят обычные вещи
     2. Монады-душы -- из них состоят все органические вещества
     3. Монады-духи -- монады со свойством "апперцепции".
   * В разуме есть зародыши идей, то есть отвергается сенсуализм с
     tabula rasa.
   * Истинные утверждения должны удовлетворять принципам:
     1. Противоречия -- не должно быть противоречий
     2. Достаточного основания -- нельзя признавать что-то не
        рассмотрев до конца.
   * Родоначальник математической логики и вероятностной логики.
** Иммануил Кант
   * Трансцендентальный идеализм (первичность трансцендентных
     сущностей -- бога-материи)
   * Гносеология, невозможность познания "вещей в себе".
   * Знание -- совершенное и несовершенное. Совершенное знание имеет
     исключительно априорный (не эмпирический) характер.
   * Чистый разум -- разум, наделенный априорным знанием.
   * Трансцендентальная эстетика -- учение об априорных формах
     чувственности. Трансцендентальная логика -- об априорных формах
     рассудка.
   * "Критика чистого разума" отвечает на три вопроса -- "как возможна
     чистая математика", "как возможно чистое естествознание" и "как
     возможна метафизика как наука".
   * Предметом трансцендентальной эстетики есть рассмотрение
     пространства и времени как априорных форм чувственности (чистые
     созерцания).
   * Чувственность пассивна, рассудок активен.
   * Познание -- это конструирование с помощью чувственности и
     рассудка, а не интуиции.
   * Трансцендентальная логика -- это трансцендентальная аналитика
     (рассудок и его априорные принципы) и трансцендентальная
     диалектика (исследование разума, как высшей познавательной
     способности).
   * Рассудок имеет дело с априорными категориями. Категории:
     1. По количеству: единство, множество, целокупность.
     2. По качеству: реальность, отрицание и ограничение.
     3. По отношению:
        1. Присущность и самостоятельное существование (субстанция и
           акциденция).
        2. Причина и действие.
        3. Общение (действие и подвергающиеся действию).
     4. По модальности: возможность-невозможность,
        существование-несуществование, необходимость-случайность.
   * Категории доступны рассудку априори.
   * Трансцендентальная апперцепция -- априорное самовосприятие, то
     есть самосознание.
   * Трансцендентальная схема -- априорная форма, однородная с
     категориями и явлениями (и интеллектуальное, и чувственное).
   * Естествознание есть наука, обусловленная априорной необходимостью
     (категория), с помощью схемы рассматривает суждения
     (чувственность).
   * Разум -- способность давать принципы, а рассудок -- способность
     давать правила. Рассудок аппелирует к опыту, а разум анализирует
     рассудок и ничего больше.
   * Трансцендентальные идеи (чистые понятие разума) -- то, что
     создает разум. Рассудок создать не может. Выделяется три:
     1. Идея о душе или об абсолютном безусловном единстве мыслящего
        субъекта. Психология.

        Душа недоказуема и неопровержима, как "вещь в себе", поскольку
        эмпирический опыт субъективен, категории "субстанция", а также
        понятия "простота и неделимость" не применимы к
        трансцендентальному субъекту, а также бессмертие души не
        наблюдается в опыте.
     2. Идея о мире или об абсолютном единстве условий
        явлений. Космология.

        Набор антиномий (тезисы и антитезисы) о космосе, доказывающих
        его непознаваемость.

        * Выводы из антиномичности космоса:
          1. Рассудку следует ограничиться регулятивной деятельностью
             упорядочения опыта.
          2. Разуму следует истолковывать решения, касающиеся тезисов
             и антитезисов антиномий только в регулятивном смысле.
          3. Понимать саму косологическую идею следует как регулятор
             мысли о природе -- что-то, что можно рассматривать, хотя
             невозможно познать.
     3. Идея об абсолютном единстве всех предметов мышления вообще или
        о боге. Теология.

        Попытки применения разума к теологии бесплодны и
        никчемны. Применения разума к природе не ведут к
        теологии. Значит, бог тоже есть "вещь в себе".
   * Польза философии чистого разума -- предохранение от заблуждений,
     методология определения границ. Истина непостижима.
   * Рациональная психология, космология и теология -- не науки,
     поскольку пытаются рационализировать вещи в себе. Поскольку из
     них состоит метафизика, то она тоже не наука.
   * Метафизика возможна как наука об априорных фофрмах познания,
     следующая из естественного стремления человека к познанию. Ей
     следует также быть критикой всех претензий на познавание
     недоказуемого. Также метафизика должна стать этической
     онтологией.
   * Метафизика в смысле онтологии должна отвечать на вопросы "что я
     могу знать?", "что я должен делать?", "на что я могу надеяться?".
   * Примат разума практического над теоретическим -- необходимость
     человека познать сверхчувственный мир.
   * "Критика практического разума" показывает, что развитая личностью
     нуждается только в знании, а не в его опеке, ибо цель и ориентир
     познавания априорны.
   * Этика Канта априорна и автономна (независимость моральных
     постулатов от внешней морали). Этика есть долг.
   * Нравственные, моральные законы (или императивы) -- законы
     долженствования, но законы природы -- законы необходимости.
   * Императивы:
     1. Гипотетический (гетерономная этика, сообразность с
        долгом, легальность). Условные императивы -- суждения о том,
        что поступки могут быть верными по отношению к какой-либо
        ситуации.
     2. Категорический (бесусловный-априорный, из чувства долга,
        моральность). Вытекает из трансцендентной природы человека.
        Формулизуется следующим суждением: "поступай только согласно
        такой максиме, руководствуясь которой ты в то же время можешь
        пожелать, чтобы она стала всеобщим законом".
   * Вера -- необходимый элемент для априорности нравственного
     закона, трансцендентального. Мнение -- признание истинности
     чего-либо потенциально субъективно или объективно
     недостаточного.
   * Свобода трансцендентна и может быть только в сверхчувственном
     мире "вещей в себе". Требует веры в себя.
   * Свидетельством соединения в человеке чувственного и
     сверхчувственного есть антагонизм между естественными и
     нравственными стремлениями. Единство человека требует синтеза
     нравственности (добродетели) и благополучия. Следовательно, для
     нравственного сознания лишь добродетель достойна благополучия. С
     другой стороны, это на практике не наблюдается -- добродетельные
     люди не всегда блкгополучны. Поскольку благополучие не нужно
     искать в сфере сверхчувственного, но его достижимость необходима,
     то необходимо признавать Бога и бессмертную душу.
** Иоганн Фихте
   * Развивался от Канта, изменил его с точки зрения субъективного
     материализма.
   * Выведение всего сущего из абсолютного чистого "Я".
   * Я -- это понятие человеческого духа, выражающее единство разума и
     воли, познания и нравственности, действия и страдания.
   * Наукоучение:
     1. Я полагает само себя и оно есть только из-за
        этого положения.
     2. Я полагает не-Я.
     3. Я противополагает делимому Я делимое не-Я.
   * Признает диалектику.
** Фридрих Шеллинг
   * Кант с объективным идеализмом.
   * Развивает наукоучение Фихте, но принимает в качестве первоосновы
     сущего не "Я", а более общий абсолют, в котором растовряется как
     "Я", так и "не-Я".
   * Монизм в виде тождества мышления и бытия.
** Георг Гегель
   * Объективный идеализм, идеалистическая диалектика
   * Известные произведения -- "Феноменология духа", "Логика",
     "Энциклопедия философских наук", "Философия права".
   * Исходил из монистических идей Шеллинга, но видел различие в бытие
     и сознании, не отрицая тождество (как не абсолютное). Это
     различие -- побудительная причина существования мира. Также
     абсолют сознательный, а не случайный как у Шеллинга.
   * Признает познавание бытия, отрицает непознаваемость "вещи в
     себе".
   * Принцип развития -- абсолют (мировой дух, абсолютная идея)
     непрерывно развивается. Саморазвитие абсолюта и его самопознание
     -- одно и то же.
   * Абсолют похож на субстанцию Спинозы, за исключением постоянного
     движения. Абсолют -- синтез шеллинго-фихтеанского "я" и
     субстанции Спинозы.
   * Абсолютная идея проходит 3 этапа -- логический, природный и
     духовный. Деление философии на философию логики, природы и духа.
   * Задача философии -- показать, что все конкретныме эмпирические
     формы жизни природной/животной/общественной есть исторически
     различные ступени абсолютного духа.
   * Первая стадия абсолюта (логика) делится на бытие, сущность,
     понятие. Рассматривается в "науке логики".
     * Бытие -- качество, количество, мера.
     * Сущность -- полагание сущности самой собой, утверждение
       самосуществования (явления), снимание абстрактых определений.
     * бытие → качество → количество → мера → сущность → явление →
       действительность.
     * Понятие -- подлинное развитие, диалектический процесс.
   * Наука логики определяет идеалистическую диалектику Гегеля:
     1. Принцип перехода качества в количество
     2. Принцип противоречия как источника движения
     3. Принцип двоного отрицания
        (тезис-антитезис-синтез). Спиралевидная форма развития.
   * Понятие проходит три ступении -- субъективное понятие,
     объективность, идею (единство понятия и объективности, истину).
   * Идея проходит жизнь, познание и абсолютную идею.
     * В качестве процесса идея -- чувственность, раздражимость и
       воспроизведение.
     * Познание -- стремление к истине, теоретическая деятельность
       (но воление -- практическая деятельность идеи).
     * Абсолютная идея -- единство теоретической и практической
       идей. Она начинает созерцать свое собственное содержание. Но
       созерцающая идея -- это природа, то есть бытие. Вернулись к
       бытию, но в виде природы, себя осознающей.
   * Исследование природы -- вторая составляющая гегелевской
     философской системы.
   * Природа -- материальное. Развивается ступенчато, но метаморфоза
     только в виде живых существ, так как метаморфоза в полной мере
     доступна лишь в сфере понятия.
   * Переход между ступенями природы -- эманация или
     эволюция. Эманация рассматривается как переход от более
     совершенного к менее, эволюция -- наоборот.
   * Идея обнаруживает себя в виде механики, физики и органики.
     1. Механика -- пространство, время, материя, движение. Материя
        качественно неопределена тут.
     2. Физика определяет материю в виде физических и химических
        свойств.
     3. Органика есть верх развития химии.
   * Органическая природа -- минеральная, растительная и животная.
   * Дух -- наивысшая форма существования идеи. Свобода духа -- власть
     над всем имеющемся в нем содержанием.
   * Дух развивается как субъективный → объективный → абсолютный.
   * Нравственность (конец объективного духа) -- семья, гражданское
     общество, государство.
   * Одобряет монархию.
   * Государство находит свое полное развитие во всемирной истории.
   * Всемирная история -- имеет своей целью и содержанием развитие
     свободы путем ее осознания.
   * Европоцентризм -- развитие истории с Азии на запад (азиатская
     философия и рабство, греческая и и римская с частичным рабством,
     германо-западная как свобода всех людей). Христианство --
     идеальная религия.
   * Абсолютный дух -- искусство, религия, философия.
   * Диалектика Гегеля -- переход тезиса в антитезис, синтез, и снова по
     новой (третий закон диалектики). По большей части относится к
     познанию, но можно применять и к истории.
** Людвиг Фейербах
   * Антропологический материализм.
   * Прочитал Гегеля и сказал, что это полный бред.
** Карл Маркс, Фридрих Энгельс
   * Критический материализм, основанный на критике Гегеля и
     переосмысления Фейербаха.
   * Диалектика основана на Гегелевской, но в намного более
     материалистическом стиле.
   * Первичность бытия, вторичность духа. Признается творческий момент
     в сознании (в отличии от Фейербаха).
   * Материя -- единственное, что существует. Она пребывает в
     постоянном движении. Движение определяется как атрибут материи.
   * Формы движения материи: механическая, физическая, химическая,
     биологическая, социальная. Порядок соответствует развитию. Между
     формами есть диалектическая связь так как все последующее было
     создано из предыдущего.
   * Пространство и время -- основные формы бытия.
   * Материя, движение, пространство и время -- аксиоматика
     (неразделимы).
   * Материя познаваема. Критика Канта.
   * Сознание -- сложный диалектический процесс. Делится на
     чувственно-эмперический и мысленно-теоретический.
   * Человек стремится познать бесконечный мир, но его возможности
     ограничены. Познание есть приближение к абсолютному знанию
     (предел).
   * Также человек ограничен конечным сознанием, поэтому понимание
     бесконечного возможно лишь частично.
   * Истина всегда относительна, поскольку существует
     заблуждение. Достижение абсолютной истины значило бы завершению
     природного процесса, что противоречило бы основным законам
     диалектического мышления.
   * Истина -- знание, адекватно отображающее
     действительность. Практика -- важнейшая компонента
     познания. Только через практику сознание творит и отражает мир.
   * Диалектика делится на объективную (природа, общество) и
     субъективную (мышление и познание).
   * Законы диалектики (3 штуки) -- такие же как у Гегеля.
   * Материальное производство -- основа жизни и развития общества. Из
     производства следует общение (гражданское общество), которое
     яесть часть государственной жизни. Последняя порождает
     теоретические порождения и формы сознания, религию, философию,
     мораль. Из всего этого следует история.
   * Материальные отношения -- производственные (экономические),
     бытовые, семейные и национальные.
   * Общественное бытие -- совокупность отношений, в которых
     производственное играет основную роль.
   * Сознание -- осознанное бытие, а бытие людей есть общественное
     бытие. Общественное бытие определяет сознание.
   * Естественноисторический процесс -- результат деятельности людей,
     преследующих свои цели.
   * Социальные законы. Много их. В том числе закон о роли базиса и
     надстройки. Бывают законы независимые от периода общественного
     развития (структура производства), зависимые (разбиение на классы
     и закон классовой борьбы).
   * Собственность -- реальная совокупность отношений между людьми.
   * Общественное производство -- производственные силы (содержание) и
     производственные отношения (форма). Производственные отношения
     развиваются, пока не представится достаточно простора для
     развития производственных сил. Тогда отношения становятся оковами
     и происходит революция. Все продолжается заново.
   * Исторический материализм -- история рассматривается как смена
     способов производства.
   * Общественно-экономические формации -- типы общества в истории.
   * По Марксу пять формаций -- первобытнообщинна, рабовладельческая,
     феодальная, капиталистическая и коммунистическая. (и еще
     азиатская?)
   * Базис -- совокупность производственных, экономических
     отношений. Надстройка -- система политических, юридических,
     идеологических отношений и институтов. Каждое историческое
     общество имеет специфичный базис и надстройку.
   * Функция надстройки -- охрана базиса. Базис первичен.
   * Понятие эпохи.
   * Отчуждение -- уменьшение зависимости между продуктом труда и
     человеком.
** Артур Шопенгауэр
   С начала 17 века и до второй половины 19 века самым популярным
   движением в философии был рационализм. Рационализм прославлял разум
   и знание. Яркими представителями были:
   * Декарт, ставящий мыслящее "я" на первый план. Его метод познания
     из четырех пунктов: первенство интуиции, индукция в частных
     вопросах, дедукция всего метода познания, цель -- полнота
     знания. Знаменитое cogito ergo sum -- основатель базы
     солипсизма. Скептицизм.
   * Спиноза, пути познания (произвольное знание, чувственное, знание
     из рассуждения и интуиция). Познаваемость мира.
   * Лейбниц вообще был логиком, признавал делил истины на истины
     разума (то, что можно придумать) и факта (единичные кванты
     информации). Правила -- принцип противоречия (противоречивые
     системы рассматривать нет смысла) и принцип достаточного
     основания.
   * Кант с путями познания, вещами в себе, трансцендентальной
     эстетикой и логикой. Разум и рассудок. Императивы, категорический
     и гипотетический.
   * Фихте, субъективный идеализм, вопросы вокруг "Я".
   * Гегель, который отрицал Канта с точки зрения
     познаваемости. Диалектика гносеологии -- принципы диалектики
     (качество в количество, противоречие как источник движения,
     тезис-антитезис-синтез).
   * Энгельс, Маркс (без комментариев)

   Но рационализм постепенно начал терять свою
   популярность. Во-первых, людям свойственно интересоваться более
   практическими вещами, наблюдениями, связанными с индивидуальными
   переживаниями человека. Во-вторых, стало ясно, что знание не
   является спасением от всех проблем -- мир по-прежнему не может
   справиться с насилием, войнами, коррупцией, другими социальными
   проблемами.

   Одними из первых, кто начал серьезно развивать иррационалистические
   идеи были Фридрих Шеллинг (развивал Фихте, от него отталкивался
   Гегель) и Сёрен Кьеркегóр (первым работал над понятием
   экзистенциализма, есть на фоточке статьи на википедии про
   экзистенциализм).

   Артур Шопенгауэр (1788 год) развивал философские рассуждения на
   основе иррационализма, то есть отрицания концепции преобладания
   разума, предлагая решать проблему отношения субъекта и объекта с
   точки зрения индивидуальной, то есть рассматривать его в первую
   очередь как нечто, порожденное представлением человека. Первичность
   индивидуального рассмотрения над рациональным знанием -- главная
   идея иррационализма.

   Шопенгауэр соглашается с тезисом Канта о "вещи в себе", утверждая,
   что это вообще есть "граница рационального познания", но приходит к
   выводу, из невозможности познания рационального, к возможности
   познания интуитивного. Под интуицией тут понимается не
   рационалистическая, а интуиция, истекающая из "бытия в себе
   познающего".

   В поисках фиксированной точки сознания и самосознания Шопенгауэр
   приходит к выбору, что основой для познания есть ни что иное, как
   воля. Не может быть познающего без познаваемого и наоборот,
   следовательно в основе всего лежит нерациональное нечто, что он и
   называет хотением или волей. Воля выступает у Шопенгауэра
   кантовской вещью в себе, которая лежит в основе всего. Причем
   сознание, конечно, не отвергается, но является вторичным, зависимым
   от внутренней воли. Причем важно понимать, что эта зависимость есть
   больше "средство", чем "данность" -- единственной целью сознания
   есть то, что диктует воля.

   Воля подразделяется на три ступени: механическая причина,
   раздражение и мотив. Природа раскрывает переход воли, обретение ей
   сознательности. Насчет позиций материализма, множество вещей в
   природе есть тоже проявление воли, причем пространство и время
   присущи только представлению, а не вещам в себе как таковым.

   Большую роль в учении Шопенгауэра играет этика, занимающая
   центральное место в его философии. Категорический императив Канта
   отвеграется, поскольку он выводится из первичности сознания. По
   Шопенгауэру поступки добродетельные и разумные -- категории
   различные. Логично.

   Свобода воли не существует, поскольку любая мотивация проистекает
   напрямую из воли, оттуда же, откуда проистекают все причины. В
   процессе выбора более сильный мотив с необходимостью овладевает
   волей. Воля имеет свою собственную необходимость, цель, ориентир,
   некоторую per-user настройку. Такой необходимостью является
   характер. Характер лежит в основе всех актов, вызываемых
   мотивацией, он индивидуален и неизменен. Разница в характерах по
   Шопенгауэру врождена и необходима. Именно характер придает
   необходимость воле, лишая ее свободы (свобода воли -- возможность
   воли действовать независимо). Но отрицание свободы воли значимо
   только в контексте ее объективизации через человека, воля-то сама
   по себе свободна.

   Основная и едининственная цель воли -- воля к жизни. Инстинкт
   самосохранения, стремление к счастью и благу есть выражение этой
   цели. Так рождается понимание эгоизма как основного проявления
   двигателя воли.

   Основой любых стремлений и желаний человека является
   неудовлетворенность, недовольство своим состоянием, страдание в
   буддистском смысле. Страдание -- термин достаточно перегруженый, но
   тут оно используется в контексте духовного, психологического
   неудовлетворения -- любой психологический дискомфорт есть всегда
   конфликт некоторых внутренних интересов, и вот совокупность таких
   явлений и есть страдание. Страдание есть первичным относительно к
   наслаждению. Оно усугубляется, если неудовлетворено, а если
   удовлетворено, то оно тоже усиливается, но в другом направлении,
   поскольку это следует напрямую из понимании цели воли. Усилие для
   достижения новых целей пораждает непрерывную неудовлетворенность,
   поэтому человек не может быть счастлив, совершая поступки согласно
   своим мотивам. Желания человека есть причина страданий.

   Итогом рассуждения о страдании является этика, основанная на
   резигнации, самоотрицании, отверждении воли к жизни, квиетизмом в
   смысле следования мотивации. Причем такое самоотрешение не может
   даваться легко по умолчанию, поэтому только усилием можно достичь
   добродетели. Этическому поведению добродетель
   сопутствует. Отрицание самолюбия, воли к жизни есть у Шопенгауэра
   возможным несмотря на встроенную причинность воли, причем наличие
   конфликта он не отрицает, но объяснение его рационально невозможно.

   Вторым важным выводом из понимания воли есть учение о сострадании,
   необходимость которого следует напрямую из эгоизма. Живое существо,
   руководствующееся эгоизмом, не может усмотреть в другом живом
   существе единую волю и причинность всех поступков. На деле же
   индивидуальность лежит не в сущности, а в проявлении, поэтому
   внутренне все источники воли равны. Понимая учение и природу воли,
   человек обладает уникальным шансом, в отличии от других источников
   воли, осознанно менять свое жизненное поведение. Кроме резигнации
   это поведение следует также выражать в сострадании, поскольку
   страдание есть основа всего мироздания и любого живого существа в
   частности, а сострадание -- понимание и принятие этой истины,
   единственно добродетельная реакция на него. Любая дружба или любовь
   не есть добродетельна, пока ей не сопутствует сострадание. Любовь
   -- одно из центральны проявлений хитрости воли, как тяги к
   продолжению рода, поскольку она полностью затмевает сознание и
   интуицию. Сострадание неразделимо и неизбежно, поэтому сострадание
   -- единственное, что можно предпринять в отношении других.

   В чем конечное решение проблемы воли? Им не может быть смерть, так
   как самоубийство в большинстве случаев есть выражение эгоизма и
   страдания, неудовлетворенности понимания чего-либо. Пределом
   добродетельных действий есть нирвана, учение о нирване -- небытие
   воли.

   Злоба, эгоизм и сострадания являются тремя главными двигателями
   человеческой деятельности. Счастье рассматривается только в
   понимании субъективности восприятия и воли.

   А еще он был сексистом и говорил, что ТНН. Не оправдывая это, стоит
   отметить, что, во-первых, шовинизм и сексизм были духом того
   времени (основная причина, на самом деле), а во-вторых, Шопенгауэр
   был очень закомплексованым одиноким параноиком и короче у него
   просто бахало. Еще нагуглил в каком-то ЖЖ утверждение на уровне
   "был в плохих отношениях с матерью и с соседкой, которой должен был
   платить по суду пособие" В любом случае, это понимание достаточно
   отчуждено от главных идей его философии.
** Фридрих Ницше
   * Иррационализм
   * Копирует Шопенгауэра, но определял жизнь как волю к власти. Воля
     к власти -- это господство, в первую очередь над собой. Жизнь --
     это то, что определяется через господство.
   * Понятие нигилизма. Обычный нигилизм -- явление отрицитальное
     (этика Шопенгауэра о самоотрицании -- как раз такой нигилизм),
     активный нигилизм -- положительное.
   * Сверхчеловек -- это такой нравственный идеал человека, который
     находится в полной власти самого себя.
   * Критика христианской морали как безнравственной, что видно в
     историческом процессе.
   * Волюнтаризм. Агрессивные эгоистические инстинкты как природа
     человека, которые создают исторический процесс как борьбу власти
     господ и рабов.
   * Отрицает какой-либо врожденный смысл жизни, цель, но дает ее --
     сверхчеловек.
   * Путь и жизнь требуют мужества, твердости, творчества и
     созидания.
** Огюст Конт
   * Позитивизм, основанный на философии Сен-Симона. 19 век, середина.
   * Основное условие общественной революции есть реформа
     интеллектуальное, причем насилие не помогает переживать кризис.
   * "Позитивное" -- наличное, полезное практически, достоверное,
     конструктивное.
   * Гуманистический подход к прогрессу -- убеждение в том, что
     искоренить заблуждения и восстановить общество на правильный путь
     можно без насилия, исключительно развивая изящные искусства и науку.
   * Идея о трех фазисах развития человеческого духа:
     1. Младенчество, развитие знания, теологический фазис
     2. Метафизический фазис развития -- переходное состояние, в
        котором нету науки
     3. Факты проверяются фактами, которые часто являются тривиально
        простыми. Господство науки, отрицание философии.
   * Социологическая теория в три эпохи: богословско-военная,
     метафизико-легистская, научно-промышленная. В третьей стадии
     промышленное производство -- главная цель людей.
   * Методы естественных наук должны быть индуктивными, а общественных
     -- дедуктивными (чтобы понимать сложные, комбинированные
     объекты).
   * Противоречит диалектизму и духу немецкой философии.
   * Классификация наук: математика, астрономия, физика, химия,
     биология и социология -- возрастающая сложность и убывающая
     общность.
   * Сциентизм -- позиция полной ориентации на науку как на высшую
     культурную ценность. Наука -- динамическая система объективных
     знаний о связях действительности.
** Эрнст Мах
   * Эмпириокритицизм Маха (критика опыта, "махизм") -- сведение
     основания знаний на чувственное восприятие.
   * Твердые знания -- чувственные элементы мира -- запахи, тона,
     движения, пространства, времена.
   * Видел смысл в объяснении субъективного восприятия, в сведении
     науки к этому.
** Логический эмпиризм
   * Венский кружок, львовско-варшавская школа, Мур, Рассел,
     Вигтенштейн.
   * Логический эмпиризм (логический позитивизм) -- научное знание
     отождествляется с эмпирически подтвержденным или аналитически
     удостоверенным знанием.
   * Философия -- анализ языка, философские проблемы -- языковые.
   * Философия не имеет предела и не является наукой, а родом
     деятельности, сводящейся к анализу естественных и искусственных
     языков. Преследует две цели:
     1. Элиминировать из науки не имеющие смысла рассуждения и
        псевдопроблемы.
     2. Обеспечить построение идеальных логических моделей
        осмысленного рассуждения.
   * Критерий практической полезности первичен.
   * Логический эмпиризм Венского кружка достаточно
     радикален. Рассматривались в качестве атомарных предложений
     "протокольные", "фактуальные" предложения, выражающие данные
     чувственного восприятия (цвет зеленый). Все научнеые утверждения могут
     быть представлены как функции от атомарных, а что не
     представляется -- метафизическое.
   * Логический эмпиризм сводился к устранению сложности конструкции и
     поэтому разрушался, не имев возможности расширяться. Все время
     уходило на поддержание сложной структуры.
** Карл Поппер
   * Фальсификационизмc
   * Знание -- не обоснованная истинная вера. Отказ от процедуры
     обоснования истинности научного знания. Знание не обосновано.
   * Если знание объективно и рационально, то:
     1. Знание не обоснованная истинная вера.
     2. Знание не может рассматриваться как точное.
     3. Объективность не связана с обоснованием.
     4. Рациональность не связана с обоснованием.
     5. Отрицание скептицизма.
     6. Обоснование теорий -- не задача науки и философии.
     7. Критика того, что высказывание или теория необоснованы -- не
        критика.
     Чтобы получить доказательства, к каждому тезису в конец
     дописывается ", потому что ни одно высказыавние не может быть
     обосновано".
   * Объективное у Поппера -- теория может быть выражена в языке, и
     далее критиковаться и оцениваться другими людьми, что приводит к
     Третьему Миру.
   * Теория Попера о трех мирах:
     1. Физические (материальные) объекты, включая
        организмы. Объективен в смысле, что может быть предметом опыта
        других. Автономен -- не зависит от человека.
     2. Ментальный, сознательный опыт. Субъективен. Не автономен --
        существует за счет сознания.
     3. Продукты человеческого разума -- проблемы, теории, числа,
        законы. Объективны, автономия сложно определяется -- являются
        продуктами разума, но порождают независимые следствия.
** Томас Кун
   * Парадигма -- совокупность научных достижений признаваемых всем
     научным сообществом в определённый период времени.
   * Нормальные и кризисные периоды развития науки. Кризис --
     медленное развитие. Научная революция -- смена парадигмы, то есть
     появление теории, на которую переключится внимание сообщества.
** Эдмунд Гуссерль
   * Скептицизм, релятивизм и субъективизм разрушают знание.
   * Отвержение всякого рода предпосылок (материализм, идеализм,
     традиционализм) и исследование знание как такового.
   * Основа знания -- эйдосы или идеальные сущности. Эйдос -- более
     важное по сравнению с фактом, с реальностью. То есть, феномены
     сознания.
   * Учение об интенциональности сознания (однонаправленность),
     чувственной и интеллектуальной интуиции -- феноменология. Изучает
     интенциональные объекты, феномены.
   * Каждый объект, на который сознание обращает внимание формируют
     мир. Эти объекты поставляются сознанию, например, чувственным
     восприятием, представлением и воображением.
   * Феномен может быть обнаружен только в интуитивном акте =>
     основной метод обнаружения сущностей есть умозрительное
     интуитивное усмотрение -- феноменологический метод.
   * Феноменологическая редукция -- подвергать сомнение все и дойти до
     того, в чем нельзя усомниться. Остается лишь сомнение, которое
     является частью сознание, то есть существую Я (отсылки к Декарту).
   * Таким образом, мы имеем дело лишь с объектами, которые есть
     необходимые части сознания.
   * Феноменологическая редукция трансцендентна, Гуссерль называет
     свое учение трансцендентным идеализмом.
   * Идея интерсубъективности -- Я есть множество Я в качестве
     трансцендентальных субъектов.
   * Жизненный мир (Lebenswelt) -- мир, не сам по себе, а взятый в
     соотнесении с человеком. Мета-горизонт субъективных устремлений и
     целей, смыслов и значений. Основа, сфера первоначальных
     очевидностей, являющейся основой познания.
** Сартр
   * Экзистенциализм -- это гуманизм
   * Тошнота
** Камю
   * Миф о Сизифе
   * Посторонний
