#+TITLE: Economics notes

* 13.02.2015
  Мы изучаем экономическую теорию.
  Когда-то давно чет люди думали насчет экономики но ничего не понимали по сути, просто даже наукой не называли, просто "мыслью".
  *Меркантилизм* -- это одно из движений экономики, которое ставило превыше всего торговлю. Недостатком было отсутствие внимания производству, первозке, купечеству.
  *Физиократия* -- меркантелизм, в котором уделяется внимание производству, но в основном сельскому хозяйству.
  *Монетаризм* -- это свобода всего, государство контролирует только денежную массу + либерализм -- некая ветка английской неоклассики.
  Английская классическая теория разделется на Маркса и Мальтуса. Хотя Маркса ругают, преподаватель считает, что Маркс короче великое дело сделал, хотя сейчас его ругают (понятно).

  А, это было введение.
  Что такое экономика? У Аристотеля -- это ведение домашнего хозяйства. Политическая экономика -- это управление.

  Потербности, экономические ресурсы и их виды.
  Необходимо постоянно удовлетворять потребности человека, общества. Потребности многообразны. Можно их классифицировать по-разному. Первичные потребности -- еда, пища, одежда, здоровье. Вторичные потребности -- духовные, образовательные, интеллектуальные, искусство, развлечения. С ростом общества происходит рост потребностей. Закон возвышения потребностей -- потребности возрастают и видоизменяются, старые отмирают. Это видоизменение побуждает создавать блага.
  * Благо -- средство для удовлетворение потребностей. Делятся на ограниченные и неограниченные.
  * Экономические блага -- ограниченные блага по отношению к потербностям. Делятся на долговременные и недолговременные блага.
  * Прямые и косвенные блага -- косвенные производят прямые.
  * Услуга -- целесообразная деятельность, результат которой выражается в полезном эффекте, удовлетворяющем какие-то потребности человека (медицинская услуга как товар).
  * Ресурсы -- имеющиеся у общества возможности для создания благ.
  * Производство -- это процесс создания блага (хлебопекарный цех, машиносборочный завод). Именно в процессе производства происходит приспособление ресурса к потребностям человека.
  * Человеческие
    * Труд -- совокупность умственных и физических способностей.
    * Предпринимательская способность. Примерно 8-10% людей обладают способностью быть предпринимателем.
  * Капитал -- это инвестиционный ресурс. Реальный капитал -- это здания, станки, вот это все. Становится средством производства. Пассивный капитал -- это типа здания. Активное -- это начинка -- станки, машины.
  * Земля -- все "даровые" ресурсы природы.
  Разное отношение между доступными ресурсами и потребностями приводит к неполному удовлетворению последних.
  Можно ли поднять целину мотыгой? Можно, но неэффективно. Эффективность общественного производства -- это отношение национального дохода к количеству занятых. Эффективность какого-либо действия вообще -- это отношение результат к затратам. Есть еще ресурсная или факторная эффективность -- производительность труда -- это производительность в единицу времени. Капиталоемкость\капиталоотдача -- это то, насколько капитал занят в работе. Оптимальность -- это 80-85% -- станки требуют наладки\модернизации и прочего. Есть еще показатель -- коэффициент сменности -- это то, сколько людей необходимо для того, чтобы капитал работал оптимально -- наибольший показатель на непрерывных процессах (а в СССР -- легкое потребление у женщин). Материалоотдача -- богатство\расточительство (???). В россии типа расточительство высокое)))))0 Типа земель много но никто не юзает, типа металл переводим на производстве и все такое хех мемы)))) 50% металла идет в стружку. Рассказала кулстори про поселок Малышево, жд-дорогу к которому делали на насыпи, а в насыпи оказалось много алмаза, потому что все затупили хех))).
  Конечно, все сразу произвести нельзя. Производственные альтернативы, кривая производственных возможностей. Экономический смысл КПВ -- экономика полной занятости альтернативна (если мы хотим что-то делать больше, то должны что-то делать меньше).
* 20.02.2015
  Типы экономических систем.
  * Собственность -- исторический определенный способ присвоения благ
    Собственность фиксирует что, кому и в каком количетве принадлежит.
    Юридическая содержание собственности -- пользование, владение, распоряжение.
    Экономическое содержание собственности: экономическую науку не интересует присвоение благ путем завоевания, дарения, воровства, она изучает присвоение благ только путем производства. Главнейшей формой реализации собственности является, прежде всего, доходы (в плане реализовать собственность как "продать"). Специфика экономической собственности состоит в:
    1. Собственность -- это не вещь и не отношение, это нечто имеющее социально-экономическое содержание и формы
    2. Монополизация условий производства характеризует условие содержание собственности
    3. Формы доходов реализуют собсвенность

    Существует теория прав собственности:
    Права собственности -- санкционированные обществом (народом, законами, традициями) поведенческие отношения между людьми.
    Права собсвтенности рассматриваются как пучок:

    1. Права владение -- физического исключительного контроля
    2. Право использования -- право ис
    3. Право управление -- решать как и кто может использовать
    4. Право на доход -- право управлять результатами
    5. Право суверена -- типа что хочу то и делаю, могу уничтожить
    6. Право на безопасность -- защита от экспроприации и вреда со стороны внешней среды.
    7. Право на передачу благ в наследство
    8. Право на бессрочность обладания благом
    9. Запрет на использование способом, наносящим вред внешней среде -- типа дом построил, но все распидорасило
    10. Право на ответственность в виде взыскания за долг -- можно собственностью оплатить долги согласно судового решения
    11. Право на остаточный характер -- право на существование процедуры института, которая обеспечивает восстановление правомочий. То есть закон может стоять выше желания хозяина.

    Виды собственности -- частная\государственная\смешанная.
  * Экономическая система
    Система -- это совокупность взаимосвязанных и опдределеным образом упорядоченных элементов экономики.
    Классификация систем может быть основана на ряде признаков:
    1. Совокупность связей -- деятельность по ... ресурсов
    2. Совокупность социальных связей -- собственность
    3. Совокупность институтов и их поведений (государство, фирмы, профсоюзы, нормы, традиции)

    Есть два способа координации экономической системы -- стихийный и рыночный.
    * Стихийный порядок -- экономические субъекты приспосабливаются к условиям путем обмена информации на основе ценовых сигналов -- типа рынок. Рынок -- любое взаимодействие для обмена результатами деятельности. В основе рынка лежит разделение труда -- нельзя делать все самому.
    * Иерархический порядок -- субъекты получают информацию путем директив, приказов из некоторых центров (типа в СССР был всякий ГОСПЛАН, ГОССНАБ, ГОССТАТ). Иерархия основана на власти.

    Транзакционные издержки -- издержки связанные не с производством, а со всякими другими вещами, типа реклама, нотариусы.
    Типы организации систем:

    1. Традиционная -- система, основанная на традицииях.
    2. Рыночная система -- это стихийный порядок. Множество продавцов, множество покупателей.
    3. Коммандная экономика -- характеризуется госсобственностью с использовагнием иерархического порядка (сейчас осталось в КНДР, Кубе. Китай -- смешанная).
    4. Смешанная экономика -- характеризуется и частной и государственной формой собственности, используются оба порядка -- и стихийный и иерархический.

       В чистом виде нету не рыночной не коммандной экономики, они обычно смешанные.
       В рамках экономических моделей можно выделить американскую, японская, шведскую -- как определяется отношение между рыночной и коммандной составляющей (в Швеции налогов много, государство дает кучу денежек народу, в Америке типа рыночная). Подсовременной подразумевается рыночная экономикой, где только самые важные функции замыкаются на государство -- здравоохранение, всякое такое.
       В экономически слабых странах превалирует традиционная экономика -- все основывается на традици. /Рассказала историю про вытяжки в OBI, в котором часть вытяжек отозвали, а потом поставили по другой цене, потому что в наглую повышать незаконно!/
       Переходная экономика -- это переход к рыночным отношениям с коммандной. В рамках этой системы выделяется восточноевропейские (Польша, Словакия, Болгария, Чехия,..). Переходная экономика призвана сформировать основу новой. Переходная экономика обладает свойством многоукладности (осуществляется государственная, частная, смешанная), нестабильность. Структурные преобразования -- меняется структура предприятий -- акционирование. Институциональные преобразвания -- формирование законов о конкуренции, монополиях и т.д -- формирование правовой основы.

  * Понятие рынка и его субъектов
    Рынок -- это способ взаимодейтвия потребителей и производителей основанный на децентрализованном, небоснованном механизме ценовых сигналов.
    При каких условиях возникает рынок: частное собвственность и разделение труда. Первое крупное разделение труда -- резделение скотоводческих племен от тех, кто выращивал чет. Постепенно разделение углублялось -- появились племена, которые специализировались на каком-то одном виде деятельности, ну они и обменивались.
    Границы эффективности рынка определяются обменом и величиной транзакционного обмена. Все зависит от общественных регуляторов -- законы, связанные с владением собственности. Обмениваются люди товаром, который является и благом, и результатом деятельности.
    Товар -- это экономическое благо. Важнейшие характеристики товара -- это потребительнская стоимость (полезность) и меновая стоимость (относительная стоимость, то, что делает товары измеримыми -- количества труда затраченные, и так далее).
    Деньги -- это специфический товар. Полезность денег в том, что они обладают абсолютной ликвидностью. То есть их можно обменять на любой товар. Количество денег за единицу одного блага -- цена.
    Домохозяйство -- это экономическая единица в составе одного или нескольких лиц, которые:
    1) Являются собственником ресурса
    2) Стремятся к удовлетворению потребностей
    3) Самостоятельно принимают решения

    Фирма -- это субъект рынка, экономическая единица:
    1) Использует ресурсы для производства товаров и услуг
    2) Стремится к максимизации прибыли
    3) Самостоятельно принимает решения

    Экономическое поеведение фирм зависит от цен, цены от ценовых сигналов. Цена -- это основная сила, также зависит все от конкуренции.
    Рынок бывает товаров и услуг, рынок факторов. Делятся на субрынки, типа рынок потребительских товаров, экономических услуг, медицинских. Можно классифицировать по географическому признаку -- национальный, межнациональный, местный.
    Колебание рыночных цен определяет основные функции:
    1) Распределение ресурсов по отраслям
    2) Стимулирование прогресса
    3) Дифферененциация доходов

    Государство формирует законодательную базу, защищает конкуренцию (ФАC). Рыночная экономика сама по себе не эффективна в некоторых областях -- ей не выгодно, например, оплачивать прививки для детей, обеспечивать. Вообще логично здравоохранение класть на плечи государства, потому что врачи часто заинтересованы в долгом и упорном лечении. В СССР было 4 уровня здравоохранение -- для илитки, для крутых госработников, местная верхушка городская и для обычной челяди.
* 27.02.2015
  * Спрос
    * Закон спроса -- чем ниже цена, тем выше спрос.
    Есть исключения из закона спроса -- некоторые продукты не индексируются этим правилом. Хлеб там, всякие товары для того, чтобы понтоваться (всякие элитные машины) -- эффект сноба.

    Алсо на спрос влияет не только цена:
    1. Объем покупателей
    2. Потребительский вкус и предпочтения
    3. Инфляционные ожидания

    Следует различать спрос и величину спроса.

  * Предложение
    Предложение -- это совокупность благ, находящихся на рынке. Величина предложение -- максимальное количество товара приготовленного для продажи в данный период времени в данных условиях.
    * Закон предложения: чем выше цена данного товара, тем больше предложение.

    Факторы:
    1. Цены на производство
    2. Налоги и субсидии
    3. Цены на другие товары
    4. Инфляционные ожидания производителей

    Товары бывают эластичные -- малоэластичные, эластичные (коэффициент <1 или больше). Эластичный товар -- это такой товар, спрос на который очень сильно зависит от цены. Ну а короче медицина это неэластичный товар. Есть также понятие эластичность относительно предложения.

    Равновесная цена -- точка пересечения графиков зависимости спроса от цены и предложения от цены.

  * Спрос и потребительский выбор
    Потребители определяют спрос
    * Общая полезность -- это полезность, получаемая субъектом от конкретного блага при прочих равных условиях.
    * Предельная потребность -- полезность дополнительной единицы блага.
    Большая часть потребностей удовлетворяется.
    Переход от неполного к полному удовлетворению происходит плавно -- типа насыщение.
    * Закон убывающей предельной полезности: по мере потребления новых единиц данного блага предельная полезность уменьшается.
    * Эффект дохода: снижаемая на товар цена повышает предельную полезность (короче если что-то стоит меньше, этого можно купить больше).
    * Эффект замещения: покупатель покупает больше товара, цена на который снизилась, заменяя товары, цена на которые повышается
    * Принцип максимизации общей полезности/принцип потребительского равновесия: необходимо распределить свой доход так, чтобы предельная полезность, полученнная в рассчете на единицу цены одного блага, равна была предельной полезности в рассчете на единицу цены другого блага.
    * Карта безразличия -- семейство кривых безразличия
  * Виды рыночных структур
    Можно выделить четыре структуры:
    1. Чистая (совершенная конкуренция) - рынок валют, рынок хозяйственных товаров
       * Большое число фирм на рынке
       * Стандартизированная продукция
       * Продавцы не осуществляют контроль над ценами
       * Свободное вхождение в область и выход из нее
    2. Монополистическая конкуренция
       * Большое количество продавцов
       * Дифференцированный продукт
       * Контроль над ценой есть, но не слишком большой
       * Легкое вхождение в отрасль
    3. Олигополия (бытовые приборы, автомобилестроение)
       * Малое число фирм
       * Продукция может быть стандартизированной или дифференцированной
       * Контроль ограничен, но может быть тайный сговор
       * Серьезные препядствия для вхождения в отрасль
    4. Монополия
       * Цена диктуется
       * Вступление заблокирована
       * Один продавец
       * Продукция стандартизирована

    Монополизация возрастала. В 1890 году акт Шермана -- антимонопольные законы:
    1. Доля рынка превышает 30%
    2. Фиксированная цена
    3. Слияние конкурирующих фирм
    4. Переплетающиеся директораты
    5. Ценовая дискриминация -- продажа одного товара по разной цене

    Закон РФ признает действия неправомерными:
    1. Сокращение\прекращение производства с целью создания дефицита.
    2. Покупка какиех-то акций, если вы выпускаете больше 30%.
    3. Moar
* 13.03.2015 Доходы населения и источники их формирования.
  Фирмы -- потребители ресурсов, собственники ресурсов -- поставщики.
  Цена:
    * Цена Земли -- рента
    * Цена капитала -- процент
    * Цена труда -- заработная плата

    # На этом месте препод выгнала двух людей и смешно пошутила про "хлопать" и чет еще
    Если меняется собственник, то земля и капитал продаются как капитальные блага. У человека нельзя отнять его способность к труду, но продать участок реально.
    Спрос на ресурс является производным от спроса на товар и услуги, производимые с его помощью.
    *Правило найма ресурса* -- любой ресурс должен наниматься до тех пор, пока предельный продукт ресурса в денежной форме не будет равен предельным издержкам на наем ресурса.
    Размер спроса на фактор (ресурс) зависит не только от цены на данный фактор, но и от уровня цен на другие ресурсы. То есть возможность взаимозамещения позволяет их использовать в соотношении, поддерживающем наименьшие издержки и наибольшую прибыль.
    Фирма будет заменять один ресурс другим, пока сумма денег не будет давать одинаковый предельный продукт.
  * *Эластичность*: чем эластичнее спрос на продукт, тем эластичнее спрос на факторы производства.
  Решение о величине предложение труда определяются многими экономическими и неэкономическими факторами.
  Количество Земли достаточно фиксировано и не может измениться.
  Сумма всех факторных доходом в стране составляет валовой доход. Изменение предложение одного фактора воздействует на рынки и других факторов, то есть один фактор изменяет доходность остальных.
  Переход к рынку труда
  *Рынок* -- это механизм взаимодействия, подчиняющийся все тем же законам спроса и предложения.
  На рынке труда большую роль играют социальные и психологические факторы. *Заработная плата* -- это цена, выплачиваемая за пользование единицей труда. Решение индвида о том, какое количество труда предложить, принимает всегда сам индвивид.
  Решающим фактором является рост производтельности труда, работник высокой производительности имеет высокую ЗП.
  Три основных фактора производительности:
  1. Физический капитал
  2. Человеческий капитал (образование)
  3. Технологические знания.

  *Номинальная ЗП* -- это то количество денег, которые получают за единицу времени.
  *Реальная плата* -- это то количество товаров и услуг, которое вы можете купить на номинальную заработную плату.
  Реальную плату можно считать так: пусть номинальная плата увеличилась на сколько-то, еще короче увеличилась цена на товары, шмяк шмяк фигакс ~> ready
  Чем обусловлены различия в ЗП:
  1. Работники различаются по способностям и уровню подготовки.
  2. Виды работ различаются по своей привлекательности.
  3. Ограничение мобильности работников.

     *Феномен суперзвезды* -- некоторые актеры или спортсмены получают огромные доходы:
  1. Потребитель желает получить товар, предложенный лучшим работником
  2. Товар произведён с помощью технологии, благодаря которой лучший производитель может поставлять его каждому потребителю по низкой цене.
  # Фактор неравенства доходов -- в тесте 6/6 верных вариантов.
  Конкретная величина ЗП складывается под воздействием трех сил:
  1. Предприниматели
  2. Профсоюзы
  3. Государство

  *Тарифное соглашение* -- хз что вообще
  *Безработица* -- ситуация, в которой существуют люди, желающие работать, но не имеющие возможности реализовать это желание.
  1. Люди потерявшие работу
  2. Люди добровольно оставившие работу
  3. Пришедшие на рынок труда впервые
  4. Пришедшие после перерыва

  *Структура ЗП* -- количественное соотношение элементов, формирующих ЗП. Например -- надбавки за перевыполнение, премии, доплаты, сверхурочное, ночные часы.
  Социальная политика государства направлена на улучшение уровня жизни -- количетсвенных и качественных показателей -- реальные доходы население, продолжительность рабочего времени, жилищных условий, условий работы, прочее. ООН использует индекс человеческого развития -- ИЧР.
  *ИЧР* -- вычисляется:
  1. ВП на душу населения
  2. Средний уровень жизни
  3. Уровень образования -- количество лет учебы

  *Бюджет семьи* -- структура всех ее доходов и расходят.
  Пусть у нас есть три поколения в семье и в каждом есть какой-то вклад в общий доход.
  *Закон Энгеля* -- с ростом дохода в семье удельный вес расходов на питания уменьшается, удельный вес на удовлетворение культурных и иных потребностей заметно увеличивается. Этот закон не работает в РОССИЮШКЕ, потому что у нас цены на коммунальные услуги довольно сильно варьируются.
  Для количественной дифференциации применяются различиные показатели. Степень неравенства доходов демонстрирует *кривая Лоренца* или *лук Лоренца*. Если провести биссектриссу 1 угла
  *Децельный коэффициент* -- коэффициент, выражающий соотношение между средними доходами 10% наиболее высокодоходных граждан страны и 10% наименее обеспеченными.
  Для отнесения определённых категорий на­селения в число имеющих право на получение социальной помощи ис­пользуется понятие - *черта бедности*.
  Есть две черты бедности -- абсолютная и относительная. Абсолютная черта -- ниже черты бедности, относительная -- когда доход не превышает среднего дохода в стране.
  Прожиточный минимум выражается в двух видах: социальный и физиологический.
  1. Физиологический (бюджет прожиточного минимума)(БПМ) рассчитан на удовлетворение основных физических потребностей.
  2. Социальный (минимальный потребительский бюджет)(МПБ)помимо физических потребностей, включает затраты на минимальные духовные и социальные запросы. Для определения прожиточного минимума используется обычно метод *потребительской корзины*.
